aws/sagemaker-python-sdk

src/sagemaker/session.py, src/sagemaker/user_agent.py
The previous implementation allowed for our user agent string to be overridden if the user supplied a boto3 session, SageMaker client, or SageMaker runtime client.
=> Use custom user agent string at all times

tox.ini
The current configuration presumes that the test data exists under the `sagemaker` directory, but the `tests` directory has since been moved out of `sagemaker`.
=> Update tox.ini to ignore integ test data

src/sagemaker/session.py, tests/unit/test_session.py
This change is required until we start using CloudWatch events to determine the training job status. It is allows the streaming to keep happening every 5 seconds but describing training job calls only every 30 seconds.
=> describing training job call every 30 seconds

tox.ini
Travis will run flake8 for python 3.5 tests.
=> Add flake8 within travis build

tests/integ/timeout.py
capture ValidationException errors when deleting endpoints to not override previous exceptions
=> capture ValidationException errors when deleting endpoints

.gitignore, setup.py, src/sagemaker/amazon/common.py, tests/unit/test_common.py, tox.ini
Implemented `write_numpy_to_sparse_tensor` which supports any `scipy.sparse` matrix (#27).
=> Implemented write_spmatrix_to_sparse_tensor

README.rst
Prompted by question: https://github.com/aws/sagemaker-python-sdk/issues/36
=> Add FAQ entry to README explaining how to predict against existing endpoints

tests/data/iris/failure_script.py, tests/data/mxnet_mnist/failure_script.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf.py
Just a start toward having a more comprehensive integ test suite - this change adds a simple training failure test for MXNet and TF
=> Add integration tests for basic training failure cases

src/sagemaker/session.py
At my organisation we have reached our maximum number of allowed buckets on `s3` and as a direct consequence of that we started getting the following error when using the `sagemaker-python-sdk`:
```
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): s3.amazonaws.com
Traceback (most recent call last):
File "/Users/joan.alabort/miniconda3/envs/beatrix_27/bin/sagemaker", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File "/Users/joan.alabort/cvdev/beatrix/hudl_beatrix/cli/bin/sagemaker", line 6, in <module>
fire.Fire(component=SageMakerRunner)
File "/Users/joan.alabort/miniconda3/envs/beatrix_27/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
component_trace = _Fire(component, args, context, name)
File …
```
=> Correctly handle TooManyBuckets error_code in default_bucket method

tests/integ/test_byo_estimator.py
Use Factorization Machines algorithm as an example.
=> Add test for BYO estimator

src/sagemaker/session.py
Instead of manually constructing the role ARN, use the IAM boto client
to do it. This properly expands service-roles and regular roles.
This fixes #43
=> Fix Estimator role expansion

src/sagemaker/session.py
Fix description of an argument of `sagemaker.session.train`. `input_config` should be an array which has channel objects.   The description of `input_config` is taken from https://botocore.readthedocs.io/en/latest/reference/services/sagemaker.html#SageMaker.Client.create_training_job.
=> Fix description of an argument of sagemaker.session.train

tests/integ/test_pca.py, tests/integ/test_tf_cifar.py
Opting to execute tf_cifar test without logs to eliminate delay to detect that job has finished.
=> Fixing timeouts for PCA async integration test.

.gitignore, CHANGELOG.rst, README.rst, doc/conf.py, setup.py, src/sagemaker/fw_utils.py, src/sagemaker/mxnet/defaults.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/mxnet/model.py, src/sagemaker/tensorflow/__init__.py, src/sagemaker/tensorflow/defaults.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/model.py, tests/component/__init__.py, tests/component/test_mxnet_estimator.py, tests/component/test_tf_estimator.py, tests/conftest.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf.py, tests/integ/test_tf_cifar.py, tests/unit/test_estimator.py, tests/unit/test_fw_utils.py, tests/unit/test_mxnet.py, tests/unit/test_tf_estimator.py
Add support for TensorFlow-1.5.0 and MXNet-1.0.0
=> Support TensorFlow-1.5.0 and MXNet-1.0.0 

README.rst, setup.py, tests/integ/test_tf.py, tests/integ/test_tf_cifar.py, tests/integ/timeout.py, tox.ini
SageMaker hosting creates a new log group for each endpoint created. Since we don't clean these up currently, they build up indefinitely until we hit our limit, at which point we can no longer debug test failures.
=> Dump + cleanup endpoint logs during integ tests

CHANGELOG.rst, tests/conftest.py, tests/integ/__init__.py, tests/integ/test_byo_estimator.py, tests/integ/test_factorization_machines.py, tests/integ/test_kmeans.py, tests/integ/test_lda.py, tests/integ/test_linear_learner.py, tests/integ/test_mxnet_train.py, tests/integ/test_ntm.py, tests/integ/test_pca.py, tests/integ/test_tf.py, tests/integ/test_tf_cifar.py
* revised the integ tests so that they're using a common pytest fixture for `sagemaker_session` (does not get created if not used, i.e. during unit tests)
* added configuration options for aforementioned pytest fixture
=> Create configurable sagemaker_session fixture for all integ tests

CHANGELOG.rst, src/sagemaker/amazon/kmeans.py, src/sagemaker/amazon/linear_learner.py, src/sagemaker/amazon/pca.py, tests/integ/test_linear_learner.py, tests/unit/test_amazon_estimator.py, tests/unit/test_fm.py, tests/unit/test_kmeans.py, tests/unit/test_lda.py, tests/unit/test_linear_learner.py, tests/unit/test_ntm.py, tests/unit/test_pca.py
Description:
1, Remove unused codes in unit tests of ntm and lda
2, Add more tests in unit test of factorization machines
3, Add pca and kmeans unit tests
4, Fix type of hyper-parameter tol in kmeans
5, Add missing hyper-parameter eval_metrics in kmeans
6, Remove some tests in test_amazon_estimator since they are in unit test of pca
7, Use validator function in pca instead of lambda
Test:
tox tests/unit passed
=> Update unit tests of kmeans, pca, factorization machines, lda and ntm

tests/conftest.py
there is a bug where if the region is not configured at all on the box, boto3 will be unable to create clients. This change ensures that the region is configured first.
=> Fix region-handling for integ test sagemaker_session

doc/conf.py
The current docs are failing with `error: no lapack/blas resources found`.
The docs build locally on my machine even without this change, so I unfortunately wasn't able to recreate the exact error.
=> Mock scipy and numpy for Read the Docs

CHANGELOG.rst, README.rst, doc/conf.py, setup.py, src/sagemaker/amazon/linear_learner.py, tests/integ/test_linear_learner.py, tests/unit/test_linear_learner.py
* adding hyper-parameters for early stopping and new loss types.
* fix hyper-parameter validation ranges
* bump version to 1.1.3
**Testing**
pytest tests/unit/test_linear_learner.py 
pytest tests/integ/test_linear_learner.py
=> add new hyper-parameters for linear learner

CHANGELOG.rst, src/sagemaker/fw_utils.py, tests/unit/test_fw_utils.py, tests/unit/test_mxnet.py, tests/unit/test_tf_estimator.py
We are switching to an ECR repo naming convention which more closely follows typical docker repo conventions. Instead of including device and python version info in the repo name, e.g. 'sagemaker-tensorflow-py2-cpu:1.5', we have one repo for all images of a framework, and put the rest of the info in the tag, e.g. 'sagemaker-tensorflow:1.5-cpu-py2'.
=> Use new repository names for Framework images

src/sagemaker/local/image.py, src/sagemaker/local/local_session.py
Switch local mode to use nvidia-docker2 + docker-compose
instead of nvidia-docker + nvidia-docker-compose.
Also get rid of the log output for billable seconds in local mode as it
doesn't make sense.
Finally, let the users know if we can't cleanup a container directory
but not fail the training job.
=> Local mode improvements

CHANGELOG.rst, README.rst, setup.py, src/sagemaker/mxnet/defaults.py, src/sagemaker/tensorflow/defaults.py, tests/conftest.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf.py
Also bumping our minor version up, since TensorFlow 1.6 / MXNet 1.1 may have some backwards incompatible API changes.
Also includes a minor change to integ tests - removed the framework version parameter from the TF/MXNet async fit tests. These tests cover the same cases as their synchronous fit tests.
=> Update default versions to TensorFlow 1.6 and MXNet 1.1

CHANGELOG.rst, setup.py, src/sagemaker/local/image.py, tests/unit/test_image.py
This also includes:
Use 'sagemaker-local' docker network for LocalMode
Instead of having docker-compose generate a random network each time,
use a constant network.
=> Login to ECR if needed for Local Mode

CHANGELOG.rst, README.rst, doc/conf.py, setup.py, src/sagemaker/amazon/linear_learner.py
1, Fix inaccurate range and doc for linear learner hyper-parameters
2, Fix the inaccurate version in doc and readme
=> Fix inaccurate linear learner hyper-parameter and sagemaker version in doc and readme

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Updated contributing.md and pull request template to remind contributor to update changelog.
=> Update contributing and pull request template

CHANGELOG.rst, src/sagemaker/local/image.py, tests/unit/test_image.py
Local Mode should honor the inputs instead of wrongly assuming that
everyone is using the default bucket. Fixes #137 #145 
=> Fix local mode not using the right s3 bucket.

CHANGELOG.rst, README.rst, doc/conf.py, setup.py
=> Bump version to 1.2.3

src/sagemaker/session.py, tests/integ/test_tf_cifar.py
* Our tests regularly fail due to throttling on DescribeLogStreams - this should mitigate that.
* Sometimes, test_cifar takes a long time to complete and the test times out. This is obviously a problem in of itself, but setting the training timeout is a quick fix to release the training instances when the test fails due to client timeout. I'll still need to deep dive on the test itself.
=> Test stability - increase retries on cloudwatch log client + set training timeout for test_cifar

tests/integ/test_tf_cifar.py
We have a known issue with multi-machine TF training where, if the master finishes before the worker initializes, the training job hangs indefinitely. (This generally only happens with very small datasets / # of training steps.) While it's an issue that we should fix, it's more urgent to fix our integ test to prevent false positives, which is what this change does.
By increasing the number of training steps, the training consistently avoids this race condition. The job still finishes in ~8 minutes counting SageMaker startup time, which is about the same as what it was before, so it shouldn't affect test runtime noticeably.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! …
=> Increase # training steps for test_tf_cifar to mitigate race condition

src/sagemaker/estimator.py
In the current implementation, when the `Estimator` is executed in the local mode, the underlying `sagemaker_session` is created via a default `LocalSession()` call. Therefore, if the user wants to create their own `boto3.Session()` with a custom profile name or region name, the information would get lost at this stage and S3 data downloading would fail.
In this PR I've made a simple fix. …
=> Correctly pass boto3 Session while creating Estimator

src/sagemaker/session.py
Update docstrings of `logs_for_job` and `train` methods.
=> Update docstrings of logs_for_job and train methods

tests/integ/test_byo_estimator.py, tests/integ/test_factorization_machines.py, tests/integ/test_kmeans.py, tests/integ/test_lda.py, tests/integ/test_linear_learner.py, tests/integ/test_mxnet_train.py, tests/integ/test_ntm.py, tests/integ/test_pca.py, tests/integ/test_randomcutforest.py, tests/integ/test_tf.py
Mark tests so that when we run tests continuously, we can use `pytest -v -m continuous_testing` to run only certain tests.
=> Mark tests for continuous testing

tests/integ/test_tf_cifar.py
Though this test has historically been relatively flaky, there was a recent change to the training steps that helped stabilize it, so it should be fine to include this test with our continuous testing. This test is important because it's currently our only one that tests distributed training and the only one to run on GPU instances.
=> Add TF CIFAR test to continuous testing set

src/sagemaker/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/local/image.py, src/sagemaker/local/local_session.py, src/sagemaker/model.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/session.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/model.py, src/sagemaker/utils.py, tests/component/test_mxnet_estimator.py, tests/component/test_tf_estimator.py, tests/unit/test_amazon_estimator.py, tests/unit/test_estimator.py, tests/unit/test_fm.py, tests/unit/test_fw_utils.py, tests/unit/test_image.py, tests/unit/test_kmeans.py, tests/unit/test_lda.py, tests/unit/test_linear_learner.py, tests/unit/test_local_session.py, tests/unit/test_model.py, tests/unit/test_mxnet.py, tests/unit/test_ntm.py, tests/unit/test_pca.py, tests/unit/test_randomcutforest.py, tests/unit/test_tf_estimator.py, tests/unit/test_utils.py
This change works when ~/.sagemaker/config.yaml has
local:
local_code: True
It depends on the container image supporting a local training script
instead of an s3 location.
=> Allow Local Mode to work with a local training script.

README.rst
*Issue #169*
Removed non-ascii (128) characters from README.rst that caused pip install to fail. Two non-breakable spaces (0xA0) were replaced by normal spaces.
=> Fix non-ascii chars in README.rst that broke pip install (issue #169)

README.rst
=> fix link to npy

CHANGELOG.rst, src/sagemaker/amazon/kmeans.py, tests/integ/test_kmeans.py, tests/unit/test_kmeans.py
The 1P KMeans algorithm is expecting the hyperparameter 'local_lloyd_max_iter' instead of 'local_lloyd_max_iterations', which we do currently. This causes the training to fail due to an invalid hyperparameter provided. The integration test never caught this because the correct class variable wasn't updated, which would have caught this. The variable that contains the value for the hyperparameter isn't an instance of the hyperparameter class, thus it ends up never calling the __set__ method within hyperparameter.py, which is used to correctly populate the _hyperparameters dict used within the hyperparameters().
Change hyperparameter key name to local_lloyd_max_iter. Add additional test within integration test asserting the hyperparameters …
=> Fix kmeans max_iterations hyperparameter

CHANGELOG.rst, src/sagemaker/estimator.py
job detail is always fetched by sagemaker_session. So passing it as an argument to EstimatorBase.attach() does not make sense.
=> Remove unused arg job_detail for EstimatorBase.attach()

CHANGELOG.rst, src/sagemaker/estimator.py, src/sagemaker/session.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_mxnet.py, tests/unit/test_session.py, tests/unit/test_tf_estimator.py
This has been supported in SageMaker but not in the Python SDK - this change allows users to add tags to training jobs.
=> Add tags for training jobs

README.rst
First go at some documentation for hyperparameter tuning job support in our README. I plan on adding some links to example notebooks, and I know some of the links are currently broken.
=> Add README section for hyperparameter tuning jobs

doc/analytics.rst, doc/index.rst, doc/tuner.rst, src/sagemaker/analytics.py, src/sagemaker/estimator.py, src/sagemaker/session.py, src/sagemaker/tuner.py
Updated docstrings for the new tuning/analytics code
=> Update hyperparameter tuning/analytics docstrings

README.rst
=> edited hyperparameter tuning section of readme

CHANGELOG.rst, src/sagemaker/amazon/lda.py, tests/conftest.py, tests/data/chainer_mnist/mnist.py, tests/data/iris/iris-dnn-classifier.py, tests/integ/test_tuner.py
Add integration tests for tuning jobs.
Add ability to attach for LDA jobs.
=> Add integ tests for tuning jobs

README.rst
Adding some more detail in light of #224 and other feedback
=> Add more detail to README for automatic model tuning

CHANGELOG.rst, src/sagemaker/estimator.py, tests/unit/test_estimator.py
Optionally, enable matching the behaviour when using sagemaker's default bucket where a key prefix is not permitted
*Issue #, if available:* 226
*Description of changes:* Addressing item 2.a on the issue
- [ x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ x] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a …
=> Allow code_location to have no key prefix

CHANGELOG.rst, README.rst, setup.py
=> Upgrade version to 1.4.2.

CHANGELOG.rst, src/sagemaker/local/image.py, src/sagemaker/model.py, src/sagemaker/predictor.py, tests/integ/test_local_mode.py, tests/unit/test_image.py, tests/unit/test_model.py
if a model is located in S3, download and extract it and then start
serving as usual. By overriding the SageMaker Session on any Model
Object, local serving is possible on pre-trained models.
=> Allow Local Serving of Models in S3

CHANGELOG.rst, README.rst, src/sagemaker/tuner.py, tests/integ/test_tuner.py, tests/unit/test_tuner.py
This was originally just writing an integ test for the BYO estimator case, but using an Amazon ML algorithm with the generic `Estimator` revealed that class can't be used with an algorithm that won't accept extra (unrecognized) hyperparameters. Since that generic class was created primarily for use with the Amazon ML algorithms that we don't have custom estimators for, I've added a new kwarg for not injecting the estimator class and module in a hyperparameter tuning job.
This PR does also include an integ test for the BYO estimator case. …
=> Add option for not including estimator metadata in hyperparameter tuning job

CHANGELOG.rst, src/sagemaker/tensorflow/estimator.py, tests/unit/test_tf_estimator.py
1, Fix unit tests
2, Join tensorboard thread when quit tensorboard
=> Fix tensorboard thread after fitting

CHANGELOG.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_chainer.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py
- This addresses problem 1 in https://github.com/aws/sagemaker-python-sdk/issues/226
- This relies on the tar_and_upload_dir's behaviour when given S3 paths for directory
- This updates MXNet, TensorFlow and Chainer frameworks
*Issue #, if available:* #226 
=> Let Framework models reuse code uploaded by Framework estimators

CHANGELOG.rst, src/sagemaker/chainer/model.py, src/sagemaker/fw_utils.py, src/sagemaker/model.py, src/sagemaker/mxnet/model.py, src/sagemaker/pytorch/model.py, src/sagemaker/tensorflow/model.py, tests/unit/test_fw_utils.py, tests/unit/test_model.py
- Extract repeated key_prefix calculation in different models (base, mxnet, tensorflow, chainer) into a common utility method in fw_utils.py
- The generated location now always respects the code_location prefix if present but it also concatenates either the model name or image-derived name to it
- This is related to 2.b in https://github.com/aws/sagemaker-python-sdk/issues/226
*Issue #, if available:* 226 point 2.b …
=> Unify generation of model uploaded code location

README.rst
Clarify what's needed to run unit and integration tests
=> Update README running tests section

README.rst
Add reference to PyTorch Estimators in the table of contents.
=> Add reference to PyTorch Estimators in the table of contents.

src/sagemaker/tensorflow/README.rst
This functionality has been present for awhile, but was never documented in the README, so adding that with this change
=> Add documentation for using channels when training with TF

CHANGELOG.rst, setup.py
Hi, I'm on a team at Amazon.
We've been successfully using sagemaker-1.1.3 with scipy 0.19.0. Now we'd like to continue using scipy 0.19.0 with the newest version of sagemaker.
This PR changes the minimum required scipy dependency from 1.0.0 to 0.19.0. We've applied this change to the internal Amazon Python-sagemaker (see version 1.1.3's 01_use_scipy_0_19_0_in_setup_py.patch file). We'd like the change applied to the github code so that we don't have to keep patching the code after it is pulled in to Amazon's package repo.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …
=> Change minimum required scipy dependency from 1.0.0 to 0.19.0

src/sagemaker/chainer/README.rst
=> fix code formatting for chainer readme

tests/unit/test_estimator.py
Since the job name generation depends on timestamps being unique, if the two names were generated quickly enough, the names could end up being the same despite the code's logic being correct. Adding a sleep statement in the test should fix this.
=> Fix unit test stability with testing job name generation

src/sagemaker/local/image.py
resolves #245 
When training locally the `train_data_location` (s3 uri) provided in the `.fit` method of estimator is downloaded recursively. While downloading if any folders is present in `train_data_location` we get an error as mentioned in #245. this PR fixes this issue
=> skip object download if its a folder [Bug fix] (Local mode)

CHANGELOG.rst, src/sagemaker/chainer/README.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/mxnet/README.rst, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/README.rst, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/estimator.py, tests/unit/test_chainer.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_tf_estimator.py
Chainer, Tensorflow and MXNet estimators can now pass
an image_name argument to the constructor to use that image
instead of the default sagemaker ones.
=> Allow Framework Estimators to use custom image

CHANGELOG.rst, src/sagemaker/model.py, src/sagemaker/session.py, tests/unit/test_model.py, tests/unit/test_session.py
Option to add Tags on SageMaker Endpoints. I'd like this option so that to tag endpoints for auditing and linking IDs of trained models to endpoints. The latter is very important because I can know which models are dpeloyed in production.
=> Add tags on endpoints

src/sagemaker/amazon/kmeans.py
We have a couple incorrect links, and one that never got filled in.
=> Fix links in KMeans docstring

tests/data/cifar_10/source/resnet_cifar_10.py
We've been seeing a lot of errors that say failure due to NaN loss. One suggestion from https://stackoverflow.com/questions/40050397/deep-learning-nan-loss-reasons is to use a lower number for learning rate.
=> Lower learning rate for TF cifar integ test

CHANGELOG.rst, src/sagemaker/local/image.py, tests/unit/test_image.py
#261 
In the local mode image code, we were incorrectly calling `e.message`, which doesn't work in Python. This change is to remedy that so RuntimeErrors get handled correctly.
=> Fix local mode error message

CHANGELOG.rst, src/sagemaker/analytics.py, src/sagemaker/estimator.py, src/sagemaker/utils.py, tests/unit/test_estimator.py, tests/unit/test_utils.py
*Issue* #273 
*Description of changes:*  When TrainingJobAnalytics object, the metric_names list is now optional.  If not specified, it will use all configured metrics.  To discover them, it looks for a hyperparameter tuning job associated with the training job, and finds the metric definitions there.
=> Make the metric_names list optional in TrainingJobAnalytics object.

tests/integ/test_chainer_train.py, tests/integ/test_pytorch_train.py
=> Mark pytorch and chainer tests to be used for continuous testing.

CHANGELOG.rst, README.rst, doc/index.rst, doc/transformer.rst, setup.py, src/sagemaker/estimator.py, src/sagemaker/job.py, src/sagemaker/session.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/transformer.py, tests/unit/test_estimator.py, tests/unit/test_session.py, tests/unit/test_transformer.py
* Add a `Transformer` class for creating batch transform jobs
* Add a section to the TF README about using pipe mode
=> Add support for Batch Transform and update README with TF Pipe Mode

CHANGELOG.rst, src/sagemaker/session.py, tests/unit/test_session.py
Currently an exception is raised if a model already exists. This change instead logs a warning that an existing model is being used, but allows the existing model to be used in place of needing to create a new one.
=> Use existing model instead of failing during Session.create_model()

tests/unit/test_session.py, tests/unit/test_tf_estimator.py
This change speeds up our unit tests.
Current test-run duration:
real    0m49.736s
user    0m6.219s
sys     0m1.089s
With this change:
real    0m9.447s
user    0m6.856s
sys     0m1.115s
=> Mock time.sleep in unit tests

README.rst
If there is an existing model it can be deployed locally
using local mode. This feature is already present but there
is no example in the README.
=> Add an example for local mode deployment of models

CHANGELOG.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_tf_estimator.py
#303 
This change allows for a different role to be specified when creating a `Model` or `Transformer` from an `Estimator`. Still defaults to the estimator's role if nothing's specified.
=> Allow Model and Transformer to use a different role from the Estimator

tests/integ/test_pytorch_train.py, tests/integ/timeout.py
=> Deleting endpoint for PyTorch test, retrying endpoint deletion 3 times

CHANGELOG.rst, README.rst, setup.py, src/sagemaker/tensorflow/predictor.py, tests/unit/test_tf_predictor.py
Bug fix for https://github.com/aws/sagemaker-python-sdk/issues/123
- added test to reproduce issue
- parsing response from TF serving
=> Bug fix: https://github.com/aws/sagemaker-python-sdk/issues/123

README.rst
#311 
Doc update with supporting os.
=> Update readme with supporting os

src/sagemaker/tuner.py
One of the docstrings was missing an arg that got added later, though its usage is already documented in the README
=> Add missing arg to Tuner docstring

tests/integ/test_tf_cifar.py
*Description of changes:* This test frequently fails in FRA, seemingly due to difficulty getting p2.xlarge (takes more than 20 minutes to start in some cases), causing spurious canary failures.
=> modify cifar test to avoid timeouts

CHANGELOG.rst, src/sagemaker/session.py, src/sagemaker/utils.py, tests/unit/test_session.py, tests/unit/test_utils.py
* Generate better training job status report
With this feature while waiting for a training job to finish user will be able
see more detailed status from the output.
The output is in the format of '<StarTime> <SecondaryStatus> <StatusMessage>...'
=> Generate better training job status report

src/sagemaker/mxnet/README.rst
* Change the default channel name from 'train' to 'training'
*Issue #332, if available:*
=> Fix default input channel name in mxnet README

src/sagemaker/chainer/README.rst, src/sagemaker/mxnet/README.rst, src/sagemaker/pytorch/README.rst, src/sagemaker/tensorflow/README.rst
https://github.com/aws/sagemaker-python-sdk/issues/312
README is not accurate for usage of source_dir. The entry point file should be in source_dir too.
=> Update doc for parameter source_dir

src/sagemaker/chainer/README.rst, src/sagemaker/mxnet/README.rst, src/sagemaker/pytorch/README.rst, src/sagemaker/tensorflow/README.rst
Fixed typo in Tensorflow README - train_max_run argument in the Tensorflow constructor is in seconds, not hours
=> Typo in READMEs regarding train_max_run parameter

CHANGELOG.rst, README.rst, setup.py, src/sagemaker/mxnet/README.rst, src/sagemaker/mxnet/defaults.py, tests/conftest.py
=> Add MXNet 1.2.1 and bump SDK to v1.9.0

CHANGELOG.rst, src/sagemaker/amazon/common.py, tests/unit/test_common.py
#320 
The record serializer processes reshaped arrays.
A unit test for the corresponding one-dimensional case added.
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ x ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ x ] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a description of my changes (if …
=> Make record serializer accept one-dimensional arrays (#320)

src/sagemaker/tensorflow/README.rst
Add documentation about how to disable MKL-DNN optimization for tensroflow.
=> How to disable MKL-DNN optimization for tensroflow.

src/sagemaker/tensorflow/README.rst
* removed duplicate `PipeModeDataset` instantiation
* wrapped usage in `train_input_fn` to match other examples
- [ X ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
=> PipeModeDataset code block example improvements

README.rst
Edited the readme for clarity/style.
Please review, esp hyperparameter tuning and batch transform sections for technical accuracy.
=> edited general repo readme

tests/integ/test_tf_cifar.py
Increasing training timeout to be consistent with overall timeout.
=> Increase max_runtime for tf cifar

tests/conftest.py
Freeze the framework integ test to latest version.
=> Freeze framework integ test to latest version

CHANGELOG.rst, src/sagemaker/estimator.py, src/sagemaker/job.py, src/sagemaker/session.py, tests/integ/test_tf.py, tests/integ/vpc_utils.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_session.py, tests/unit/test_tf_estimator.py
CreateTraningJob api supports vpc. This change adds vpc config as an optional
argument to Estimator.
=> Add VPC config to estimator for training job creation

src/sagemaker/session.py
Increase read timeout for SageMaker runtime, as the hosting endpoint has a time limit on how long an inference can take.
=> Increase read timeout for sagemaker runtime

CHANGELOG.rst, README.rst, setup.py
=> Bump version to 1.9.1

README.rst, src/sagemaker/pytorch/README.rst
Just some minor things I noticed while reading the READMEs. Also, figured we should remove the explicit SDK version reference because it's so easy for that to become outdated.
=> Fix formatting in PyTorch README and remove SDK version in general README

CHANGELOG.rst, README.rst, setup.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/defaults.py, tests/conftest.py
1. Support tensorflow 1.9
2. Bump version to 1.9.2
=> Support tensorflow 1.9 and bump version to 1.9.2

src/sagemaker/session.py
Correct docs to reflect that upload_data would create only default bucket.
Issue #371 
=> Correct docs to reflect that upload_data would create only default bucket.

src/sagemaker/session.py, tests/integ/__init__.py, tests/integ/test_local_mode.py, tests/integ/test_tf.py, tests/integ/test_tf_cifar.py, tests/integ/test_tf_keras.py, tests/integ/test_tuner.py
Do not run tensorflow integ tests when running python 3 since we do not have python 3 image for tensorflow.
=> Do not run tensorflow integ tests when running python 3.

tests/integ/test_chainer_train.py, tests/integ/test_local_mode.py, tests/integ/test_mxnet_train.py, tests/integ/test_pytorch_train.py, tests/integ/test_tuner.py
Add the ability to run chainer and mxnet integ tests for python 2 and 3 images by using python version of the environment.
=> Run chainer and mxnet integ tests based on environment python version.

src/sagemaker/chainer/README.rst
noticed this when I was looking at the README. figured I might as well put out a quick PR.
=> Add 4.1.0 to supported Chainer version list

CHANGELOG.rst, README.rst, setup.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/defaults.py, tests/conftest.py
1. Add support for tensorflow 1.10.10
2. Bump version up to 1.9.4
=> Add support for tensorflow 1.10.0 and bump version up to 1.9.4

src/sagemaker/amazon/knn.py, src/sagemaker/estimator.py, src/sagemaker/job.py, src/sagemaker/session.py, tests/unit/test_estimator.py, tests/unit/test_job.py
https://github.com/aws/sagemaker-python-sdk/issues/383
Add missing parameter - see: https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateTrainingJob.html
=> Add train_volume_kms_key parameter

src/sagemaker/mxnet/README.rst
This change adds a warning to the README about the upcoming MXNet training script format, in addition to basic instructions of what kind of changes will be needed once the format is changed.
I didn't use a ReST admonition for the warning because [GitHub won't render them](https://github.com/github/markup/issues/68).
=> Document upcoming MXNet training script format

src/sagemaker/tensorflow/README.rst
Add docs on TensorFlowModel usage (deploying directly from model artifacts).
=> Add docs on TensorFlowModel class usage + requirements file for serving

src/sagemaker/fw_utils.py, tests/unit/test_fw_utils.py
Add gov cloud account number for framework
=> Add gov cloud account number for framework

CHANGELOG.rst, setup.py
* bug-fix: setting health check timeout limit on local mode to 30s
* bug-fix: make Hyperparameters in local mode optional.
* enhancement: add support for volume KMS key to Transformer
* feature: add support for GovCloud
=> Bump version to 1.11.0

CHANGELOG.rst, src/sagemaker/local/image.py, tests/unit/test_image.py
SageMaker Training sets various environment variables for every training job, while Local Mode replicates none of these. This change adds the environment variables for the AWS region and training job name.
=> Local mode pass training env var

CHANGELOG.rst, src/sagemaker/local/entities.py, src/sagemaker/local/image.py, src/sagemaker/local/local_session.py, tests/unit/test_image.py
https://github.com/aws/sagemaker-python-sdk/issues/421
Pass in the job_name param for local mode instead of reading from hyperparameters.
=> Add job_name parameter for local mode

CHANGELOG.rst, src/sagemaker/utils.py, tests/unit/test_utils.py
*Issue #, if available
After this change the output of training job looks like this:
INFO:sagemaker:Creating training-job with name: sagemaker-mxnet-2018-10-11-22-39-27-822
2018-10-11 22:39:29 Starting - Starting the training job...
2018-10-11 22:39:29 Starting - Launching requested ML instances......
2018-10-11 22:40:30 Starting - Preparing the instances for training......
2018-10-11 22:41:53 Downloading - Downloading input data.. …
=> Add timestamp to secondary status for traning job logs

CHANGELOG.rst, setup.py, src/sagemaker/local/image.py, tests/unit/test_image.py
Local Mode with GPU relied on the environment having
the nvidia runtime as default. This changes that so that
runtime: nvidia is passed in docker-compose.yaml allowing
local mode to work with a vanilla nvidia-docker2 installation.
=> support nvidia-docker2 natively in local mode.

tests/integ/test_local_mode.py
Add a lock for the transformer test, similar to the serving tests
as the serving container will still run on the same port. Also remove
this test from the continuous testing suite.
=> Improve local mode transformer test

CHANGELOG.rst, src/sagemaker/local/image.py, src/sagemaker/utils.py, tests/unit/test_image.py
*Issue #421 , if available:*
We had the default value flipped for additional_env_vars and additional_volumes. This change also adds a unit test for this code path.
=> Fix bug in local mode

CHANGELOG.rst, README.rst, src/sagemaker/chainer/README.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/mxnet/README.rst, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/README.rst, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/estimator.py
In the near future, we will make framework_version a required argument for all framework estimators. This change adds a warning if framework_version is not currently set.
=> Add warning if framework_version is not set

src/sagemaker/chainer/README.rst, src/sagemaker/mxnet/README.rst, src/sagemaker/pytorch/README.rst
remove request size limit in doc comments
=> remove request size limit in doc comments

setup.py, src/sagemaker/__init__.py, tests/unit/test_init.py
https://github.com/aws/sagemaker-python-sdk/issues/434
add PEP-396 version attribute to sagemaker module
=> add PEP-396 version attribute to sagemaker module

CHANGELOG.rst, README.rst, src/sagemaker/__init__.py, src/sagemaker/fw_utils.py, src/sagemaker/session.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/defaults.py, tests/conftest.py, tests/data/cifar_10/source/keras_cnn_cifar_10.py, tests/integ/test_tf_keras.py, tests/integ/test_tuner.py, tests/integ/timeout.py
- add support for TensorFlow 1.11.0 
- bump library version up to 1.12.0
=> Add support for TensorFlow 1.11.0 and bump library version up to 1.12.0

CHANGELOG.rst, README.rst, src/sagemaker/__init__.py, src/sagemaker/amazon/amazon_estimator.py, src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/job.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/session.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_estimator.py, tests/unit/test_job.py, tests/unit/test_session.py
This code change adds the following changes to Estimators:
- Added the ability to set the input mode on each channel. The input mode will default to whatever's set on the Estimator, but if a channel specifies its own input mode it will override that value.
- Added two new parameters to the Estimator class: model_uri, which points to pre-existing model artifacts in S3 or locally, and model_channel_name (default: 'model'). When both are set and a user calls Estimator.fit(), the estimator will create a new input channel under that name, pointing to the contents of model_uri and using SageMaker's recommended settings for model artifact consumption.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If …
=> Add model parameters to Estimator, and bump library version to 1.13.0

CHANGELOG.rst, src/sagemaker/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/local/data.py, src/sagemaker/local/entities.py, src/sagemaker/local/image.py, src/sagemaker/local/local_session.py, src/sagemaker/local/utils.py, src/sagemaker/session.py, src/sagemaker/utils.py, tests/integ/test_local_mode.py, tests/unit/test_estimator.py, tests/unit/test_image.py, tests/unit/test_local_entities.py, tests/unit/test_local_utils.py, tests/unit/test_utils.py, tox.ini
Can be either file:// or s3:// - This also changes the default
behavior of local mode to use the SDK provided default S3 bucket
if nothing is passed. This makes it easier for customers to create
models in SageMaker too since their Model Artifacts will already be
a tarfile in S3.
=> local mode: support output_path

src/sagemaker/fw_utils.py, src/sagemaker/tensorflow/serving.py, tests/integ/test_tfs.py, tests/unit/test_fw_utils.py, tests/unit/test_tfs.py
simplify create_image_uri function
add failure test case for tensorflow serving predictor
=> simplify create_image_uri function

CHANGELOG.rst, setup.py
docker-compose 1.23 has moved to a newer version of requests
which allows us to remove the upper bound on urllib3 that
was causing a lot of problems for everyone.
- [ x] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a description of my changes (if appropriate) …
=> build: upgrade docker-compose to 1.23

CHANGELOG.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_chainer.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_tf_estimator.py
This is in accordance with our new strategy around this since we're no longer making `framework_version` completely mandatory
=> Update empty framework_version warning

CHANGELOG.rst, src/sagemaker/session.py
=> Remove hardcoded 'training' in error message for checking job status

CHANGELOG.rst
=> Add missing changelog entry for 1.14.2

tests/integ/__init__.py, tests/integ/test_tfs.py
- add canary tests for tensorflow serving container
=> add canary tests for tf serving container

src/sagemaker/job.py, src/sagemaker/session.py, src/sagemaker/utils.py, src/sagemaker/workflow/__init__.py, src/sagemaker/workflow/airflow.py, tests/unit/test_airflow.py
1. Add sagemaker.workflow.airflow module that has function get_training_config to export boto create_training_job config from python sdk estimator.
2. Add corresponding unit tests that test the config exported from BYO Estimator, 1P Estimator and Framework.
3. Bypass some validations in job.py to enable usage of Jinja templating in arguments.
=> Add airflow module that could export training config

CHANGELOG.rst, src/sagemaker/analytics.py, tests/unit/test_estimator.py
N/A
Remove MetricDefinition lookup via tuning job in TrainingJobAnalytics. MetricDefinition is now available on all built-in algorithms.
=> Remove MetricDefinition lookup via tuning job in TrainingJobAnalytics

CHANGELOG.rst, doc/estimators.rst
Given our use of `**kwargs` with our estimators, we need to have our base classes in our API docs
=> Add the estimator base classes to API docs

CHANGELOG.rst, src/sagemaker/utils.py, src/sagemaker/workflow/airflow.py, tests/unit/test_airflow.py
1. Improve airflow_name_from_base, add limits for length and auto trim naming to fit length.
2. Fix missing hyperparameter mini_batch_size from training config.
3. Add tuning_config API to export tuning config from a tuner.
=> Add airflow tuning config export API

CHANGELOG.rst, src/sagemaker/session.py, src/sagemaker/tuner.py, tests/integ/test_tuner.py, tests/unit/test_session.py, tests/unit/test_tuner.py
This change adds sdk support for:
* Transfer Learning Warm Start Tuning Job
* Identical Data and Algorithm Warm Start Tuning Job
=> Add support for automatic model tuner's warm start jobs

CHANGELOG.rst, setup.py, src/sagemaker/session.py, src/sagemaker/tuner.py, tests/unit/test_tuner.py
Make inputs optional for hyperparameter tuning job.
=> Make inputs optional for hyperparameter tuning job.

CHANGELOG.rst, src/sagemaker/chainer/README.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/model.py, src/sagemaker/mxnet/README.rst, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/README.rst, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/estimator.py, tests/data/pytorch_source_dirs/train.py, tests/integ/test_source_dirs.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_fw_utils.py, tests/unit/test_model.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_tf_estimator.py, tests/unit/test_transformer.py
Introduces the following argument in the Estimator and Model classes.
- ``**dependencies** (list[str])`` A list of paths to directories (absolute or relative) with
any additional libraries that will be exported to the container (default: []).
The library folders will be copied to SageMaker in the same folder where the entrypoint is copied.
If the ```source_dir``` points to S3, code will be uploaded and the S3 location will be used
instead. Example:
The following call
>>> Estimator(entry_point='train.py', lib_dirs=['my/libs/common', 'virtual-env'])
results in the following inside the container:
>>> $ ls
>>> opt/ml/code
>>>     ├── train.py
>>>     ├── common
>>>     └── virtual-env
_Put an `x` in the boxes that apply. You can also fill these out after creating the …
=> Add support for additional libraries in the Estimator

CHANGELOG.rst, src/sagemaker/estimator.py, src/sagemaker/workflow/airflow.py, tests/unit/test_airflow.py
The docstring for code_location is not correct. code_location can be a S3 URI, not just a bucket. And I need to change related Airflow API because it treats code_location as a bucket.
=> Make code_location to be S3 URI instead of bucket in training_config()

CHANGELOG.rst
The feature of tensorflow script mode and python3 support from 1.5.0 is missing in changelog. This PR adds it back.
=> Add missing feature 1.5.0 in change log

CHANGELOG.rst, doc/conf.py, src/sagemaker/__init__.py, src/sagemaker/fw_utils.py, tests/integ/test_chainer_train.py, tests/integ/test_mxnet_train.py, tests/integ/test_pytorch_train.py, tests/integ/test_tf.py, tests/unit/test_fw_utils.py
- fix FileNotFoundError for entry_point without source_dir
=> fix FileNotFoundError for entry_point without source_dir

README.rst, src/sagemaker/mxnet/README.rst, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/deploying_tensorflow_serving.rst
Add versions for EI along with code example.
=> Eia fw versions

CHANGELOG.rst, doc/conf.py, setup.py, src/sagemaker/__init__.py
Update version to 1.16.1.post1
=> Update version to 1.16.1.post1

tests/integ/test_inference_pipeline.py
Removing the logic of skipping the integration test for Inference Pipeline.
I have run the integration test for both Python version locally and both ran fine.
=> Removing the logic of skipping inference pipeline integration test

src/sagemaker/fw_utils.py, src/sagemaker/tensorflow/serving.py, src/sagemaker/utils.py, tests/integ/local_mode_utils.py, tests/integ/test_local_mode.py, tests/integ/test_source_dirs.py, tests/integ/test_tuner.py, tests/unit/test_utils.py, tox.ini
- fix flaky tests
- run pylint concurrently
- use raw string (r'...') for a regex
- remove out of date comment
=> fix flaky tests

tests/integ/test_inference_pipeline.py
- fix region error in test
- fix line lengths, imports
=> fix region error in test

CHANGELOG.rst, src/sagemaker/local/entities.py, src/sagemaker/local/image.py
Increase timeout of docker-compose to 120 along with ping for serving. Increase the interval between pings from 1 to 5.
=> increase docker-compose timeout to 120 and ping interval to 5

CHANGELOG.rst, doc/index.rst, doc/sagemaker.workflow.airflow.rst
1. Add API doc for Airflow
2. Fix API doc for RL
=> Add API doc for Airflow

tests/integ/__init__.py, tests/integ/test_byo_estimator.py, tests/integ/test_chainer_train.py, tests/integ/test_factorization_machines.py, tests/integ/test_ipinsights.py, tests/integ/test_kmeans.py, tests/integ/test_knn.py, tests/integ/test_lda.py, tests/integ/test_linear_learner.py, tests/integ/test_ntm.py, tests/integ/test_object2vec.py, tests/integ/test_pca.py, tests/integ/test_pytorch_train.py, tests/integ/test_randomcutforest.py, tests/integ/test_tf_cifar.py, tests/integ/test_tf_keras.py, tests/integ/test_tfs.py
fix additional p2 and job/endpoint naming issues
=> fix additional p2 and job/endpoint naming issues

README.rst, src/sagemaker/sklearn/README.rst
Add Scikit-learn Estimator in Table of contents in root README.rst
Add Scikit-learn Estimator description next to other framework descriptions in README.rst
Fix Sciki-learn documenetation under /src/sagemaker/sklearn
=> Sklearn docs 2018 11 12

doc/index.rst, doc/sagemaker.chainer.rst, doc/sagemaker.pytorch.rst, doc/sagemaker.rl.rst, doc/sagemaker.tensorflow.rst, src/sagemaker/rl/estimator.py
Add readme docs for chainer, pytorch and rl.
=> Add readme docs for chainer, pytorch, rl and tensorflow serving.

CHANGELOG.rst, README.rst, doc/conf.py, setup.py, src/sagemaker/__init__.py, src/sagemaker/session.py, src/sagemaker/tuner.py, tests/integ/test_tuner.py, tests/unit/test_session.py, tests/unit/test_tuner.py
=> Add support for Hyperparameter Tuning Early Stopping

CHANGELOG.rst, src/sagemaker/utils.py, tests/unit/test_airflow.py
… in retry
Now during Airflow operator retry, the job names (training/model/tuning/transform/endpoint-config/endpoint) are same as before. So there will be naming collision and all retries will fail for job already existed. This PR appends a retry id to the default job names. Then different attempt of operator will have different job_name which avoids failure due to naming collisions. …
=> Append retry id to default Airflow job name to avoid naming collision in retry

CHANGELOG.rst, src/sagemaker/local/image.py, src/sagemaker/model.py, src/sagemaker/rl/estimator.py
https://github.com/aws/sagemaker-python-sdk/issues/554
Moved sagemaker_s3_output to model class.
There was a dependency error, in that a file in the local directory was taking dependency on a file in the rl directory.
I could have also allowed the rl directory to be properly scoped so that all directories have access, however that doesn't seem like the right call, as parameters and what not should be generic and not specific.
Reproduced customer error on a notebook instance and installed changes and tested properly.
It is difficult to write a test that catches this, as there seems to be weird interaction with tox and how our tests import classes. For now this is a quick fix.
Refactoring these parameters to a common class in the sagemaker …
=> move sagemaker_s3_output to model class

CHANGELOG.rst, README.rst, src/sagemaker/pytorch/README.rst, src/sagemaker/pytorch/defaults.py, src/sagemaker/pytorch/estimator.py, tests/conftest.py
Update latest version of PyTorch to 1.0
=> Update latest version of PyTorch to 1.0

CHANGELOG.rst, src/sagemaker/chainer/__init__.py, src/sagemaker/local/__init__.py, src/sagemaker/pytorch/__init__.py, src/sagemaker/rl/__init__.py, src/sagemaker/sklearn/__init__.py, src/sagemaker/sparkml/__init__.py
*Issue #, if available:* #553
Removed all the instances I could find based on [this search](https://github.com/aws/sagemaker-python-sdk/search?q=__all__&unscoped_q=__all__)
=> Remove __all__ from __init__.py files

CHANGELOG.rst, src/sagemaker/utils.py, tests/unit/test_airflow.py
Just appending retry id after a job name is not a good solution for solving naming collisions in Airflow operators. It may add more risk for users to manage jobs across operators. So revert the changes in:
https://github.com/aws/sagemaker-python-sdk/commit/2ad6c1da29eba210a1fcd51156d9b5e7ab0627f5
=> Remove retry_id in Airflow job name, needs more design on this

tests/integ/__init__.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf.py
Enabling the tests specified here as canaries: https://github.com/aws/sagemaker-python-sdk/pull/527
The regions were determined based on: https://aws.amazon.com/machine-learning/elastic-inference/pricing/
=> enable canary for EI supported regions

CHANGELOG.rst, README.rst, src/sagemaker/tuner.py, tests/unit/test_tuner.py
When a `HyperparameterTuner` is created using `attach()`, the tuner needs to pick an Estimator class to use. It looks for the following things (in this order):
1. if the hyperparameters have class metadata (e.g. a path like sagemaker.tensorflow.estimator.TensorFlow)
1. if the image being used corresponds to one of our 1P estimators
1. if nothing is present, in which case it just uses the generic Estimator class
These are the following scenarios I see currently:
1. Framework (e.g. TensorFlow): defaults to including the class, and our framework images can handle arbitrary hyperparameters. No problem.
1. 1P with a dedicated Python SDK estimator (e.g. kNN, NTM): defaults to not including the class and determines the estimator class based on the image name. No …
=> Make include_cls_metadata default to False for everything except Frameworks

CHANGELOG.rst, README.rst, doc/conf.py, src/sagemaker/__init__.py, src/sagemaker/algorithm.py, src/sagemaker/estimator.py, src/sagemaker/session.py, src/sagemaker/tuner.py, tests/integ/test_tf.py, tests/integ/vpc_test_utils.py, tests/unit/test_algorithm.py, tests/unit/test_estimator.py, tests/unit/test_session.py, tests/unit/test_tuner.py
We're supporting the  ``encrypt_inter_container_traffic`` flag while instantiating ``Estimator`` objects. Setting this flag as **``True``** in the VPC Mode will create training jobs with inter-container traffic encrypted between them.
*Testing*
``tox tests/unit``
``python setup.py sdist && cd dist``
``pip install --upgrade sagemaker-1.17.0.tar.gz && cd ..``
``pytest tests/integ``
=> Supporting inter-container traffic encryption flag

CHANGELOG.rst, README.rst, src/sagemaker/tensorflow/README.rst, tests/conftest.py
Update version for EI TF to 1.12
=> update EI version for TF to 1.12

CHANGELOG.rst, doc/conf.py, src/sagemaker/__init__.py
=> Bumping up version to 1.18.0 for horovod release

CHANGELOG.rst, src/sagemaker/user_agent.py, tests/unit/test_session.py
SageMaker Notebook Instances provide the version ID as a file on a
Notebook Instance.  In order to enhance version adoption from within
SageMaker, provide an extra segment to the user_agent supplied to the
boto3 ClientConfig.
=> Prepend SageMaker Notebook Instance version ID to boto3 User Agent

doc/using_mxnet.rst, src/sagemaker/mxnet/README.rst
In reference to https://github.com/aws/sagemaker-mxnet-container/pull/65#discussion_r252494747. Recommended to move documentation update from https://github.com/aws/sagemaker-mxnet-container to here.
Add detail on loading model for EI in model loading section.
=> Update EI section in regards to model loading within MXNet README

CHANGELOG.rst, doc/using_mxnet.rst, src/sagemaker/mxnet/README.rst
...and some other tweaks. The weirdness around how I formatted the ToC title is because GH doesn't seem to render the ToC directive in a nice way (i.e. the title is just normal paragraph text).
Update: things got a little messy as I was trying to merge in master. So the Sphinx file should be basically the same as the README. The reason it looks like the entire file was changed is because the Sphinx file had Windows-style line endings (CRLF). …
=> Update information about saving models in the MXNet README

CHANGELOG.rst, README.rst
=> Switch ReadTheDocs links to stable (instead of latest)

src/sagemaker/tensorflow/deploying_python.rst, src/sagemaker/tensorflow/deploying_tensorflow_serving.rst
https://github.com/aws/sagemaker-python-sdk/pull/515/
Moved incorrect EI TFS docs from the Rest API TFS docs to the Python TFS docs.
=> move EI docs from TFS Rest API docs to TFS python docs

tests/conftest.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf.py
Allow the ei versions for TF and MXNet to be configurable in the integration tests.
=> allow ei versions to be configurable in integ test

CHANGELOG.rst, doc/using_mxnet.rst, src/sagemaker/mxnet/README.rst
* The `input_fn` method signature has an extra arg (`model`), which causes a confusing error of `TypeError: input_fn() missing 1 required positional argument: 'model'`.
* The README also makes no mention of writing a custom `transform_fn` which has been supported with all versions of our MXNet images.
* I also made some more wording tweaks along the way.
* the changes to the README and Sphinx doc should be identical …
=> Add section about transform_fn and fix input_fn signature in MXNet README

CHANGELOG.rst, README.rst, src/sagemaker/local/local_session.py, src/sagemaker/model.py, src/sagemaker/predictor.py, src/sagemaker/session.py, src/sagemaker/transformer.py, tests/integ/test_transformer.py, tests/integ/timeout.py, tests/unit/test_local_session.py, tests/unit/test_model.py, tests/unit/test_predictor.py, tests/unit/test_session.py, tests/unit/test_transformer.py
… transformer to delete model.
#447 
- Add support to delete endpoint configuration by default within delete_endpoint() to predictor class.
- Add delete_model() to transformer class. Instead of linking a model class to it, the transformer class directly calls session's delete_model() method because it already has access to the model_name. We don't want to pass in a model object on top of that. We don't want to construct a model object here either because that requires extra parameters, such as the s3 path to the model artifacts, while we can just utilize the model_name variable.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
=> Add new APIs to clean up resources from predictor and transformer.

src/sagemaker/sklearn/defaults.py, src/sagemaker/sklearn/estimator.py, src/sagemaker/sklearn/model.py, tests/unit/test_sklearn.py
The SKLearnModel was defaulting to the wrong account because it was still using the fw_utils.py file methods. MLeaps and SKLearn use its own framework registry (since they use different accounts).
Also fixed exception messages.
=> Fix SKLearnModel default account in image uri.

CHANGELOG.rst, README.rst, setup.py
The README doc is broken in PyPI: https://pypi.org/project/sagemaker/1.18.3/
The code snippet below was missing a newline.
Twine provides the ability to check if your readme will render properly on PyPI.
https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup
https://github.com/aws/sagemaker-tensorflow-extensions/pull/32
Added newline in code snippet portion in README.
Bumped to 1.18.3.post1
Going to add the step in our CI.
=== TEST ===
twine check dist/*
/anaconda3/lib/python3.6/site-packages/readme_renderer/markdown.py:38: UserWarning: Markdown renderers are not available. Install 'readme_render[md]' to enable Markdown rendering.
warnings.warn(_EXTRA_WARNING)
Checking distribution …
=> fix README for PyPI

CHANGELOG.rst, tox.ini
Build the sphinx docs similar to RTD build process: https://readthedocs.org/projects/sagemaker/builds/8577862/
Added new env within tox which handles building the sphinx-docs similar to that of RTD.
=> add sphinx-build in tox

CHANGELOG.rst, src/sagemaker/estimator.py, tests/unit/test_estimator.py
- https://github.com/aws/sagemaker-python-sdk/issues/657
- Estimator.attach should work with a job without hps
=> Estimator.attach should work with a job without hps

CHANGELOG.rst, src/sagemaker/fw_utils.py, src/sagemaker/tensorflow/deploying_python.rst, src/sagemaker/tensorflow/deploying_tensorflow_serving.rst, src/sagemaker/tensorflow/serving.py, tests/unit/test_tfs.py
https://github.com/awslabs/amazon-sagemaker-examples/issues/613#issuecomment-463937167
https://github.com/aws/sagemaker-python-sdk/commit/4732545bd9d1880390b3951c9b941f2bb62d6e5a#r32336726
Pass in accelerator_type into the deploy() for the REST API TFS Model object, which should result in an exception, as EI for the TFS container isn't supported.
I can also change it so that the failure happens on SageMaker side instead of client side as the image doesn't exist and is currently in the works, however this is to mitigate users from pulling down CPU or GPU only images when expecting EI images.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> pass accelerator_type for tfs model

.travis.yml, README.rst, buildspec.yml, setup.py, tests/integ/kms_utils.py, tox.ini
=> configure for codebuild pr builds

CHANGELOG.rst, src/sagemaker/rl/README.rst, src/sagemaker/rl/estimator.py, tests/conftest.py, tests/integ/test_rl.py, tests/unit/test_rl.py
=> Update coach version for to 0.11.1 tensorflow.

tests/unit/test_image.py
the unit tests were failing with Python 3.6 with:
```
E               TypeError: join() argument must be str or bytes, not 'Mock'
```
not entirely sure what changed, but the changes in this PR made them pass on my laptop
=> Fix local image unit tests

tests/integ/kms_utils.py
https://docs.aws.amazon.com/kms/latest/developerguide/policy-conditions.html#conditions-kms-grant-is-for-aws-resource
This page shows the kms:GrantIsForAWSResource is only set to True in specific AWS services where SageMaker is not one of it. We should remove it in the policy.
=> Remove condition for kms resource policy

tests/integ/marketplace_utils.py, tests/integ/test_marketplace.py
Marketplace algorithm and model package have different ARN in different regions. This PR handles this case.
=> Add region account map to marketplace test for canary

CHANGELOG.rst, src/sagemaker/algorithm.py, tests/unit/test_algorithm.py
SupportedHyperParameters are optional:
https://aws.amazon.com/marketplace/pp/prodview-xomyqkqtxdude?qid=1552064946028&sr=0-1&ref_=srh_res_product_title
=> Make SupportedHyperParameters optional.

src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/session.py, tests/unit/test_create_deploy_entities.py, tests/unit/test_estimator.py, tests/unit/test_session.py
- https://github.com/aws/sagemaker-python-sdk/issues/586
Propagate Tags from estimator to model, endpoint, and endpoint config
=> Propagate Tags from estimator to model, endpoint, and endpoint config

CHANGELOG.rst, doc/overview.rst
Updated documentation of inference pipelines in /doc/overview.rst with content from andremoeller.
- [x ] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a description of my changes (if appropriate)
- [x ] I have updated any necessary [documentation](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) (if appropriate)
By …
=> Update inference pipelines documentation

src/sagemaker/amazon/amazon_estimator.py, src/sagemaker/fw_registry.py, src/sagemaker/fw_utils.py, src/sagemaker/utils.py, tests/unit/test_amazon_estimator.py, tests/unit/test_fw_registry.py, tests/unit/test_fw_utils.py
Add account number for govcloud with unit tests
=> change: add account number and unit tests for govcloud

tests/integ/test_horovod.py, tests/integ/test_local_mode.py, tests/integ/test_source_dirs.py
Local mode tests are special in the integration tests since there are many restrictions for them to run in parallel. For example, there's at most one local endpoint on a single instance. So to better manage them in canary tests, this PR adds pytest mark of 'local_mode' to all integ tests using local mode.
=> change: add pytest marks for integ tests using local mode

src/sagemaker/fw_utils.py, src/sagemaker/local/image.py, src/sagemaker/utils.py, tests/unit/test_fw_utils.py, tests/unit/test_image.py
Apparently, in https://github.com/aws/sagemaker-python-sdk/pull/713 I did not notice that there's ECR URI validation using regular expression. Update that part with unit tests to make things work.
=> fix: fix ECR URI validation

src/sagemaker/tuner.py
The documentation at for `attach()` looks like this:
I believe the intention was to only have `deploy()` highlighted.
According to [spinx documentation](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html):
`it (markups) must be separated from surrounding text by non-word characters. Use a backslash escaped space to work around that: thisis\ *one*\ word.` …
=> documentation: fix formatting for HyperparameterTuner.attach()

src/sagemaker/amazon/linear_learner.py
Fix the mis-spelling of argument unbias_label in linear learner docstrings.
=> doc: fix typo of argument spelling in linear learner docstrings

CONTRIBUTING.md
add info about test-friendly names to contributing guidelines
=> doc: add info about unique job names

buildspec.yml
- restore notebook test in PR builds
- also separate py27,py36 integ tests so build can fail faster
=> restore notebook test

src/sagemaker/predictor.py, tests/unit/test_predictor.py
a counterpart to our CSV serializer
=> change: add csv deserializer

buildspec.yml, tests/integ/test_byo_estimator.py, tests/integ/test_factorization_machines.py, tests/integ/test_horovod.py, tests/integ/test_ipinsights.py, tests/integ/test_kmeans.py, tests/integ/test_knn.py, tests/integ/test_lda.py, tests/integ/test_linear_learner.py, tests/integ/test_ntm.py, tests/integ/test_object2vec.py, tests/integ/test_pca.py, tests/integ/test_randomcutforest.py
- use unique names for training jobs created by integ tests. 
- fixes some transient ResourceInUse errors
=> fix: use unique names for test training jobs

tests/integ/test_horovod.py
=> fix: skip horovod p3 test in region with no p3

src/sagemaker/local/image.py, tests/integ/test_local_mode.py, tests/unit/test_image.py
see code comments in https://github.com/aws/sagemaker-chainer-container/pull/76 and https://github.com/aws/sagemaker-pytorch-container/pull/88
SageMaker Training exports model/output artifacts even when the training job fails (though it didn't when Local Mode was initially released). This change makes Local Mode emulate that behavior.
=> change: make Local Mode export artifacts even after failure

setup.py, tests/integ/test_tf_script_mode.py, tests/unit/test_predictor.py
=> fix: skip p2 test of tf script mode in regions without p2 instances

src/sagemaker/model.py, src/sagemaker/session.py, tests/integ/kms_utils.py, tests/integ/test_mxnet_train.py, tests/integ/test_transformer.py, tests/unit/test_estimator.py, tests/unit/test_model.py
This change exposes the option of using a KMS key to encrypt the instance hosting a SageMaker Endpoint.
=> change: add KMS key option for Endpoint Configs

CONTRIBUTING.md
Add a few lines of environment setup instructions to CONTRIBUTING.md as part of the contribution model action items. The README.rst already contains developing/testing env setup commands.
=> doc: add environment setup instructions to CONTRIBUTING.md

tests/integ/__init__.py, tests/integ/test_tf_script_mode.py, tox.ini
skip p2/p3 tests in eu-central-1 during continuous testing runs to avoid capacity issues
=> change: skip p2/p3 tests in eu-central-1

buildspec.yml, tests/scripts/run-notebook-test.sh
- add run-notebook-test.sh script
- simplify buildspec.yml
- fix false positive PR test results
=> fix: prevent false positive PR test results

src/sagemaker/estimator.py, src/sagemaker/tuner.py, tests/scripts/run-notebook-test.sh, tests/unit/test_estimator.py, tests/unit/test_tuner.py
*Issue #, if available:* #716 
*Description of changes:* Updating the  TrainingInputMode parameter to conform with the InputMode set in s3_input when invoking the .fit() method
=> fix: update TrainingInputMode with s3_input InputMode

doc/using_mxnet.rst
*Description of changes:* https://sagemaker.readthedocs.io/en/stable/using_mxnet.html#using-transform-fn
"If you would rather not structure your code around the three methods described above, you can instead define your own transform_fn to handle inference requests. This will override any implementation of input_fn, predict_fn, or output_fn. transform_fn has the following signature:"
the transform_fn doesn't override if any of the implementation of input, predict or output fn are present. It tosses an error instead.
https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_transformer.py#L136
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> documentation: fix docs in regards to transform_fn for mxnet

src/sagemaker/tensorflow/estimator.py
*Issue #, if available:* #669 
*Description of changes:* skip the local path validation if source_dir is an S3 location
=> fix: TF estimator s3 requirements file validation

src/sagemaker/transformer.py, tests/unit/test_transformer.py
https://github.com/aws/sagemaker-python-sdk/issues/820
As of today, the Transformer class generates a default transform job name based on the image located in the primary container of the SageMaker model, however according to the create model API docs, a PrimaryContainer is optional along with Containers.
Thus, Containers should definitely be possible and it looks like our code is throwing errors as we only expect only a PrimaryContainer.
This is definitely a bug and should be fixed.
Reference: https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateModel.html#API_CreateModel_RequestParameters
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to …
=> fix: add better default transform job name handling within Transformer

tests/integ/test_tuner.py
This is causing collisions in our automated testing.
=> fix: use unique job name in hyperparameter tuning test

src/sagemaker/session.py, tests/integ/test_data_upload.py, tests/unit/test_upload_data.py
*Issue #, if available:* 774
Added extra_args parameter to upload_data function to enable 
encrypted objects upload  in session.py
Updated unit tests to test upload_data function
Added integration tests for upload_data function
=> feature: Add extra_args to enable encrypted objects upload

tests/integ/test_horovod.py, tests/integ/test_tf_script_mode.py
* our continuous testing has seen some issues with insufficient capacity errors for c5s in certain regions. Hoping that downgrading to c4 will help. I ran the Horovod test to make sure that changing the instance type wouldn't negatively impact the test duration, and with the c4, `pytest tests/integ/test_horovod.py::test_horovod` went from 517.67 seconds _down_ to 464.24 seconds.
* the TF Script Mode tests have been restricted to testing only the Python 3 images even though we have images for both Python 2 and Python 3. There's no reason to not test half the images we support with the tests in this suite when other tests are set up to test both Python versions.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure …
=> change: downgrade c5 in integ tests and test all TF Script Mode images

.gitignore, tests/integ/lock.py, tests/integ/test_local_mode.py, tests/integ/test_source_dirs.py, tests/integ/vpc_test_utils.py
fix race condition in vpc tests that causes intermittent test failures
=> fix: prevent race condition in vpc tests

tests/integ/test_tfs.py
fixes overnight tests broken by #870 
=> fix: add pytest.mark.local_mode annotation to broken tests

src/sagemaker/fw_utils.py, tests/integ/test_tf_script_mode.py, tests/unit/test_fw_utils.py, tests/unit/test_tf_estimator.py
=> feature: use deep learning images

.pylintrc, src/sagemaker/predictor.py
The Pylint check is not actually enabled in this commit as it conflicts
directly with NumPy. Pylint has corrected this, and it will be included
in their next release (2.4.0):
https://github.com/PyCQA/pylint/issues/2684
Once Pylint 2.4.0 is released, we can consume it and remove this check.
A summary of this information is included in a TODO near the relevant
Pylint disable rule (len-as-condition).
=> change: correct code per len-as-condition Pylint check

README.rst
*Description of changes:* Added the following badges to README.rst
* pypi Latest Version
* Supported Python Versions
* Code Style: Black
* readthedocs Documentation Status Badge
=> documentation: add pypi, rtd, black badges to readme

.pylintrc, src/sagemaker/amazon/lda.py, src/sagemaker/amazon/ntm.py
I think the design choice to keep the additional parameter out of the top-most superclass makes sense, and that this pylint check should be overridden for this particular use-case.
=> change: enable signature-differs pylint check

.pylintrc, src/sagemaker/amazon/record_pb2.py, src/sagemaker/cli/tensorflow.py, src/sagemaker/tensorflow/__init__.py, tests/component/test_tf_estimator.py, tests/integ/test_horovod.py, tests/integ/test_local_mode.py, tests/integ/test_tf_cifar.py, tests/integ/test_tf_keras.py, tests/integ/test_tf_script_mode.py, tests/integ/test_tuner.py, tests/unit/test_airflow.py, tests/unit/test_tf_estimator.py, tests/unit/test_tfs.py
Reverts aws/sagemaker-python-sdk#907
=> Revert "change: enable wrong-import-position pylint check"

.pylintrc
By running Pylint before any of the unit tests (and dependency
installs), the import-error check will always fail since the
dependencies are not yet installed.
We could move Pylint to a later stage to resolve this, but there's
value in this quick check occurring before the unit tests.
As a result, this Pylint check is being disabled.
=> change: remove TODO comment on import-error Pylint check

.pylintrc, src/sagemaker/amazon/common.py, src/sagemaker/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/job.py, src/sagemaker/local/data.py, src/sagemaker/local/image.py, src/sagemaker/local/local_session.py, src/sagemaker/model.py, src/sagemaker/predictor.py, src/sagemaker/rl/estimator.py, src/sagemaker/session.py, src/sagemaker/sklearn/estimator.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/predictor.py, src/sagemaker/vpc_utils.py
change: enable no-else-return and no-else-raise pylint checks
=> change: enable no-else-return and no-else-raise pylint checks

.pylintrc, src/sagemaker/session.py
change: enable simplifiable-if-expression pylint checks
=> change: enable simplifiable-if-expression pylint checks

doc/overview.rst, src/sagemaker/estimator.py, src/sagemaker/git_utils.py, src/sagemaker/model.py, tests/integ/test_git.py, tests/unit/test_estimator.py, tests/unit/test_git_utils.py, tests/unit/test_model.py
=> feature: Git integration for CodeCommit

.pylintrc, src/sagemaker/job.py, src/sagemaker/local/data.py, src/sagemaker/model.py, src/sagemaker/pipeline.py, src/sagemaker/predictor.py, src/sagemaker/rl/estimator.py
> # Note that this commit also raises ValueErrors in situations that would previously have returned None.
Per PEP8: Be consistent in return statements. Either all return
statements in a function should return an expression, or none of them
should. If any return statement returns an expression, any return
statements where no value is returned should explicitly state this as
return None, and an explicit return statement should be present at the
end of the function (if reachable). …
=> change: enable inconsistent-return-statements Pylint check

.pylintrc, src/sagemaker/tuner.py
change: enable consider-merging-isinstance Pylint check
Note that this commit will also enable simplifiable-if-statement, as
there are no code changes needed for it.
=> change: enable consider-merging-isinstance Pylint check

.pylintrc, src/sagemaker/amazon/amazon_estimator.py, src/sagemaker/analytics.py, src/sagemaker/estimator.py, src/sagemaker/local/entities.py, src/sagemaker/model.py, src/sagemaker/pipeline.py, src/sagemaker/tuner.py
change: enable attribute-defined-outside-init Pylint check
The logic behind this rule is to improve readability by defining all
the attributes of a class inside the init function, even if it simply
sets them to None.
=> change: enable attribute-defined-outside-init Pylint check

.pylintrc, src/sagemaker/fw_utils.py, src/sagemaker/git_utils.py, src/sagemaker/local/image.py, src/sagemaker/predictor.py, src/sagemaker/session.py, src/sagemaker/user_agent.py
change: enable wrong-import-order Pylint check
Per PEP8:
Imports should be grouped in the following order:
1- Standard library imports.
2- Related third party imports.
3- Local application/library specific imports.
=> change: enable wrong-import-order Pylint check

src/sagemaker/tuner.py, tests/integ/test_tuner.py, tests/unit/test_tuner.py
Add in hyperparameter values based on any hyperparameter ranges defined in the Tuning job detail for 1P algorithms.
When creating in a tuning job for a 1P algorithm, the constructor parameters and the parameter ranges overlap and will get removed in the hyperparameters if they are present as a range, shown here: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tuner.py#L262-L266
When attaching to a hyperparameter job for a 1P algorithm, the 1p Estimator created will have required constructor parameters that never get fulfilled as they have been removed from the static_hyperparameter map and needs to be added back in.
The value that is taken doesn't matter as a tuner is being created and when the user calls fit, those constructor values will …
=> change: fix attach for 1P algorithm estimators

src/sagemaker/tensorflow/estimator.py
Waiting on the TF container with the corresponding container change to be released first.
https://github.com/aws/sagemaker-containers/issues/203
The Github issue above suggests using a smarter default for processes_per_host when using GPU instances.
The change on the container side can be seen here: https://github.com/aws/sagemaker-containers/pull/204
This change is to remove the default and only set processes_per_host variable if provided by the user. Before this change the default was always handled on both the client and container side, however the default on the container side will never kick in, as the default on the client side is interpreted as the user input, which will always take precedence over any defaults on the container …
=> change: set num_processes_per_host only if provided by user

.pylintrc, src/sagemaker/parameter.py
change: enable chained-comparison Pylint check
=> change: enable chained-comparison Pylint check

src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/data/tfs/tfs-test-entrypoint-with-handler/training.py, tests/integ/test_tf_script_mode.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_tf_estimator.py
Related: #690. This was initially motivated, however, by the TFS with pre/post-processing use case.
With TFS, there is a code path where the inference.py file is not correctly packed with the model. It was a similar enough change to just allowing the entry point script to be specified to deploy/transformer that I went ahead and made the general change.
=> change: allow serving script to be defined for deploy() and transformer() with frameworks

CONTRIBUTING.md
Added instructions that allow for a low-cost ~10min environment setup.
=> doc: add instructions for setting up Cloud9 environment.

CONTRIBUTING.md
=> doc: correct wording for Cloud9 environment setup instructions

src/sagemaker/mxnet/estimator.py, tests/unit/test_mxnet.py
MXNet Estimator only accepts a single image path for both training and hosting. I have added an optional parameter to MXNet.create_model to allow hosting image to be specified during deployment.
=> change: allow hosting image to be specified in MXNet.create_model

doc/using_sklearn.rst
The documentation did not mention support for requirements.txt file
=> fix: update sklearn document to include 3p dependency installation

src/sagemaker/workflow/airflow.py, tests/unit/test_airflow.py
https://github.com/aws/sagemaker-python-sdk/issues/770
Currently the Airflow logic always uses basename of entry_point when
taring up the source code and upload to s3. So if only the absolute
path of the script is provided the pre-processing will fail. This change
fixes the issue.
=> fix: allow Airflow enabled estimators to use absolute path entry_point

README.rst, doc/using_tf.rst, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/serving.py, tests/integ/test_tfs.py, tests/unit/test_fw_utils.py, tests/unit/test_tf_estimator.py, tests/unit/test_tfs.py, tox.ini
- Support for TensorFlow 1.14
- TensorFlow Python 3 containers are default starting by 1.14 version
- TensorFlow Python 2 containers are not available starting by 1.14 version
=> feature: support for TensorFlow 1.14

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This commit covers adding a development workflow to ease
contributions.
This commit also includes:
* Refactoring/formatting.
* Adding a Table of Contents.
* Capitalization changes.
* Consistency changes.
* Updating PULL_REQUEST_TEMPLATE to reflect changes.
=> rework CONTRIBUTING.md to include a development workflow

src/sagemaker/sklearn/estimator.py, tests/unit/test_sklearn.py
fixes #974 
prevent sklearn.transformer()  from passing multiple values of entry_point arg to model constructor.
=>  fix: prevent multiple values error in sklearn.transformer()

tests/integ/test_ipinsights.py, tests/integ/test_marketplace.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf_script_mode.py, tests/integ/test_tuner.py
For background into the original issue, see
https://github.com/aws/sagemaker-python-sdk/pull/968
=> change: fix integration test failures masked by timeout bug

src/sagemaker/pipeline.py, tests/integ/test_inference_pipeline.py, tests/unit/test_pipeline_model.py
*Issue #, if available:* fix #963 
*Description of changes:* Create the update_endpoint argument and added a check for its value to create a new endpoint config for an existing endpoint
=> fix: update_endpoint for PipelineModel

tests/integ/vpc_test_utils.py
Canaries have failed in Tokyo (ap-northeast-1) since inception because
the ap-northeast-1b region doesn't exist.
This commit makes the check dynamic instead of blindly assuming that
a and b exist, as that isn't the case for 3 regions:
ap-northeast-1
ap-northeast-2
sa-east-1
=> change: Integration Tests now dynamically checks AZs

src/sagemaker/estimator.py, src/sagemaker/job.py, src/sagemaker/session.py, tests/unit/test_estimator.py, tests/unit/test_job.py, tests/unit/test_session.py
Add support for Managed Spot Training as well as Checkpoint support.
=> Spot training

src/sagemaker/algorithm.py, src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/pipeline.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/transformer.py, src/sagemaker/workflow/airflow.py
https://github.com/aws/sagemaker-python-sdk/issues/994
Updated all the instances I could find with the suggested wording in the issue above
=> doc: updated description for "accept" parameter in batch transform

tests/integ/__init__.py
Skip all efs and fsx integ tests due to some random failures which might be caused  by different code build setup in Canary
Skip 8 efs and fsx integ tests
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x ] I have added tests that prove my fix is …
=> fix: skip efs and fsx integ tests in canary pdx

tests/integ/test_transformer.py
#850 introduced a new test that didn't use the `cpu_instance_type` fixture that got introduced later.
=> change: use cpu_instance_type fixture for stop_transform_job test

src/sagemaker/session.py, src/sagemaker/utils.py, tests/unit/test_session.py, tests/unit/test_utils.py
`get_execution_role()` fails in a custom VPC because the AWS STS client is created using the global endpoint. However, the AWS SDK doesn't currently honor the `region_name` parameter, so we have to have our own function to get the correct endpoint. This does mean that with each new region we'll need to check [AWS STS's endpoints](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#id_credentials_region-endpoints) - I've added this to our region expansion checklist.
By …
=> change: use regional endpoint when creating AWS STS client

src/sagemaker/estimator.py, tests/unit/test_estimator.py
There's currently no way to enable network isolation when using a custom image with the generic estimator class
=> fix: add enable_network_isolation to generic Estimator class

src/sagemaker/amazon/amazon_estimator.py
Added quotes around warning log so customers can copy paste directly.
=> Fix get_image_uri warning log for default xgboost version.

src/sagemaker/session.py, src/sagemaker/transformer.py, tests/integ/test_transformer.py, tests/unit/test_session.py
* Estimator.fit has a logs flag attribute but that is not the same for Transformer. We need to create the same experience in the Transformer.
=> feature: Estimator.fit like logs for transformer

tests/integ/test_git.py
One of the integration tests had a plain-text credential for CodeCommit. I have disabled the access key for that IAM user already, so we should skip this test until we implement a better solution.
=> change: remove hardcoded creds from integ test

src/sagemaker/utils.py, tests/unit/test_utils.py
https://github.com/aws/sagemaker-python-sdk/issues/1034
#1026 was incorrect, so here's a PR to fix it.
```python
>>> boto3.client("sts", endpoint_url="https://sts.us-west-2.amazonaws.com")
<botocore.client.STS object at 0x102f62358>
```
=> fix: add https to regional STS endpoint

src/sagemaker/estimator.py, tests/integ/test_transformer.py, tests/unit/test_estimator.py
This change in the `Estimator.transformer` implementation should help make sure various parameters don't get lost when going from an estimator to a model. This was specifically seen with network isolation, but there might be similar things in the future.
=> change: use Estimator.create_model in Estimator.transformer

src/sagemaker/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_estimator.py
This is an argument in every implementation of `create_model()`, but because `transformer()` doesn't use kwargs (unlike `deploy()`), there's currently not a way to set `vpc_config_override` if you're using Batch Transform.
=> fix: expose vpc_config_override in transformer() methods

src/sagemaker/fw_utils.py, tests/unit/test_fw_utils.py
* There are new images for us-iso-east-1
* I also fixed the mxnet-serving logic around the new images (for all regions)
* I removed the unit tests for GPU + EI because that doesn't exist
=> change: use new ECR images in us-iso-east-1 for TF and MXNet

src/sagemaker/estimator.py
The airflow workflow for BYO estimators has been broken since a fix
made on 09/13/2019. This resolves that issue.
Tests to ensure this does not happen again will be added as part of
the next airflow commit that prepares training jobs as part of
defining training configuration.
=> fix: correct airflow workflow for BYO estimators.

setup.py, src/sagemaker/amazon/amazon_estimator.py, src/sagemaker/estimator.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/workflow/airflow.py, src/sagemaker/xgboost/estimator.py, tests/integ/test_airflow_config.py, tests/unit/test_airflow.py, tests/unit/test_tf_estimator.py
feature: add estimator preparation to airflow configuration
Also added airflow configuration tests, as those did not exist.
This change also contains a number of airflow fixes, as the tests
revealed a few bugs.
=> feature: airflow workflow now prepares estimators for training

src/sagemaker/tensorflow/predictor.py
- Importing tensorflow modules only in the last moment, allowing Python SDK to be used by clients without TensorFlow installed.
=> change: lazy import of tensorflow module

buildspec-unittests.yml
There seems to be a ~5% failure rate when the code checks are run in
parallel. This change adds a minute or two to the unit tests running
in the pipeline, but avoids the small failure rate that may confuse
contributors.
=> change: stop unit test code checks from running in parallel

src/sagemaker/model.py, src/sagemaker/session.py, tests/integ/test_mxnet_train.py, tests/unit/test_endpoint_from_model_data.py, tests/unit/test_model.py
The test [test_deploy_model_with_update_non_existing_endpoint](https://github.com/aws/sagemaker-python-sdk/blob/a907597880cbaaa5520f38256bba4cbc63d4295c/tests/integ/test_mxnet_train.py#L204)  is failing in the canaries because these changes with the following error:
```
----------------------------- Captured log setup ------------------------------ 
session.py                 390 INFO     Creating training-job with name: ·[1mmxnet-training-2019-10-01-01-33-22-030·[0m 
----------------------------- Captured stdout call ----------------------------- 
[·[34m2019-10-01 01:39:20,048·[0m] {·[34msession.py:·[0m770} INFO·[0m - Creating model with name: ·[1mmxnet-inference-2019-10-01-01-39-19-106·[0m·[0m 
[·[34m2019-10-01 01:39:20,430·[0m] {·[34msession.py:·[0m972} INFO·[0m - Creating endpoint …
```
=> Revert "fix: #987 Add Instance_Type in Endpoint_Config_Name"

src/sagemaker/inputs.py, tests/integ/file_system_input_utils.py, tests/integ/test_tf_efs_fsx.py, tests/unit/test_inputs.py
content_type parameter is not supported in FileSystemInput
- added an optional param `content_type` in `FileSystemInput`
- fixed a test setup method here: https://github.com/aws/sagemaker-python-sdk/blob/master/tests/integ/file_system_input_utils.py#L110 (key_filename is expecting a list instead of a string)
- since we disabled the EFS integ tests, I manually ran a EFS integ test with content_type …
=> fix: support content_type in FileSystemInput

src/sagemaker/amazon/factorization_machines.py, src/sagemaker/amazon/ipinsights.py, src/sagemaker/amazon/knn.py, src/sagemaker/amazon/ntm.py, src/sagemaker/amazon/object2vec.py, src/sagemaker/amazon/pca.py, src/sagemaker/amazon/randomcutforest.py
Reference: 0413038016
Pass kwargs into the create_model function for all 1p algorithms according to the changes introduced in this PR: https://github.com/aws/sagemaker-python-sdk/pull/1061/files#diff-0ca4fc3e292478e04c0a7722f675fdc7R151
The PR above only passed kwargs for LDA, KMeans and Linear Learner.
Due to the passing of the kms_key in the kwargs it has caused errors for any create_model methods that are not expecting it. This will enable using kms_keys for the rest of the 1p Algos.
I have tested these changes against this notebook: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/random_cut_forest/random_cut_forest.ipynb
File showcasing my testing: [tested_notebook.zip](https://github.com/aws/sagemaker-python- …
=> fix: add kwargs to create_model for 1p to work with kms

buildspec.yml
Use us-west-2 endpoint for sts in the buildspec.yml.
According to: https://docs.aws.amazon.com/general/latest/gr/rande.html#sts_region
"AWS recommends using Regional STS endpoints to reduce latency, build in redundancy, and increase session token validity."
=> fix: use us-west-2 endpoint for sts in buildspec

src/sagemaker/session.py
Use regional STS endpoint when utilizing STS in the default_bucket method within Session.
I pass both region_name and endpoint as AWS STS recommends setting both variables as defined here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#id_credentials_temp_enable-regions_writing_code
Reasons for the change are due to the benefits described here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html …
=> fix: use sts regional endpoint when creating default bucket

tests/integ/test_tf_script_mode.py
Use sagemaker_session.default_bucket() as checkpoint_s3_uri, otherwise need to create bucket in each region account for this test.
=> fix: use default bucket for checkpoint_s3_uri

tests/integ/__init__.py
Added the following regions to P2 Training exclusions:
us-west-1
ca-central-1
eu-west-2
eu-central-1
=> change: exclude regions for P2 tests

doc/using_rl.rst
inspired by https://github.com/aws/sagemaker-tensorflow-container/pull/243, I went checked all of our other repositories for dead links, and found this one.
=> doc: update link to point to ReadTheDocs

buildspec.yml, ci-scripts/queue_build.py, tests/integ/kms_utils.py
Part of the effort to use the regional endpoint for STS.
=> change: use regional endpoint for STS in builds and tests

src/sagemaker/estimator.py
https://stackoverflow.com/questions/57686852/sagemaker-estimator-source-dir-from-s3
=> doc: clarify that source_dir can be an S3 URI

src/sagemaker/logs.py, tox.ini
there's been some feedback about red logs looking like an error even though everything's actually alright. I changed the order a bit because blue is probably the most neutral and I believe it has the highest contrast ratio against white (given that a lot of people view these logs in Jupyter with its white background).
=> change: remove red from possible colors when streaming logs

setup.py, src/sagemaker/local/image.py
Remove docker-compose as a required dependency, because it has a very restrictive list of dependencies that has been causing numerous issues. Throw an error if it is not installed.
*Issue #, if available:* #1118 
=> fix: remove docker-compose as a required dependency.

doc/overview.rst, setup.py, src/sagemaker/local/entities.py, src/sagemaker/local/local_session.py
Adding extras_require dependencies subsets for local mode and analytics dependencies. 
=> feature: separating sagemaker dependencies into more use case specific installable components.

setup.py
Final step in safely removing local mode dependencies from the list of required dependencies.
Related PRs: #1130 #1128 
Issue: #1118
=> feature: remove local mode dependencies from the list of required dependencies.

setup.py, src/sagemaker/local/image.py, src/sagemaker/local/local_session.py, src/sagemaker/session.py, src/sagemaker/utils.py
=> fix: move sagemaker config loading to LocalSession since it is only used for local code support.

tests/integ/test_tuner_multi_algo.py
The canaries are failing randomly due to the prediction result not containing a specific key. To mitigate this, I've done assertion on the prediction object instead of on the specific key, as it is possible an algorithm may have different output bodies.
Assert on the prediction instead of key.
=> change: make multi algo integration test assertion less specific

src/sagemaker/estimator.py, tests/unit/test_estimator.py
https://github.com/aws/sagemaker-python-sdk/issues/1120
Originally, the `estimator's` `deploy` function supported tags by utilizing kwargs. This would run into problems depending on if each inherited `estimator's` `create_model` function was able to handle kwargs in the function. This causes problems as reported for the user above, who is using tags for a generic estimator class. 
Make tags an explicit parameter in the Estimator's `deploy` function, similar to the Model's `deploy` function. This will end up not using kwargs to pass tags and not force `create_model` function to handle it.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …
=> fix: fix tags in deploy call for generic estimators

src/sagemaker/tensorflow/estimator.py, tests/unit/test_tf_estimator.py
Checking if current version is just greater than highest support py2 version. 
Added a test to make sure highest tf version is supported. Expanded the HIGHEST version to include patch because [1,15,0] is greater than [1,15].
=> Fixing py2 support for latest TF version

tests/integ/__init__.py, tests/integ/auto_ml_utils.py, tests/integ/test_auto_ml.py
For auto ml jobs, create a base auto ml job for tests that base on an existing auto ml job.
=> fix: create auto ml job for tests that based on existing job

src/sagemaker/processing.py, src/sagemaker/sklearn/processing.py, tests/unit/test_processing.py
https://github.com/aws/sagemaker-python-sdk/issues/1163
* fixes `ScriptProcessor` and its inheriting classes to let users specify and run code in S3 to fix issue 1163.
* adds validation on the URL scheme for `code`, SKLearn versions, whether the file exists.
* adds unit tests to test `code` schemes and new validation
* unit tests changes:
* tests changed to test `ScriptProcessor` directly rather than through `SKLearnProcessor`. `SKLearnProcessor` tests test added behavior added for SKLearn.
* added "required_parameters" and "all_parameters" tests for the other two Processing classes.
* refactored unit tests to avoid repetitive constructors and expectations.
* unit tests: `tox -- tests/unit/test_processing.py`
* sanity …
=> fix: allow processing users to run code in s3

src/sagemaker/local/local_session.py, src/sagemaker/session.py, tests/integ/test_local_mode.py, tests/integ/test_processing.py, tests/unit/test_create_deploy_entities.py, tests/unit/test_default_bucket.py, tests/unit/test_endpoint_from_job.py, tests/unit/test_endpoint_from_model_data.py, tests/unit/test_exception_on_bad_status.py, tests/unit/test_local_session.py, tests/unit/test_session.py, tests/unit/test_upload_data.py
https://github.com/aws/sagemaker-python-sdk/issues/1174
Reverts aws/sagemaker-python-sdk#1168
=> fix: Revert "feature: allow setting the default bucket in Session"

tests/integ/test_processing.py
=> change: make test's custom bucket include region and account name.

src/sagemaker/automl/automl.py, tests/unit/sagemaker/automl/test_auto_ml.py
Change auto_ml.py back to use ``name_from_base`` instead of ``unique_name_from_base``. Other classes are appending a time string.
*Testing done:* Unit test.
=> fix: use name_from_base in auto_ml.py but unique_name_from_base in tests.

README.rst, doc/amazon_sagemaker_model_monitoring.rst, doc/index.rst, doc/model_monitor.rst, doc/overview.rst, src/sagemaker/predictor.py
*Description of changes:* copy edit
*Testing done:* tox tests/unit
=> doc: add Model Monitor documentation

doc/amazon_sagemaker_model_monitoring.rst
The documentation still reads like a SageMaker Studio tutorial, but I don't think that's as helpful in general documentation. It's hard to tell what the point of the code snippets are when they're clearly just meant to be run.
`tox -e sphinx`
=> doc: generalize Model Monitor documentation from SageMaker Studio tutorial

tests/integ/test_data_capture_config.py
Increase number of retries when describing an endpoint since tf-2.0 has larger images and takes longer to start.
=> change: Increase number of retries when describing an endpoint.

tests/integ/test_data_capture_config.py
=> change: reduce test's describe frequency to eliminate throttling error.

src/sagemaker/session.py
Too frequent DescribeEndpoint polling (5) caused throttling exception in our canary tests.
Changing polling number from 5 to 30.
No tests changed.
=> fix: increase poll from 5 to 30 for DescribeEndpoint lambda.

src/sagemaker/fw_utils.py, src/sagemaker/mxnet/model.py
There was a lot of duplicated logic, as well as some convoluted logic around Python versions, so I'm hoping to simplify it (and go back to having all the framework version thresholds in one place).
I also removed some of the usage of "merged" as it was confusing to some. (it referred to the merging of the SageMaker and DLC images, but was vague enough that at first glance it could mean the merging of training/inference images or something else like that.)
* `tox -e flake8,pylint,py36 tests/unit`
* also manually pulled the MXNet 1.4.1 EI images to verify which versions existed (I was surprised that the 1.4.1 images are indeed DLC images for both Python 2 and 3)
_Put an `x` in the boxes that apply. You can also fill these …
=> change: refactor logic in fw_utils and fill in docstrings

src/sagemaker/pytorch/estimator.py, tests/unit/test_pytorch.py
The warning when `framework_version` is empty should include the latest version of PyTorch. (The other frameworks already do this.)
`tox test/unit`
=> fix: make PyTorch empty framework_version warning include the latest PyTorch version

src/sagemaker/model.py
Starting from version `1.2` deployment of PyTorchModel always [initiates **repacking**](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/pytorch/model.py#L154) when uploading the code.  It is done by calling `_upload_code` with `repack=True` parameter.
On Windows, this will lead to a crash, because `os.path.join` method used to generate `repacked_model_uri` will use backslashes instead of slashes. So `utils.repack_model` will fail to parse it.
Replaced `os.path.join(bucket, key_prefix, "model.tar.gz")` with `'/'.join(...)` for creating repacked_model_uri.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …
=> fix: fix PyTorchModel deployment crash on Windows

doc/using_pytorch.rst
=> fix typo and improve clarity on installing packages via "requirements.txt"

tests/integ/test_tuner_multi_algo.py
Need to do this to avoid job name collisions with our continuous testing.
`tox -e py36 tests/integ/test_tuner_multi_algo.py`
=> change: use unique_name_from_base for multi-algo tuning test

.github/PULL_REQUEST_TEMPLATE.md
we often forget when reviewing integ tests that resource name collisions often occur during continuous testing. I also split the checklist into sections because there are a lot more items now.
looked at https://github.com/laurenyu/sagemaker-python-sdk/blob/pr-checklist/.github/PULL_REQUEST_TEMPLATE.md for formatting
=> change: add PR checklist item about unique_name_from_base()

src/sagemaker/automl/automl.py, tests/unit/sagemaker/automl/test_auto_ml.py
=> fix: allow predictor to be returned from AutoML.deploy()

doc/amazon_sagemaker_operators_for_kubernetes_jobs.rst
Description of changes:
Adding description about role-arn when job is being submitted using plain yaml.
=> Adding role arn explanation for sagemaker role 

src/sagemaker/chainer/defaults.py, src/sagemaker/chainer/estimator.py, src/sagemaker/chainer/model.py, src/sagemaker/mxnet/defaults.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/mxnet/model.py, src/sagemaker/pytorch/defaults.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/pytorch/model.py, src/sagemaker/tensorflow/defaults.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/model.py, tests/unit/test_chainer.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_tf_estimator.py
Framework Model classes do not log warning when they are defaulted to default framework versions (not the latest versions) as Estimator classes do.
Default ``framework_version`` to ``None`` in Model classes, emit warning message and then assign default values.
Unit tests in each modified framework unit tests:
Chainer, MXNet, PyTorch, TensorFlow
=> fix: add default framework version warning message in Model classes

doc/using_chainer.rst, doc/using_mxnet.rst, doc/using_pytorch.rst, doc/using_sklearn.rst
This change is just a copy of #1215, which revised the PyTorch docs.
=> doc: clarify requirements.txt usage for Chainer, MXNet, and Scikit-learn

src/sagemaker/model.py, src/sagemaker/multidatamodel.py, src/sagemaker/pipeline.py, src/sagemaker/session.py, tests/unit/test_model.py, tests/unit/test_multidatamodel.py, tests/unit/test_pipeline_model.py, tests/unit/test_session.py
Currently, `wait` is being ignored if `deploy()` is called with `update_endpoint=True`. This change should fix that.
`tox test/unit`
=> fix: honor 'wait' flag when updating endpoint

tests/integ/test_auto_ml.py, tests/integ/test_debugger.py, tests/integ/test_experiments_analytics.py, tests/integ/test_model_monitor.py, tests/integ/test_processing.py
**Description of changes:** Flagged re:Invent tests for quick canary. Selected one of each major piece of functionality.
- Debugger: tests/integ/test_debugger.py::test_mxnet_with_all_rules_and_configs => Reasoning: Exercises all variants in a single test.
- Monitoring: tests/integ/test_model_monitor.py::test_default_monitor_suggest_baseline_and_create_monitoring_schedule_with_customizations => Reasoning: These tests are quite slow, so I only want one of them in the quick canary. Given that choice, this is the best test, as it tests the most common use-case (default monitor) with all customizations.
- Processing: Added test_sklearn_with_customizations + test_script_processor + test_processor. => Reasoning: One of each main use-case.
- AutoPilot: One for auto_ml.fit, one for auto_ml.deploy. …
=> change: add tests to quick canary

src/sagemaker/algorithm.py, tests/unit/test_algorithm.py
SageMaker Automatic Model Tuning adds a private hyperparameter to all of its training jobs. This can cause an issue when attaching to a training job with the hyperparameter:
```
ValueError: Invalid hyperparameter: _tuning_objective_metric is not supported by <algorithm>
```
I tested this with KMeans, and the private hyperparameter is not included after attaching, so I've gone for the same approach with `AlgorithmEstimator`.
Tested manually by adapting the code from [this notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/aws_marketplace/using_data/using_data_from_aws_data_exchange_to_predict_product_popularity/Introduction_to_training_a_model_using_data_from_AWS_Data_Exchange.ipynb) to create a …
=> fix: ignore private Automatic Model Tuning hyperparameter when attaching AlgorithmEstimator

src/sagemaker/mxnet/model.py, src/sagemaker/pytorch/model.py, src/sagemaker/tensorflow/model.py, tests/integ/test_airflow_config.py, tests/unit/test_airflow.py
https://github.com/awslabs/amazon-sagemaker-examples/issues/965
Appends `-serving` to the framework name in PyTorch, MXNet, and TensorFlow models.
- ran unit tests
- ran integ tests
=> fix: Append serving to model framework name

src/sagemaker/model.py, src/sagemaker/workflow/airflow.py, tests/integ/test_airflow_config.py
https://github.com/aws/sagemaker-python-sdk/issues/1201#issuecomment-576389994
TFS does not require an entry point. When an entry point is not provided (and not defaulted, in the case of TFS), this fix removes the expectation of an entry point and does not set the script and code directory.
Ran unit tests and `integ/test_airflow_config.py`
=> fix: do not use script for TFS when entry_point is not provided

doc/amazon_sagemaker_operators_for_kubernetes.rst
Updated the documentation for installation of the Amazon SageMaker Operator for Kubernetes helm charts.
=> Updated SageMaker operator Helm chart installation guide

buildspec-localmodetests.yml, buildspec-notebooktests.yml, buildspec.yml
*Description of changes:* Assigning has-matching-changes script to variable, to expose non-zero exit codes and properly fail the build if the script is unable to get git details.
*Testing done:* Script is run by build.
=> infra: properly fail PR build if has-matching-changes fails

doc/using_mxnet.rst
This is my attempt to take one of our existing pages and make things consistent with what we would like to see in our documentation. This includes:
* using the imperative mood for headings
* using present tense
* linking to the reference docs rather than repeating information about arguments (which look outdated in this particular file)
* using full names for AWS products
The headings were also slightly inaccurate in terms of their organization (and which were subheadings of which), so I adjusted those as well.
built the docs locally to check formatting
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This …
=> doc: clean up headings, verb tenses, names, etc. in MXNet overview

src/sagemaker/local/local_session.py, src/sagemaker/multidatamodel.py, tests/integ/test_multidatamodel.py
``MultiDataModel.deploy()`` uses the non local session when ``instance_type="local"``
Init ``LocalSession`` when instance_type is "local" and ``MultiDataModel`` object's ``sagemaker_session`` is not ``LocalSession``. The ``sagemaker_session`` needs to be initiated because this class provides a method (``add_model``) that uploads tarball to s3 which requires session.
Integration test with local mode. …
=> fix: create the correct session for MultiDataModel

doc/using_tf.rst, tests/scripts/run-notebook-test.sh
*Description of changes:* Update links to TF notebook examples to link to script mode examples.
=> doc: update links to TF notebook examples to link to script mode examples.

src/sagemaker/utils.py, tests/unit/test_utils.py
Create lib dir for dependencies safely (only if it doesn't exist yet).
*Issue #, if available:* TT-0303440807
*Testing done:* unit tests updated to address the missed use case.
=> fix: create lib dir for dependencies safely.

tests/scripts/run-notebook-test.sh
the notebook chosen in #1268 makes the notebook PR build run longer. Chose this one based on the fastest succeeding notebook in #1256.
=> infra: choose faster notebook for notebook PR build

README.rst
TravisCI and Codecov are no longer used. The badges have been removed.
N/A
=> doc: Remove outdated badges from README

src/sagemaker/tensorflow/estimator.py, tests/unit/test_tf_estimator.py
SMDebug now supports this, so the hardcoded disabling can be removed.
=> change: enable smdebug for Horovod (MPI) training setup

src/sagemaker/session.py, tests/integ/kms_utils.py, tests/integ/test_tf_script_mode.py, tests/unit/test_default_bucket.py
*Issue #, if available:* #1258 
Previously, the code would create the bucket and enact business logic
based on the exceptions thrown.
This commit makes it such that the code checks that the bucket exists
before trying to create it.
In addition to being cleaner, this also avoids issues if customers
have no S3 bucket creation permissions.
UTs. PR will run ITs.
=> fix: modify session and kms_utils to check for S3 bucket before creation

doc/overview.rst
Update links to the local mode notebooks examples.
=> doc: update links to the local mode notebooks examples.

src/sagemaker/automl/README.rst
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/1276
*Description of changes:* Fixing the broken AutoML API doc link.
=> doc: correct broken AutoML API documentation link

src/sagemaker/estimator.py, src/sagemaker/model.py
*Description of changes:* Remove NEO_ALLOWED_TARGET_INSTANCE_FAMILY set. Fallback to Neo Service for validating target devices.
=> change: remove NEO_ALLOWED_TARGET_INSTANCE_FAMILY

doc/using_tf.rst
None
The documentation incorrectly specifies SM_CHANNEL_TRAIN instead of SM_MODEL_DIR for the directory where models are stored. There is also example code missing quotation marks.
None
=> doc: Fixed typo with SM_MODEL_DIR, missing quotes

src/sagemaker/model.py, tests/unit/test_model.py
#1184 
This is a combination of #1185 and #1156 due to the inactivity on both PRs. I originally thought it would make sense to put this in the constructor of `Model`, but determining which type of session object to include necessitates knowing the instance type :(
=> fix: create Session or LocalSession if not specified in Model

src/sagemaker/estimator.py, src/sagemaker/model.py
*Description of changes:* Update inline documentation about valid compilation target devices to point to public AWS docs.
=> doc: remove hardcoded list of target devices in compile()

setup.py
turns out requests is used for [only one integ test](https://github.com/aws/sagemaker-python-sdk/search?q=%22import+requests%22&unscoped_q=%22import+requests%22), so I don't think it needs to be a core dependency of this library.
=> change: move requests library from required packages to test dependencies

src/sagemaker/estimator.py, tests/unit/test_estimator.py
follow-up to #1230 
The AlgorithmSpecification for a training job that is part of a hyperparameter tuning job will have TrainingImage set to "", rather than not being present in the training job description. Looking for AlgorithmName first, instead of TrainingImage, fixes the issue of algorithm_arn not being populated when attaching a hyperparameter tuning job.
`tox tests/unit` …
=> fix: fix HyperparameterTuner.attach for Marketplace algorithms

src/sagemaker/amazon/amazon_estimator.py, tests/integ/test_pca.py, tests/unit/test_amazon_estimator.py
This enables the network isolation mode for Amazon Estimator, which is the super class for all 1P algorithm estimators. 
*Testing done:*  
unittest and integration test. Verified launched PCA training job and models are with network isolation feature and successful.
=> change:enable network isolation for amazon estimators

doc/using_pytorch.rst
#1292 
copy/pasted the wording from the MXNet doc.
=> doc: clarify channel environment variables in PyTorch documentation

src/sagemaker/utils.py, tests/unit/test_utils.py
#1283
S3 doesn't provide a way of definitively determining if a prefix is a folder, so originally we used `ListObjects` to try and gauge that. However, `ListObjects` requires extra permissions on the bucket, and so download a public file from a private bucket fails. In this PR, I've changed the logic to try and download the file first, and then if that incurs a 404 because it's a folder (no idea why that's how S3 chooses to implement this...), then the code will proceed with as if the prefix points to a folder.
Side note - I noticed that pylint was requiring me to put `botocore` in the wrong order for the imports. I'll fix that in a separate PR.
tried the example S3 path from #1283:
```python
>>> import sagemaker
>>> from …
```
=> fix: allow download_folder to download file even if bucket is more restricted

.pylintrc, src/sagemaker/model_monitor/monitoring_files.py, src/sagemaker/session.py
noticed this while working on my last PR. not entirely sure why pylint wasn't recognizing boto3 and botocore.
`tox -e pylint`
=> infra: configure pylint to recognize boto3 and botocore as third-party imports

src/sagemaker/utils.py, tests/unit/test_airflow.py, tests/unit/test_fw_utils.py, tests/unit/test_processing.py, tests/unit/test_session.py, tests/unit/test_utils.py
Finally paying back my tech debt from #1054 
`tox -e black-format,pylint,py36 tests/unit`
=> change: dynamically determine AWS domain based on region

src/sagemaker/tensorflow/serving.py
https://github.com/aws/sagemaker-python-sdk/issues/831#issuecomment-588122114
S3 paths always use forward slashes ("/") regardless of the OS, so using `os.path.join` will cause issues when the user is on Windows.
`tox --parallel all tests/unit`
=> fix: don't use os.path.join for S3 path when repacking TFS model

src/sagemaker/model.py, tests/conftest.py, tests/data/mxnet_mnist/mnist_neo.py, tests/integ/test_neo_mxnet.py
These tests were introduced as part of re:Invent 2018 (#513). We have the necessary AWS SDK version for these tests, and so after 15 months I think we should probably enable them 😂 
This change also fixes the logic for generating a model name when compiling a model if `self.name` is not already set.
`pytest tests/integ/test_neo_mxnet.py`
=> change: enable Neo integ tests

src/sagemaker/automl/automl.py, tests/unit/sagemaker/automl/test_auto_ml.py
`AutoML` already keeps track of a `sagemaker_session` object, so it seems like it would make sense to use that if another one isn't specified in a `deploy()` call.
* unit tests
* integ tests where a `Session()` call on its own will fail
=> make AutoML.deploy use self.sagemaker_session by default

tests/integ/test_airflow_config.py
There were a few instances where the fixture was not passed to the appropriate classes.
ran locally
=> infra: use sagemaker_session fixture in all Airflow tests

src/sagemaker/model_monitor/data_capture_config.py, src/sagemaker/predictor.py, tests/integ/test_data_capture_config.py, tests/integ/test_model_monitor.py, tests/unit/sagemaker/monitor/test_data_capture_config.py
`DataCaptureConfig` uses `Session.default_bucket()` if `destination_s3_uri` is not specified. This doesn't let the user specify what default bucket is used (if they want the rest of the path generated automatically) or what region name to use in the default bucket name (if they don't want to configure their AWS region via an environment variable or config file).
I also renamed the unit tests because they were confusing to me.
unit tests + integ tests
By submitting …
=> change: add sagemaker_session parameter to DataCaptureConfig

src/sagemaker/model_monitor/model_monitoring.py, src/sagemaker/model_monitor/monitoring_files.py, tests/integ/test_model_monitor.py, tests/integ/test_monitoring_files.py
same idea as #1312 
unit tests + integ tests
=> change: use sagemaker_session when initializing Constraints and Statistics

src/sagemaker/utils.py, tests/integ/kms_utils.py, tests/integ/test_marketplace.py, tests/unit/test_utils.py
*Description of changes:* Now dynamically determining partition based on region.
*Testing done:* UTs/ITs.
=> infra: programmatically determine partition based on region

src/sagemaker/tuner.py
doc: improve docstring for tuner.best_estimator()
=> doc: improve docstring for tuner.best_estimator()

src/sagemaker/algorithm.py, src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/pipeline.py, src/sagemaker/session.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/workflow/airflow.py
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/1333
*Description of changes:* Fix docstring
*Testing done:* UTs/ITs already exist using the correct version.
=> doc: correct MultiString/MULTI_STRING docstring

src/sagemaker/processing.py, tests/integ/test_processing.py
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/1341
*Description of changes:* Properly populate local instance of ProcessingJob from description in case inputs and/or outputs are empty.
*Testing done:* UTs/IT.
=> fix: handle empty inputs/outputs in ProcessingJob.from_processing_name()

doc/using_pytorch.rst
#1360 
Adding more details about PyTorch EIA in readthedocs
=> doc: add more details about PyTorch eia

src/sagemaker/session.py, tests/unit/test_session.py
#1301 
AWS doesn't allow for any tag keys to start with "aws:" so that its own services can make use of such tags.
unit tests
=> change: ignore tags with 'aws:' prefix when creating an EndpointConfig based on an existing one

doc/using_tf.rst, src/sagemaker/tensorflow/estimator.py
#1355 
The docs weren't clear about how `model_dir` is generated for the various use cases of TF (see #1355)
* `tox -e pylint`
* built the docs locally to verify formatting:
=> doc: fix description of default model_dir for TF

src/sagemaker/model.py, tests/unit/test_model.py
*Description of changes:* Add TFLite framework support in SDK
=> change: add tflite to Neo-supported frameworks

src/sagemaker/estimator.py, tests/integ/test_airflow_config.py, tests/unit/test_estimator.py
if the user passes sagemaker.session.Session the error message is not clear.
If the user passes a session object to the estimator and tries to train in local mode, the fit method returns an error:
```
ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: 1 validation error detected: Value 'local_gpu' at 'resourceConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [ml.p2.xlarge, ml.m5.4xlarge, ml.m4.16xlarge, ml.c5n.xlarge, ml.p3.16xlarge, ml.m5.large, ml.p2.16xlarge, ml.c4.2xlarge, ml.c5.2xlarge, ml.c4.4xlarge, ml.c5.4xlarge, ml.c5n.18xlarge, ml.g4dn.xlarge, ml.g4dn.12xlarge, ml.c4.8xlarge, ml.g4dn.2xlarge, ml.c5.9xlarge, ml.g4dn.4xlarge, ml.c5.xlarge, ml.g4dn.16xlarge, ml.c4.xlarge, …
```
=> change: Check that session is a LocalSession when using local mode

src/sagemaker/local/image.py
*Issue #, if available:* aws#1374
*Description of changes:* Set either the `--abort-on-container-exit` or `--detach` docker-compose option but not both.
*Testing done:* Tried the class locally and the container was able to start correctly. I also executed the unit tests per the Contributing Guidelines
=> Fix local _SageMakerContainer detached mode (aws#1374)

src/sagemaker/chainer/estimator.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/pytorch/estimator.py, tests/unit/test_chainer.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py
The docstring in `create_model` indicates that `kwargs` is passed to the Model constructor. This was not the case for PyTorch, MXNet, and Chainer.
`kwargs` has been modified to account for the `image` keyword and passed to the constructor.
Ran unit tests. Modified `create_model` unit tests with an `env` keyword argument to test `kwargs` being passed to the Model. …
=> fix: Pass kwargs from create_model to Model constructors

src/sagemaker/sklearn/estimator.py
The default Python Version for the SKLearn estimator is `py3` now, but the comment says `py2`, this change corrects this.
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change) …
=> documentation: Correct comment in SKLearn Estimator about default Python version

doc/using_tf.rst
Use instance type with more than 1 GPU (p3.8xlarge has 4 GPUs and p2.xlarge thas only 1) to provide a working example in the documentation.
=> doc: fix documentation to provide working example.

doc/using_tf.rst, src/sagemaker/utils.py
*Description of changes:* No longer filter on host for ecr image uri validation.
*Testing done:* Local mode IT.
=> fix: correct local mode behavior for CN regions

src/sagemaker/processing.py
S3 paths always use forward slashes ("/") regardless of the OS,
so using an os.path.join will cause issues when the user is on Windows.
=> fix: use .format instead of os.path.join for Processing S3 paths.

src/sagemaker/amazon/amazon_estimator.py, src/sagemaker/estimator.py, tests/unit/test_estimator.py
This removes the need of having redundant logic in each of the subclasses of `EstimatorBase`, since network isolation mode has been added to all of the subclasses now.
`tox tests/unit --parallel all`
=> change: add enable_network_isolation to EstimatorBase

src/sagemaker/estimator.py, src/sagemaker/sklearn/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_estimator.py, tests/unit/test_tf_estimator.py
This change exposes the `enable_network_isolation` option from `transformer()`, defaulting to the estimator's setting if not specified
`tox tests/unit --parallel all`
=> fix: allow model with network isolation when creating a Transformer from an Estimator

src/sagemaker/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/unit/test_estimator.py, tests/unit/test_tf_estimator.py
This was the motivation behind #1396 and #1397. Previously, the way to customize the model name was to start with the `Model` class instead of using an estimator.
`tox tests/unit --parallel all`
=> change: allow specifying model name when creating a Transformer from an Estimator

src/sagemaker/transformer.py
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/1395
*Description of changes:* Fix doc to reflect accurate "wait" parameter default
Also verified no other instances of misdocumented "wait=False" exist.
=> doc: correct transform()'s wait default value to "False"

doc/using_pytorch.rst
The default `model_fn` for PyTorch exists only for Elastic Inference. [PR 68](https://github.com/aws/sagemaker-pytorch-serving-container/pull/68) changes the `model_fn` implementation. This PR changes the documentation to reflect that.
=> doc: Explain why default model_fn loads PyTorch-EI models to CPU by default

doc/using_pytorch.rst
The section "SageMaker PyTorch Docker Containers" has a weird url (https://sagemaker.readthedocs.io/en/stable/using_pytorch.html#id3).
Because the anchor link is #id3, existing references are broken. For example, under the third party libraries section, "For more information on the runtime environment, including specific package versions, see SageMaker PyTorch Docker containers.". The link is broken because it refers to id4.
Update SageMaker PyTorch Docker containers reference links.
tox -e sphinx …
=> doc: update sagemaker pytorch containers to external link

tests/integ/test_transformer.py
These integ tests are tested batch transform jobs, not training jobs, so there's no need to start over with an estimator in every test. Also, it's the same input data getting uploaded to S3 for each MXNet test, so there's also no need to do that every time.
I tried not to modify the actual content of any test.
`tox -e black-format`
=> infra: use pytest fixtures in batch transform integ tests to train and upload to S3 only once

src/sagemaker/s3.py, tests/unit/test_s3.py
S3 has a different set of args that are allowed for `ExtraArgs` for downloading vs uploading. docs: https://boto3.amazonaws.com/v1/documentation/api/1.9.42/reference/customizations/s3.html#boto3.s3.transfer.S3Transfer.ALLOWED_DOWNLOAD_ARGS
`tox -e py36 tests/unit/test_s3.py`
=> fix: use valid encryption key arg for S3 downloads

tests/unit/sagemaker/model/test_framework_model.py, tests/unit/sagemaker/model/test_model.py
I might consider moving the `deploy()` tests to their own file after this...
`pytest tests/unit/sagemaker/model/`
=> infra: add Model unit tests for prepare_container_def and _create_sagemaker_model

buildspec-localmodetests.yml, buildspec.yml
After working on unit tests for a solid day, I'm not sure why I didn't do this sooner 😅 
=> infra: skip integ tests in PR build if only unit tests are modified

tests/unit/sagemaker/model/test_framework_model.py, tests/unit/sagemaker/model/test_model.py
similar to #1418
`pytest tests/unit/sagemaker/model/`
=> infra: add Model unit tests for delete_model and enable_network_isolation

README.rst, src/sagemaker/tensorflow/README.rst, src/sagemaker/tensorflow/serving.py, tests/conftest.py, tests/integ/test_tfs.py, tests/unit/test_fw_utils.py, tests/unit/test_tfs.py
Update documentation of EIA support for TF versions
Update create image uri unit test to latest TF version
Update TFS EI integ tests to test 1.15.0 and 2.0.0
=> feature: add EIA support for TFS 1.15.0 and 2.0.0

src/sagemaker/processing.py
When using the Python SDK to construct paths for Docker containers, no matter what the user's platform is, we still expect the Docker container to use Ubuntu (since that's what all the prebuilt SageMaker images use).
This PR is similar to #1391 
unit tests - I did some digging to see if I could write a unit test for the Windows case, but it seems like the `os.path.join` implementation for Unix systems hardcodes "/" (at least in Python 2.7): https://hg.python.org/cpython/file/v2.7.3/Lib/posixpath.py …
=> fix: use format strings intead of os.path.join for Processing paths intended for Unix

src/sagemaker/local/data.py
This is to address Pylint's W0231 (super-init-not-called)
`tox -e pylint`
=> change: add super() call in Local Mode DataSource subclasses

src/sagemaker/estimator.py
Looks like these may have been missed during the re:Invent 2019 launch.
none
=> doc: add documentation for EstimatorBase parameters missing from docstring

doc/using_mxnet.rst, doc/using_pytorch.rst
We've had many questions about this, and yet have never properly documented it. I was originally told that the [TFS documentation](https://github.com/aws/sagemaker-tensorflow-serving-container/#prepost-processing) had the same structure, but it's actually slightly different.
I also fixed some headers so that topics would be nested correctly.
* `tox -e doc8,sphinx`
* downloaded models from successful batch transform jobs to verify model structure
* viewed the RST files rendered by GitHub to verify that the table of contents looked correct with the updated headers: [MXNet](https://github.com/aws/sagemaker-python-sdk/blob/0bcb6274f7241a79d7e1913714f37d2b4c78b92a/doc/using_mxnet.rst), …
=> doc: document model.tar.gz structure for MXNet and PyTorch

src/sagemaker/workflow/airflow.py, tests/unit/test_airflow.py
#1448 
If the Estimator has `metric_definitions`, return it in the `train_config`.
Added a unit test.
=> fix: training_config returns MetricDefinitions

README.rst, buildspec-localmodetests.yml, buildspec-release.yml, buildspec-unittests.yml, buildspec.yml, setup.py, src/sagemaker/tensorflow/estimator.py, tox.ini
Python SDK py37 support
Add Python3.7 test environment.
Unit tests run against py27, py36, py37.
Integ tests run against py37.
Release build tests run against py36.
Made a change in  src/sagemaker/tensorflow/estimator.py to accommodate Python3.7 change: [PEP 479](https://www.python.org/dev/peps/pep-0479/) is enabled for all code in Python 3.7 
=> infra: support Python 3.7

README.rst, doc/index.rst
This adds a link at the top of our main doc pages to https://github.com/aws/sagemaker-python-sdk/issues/1459. Since GitHub doesn't render admonitions (https://github.com/github/markup/issues/68), I made a table instead for the README.
built the API docs locally:
README:
=> doc: add note that v2.0.0 plans have been posted

tools/compatibility/v2/files.py
#1478
follow-up to #1492. This class reads in Python source files and feeds the code to `ASTTransformer`.
unit tests will come later (see #1478)
manual testing:
```bash
$ cat input.py
from sagemaker.mxnet import MXNet
m = MXNet()  # TODO: fill in parameters
m.fit()
$ python -c "import files; files.PyFileUpdater('input.py', 'foo/bar/output.py').update()" && cat foo/bar/output.py
from sagemaker.mxnet import MXNet
m = MXNet(framework_version='1.2.0')  # TODO: fill in parameters
m.fit()
$ python -c "import files; files.PyFileUpdater('input.py', 'output.py').update()" && cat output.py
from sagemaker.mxnet import MXNet
m = MXNet(framework_version='1.2.0')  # TODO: fill in parameters
m.fit()
$ python -c "import files; …
```
=> change: add class to read Python scripts and update code for v2

tools/__init__.py, tools/compatibility/__init__.py, tools/compatibility/v2/__init__.py, tools/compatibility/v2/files.py, tools/compatibility/v2/modifiers/framework_version.py, tox.ini
=> infra: add tools/ dir to pylint check

tools/compatibility/v2/sagemaker_upgrade_v2.py
#1478
follow-up to #1497. I did look into [click](https://click.palletsprojects.com/en/7.x/why/#why-not-argparse), but decided against it since this is meant to be just a side tool to the Python SDK. Click is relatively small in size (~500 KB), but it still felt a little weird to add another dependency just for the sake of some CLI-parsing features we won't use in the main part of this repository.
```bash
$ python sagemaker_upgrade_v2.py --help
usage: sagemaker_upgrade_v2.py [-h] [--in-file IN_FILE] [--out-file OUT_FILE]
A tool to convert files to be compatible with v2 of the SageMaker Python SDK.
Simple usage: sagemaker_upgrade_v2.py --in-file foo.py --out-file bar.py
optional arguments:
-h, --help           show this …
```
=> change: add CLI wrapper for v2 migration script

tools/compatibility/v2/files.py, tools/compatibility/v2/sagemaker_upgrade_v2.py
#1478
The notebook counterpart to #1497.
Created a simple notebook:
Then ran:
```bash
$ python sagemaker_upgrade_v2.py --in-file Untitled.ipynb --out-file output.ipynb
$ diff Untitled.ipynb output.ipynb
30c30
<     "MXNet()"
---
>     "MXNet(framework_version='1.2.0')"
48c48
<     "mx = sagemaker.mxnet.MXNet()"
---
>     "mx = sagemaker.mxnet.MXNet(framework_version='1.2.0')"
```
And also opened up the new notebook: …
=> change: add .ipynb file support for v2 migration script

src/sagemaker/s3.py
#1511 (#1501)
similar to #1435 and #1391 
`tox -e py36,flake8,pylint,black-format --parallel all tests/unit`
=> fix: use format strings instead of os.path.join for S3 URI in S3Downloader

doc/using_tf.rst
follow-up to #1512 - TF script mode support for `requirements.txt` for versions before TF 1.15.2 with Python 3.7 and TF 2.2 was a bit of a fluke rather than intended behavior, as indicated by #839. However, it doesn't work consistently, which I verified by trying it out with the TF 1.14 image. This PR is to change the documentation to go with what we "officially recommended" at the time, which was the shell script workaround.
here's what I did to make sure that the shell script workaround works for TF 1.14:
```
$ cat src/entry.sh
python -m pip install -r requirements.txt
python hello.py
$ cat src/requirements.txt
pyfiglet
$ cat src/hello.py
from pyfiglet import Figlet
print(Figlet().renderText('hello').strip())
$ cat …
```
=> doc: fix TF requirements.txt documentation

doc/frameworks/tensorflow/sagemaker.tensorflow.rst
Docs build was failing on some extra tabs.
=> documentation: fix undoc directive; removes extra tabs

src/sagemaker/sklearn/estimator.py, src/sagemaker/xgboost/estimator.py, tests/unit/test_sklearn.py, tests/unit/test_xgboost.py
N/A
Add explicit handling for `entry_point`, `source_dir`, and `dependencies` arguments in `create_model` for SKLearn and XGBoost to match other framework estimators. Improve handling for `image` argument as well.
Unit tests updated to check for handling these arguments. Unit tests run with `tox tests/unit`, all tests passing.
=> fix: explicitly handle arguments in create_model for sklearn and xgboost

src/sagemaker/cli/compatibility/v2/files.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/test_file_updaters.py
#1478 
follow-up to #1492, #1497, and #1508 
`tox -e py36,pylint,flake8,black-format --parallel all -- -n 8 tests/unit`
=> infra: add unit tests for v2 migration script file updaters and modifiers

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tensorboard_remove_param.py
#1462, #1478 
follow-up to #1534 for covering the changes in #1510. I considered checking if the object having fit invoked contained "estimator", "tensorflow", or "tf", but after [Googling "run_tensorboard_locally"](https://www.google.com/search?q="run_tensorboard_locally"), it seems like this is the only place where such a parameter name exists. Even the search suggestions are all SageMaker-related:
As such, I feel confident that there won't be too many false positives with the criteria for `should_node_be_modified()`
unit tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …
=> change: make v2 migration script remove legacy run_tensorboard_locally parameter

doc/sagemaker.tensorflow.rst, src/sagemaker/cli/tensorflow.py, src/sagemaker/rl/estimator.py, src/sagemaker/tensorflow/__init__.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/model.py, tests/integ/test_data_capture_config.py, tests/integ/test_model_monitor.py, tests/integ/test_tfs.py, tests/unit/sagemaker/tensorflow/test_estimator.py, tests/unit/sagemaker/tensorflow/test_tfs.py, tests/unit/test_rl.py, tox.ini
#1462 
This changes the following two classes:
* `sagemaker.tensorflow.serving.Model` --> `sagemaker.tensorflow.model.TensorFlowModel`
* `sagemaker.tensorflow.serving.Predictor` --> `sagemaker.tensorflow.model.TensorFlowPredictor`
This PR also changes two attributes to match the other framework model classes:
* `FRAMEWORK_NAME` --> `__framework_name__`
* `_framework_version` --> `framework_version`
By submitting this pull request, I confirm that …
=>  breaking: rename sagemaker.tensorflow.serving to sagemaker.tensorflow.model

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/__init__.py, src/sagemaker/cli/compatibility/v2/modifiers/deprecated_params.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, tests/unit/sagemaker/cli/__init__.py, tests/unit/sagemaker/cli/compatibility/__init__.py, tests/unit/sagemaker/cli/compatibility/v2/__init__.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/__init__.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/ast_converter.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tensorboard_remove_param.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_legacy_mode.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_script_mode.py
=> change: make v2 migration script remove script_mode param and set model_dir=False if needed

doc/conf.py, setup.py, tox.ini
#1462
Now that the old serializers have been removed, there's no need to have `tensorflow` installed just to be able to use this SDK for TensorFlow inference.
=> infra: remove TF from optional dependencies

src/sagemaker/session.py, tests/unit/test_session.py
*Issue #:* #1542 
*Description of changes:* Use boto3 DEFAULT_SESSION when no boto3 session specified.
*Testing done:* Unit tests.
=> feature: Use boto3 DEFAULT_SESSION when no boto3 session specified.

src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_legacy_mode.py
https://github.com/aws/sagemaker-python-sdk/pull/1540#pullrequestreview-423731071
Addresses @nadiaya's comment on #1540
unit test, linters
=> fix: look for 'sagemaker.tensorflow.estimator' module in v2 migration tool

src/sagemaker/cli/compatibility/v2/modifiers/framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py
same thing as https://github.com/aws/sagemaker-python-sdk/pull/1550, but for the framework version modifier
=> fix: look for 'sagemaker.<framework>.<estimator/model>' module in v2 migration tool

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/__init__.py, src/sagemaker/cli/compatibility/v2/modifiers/tfs.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/ast_converter.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tfs.py
#1462
follow-up to #1541 
also manually tested:
```
$ cat input.py
import sagemaker.tensorflow.serving
from sagemaker.model import Model
from sagemaker.tensorflow.serving import Model as tfsModel
from sagemaker.tensorflow.serving import Predictor
sagemaker.tensorflow.serving.Model("foo")
sagemaker.tensorflow.serving.Predictor(name="foo")
Model()
tfsModel()
Predictor()
$ sagemaker-upgrade-v2 --in-file input.py --out-file output.py && cat output.py
import sagemaker.tensorflow
from sagemaker.model import Model
from sagemaker.tensorflow import TensorFlowModel as tfsModel
from sagemaker.tensorflow import TensorFlowPredictor
sagemaker.tensorflow.TensorFlowModel("foo") …
```
=> change: update v2 migration tool to rename TFS classes/imports

doc/frameworks/rl/using_rl.rst, doc/frameworks/tensorflow/deploying_tensorflow_serving.rst, doc/frameworks/tensorflow/index.rst, doc/frameworks/tensorflow/upgrade_from_legacy.rst, doc/frameworks/tensorflow/using_tf.rst
#1462 
TF doc update for v2 (see #1462)
built the docs locally and viewed them/clicked on the links I added
=> doc: update TF documentation to reflect breaking changes and how to upgrade

src/sagemaker/session.py
The Session refactor has been deprioritized, so no need for these warnings at the moment.
=> change: remove v2 Session warnings

doc/frameworks/tensorflow/upgrade_from_legacy.rst, src/sagemaker/cli/compatibility/v2/__init__.py, src/sagemaker/cli/compatibility/v2/files.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, src/sagemaker/cli/compatibility/v2/modifiers/tfs.py, src/sagemaker/cli/compatibility/v2/sagemaker_upgrade_v2.py
following a discussion on a previous PR
`tox -e doc8,sphinx`
=> doc: change "v2" to "version 2.0 or later"

doc/index.rst, doc/v2.rst
#1478 
This change begins documenting usage for v2 and for upgrading one's code for v2. I took some inspiration from TF's documentation (https://www.tensorflow.org/guide/upgrade).
Some notes:
* I wasn't sure where to put it, so it's in the top level for now, but feel free to suggest somewhere better.
* I plan on updating the changelog right before doing each release (v2.0.0.rc0 being the first one)
* I will likely add something akin to https://www.tensorflow.org/guide/migrate to the "Changes" section instead of just pointing to the changelog.
* `tox -e sphinx,doc8`
* built the docs locally and verified that they rendered as expected
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If …
=> doc: start v2 usage and migration documentation

src/sagemaker/local/local_session.py, src/sagemaker/predictor.py, tests/integ/test_multi_variant_endpoint.py, tests/unit/test_predictor.py
**Description of changes:**
Add support for specifying a target variant parameter when invoking a SageMaker endpoint with multiple production variants. 
**Testing done:**
- Unit Tests:
- Integration tests: 
=> feature: Support for multi variant endpoint invocation with target variant param

src/sagemaker/xgboost/estimator.py, src/sagemaker/xgboost/model.py, tests/integ/__init__.py, tests/integ/test_airflow_config.py, tox.ini
During work of requiring `framework_version` for all frameworks, some small doc and test improvements.
*Issue #, if available:* #1465
* small updates to docstrings
* small updates to tests
```
% tox --parallel 3 tests/unit
✔ OK black-format in 12.047 seconds
✔ OK flake8 in 25.667 seconds
✔ OK twine in 15.207 seconds
✔ OK pylint in 39.186 seconds
✔ OK doc8 in 22.472 seconds
✔ OK py36 in 35.675 seconds
✔ OK py37 in 37.08 seconds
✔ OK sphinx in 1 minute, 43.377 seconds
✔ OK py27 in 1 minute, 48.411 seconds
``` …
=> change: require framework_version, py_version for xgboost

doc/frameworks/sklearn/using_sklearn.rst, src/sagemaker/sklearn/estimator.py, src/sagemaker/sklearn/model.py, tests/integ/test_git.py, tests/integ/test_sklearn_train.py, tests/unit/test_sklearn.py
require framework_version and py_version for sklearn
*Issue #, if available:* #1465 
* framework_version, py_version required for framework SKLearn
* framework_version, py_version required for framework SKLearnModel
* py_version requires py3 or None, as py2 support dropped
* image_name required if either framework_version or py_version None
* unit and integ testing updates
* doc updates
unit:
```
% tox --parallel 3 tests/unit
✔ OK black-format in 11.287 seconds
✔ OK flake8 in 23.448 seconds
✔ OK twine in 13.898 seconds
✔ OK pylint in 35.064 seconds
✔ OK doc8 in 18.61 seconds
✔ OK py36 in 35.846 seconds
✔ OK sphinx in 1 minute, 26.284 seconds
✔ OK py37 in 36.384 seconds
✔ OK py27 in 1 minute, 50.325 seconds
```
integ:
```
% export …
```
=> breaking: require framework_version, py_version for sklearn

src/sagemaker/amazon/factorization_machines.py, src/sagemaker/amazon/ipinsights.py, src/sagemaker/amazon/kmeans.py, src/sagemaker/amazon/knn.py, src/sagemaker/amazon/lda.py, src/sagemaker/amazon/linear_learner.py, src/sagemaker/amazon/ntm.py, src/sagemaker/amazon/object2vec.py, src/sagemaker/amazon/pca.py, src/sagemaker/amazon/randomcutforest.py, src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/multidatamodel.py, src/sagemaker/sparkml/model.py, tests/unit/sagemaker/model/test_deploy.py, tests/unit/sagemaker/model/test_model.py, tests/unit/sagemaker/model/test_neo.py
https://github.com/aws/sagemaker-python-sdk/issues/1459#issuecomment-625936632
I'm not sure why we original made `model_data` required when it's technically not required for `CreateModel`. I did build my own Docker image to verify that I could make a working SageMaker Model with only an image for the container definition in `CreateModel` before making this change.
This change should affect only the interface for the generic `Model` class. I didn't want to change the other ones (i.e. first-party algos, frameworks) because afaik the Docker images associated with those do require model data in S3.
unit tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
=> breaking: change Model parameter order to make model_data optional

doc/frameworks/chainer/using_chainer.rst, src/sagemaker/chainer/estimator.py, src/sagemaker/chainer/model.py, tests/integ/test_chainer_train.py, tests/integ/test_tuner.py, tests/unit/test_chainer.py, tox.ini
*Issue #, if available:* #1465 
* framework_version, py_version required for framework Chainer
* framework_version, py_version required for framework ChainerModel
* re-order of args: convention to follow entry_point, push args with defaults below
* testing updates
* doc updates
unit:
```
% tox --parallel 3 tests/unit
✔ OK black-format in 8.452 seconds
✔ OK flake8 in 25.622 seconds
✔ OK twine in 17.197 seconds
✔ OK pylint in 40.253 seconds
✔ OK doc8 in 25.072 seconds
✔ OK py36 in 41.303 seconds
✔ OK py37 in 40.708 seconds
✔ OK sphinx in 1 minute, 49.507 seconds
✔ OK py27 in 2 minutes, 10.004 seconds
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
=> breaking: require framework_version, py_version for chainer

CHANGELOG.md, doc/v2.rst
doc update in preparation of releasing v2.0.0.rc0. I know we typically don't update the changelog manually (anymore), but since the release will be GitHub-only and not on PyPI, I don't plan on utilizing our CI/CD for it.
built the docs locally
=> doc: update documentation with v2.0.0.rc0 changes

src/sagemaker/cli/compatibility/v2/modifiers/framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py
*Issue #, if available:* #1465 
* transmogrify framework and model constructors to include `framework_version` and `py_version`, as appropriate
* testing
unit:
```
% tox --parallel 3 tests/unit
✔ OK black-format in 7.752 seconds
✔ OK flake8 in 21.401 seconds
✔ OK twine in 14.38 seconds
✔ OK pylint in 34.061 seconds
✔ OK doc8 in 19.642 seconds
✔ OK py36 in 52.532 seconds
✔ OK sphinx in 1 minute, 36.107 seconds
✔ OK py37 in 50.303 seconds
✔ OK py38 in 45.694 seconds
✔ OK py27 in 2 minutes, 10.535 seconds
``` …
=> change: make v2 migration script add version args when needed

setup.py
This was a workaround while waiting for rules_config to be released to PyPI. did verify with @knakad (the author of the TODO comment) that this can be removed now.
=> change: remove include_package_data=True from setup.py

README.rst, buildspec-localmodetests.yml, buildspec-release.yml, buildspec-unittests.yml, setup.py, src/sagemaker/__init__.py, tox.ini
#1461, #1469 
finally :)
note: updating our tests to no longer rely on having both py27 and py36 tox runs in the buildspecs will come in a series of subsequent PRs.
=> breaking: drop Python 2 support

tests/conftest.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_legacy_mode.py, tests/unit/test_chainer.py, tests/unit/test_pytorch.py
#1461
following #1609 
unit tests
=> infra: remove assumption of Python 2 unit test runs

tests/conftest.py, tests/integ/test_airflow_config.py, tests/integ/test_git.py, tests/integ/test_pytorch_train.py, tests/integ/test_source_dirs.py, tests/integ/test_transformer.py, tests/integ/test_tuner.py
Because we no longer run our tests with Python 2, the `PYTHON_VERSION` constant is less meaningful. Plus, our integ tests our for testing the Python SDK, not images, so it should be sufficient for us to just test on the latest framework/Python version combination. (The unit tests can still test every combination.)
I chose to make top-level fixtures because the greater plan is to have the fixtures generated once #1464 is done.
By submitting …
=> infra: use fixture for Python version in PyTorch integ tests

tests/integ/datasets.py, tests/integ/test_airflow_config.py, tests/integ/test_byo_estimator.py, tests/integ/test_factorization_machines.py, tests/integ/test_kmeans.py, tests/integ/test_knn.py, tests/integ/test_linear_learner.py, tests/integ/test_pca.py, tests/integ/test_record_set.py, tests/integ/test_transformer.py, tests/integ/test_tuner.py, tests/integ/test_tuner_multi_algo.py
Because we no longer run our tests with Python 2, we no longer need the branched logic for pickle.load args.
=> infra: clean up pickle.load logic in integ tests

tests/conftest.py, tests/integ/test_airflow_config.py, tests/integ/test_debugger.py, tests/integ/test_git.py, tests/integ/test_local_mode.py, tests/integ/test_multidatamodel.py, tests/integ/test_mxnet_train.py, tests/integ/test_neo_mxnet.py, tests/integ/test_transformer.py, tests/integ/test_tuner.py
=> infra: use fixture for Python version in MXNet integ tests

src/sagemaker/parameter.py, src/sagemaker/tuner.py, src/sagemaker/utils.py, tests/unit/test_utils.py
#1461
This method was written for Python 2 compatibility. For Python 3+, it is the same as simply calling `str()`.
`tox tests/unit/ --parallel all`
=> breaking: deprecate sagemaker.utils.to_str()

src/sagemaker/predictor.py
This is a pretty boring change, but one that gets to be made because of #1460 
`tox -e py36,py37,py38,black-format,flake8,pylint tests/unit/ --parallel all`
=> breaking: remove check for Python 2 string in sagemaker.predictor._is_sequence_like()

tests/conftest.py, tests/integ/test_airflow_config.py, tests/integ/test_data_capture_config.py, tests/integ/test_horovod.py, tests/integ/test_model_monitor.py, tests/integ/test_tf.py, tests/integ/test_tf_efs_fsx.py, tests/integ/test_tfs.py, tests/integ/test_transformer.py, tests/integ/test_tuner.py
see description of #1612
edit: I redid the fixture names due to there being different latest versions for TF and TFS. I was already thinking of replacing "full" with "latest" in the other framework fixtures but putting it off until #1464 (not sure what my rationale was, but so be it), but the TF fixtures were already confusing me enough as it was...
linters …
=> infra: use fixture for Python version in TF integ tests

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/__init__.py, src/sagemaker/cli/compatibility/v2/modifiers/airflow.py, src/sagemaker/workflow/airflow.py, tests/integ/test_airflow_config.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_airflow.py, tests/unit/test_airflow.py
This follows the work from #1567. It doesn't make sense to require `instance_type` in these two Airflow methods when it's not always used.
For the migration tool, I thought about not including `model_config()` on its own since there's a Keras module named `model_config`, but I couldn't find any function names that might collide. (Also, I tried searching GitHub to see what might be common ways of importing the function, but mostly just found people's forks/installations of our code.)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
=> breaking: make instance_type optional for Airflow model configs

tests/conftest.py, tests/integ/test_airflow_config.py, tests/integ/test_git.py, tests/integ/test_sklearn_train.py
see description of #1612
linters
=> infra: use fixture for Python version in scikit-learn tests

tests/conftest.py, tests/integ/__init__.py, tests/integ/test_airflow_config.py, tests/integ/test_chainer_train.py, tests/integ/test_rl.py, tests/integ/test_tuner.py
see description of #1612
I also cleaned up the remaining framework version fixtures that hadn't been caught in the previous PRs.
linters
=> infra: use fixture for Chainer and XGBoost Python version, clean up remaining version fixtures

tox.ini
as I discovered in #1633, [Python 3.8 introduced a change that required changes in `coverage`](https://github.com/nedbat/coveragepy/issues/707). This has been fixed in `coverage>=4.5.2`, and even though the builds were claiming that `coverage==5.1` was installed,  the coverage check was failing for only Python 3.8. Turns out [tox has some interesting caching behavior](https://github.com/tox-dev/tox/issues/149).
`tox -e py38 tests/unit` (and tried it out in #1633)
By …
=> infra: fix tox test dependencies and bump coverage threshold to 86%

tests/integ/test_model_monitor.py
* mark long-running cron tests
* return fixture's cron expression to what it was before
local integ and codebuild testing. ex:
```
❯ tox -q -e py38 -- -n 4 -rfE --disable-warnings -s -vv tests/integ/test_model_monitor.py -m "not cron"
...
tests/integ/test_model_monitor.py::test_default_monitor_suggest_baseline_and_create_monitoring_schedule_with_customizations[2.2.0]
[gw0] PASSED tests/integ/test_model_monitor.py::test_default_monitor_suggest_baseline_and_create_monitoring_schedule_with_customizations[2.2.0]
...
py38: commands succeeded
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> infra: mark long-running cron tests

src/sagemaker/fw_utils.py
https://github.com/aws/sagemaker-python-sdk/pull/1636/files#r446257630
=> change: fix punctuation in warning message

tests/integ/test_chainer_train.py, tests/integ/test_inference_pipeline.py, tests/integ/test_mxnet_train.py, tests/integ/test_neo_mxnet.py, tests/integ/test_pytorch_train.py, tests/integ/test_sklearn_train.py, tests/integ/test_sparkml_serving.py, tests/unit/sagemaker/automl/test_auto_ml.py, tests/unit/test_image.py, tox.ini
I got annoyed at having to scroll up so much when looking at test failures 😂 
`tox -e py38 tests/unit`
=> infra: address warnings about pytest custom marks, error message checking, and yaml loading

src/sagemaker/tensorflow/estimator.py
take 2. addressing a todo I left myself a few weeks ago.
=> change: add TF migration documentation to error message

src/sagemaker/model.py, src/sagemaker/utils.py, tests/unit/sagemaker/model/test_neo.py, tests/unit/test_utils.py
discovered this from the test failures in #1639 
=> fix: ensure generated names are < 63 characters when deploying compiled models

src/sagemaker/tuner.py, tests/unit/test_tuner.py
same as #1648 except for tuners. Also did a tiny bit of refactoring.
=> change: set _current_job_name and base_tuning_job_name in HyperparameterTuner.attach()

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/__init__.py, src/sagemaker/cli/compatibility/v2/modifiers/predictors.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_predictors.py
*Issue #, if available:* #1473 
* rename `RealTimePredictor` constructors as `Predictor`
* rename `endpoint` to `endpoint_name` in relevant Predictor base and derived classes
* rename `RealTimePredictor` in imports where appropriate
unit
=> infra: add cli modifier for RealTimePredictor and derived classes

doc/overview.rst, src/sagemaker/estimator.py, src/sagemaker/tuner.py, tests/integ/test_local_mode.py, tests/integ/test_source_dirs.py, tests/unit/test_estimator.py, tests/unit/test_tuner.py
This is a direct consequence of #1639 (and why the local mode tests aren't getting properly cleaned up in that PR build).
linters
=> breaking: deprecate delete_endpoint() for estimators and HyperparameterTuner

src/sagemaker/algorithm.py, src/sagemaker/chainer/estimator.py, src/sagemaker/estimator.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/predictor.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/rl/estimator.py, src/sagemaker/sklearn/estimator.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/xgboost/estimator.py, tests/integ/test_mxnet_train.py, tests/unit/sagemaker/tensorflow/test_estimator.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py, tests/unit/test_rl.py, tests/unit/test_sklearn.py, tests/unit/test_tuner.py, tests/unit/test_xgboost.py
#1470, #987 
By reusing the training job name for models, endpoint configs, and endpoints, trying to call `deploy()` twice on the same estimator can lead to a frustrating experience (e.g. #987).
I thought about letting the respective Model classes handle the name generation, but thought it would be nice to honor `base_job_name`, so that's why I went with what I did.
unit and integ tests …
=> breaking: create new inference resources during estimator.deploy() or estimator.transformer()

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/airflow.py, src/sagemaker/cli/compatibility/v2/modifiers/deprecated_params.py, src/sagemaker/cli/compatibility/v2/modifiers/framework_version.py, src/sagemaker/cli/compatibility/v2/modifiers/matching.py, src/sagemaker/cli/compatibility/v2/modifiers/predictors.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, src/sagemaker/cli/compatibility/v2/modifiers/tfs.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_matching.py
https://github.com/aws/sagemaker-python-sdk/pull/1653#discussion_r447897193
I was about to add another modifier and realized I might as well get this refactoring done so I don't re-implement this logic again.
=> infra: refactor matching logic in v2 migration tool

src/sagemaker/predictor.py, src/sagemaker/session.py, tests/integ/test_inference_pipeline.py, tests/integ/test_multidatamodel.py, tests/integ/test_mxnet_train.py, tests/unit/test_predictor.py
#1470 
tangentially related to #1470 is to move the endpoint-related methods away from estimators. Deprecating the `update_endpoint` arg in `deploy()` will come in a separate PR.
I chose not to take values from an existing `ProductionVariant` because I thought it would complicate the logic too much. Open to being convinced otherwise.
unit tests, linters, the affected integ tests
By submitting this pull request, I confirm that my contribution is made under the terms …
=> feature: add Predictor.update_endpoint()

doc/frameworks/mxnet/using_mxnet.rst, doc/frameworks/tensorflow/using_tf.rst, src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/__init__.py, src/sagemaker/cli/compatibility/v2/modifiers/estimators.py, src/sagemaker/fw_utils.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/tensorflow/estimator.py, tests/integ/test_horovod.py, tests/integ/test_local_mode.py, tests/integ/test_mxnet_train.py, tests/integ/test_tf.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_distribution.py, tests/unit/sagemaker/tensorflow/test_estimator.py, tests/unit/test_fw_utils.py, tests/unit/test_mxnet.py
#1473
This was a typo that wasn't caught until after a couple releases, so the consensus was to wait until other breaking changes to fix this.
=> breaking: rename distributions to distribution in TF/MXNet estimators

src/sagemaker/estimator.py, src/sagemaker/model_monitor/model_monitoring.py, src/sagemaker/model_monitor/monitoring_files.py, src/sagemaker/processing.py, src/sagemaker/s3.py, tests/integ/test_model_monitor.py, tests/integ/test_monitoring_files.py, tests/integ/test_multi_variant_endpoint.py, tests/integ/test_s3.py, tests/integ/test_transformer.py, tests/unit/test_s3.py
This is for consistency with the sagemaker_session parameter that is used everywhere else in this library.
I'll do the migration tool changes in a separate PR.
=> breaking: rename session parameter to sagemaker_session in S3 utilities

src/sagemaker/model.py, src/sagemaker/pipeline.py, tests/unit/sagemaker/model/test_deploy.py, tests/unit/sagemaker/model/test_model.py, tests/unit/sagemaker/model/test_model_package.py, tests/unit/sagemaker/model/test_neo.py
#1470 
This also changes how model and endpoint names are generated for compiled models, and removes the unused private attribute `model._model_name`.
=> breaking: create new inference resources during model.deploy() and model.transformer()

src/sagemaker/algorithm.py, tests/unit/test_algorithm.py
*Issue #, if available:* #1658 
* adding defaulted `train_use_spot_instances` and `train_max_wait` to the constructor and passing them on to the base class
unit:
```
✔ OK black-format in 10.938 seconds
✔ OK flake8 in 28.519 seconds
✔ OK twine in 22.751 seconds
✔ OK pylint in 49.668 seconds
✔ OK doc8 in 34.081 seconds
✔ OK sphinx in 56.674 seconds
✔ OK py36 in 48.587 seconds
✔ OK py37 in 47.733 seconds
✔ OK py38 in 41.45 seconds
✔ OK py27 in 2 minutes, 40.219 seconds
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …
=> feature: add spot instance support for AlgorithmEstimator

doc/frameworks/xgboost/using_xgboost.rst
Adding XGBoost documentation for inference.
=> doc: add xgboost documentation for inference

doc/algorithms/factorization_machines.rst, doc/algorithms/ipinsights.rst, doc/algorithms/kmeans.rst, doc/algorithms/knn.rst, doc/algorithms/lda.rst, doc/algorithms/linear_learner.rst, doc/algorithms/ntm.rst, doc/algorithms/object2vec.rst, doc/algorithms/pca.rst, doc/algorithms/randomcutforest.rst, doc/frameworks/chainer/using_chainer.rst, doc/frameworks/pytorch/using_pytorch.rst, doc/frameworks/rl/using_rl.rst, doc/frameworks/sklearn/using_sklearn.rst, doc/frameworks/tensorflow/upgrade_from_legacy.rst, doc/overview.rst, doc/v2.rst
#1473 
follow-up to #1667 and #1670 
* `tox -e doc8,sphinx`
* built the docs locally to verify some of the links
=> doc: update documentation for image_name/image --> image_uri

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/airflow.py, src/sagemaker/cli/compatibility/v2/modifiers/framework_version.py, src/sagemaker/cli/compatibility/v2/modifiers/matching.py, src/sagemaker/cli/compatibility/v2/modifiers/parsing.py, src/sagemaker/cli/compatibility/v2/modifiers/renamed_params.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_airflow.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_matching.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_parsing.py
#1473
follow-up to #1667 and #1670. Going to do the migration tool changes in pieces to try and keep the amount of changes per PR down.
This PR also adds some more utility functions for parsing and checking AST nodes.
=> change: handle image_uri rename in Airflow model config functions in v2 migration tool

src/sagemaker/deserializers.py, src/sagemaker/predictor.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_predictors.py, tests/unit/sagemaker/test_deserializers.py, tests/unit/test_predictor.py
* Added BytesDeserializer to sagemaker.deserializers
* Removed BytesDeserializer from sagemaker.predictor
* Added test to tests.unit.sagemaker.test_deserializers
=> breaking: Add BytesDeserializer

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/framework_version.py, src/sagemaker/cli/compatibility/v2/modifiers/renamed_params.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_image_uri.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_legacy_mode.py
#1473 
follow-up to #1667, #1670, and #1673.
=> change: handle image_uri rename for estimators and models in v2 migration tool

src/sagemaker/cli/compatibility/v2/modifiers/renamed_params.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_estimator_create_model.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_session_image_uri.py
#1473 
follow-up to #1667, #1670, #1673, and #1675.
for `create_model()`, I did a bunch of GitHub searches to verify that nothing I added to the "potential estimator name" list had a good chance for collision with non-SageMaker code. I thought about looking for anything with "estimator" in the name, but that had a few potential collisions. …
=> change: handle image_uri rename for Session methods

src/sagemaker/amazon/common.py, src/sagemaker/amazon/factorization_machines.py, src/sagemaker/amazon/kmeans.py, src/sagemaker/amazon/knn.py, src/sagemaker/amazon/lda.py, src/sagemaker/amazon/linear_learner.py, src/sagemaker/amazon/ntm.py, src/sagemaker/amazon/pca.py, src/sagemaker/amazon/randomcutforest.py, tests/unit/test_common.py
Renamed record_deserializer to RecordDeserializer and subclass BaseSerializer.
Fixed record_deserialzier tests.
=> breaking: rename record_deserializer to RecordDeserializer

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/__init__.py, src/sagemaker/cli/compatibility/v2/modifiers/renamed_params.py, src/sagemaker/cli/compatibility/v2/modifiers/training_params.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_training_params.py
=> change: handle "train_*" renames in v2 migration tool

src/sagemaker/chainer/model.py, src/sagemaker/deserializers.py, src/sagemaker/predictor.py, src/sagemaker/pytorch/model.py, src/sagemaker/sklearn/model.py, tests/unit/sagemaker/test_deserializers.py, tests/unit/test_predictor.py
*Issue #, if available:* #1694 
Moved `sagemaker.predictor._NumpyDeserializer` to `sagemaker.deserializers.NumpyDeserializer`. 
Moved relevant tests from `tests.unit.test_predictor` to `tests.unit.sagemaker.test_deserializers`
=> breaking: Move _NumpyDeserializer to sagemaker.deserializers.NumpyDeserializer

doc/frameworks/tensorflow/upgrade_from_legacy.rst, src/sagemaker/mxnet/model.py, src/sagemaker/predictor.py, src/sagemaker/serializers.py, src/sagemaker/tensorflow/model.py, tests/integ/test_inference_pipeline.py, tests/integ/test_multidatamodel.py, tests/unit/sagemaker/test_serializers.py, tests/unit/test_predictor.py
*Issue #, if available:* #1694 
Moved `sagemaker.serializers._JsonSerializer` to `sagemaker.serializers.JSONSerializer`
Moved related tests from `tests.unit.test_predicctor` to `tests.unit.sagemaker.test_serializers`.
=> breaking: Move _JsonSerializer to sagemaker.serializers.JSONSerializer

src/sagemaker/cli/compatibility/v2/modifiers/framework_version.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_framework_version.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_legacy_mode.py
admittedly not my best code, but I didn't want to tamper too much with the setup in `test_framework_version`
=> fix: handle named variables in v2 migration tool

src/sagemaker/tensorflow/defaults.py, tests/conftest.py, tests/integ/test_data_capture_config.py, tests/integ/test_model_monitor.py, tests/integ/test_tf_script_mode.py, tests/integ/test_tfs.py, tests/integ/test_transformer.py, tests/unit/test_fw_utils.py
duplicate of #1595 
update TensorFlow.defaults.LATEST_SERVING_VERSION to 2.2.0
update tf and related integ tests to use py_version fixture
=> feature: support TFS 2.2

tests/conftest.py, tests/integ/test_airflow_config.py, tests/integ/test_chainer.py, tests/integ/test_tuner.py
#1464 
follow-up to #1701 
* linters
* `--collect-only` with pytest to verify the fixtures
=> infra: generate Chainer latest version fixtures from config

src/sagemaker/image_uri_config/factorization-machines.json, src/sagemaker/image_uri_config/tensorflow.json, src/sagemaker/image_uris.py, tests/unit/sagemaker/image_uris/__init__.py, tests/unit/sagemaker/image_uris/expected_uris.py, tests/unit/sagemaker/image_uris/test_algos.py, tests/unit/sagemaker/image_uris/test_dlc_frameworks.py, tests/unit/sagemaker/image_uris/test_retrieve.py
#1464 
This also adds configuration for Factorization Machines.
=> feature: add support for Amazon algorithms in image_uris.retrieve()

src/sagemaker/model_monitor/model_monitoring.py
Add information of Amazon-provided analysis image used by Model Monitor
Tested by running sample Model Monitor notebooks with this monkey-patched in.
=> feature: Add model monitor support for us-gov-west-1

doc/frameworks/mxnet/using_mxnet.rst
I realized I'd gotten these wrong before 😭 
the nitty gritty behind the different versions:
* 0.12.1-1.2.1: the images relied on `sagemaker-container-support<2`, which didn't have requirements.txt support
* 1.3.0: the images relied on `sagemaker-containers>=2`, which did have requirements.txt support
* 1.4.0-1.4.1
* training: still using `sagemaker-containers>=2`
* serving: used `sagemaker-inference`, which initially didn't have requirements.txt support
* 1.6.0
* training: I think it moved to using `sagemaker-training`, which does still have requirements.txt support
* serving: `sagemaker-inference` gained requirements.txt support by the time these were released
_Put an `x` in the boxes that apply. You can also fill these …
=> doc: fix MXNet version info for requirements.txt support

src/sagemaker/image_uri_config/image-classification-neo.json, src/sagemaker/image_uri_config/xgboost-neo.json, src/sagemaker/image_uris.py, tests/unit/sagemaker/image_uris/test_algos.py, tests/unit/sagemaker/image_uris/test_neo.py, tests/unit/sagemaker/image_uris/test_retrieve.py, tests/unit/sagemaker/image_uris/test_xgboost.py
#1464 
This was common enough that I decided to go ahead and add logic for the case where a single image is used for both training and inference. This should also hopefully help with making it easier to migrate from `sagemaker.amazon.amazon_estimator.get_image_uri` to `sagemaker.image_uris.retrieve`
unit tests
=> change: make image_scope optional for some images in image_uris.retrieve()

src/sagemaker/chainer/model.py, src/sagemaker/cli/compatibility/v2/modifiers/tf_legacy_mode.py, src/sagemaker/estimator.py, src/sagemaker/mxnet/model.py, src/sagemaker/pytorch/model.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/model.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_tf_legacy_mode.py, tests/unit/sagemaker/tensorflow/test_estimator.py, tests/unit/sagemaker/tensorflow/test_tfs.py, tests/unit/test_airflow.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py
#1464 
still need to add configuration for inferentia, Neo, and RL before fully deprecating `create_image_uri`
unit tests
=> change: use image_uris.retrieve instead of fw_utils.create_image_uri for DLC frameworks

doc/overview.rst, src/sagemaker/amazon/amazon_estimator.py, src/sagemaker/amazon/factorization_machines.py, src/sagemaker/amazon/ipinsights.py, src/sagemaker/amazon/kmeans.py, src/sagemaker/amazon/knn.py, src/sagemaker/amazon/lda.py, src/sagemaker/amazon/linear_learner.py, src/sagemaker/amazon/ntm.py, src/sagemaker/amazon/object2vec.py, src/sagemaker/amazon/pca.py, src/sagemaker/amazon/randomcutforest.py, tests/integ/test_airflow_config.py, tests/integ/test_byo_estimator.py, tests/integ/test_tuner.py, tests/integ/test_tuner_multi_algo.py, tests/unit/test_airflow.py, tests/unit/test_amazon_estimator.py, tests/unit/test_estimator.py, tests/unit/test_fm.py, tests/unit/test_ipinsights.py, tests/unit/test_kmeans.py, tests/unit/test_knn.py, tests/unit/test_lda.py, tests/unit/test_linear_learner.py, tests/unit/test_ntm.py, tests/unit/test_object2vec.py, tests/unit/test_pca.py, tests/unit/test_randomcutforest.py
#1464 
This also deprecates sagemaker.amazon.amazon_estimator.registry()
unit tests
=> breaking: deprecate sagemaker.amazon.amazon_estimator.get_image_uri()

src/sagemaker/workflow/airflow.py
Fixes nullable values in processing_config for MaxRuntimeInSeconds and ProcessingInputs/Outputs.
=> fix: Nullable fields in processing_config

src/sagemaker/workflow/airflow.py, tests/unit/test_airflow.py
Error "TypeError: Object of type 'NetworkConfig' is not JSON serializable" when using network_config with ScriptProcessor. Need to convert this to a dict. 
Unit tests pass. 
=> fix: convert network_config in processing_config to dict

src/sagemaker/user_agent.py, tests/unit/test_create_deploy_entities.py, tests/unit/test_default_bucket.py, tests/unit/test_endpoint_from_job.py, tests/unit/test_endpoint_from_model_data.py, tests/unit/test_exception_on_bad_status.py, tests/unit/test_image.py, tests/unit/test_session.py, tests/unit/test_upload_data.py, tests/unit/test_upload_string_as_file_body.py, tests/unit/test_utils.py
Remove redundant information from the user_agent string.
=> fix: remove redundant information from the user_agent string.

buildspec-unittests.yml, tox.ini
this also parallelizes the linters
unit tests
=> infra: use pytest-cov instead of coverage

tests/integ/test_tfs.py
We're getting some collisions with our continuous testing when log groups are cleaned up
=> infra: use unique model name in TFS integ tests

src/sagemaker/deserializers.py, tests/unit/sagemaker/test_deserializers.py
*Issue #, if available:* #1753 
* Added `allow_pickle` parameter to `NumpyDeserializer` with default argument `True`
* Updated one test to more accurately test deserializer picked objects
* Adding a new test.
=> change: Add allow_pickle parameter to NumpyDeserializer

doc/v2.rst
#1749, #1462 
I forgot to document the TFS changes in #1462. 
* `tox -e sphinx,doc8 --parallel all`
* built the docs locally to check formatting and links
=> doc: document name changes for TFS classes

src/sagemaker/serializers.py, tests/unit/sagemaker/test_serializers.py
* Added `JSONLinesSerializer` to `serializers.py`
* Added appropriate tests to `test_serializers.py`
=> feature: Add JSON Lines serializer

src/sagemaker/estimator.py, src/sagemaker/model.py, tests/unit/sagemaker/model/test_neo.py
Add Granular Target Description support for DL model compilation.
Example:
```
model.compile(
target_instance_family=None,
input_shape={"data": [1, 3, 1024, 1024]},
output_path="s3://output",
role="role",
framework="tensorflow",
job_name="compile-model",
target_platform_os="LINUX",
target_platform_arch="ARM64",
target_platform_accelerator="NVIDIA",
compiler_options={"gpu-code": "sm_72", "trt-ver": "6.0.1", "cuda-ver": "10.1"}
)
```
=> feature: Add Granular Target Description support for compilation (Neo)

doc/amazon_sagemaker_processing.rst
SageMaker Processing tech docs had multiple typos. See SIM-ticket #P38040016
Fixed typos. Re-worded sentence in the "Background" section so it is more readable. 
None. 
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
By submitting this pull …
=> fixed typos on processing docs

src/sagemaker/serializers.py, tests/unit/sagemaker/test_serializers.py
Depending on the version of scipy installed, you might not be able to do `import scipy` and then access the attribute `scipy.sparse`. Instead, you should either do `from scipy import sparse` or directly `import scipy.sparse`.
* Updated import statement in `serializers.py`
=> fix: Fix scipy.sparse imports

src/sagemaker/cli/compatibility/v2/modifiers/serde.py
This is a follow-up to #1735.
Fixed a couple docstrings and a generator expresion.
=> change: Improve code style of SerDe compatibility

src/sagemaker/rl/estimator.py, tests/conftest.py, tests/data/ray_cartpole/train_ray.py, tests/integ/test_rl.py, tests/unit/sagemaker/image_uris/test_rl.py, tests/unit/test_rl.py
#1464 
follow-up to #1729. I also incorporated most of @yijiezh's remaining changes from #1618.
relevant unit tests and integ tests
=> change: use generated RL version fixtures and update Ray version

src/sagemaker/chainer/estimator.py, src/sagemaker/chainer/model.py, src/sagemaker/estimator.py, src/sagemaker/model.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/mxnet/model.py, src/sagemaker/pytorch/estimator.py, src/sagemaker/pytorch/model.py, src/sagemaker/sklearn/estimator.py, src/sagemaker/sklearn/model.py, src/sagemaker/tensorflow/estimator.py, src/sagemaker/tensorflow/model.py, src/sagemaker/xgboost/estimator.py, src/sagemaker/xgboost/model.py, tests/unit/sagemaker/tensorflow/test_estimator_init.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_job.py, tests/unit/test_mxnet.py, tests/unit/test_pytorch.py
*Issue #, if available:* #1607 
rename `__framework_name__` as `_framework_name`
unit:
```
❯ tox tests/unit
...
black-format: commands succeeded
twine: commands succeeded
sphinx: commands succeeded
doc8: commands succeeded
py36: commands succeeded
py37: commands succeeded
py38: commands succeeded
```
=> change: rename __framework_name__ as _framework_name

src/sagemaker/cli/compatibility/v2/ast_transformer.py, src/sagemaker/cli/compatibility/v2/modifiers/serde.py, tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_serde.py
* Update `sagemaker.cli.compatibility.v2.serde.py` 
* Added two parameterized tests to `test_serde.py`
=> feature: Update migration tool to support breaking changes to create_model

tests/scripts/run-notebook-test.sh
* the TF notebook being removed uses Python 2.7
* the MXNet one has some parameters that have been renamed
=> infra: remove v2-incompatible notebooks from notebook build

setup.py
upgrade airflow to latest stable release from 1.10.9 to 1.10.11
```
❯ tox tests/unit
...
black-format: commands succeeded
twine: commands succeeded
sphinx: commands succeeded
doc8: commands succeeded
py36: commands succeeded
py37: commands succeeded
py38: commands succeeded
```
=> change: upgrade airflow to 1.10.11

setup.py
We have recently released smdebug_rulesconfig package 0.1.5
This change updates the dependecy of this package of rulesconfig from 0.1.4 to 0.1.5
Testing done:
Ran tox -e py37 tests/unit 
Ran export IGNORE_COVERAGE=- ; tox -e py37 -- -s -vv tests/integ
=> change: update rulesconfig to 0.1.5

src/sagemaker/cli/compatibility/v2/modifiers/image_uris.py, tests/unit/sagemaker/cli/compatibility/v2/test_ast_transformer.py
Fixes #1847 
check for `None` on node for renamers following the serde renamers for the cli v2 updater
new test included:
```
✔ OK black-format in 7.632 seconds
✔ OK flake8 in 23.871 seconds
✔ OK twine in 17.505 seconds
✔ OK pylint in 32.506 seconds
✔ OK doc8 in 19.725 seconds
✔ OK sphinx in 32.056 seconds
✔ OK py37 in 4 minutes, 18.556 seconds
✔ OK py36 in 4 minutes, 39.279 seconds
✔ OK py38 in 4 minutes, 26.307 seconds
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
=> fix: check ast node on later renamers for cli v2 updater

src/sagemaker/estimator.py, src/sagemaker/session.py
this provides two additional internal methods to get arguments for train methods
unit:
```
✔ OK black-format in 10.134 seconds
✔ OK flake8 in 27.386 seconds
✔ OK twine in 20.222 seconds
✔ OK pylint in 38.212 seconds
✔ OK doc8 in 19.645 seconds
✔ OK sphinx in 56.737 seconds
✔ OK py36 in 7 minutes, 48.56 seconds
✔ OK py38 in 7 minutes, 5.45 seconds
✔ OK py37 in 7 minutes, 43.492 seconds
```
By submitting this …
=> change: separate out methods to get train arguments

src/sagemaker/processing.py, src/sagemaker/session.py
This provides two additional internal methods to get arguments for processing methods
unit:
```
✔ OK black-format in 13.813 seconds
✔ OK flake8 in 28.431 seconds
✔ OK twine in 20.916 seconds
✔ OK pylint in 40.527 seconds
✔ OK doc8 in 20.635 seconds
✔ OK sphinx in 42.729 seconds
✔ OK py36 in 5 minutes, 6.696 seconds
✔ OK py37 in 5 minutes, 13.55 seconds
✔ OK py38 in 4 minutes, 57.917 seconds
```
By submitting …
=> change: break out methods to get processing arguments

mypy.ini, tox.ini
Include mypy as tox testenv tox target, but don't include it in the tested environments.
Informational run:
```
tox -e typing
...
Found 36 errors in 19 files (checked 112 source files)
```
=> feature: add mypy tox target

src/sagemaker/tensorflow/defaults.py, src/sagemaker/tensorflow/estimator.py, tests/unit/sagemaker/tensorflow/test_estimator_init.py
Set TF 2.1.1 as the highest version of TensorFlow which can be used with Python 2
Tested by running unit tests locally.
=> change: Set TF 2.1.1 as highest py2 version for TF

tests/unit/sagemaker/image_uris/test_debugger.py
Adding Debugger Repo Account IDs for `af-south-1` (Cape Town) and `eu-south-1` (Milan)
None
- [] I have added tests that prove my fix is effective or that my feature works (if appropriate)
=> infra: add regional account ids for af-south-1 and eu-south-1 to unit test

doc/v2.rst
Change max_run_wait to max_wait required by estimators.
Issue #, if available: max_run_wait is not accepted by estimators.
Description of changes: Change max_run_wait to max_wait required by estimators.
Testing done: Launched an estimator with `max_wait` parameter
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-cha …
=> documentation Update v2.rst - max_wait 

buildspec.yml
* run integ tests when image_uri_config jsons are changed. such changes would go ignored and integs would pass
=> fix: run integ tests when image_uri_config jsons are changed

src/sagemaker/analytics.py, tests/integ/test_experiments_analytics.py, tests/unit/test_experiments_analytics.py
*Issue #, if available:* https://github.com/aws/sagemaker-experiments/issues/99
*Description of changes:* map "Parents" field in search response to experiments analytics dataframe
*Testing done:* run unit tests
=> reshape Parents into experiment analytics dataframe

tests/integ/test_tf.py
`training_job_analytics` gives empty DataFrame. TrainingJob does not seem to be emitting metrics to cloudwatch.
Also this assertion seems to be unrelated to the test itself.
Remove DataFrame assertion from the test.
We need to add independent integ test for `training_job_analytics`.
=> fix: remove DataFrame assert from unrelated test

buildspec-release.yml, tests/scripts/run-notebook-test.sh
- Follow up on https://github.com/aws/sagemaker-python-sdk/pull/1908
- remove notebooks from test that call `pip install -U sagemaker`
=> infra: update buildspecs for v1

buildspec-release.yml
- Follow up on https://github.com/aws/sagemaker-python-sdk/pull/1916
=> infra: fix release buildspec pytest command flag order

tests/integ/test_neo_mxnet.py
We need to upgrade the Neo version, update the image uri and update the training script.
=> fix: temporarily skip the MxNet Neo test until we fix them

buildspec-release.yml, tests/integ/test_airflow_config.py
- Follow up on https://github.com/aws/sagemaker-python-sdk/pull/1916 and https://github.com/aws/sagemaker-python-sdk/pull/1918
- Skipping the broken test with `-k` does not seem to be working in the release build. Instead, removing `canary_quick` from the test.
=> infra: remove canary_quick pytest mark

buildspec-release.yml
Fixed the issue that https://github.com/aws/sagemaker-python-sdk/pull/1918 and https://github.com/aws/sagemaker-python-sdk/pull/1919 attempted to address.
Manually started a build on CodeBuild using the command in this modified buildspec. Confirmed that it executes the correct tests as expected and passes.
=> infra: update release build integ test command

setup.py
The `--result-log` option has been removed. Users are recommended to use the pytest-reportlog plugin instead.
Pin pytest < 6.1.0 to unblock PR builds, adopt `pytest-reporting` later
=> fix: pin pytest<6.1.0 to avoid pytest-rerunfailures breaking changes

src/sagemaker/model.py
#1932 
Rename the .json that holds registry information for neo containers.
```
tox -e flake8,pylint,twine,black-check --parallel all
tox -e py38 tests/unit
```
=> Add a condition to retrieve correct image URI for xgboost

src/sagemaker/deprecations.py, src/sagemaker/estimator.py, src/sagemaker/mxnet/estimator.py, src/sagemaker/predictor.py, tests/unit/test_deprecations.py
In forward-porting of attributes, also update `kwargs`, as the instance attribute itself may not be used in the constructor, even if initially set.
```
✔ OK black-format in 13.06 seconds
✔ OK flake8 in 31.197 seconds
✔ OK docstyle in 31.286 seconds
✔ OK pylint in 44.389 seconds
✔ OK twine in 7.858 seconds
✔ OK doc8 in 14.121 seconds
✔ OK sphinx in 40.423 seconds
✔ OK py36 in 5 minutes, 51.503 seconds
✔ OK py37 in 6 minutes, 2.295 seconds
✔ OK py38 in 5 minutes, 52.853 seconds
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …
=> fix: update kwargs target attribute

src/sagemaker/model.py, src/sagemaker/mxnet/model.py, src/sagemaker/pytorch/model.py, src/sagemaker/tensorflow/model.py, src/sagemaker/xgboost/model.py
=> documentation: kwargs descriptions include clickable links

src/sagemaker/pipeline.py, tests/unit/test_pipeline_model.py
Pass `enable_network_isolation` to `create_model` when instantiating a `PipelineModel`.
Ran unit tests locally.
=> feat: add network isolation support for PipelineModel

src/sagemaker/session.py
=> change: refactor _create_model_request

src/sagemaker/debugger.py
#1964
- Updated docstrings
- Added more explanations, available parameter values, and examples
- local build is successful
=> doc: Debugger API - improve docstrings and add examples

doc/v2.rst
After #1939, some items are no longer breaking changes in v2. This PR updates the documentation accordingly.
`tox -e sphinx`
=> doc: clarify non-breaking changes after v1 forward port

src/sagemaker/workflow/airflow.py
Create the default bucket only if the `output_path` is `None`.
`tox -e black-format,py38 tests/unit/test_airflow.py`
=> fix: create default bucket only if needed

src/sagemaker/tensorflow/estimator.py
Call `deprecations.renamed_kwargs` to check for the `distributions` keyword argument in the TensorFlow Estimator.
=> fix: check for distributions in TF estimator

src/sagemaker/feature_store/feature_group.py, tests/unit/sagemaker/feature_store/test_feature_store.py
itertuples doesn't return named tuples with large number of column(>254)
with python versions < 3.7. See:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html
row._asdict() would fail with regular tuples. Switching to iterrows here
to avoid this limitation.
=> fix: use iterrows to iterate pandas dataframe

src/sagemaker/cli/compatibility/v2/files.py, tests/unit/sagemaker/cli/compatibility/v2/test_file_updaters.py
We have example notebooks with cells contains "%cd". Those notebooks are failing to convert currently.
=> fix: v2 upgrade tool should ignore cell starts with '%'

tests/integ/__init__.py, tests/integ/test_edge.py, tests/integ/test_smdataparallel_pt.py, tests/integ/test_smdataparallel_tf.py
=> fix: only run DataParallel and EdgePackaging tests in supported regions

doc/api/training/smd_data_parallel.rst, doc/api/training/smd_model_parallel.rst, doc/frameworks/pytorch/using_pytorch.rst
* Adding note to clarify SMP CUDA version support
* ```tox -e black-check,flake8,pylint,docstyle,sphinx,doc8 --parallel all```
=> documentation: adding note about CUDA 11 to SMP

doc/api/training/smd_data_parallel.rst, doc/api/training/smd_model_parallel.rst, doc/api/training/smd_model_parallel_general.rst
* SMP code sample was incorrect - missing `modelparallel` parameter
* Added `modelparallel` to estimator definition code example
* Added note about CUDA 11 in SDP documentation 
* ` tox -e black-check,flake8,pylint,docstyle,sphinx,doc8 --parallel all` 
=> documentation: fix SMP code example, added note for CUDA 11 to SDP

tests/integ/test_workflow.py, tests/integ/test_workflow_with_clarify.py
Added integ tests for workflow with clarify and debugger configuration
- tests/integ/test_workflow_with_clarify.py: Executes a pipeline with processing step that uses analysis config with pre_training_bias and post_training bias. Pipeline also runs a condition step based on the processing step bias result.
- tests/integ/test_workflow.py: Executes a pipeline with training step with rules and debugger hook config configured
Executed both the integ tests locally
By …
=> change: include workflow integ tests with clarify and debugger enabled

src/sagemaker/feature_store/feature_group.py, tests/integ/test_feature_store.py
iterrows converts int to floats which causes ingestion to fail see - https://github.com/aws/sagemaker-python-sdk/issues/2032
=> fix: use itertuples to ingest pandas dataframe to FeatureStore

tests/integ/test_feature_store.py
* lower value used and use deterministic value in featurestore integ test
=> fix: lower value used in featurestore test

doc/api/training/smd_data_parallel.rst, doc/api/training/smd_data_parallel_pytorch.rst, doc/api/training/smd_data_parallel_tensorflow.rst, doc/api/training/smd_model_parallel.rst, doc/api/training/smd_model_parallel_common_api.rst, doc/api/training/smd_model_parallel_general.rst, doc/api/training/smd_model_parallel_pytorch.rst
* Fix a couple of missing links
* Refactor distributed training libraries' naming convention.
**Please push a new version, so that the RTD website gets these updates ASAP.**
`tox -e black-check,flake8,pylint,docstyle,sphinx,doc8 --parallel all`
```
black-check: commands succeeded
docstyle: commands succeeded
sphinx: commands succeeded
doc8: commands succeeded
```
=> documentation: adjust naming convention; fix links

src/sagemaker/local/image.py
Fixes https://github.com/aws/sagemaker-python-sdk/issues/2043  
Fixes https://github.com/aws/sagemaker-python-sdk/issues/2022
Check if metadata dir exists locally before mounting
Tested on Mac locally, a scenario which threw the error reported earlier, and now works fine. 
=> fix: Check if metadata dir exists locally before mounting

src/sagemaker/image_uri_config/sparkml-serving.json, src/sagemaker/sparkml/model.py, tests/unit/sagemaker/image_uris/test_sparkml.py, tests/unit/test_pipeline_model.py
fixes: #2021 
* properly include version 2.4 in image uri config
* updated default value to properly use `"2.4"` as string
* added unit test, updated tests
unit:
```
✔ OK black-format in 11.873 seconds
✔ OK flake8 in 42.442 seconds
✔ OK docstyle in 46.608 seconds
✔ OK pylint in 59.418 seconds
✔ OK twine in 12.52 seconds
✔ OK doc8 in 16.759 seconds
✔ OK sphinx in 54.736 seconds
✔ OK py36 in 7 minutes, 37.158 seconds
✔ OK py37 in 7 minutes, 50.654 seconds
✔ OK py38 in 7 minutes, 32.257 seconds
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here …
=> fix: include sparkml 2.4 in image uri config properly

CONTRIBUTING.md
=> documentation: clarify when tests should be marked as a canary

src/sagemaker/git_utils.py, tests/unit/test_git_utils.py
* set permissions correctly using octal 0o511
* add assertions in unit tests
unit testing:
```
✔ OK black-format in 12.333 seconds
✔ OK flake8 in 36.332 seconds
✔ OK docstyle in 39.275 seconds
✔ OK pylint in 53.395 seconds
✔ OK twine in 11.169 seconds
✔ OK doc8 in 16.069 seconds
✔ OK sphinx in 48.019 seconds
✔ OK py36 in 7 minutes, 5.922 seconds
✔ OK py37 in 7 minutes, 17.774 seconds
✔ OK py38 in 7 minutes, 7.518 seconds
``` …
=> fix: update git utils temp file

src/sagemaker/local/image.py, tests/unit/test_image.py
Using `shell=True` is a security risk - https://docs.python.org/2/library/subprocess.html#subprocess.check_output
=> fix: remove shell=True in subprocess.check_output

tests/integ/test_workflow.py
This test is failing in ARN. Right now we are only seeing keyerror. this should output the failure reason in the log.
=> fix: assert step execution first in pipeline test

doc/v2.rst
=> documentation: use correct classpath in V2 alias documentation.

tests/integ/sagemaker/lineage/test_artifact.py
* increase time allowed for trial components to index in integration testing
=> fix: increase time allowed for trial components to index

doc/api/training/smd_model_parallel.rst, doc/api/training/smp_versions/v1.1.0/smd_model_parallel_common_api.rst, doc/api/training/smp_versions/v1.1.0/smd_model_parallel_pytorch.rst, doc/api/training/smp_versions/v1.1.0/smd_model_parallel_tensorflow.rst, doc/api/training/smp_versions/v1.2.0/smd_model_parallel_common_api.rst, doc/api/training/smp_versions/v1.2.0/smd_model_parallel_pytorch.rst, doc/api/training/smp_versions/v1.2.0/smd_model_parallel_tensorflow.rst, doc/api/training/smp_versions/v1_1_0.rst, doc/api/training/smp_versions/v1_2_0.rst
=> documentation: Add SMP 1.2.0 API docs

tests/data/multimodel/container/Dockerfile
The multimodel tests are failing because they failed to build the image needed in the tests. The base image is ubuntu16 so the default python3 version installed is 3.5 and it doesn't support f string which is used in the new version of get-pip.py:
```
File "get-pip.py", line 82, in bootstrap
from pip._internal.cli.main import main as pip_entry_point
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 896, in _find_spec
File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec …
```
=> fix: use 3.5 version of get-pip.py

tests/integ/sagemaker/lineage/conftest.py, tests/integ/sagemaker/lineage/test_artifact.py
add integration test for listing artifacts by type
```
tox -e py38 -- tests/integ/sagemaker/lineage/test_artifact.py -k 'test_list_by_type'
```
=> change: add integration test for listing artifacts by type

tests/integ/sagemaker/lineage/test_action.py, tests/integ/sagemaker/lineage/test_artifact.py, tests/integ/sagemaker/lineage/test_association.py, tests/integ/sagemaker/lineage/test_context.py
*Issue #, if available:* https://sim.amazon.com/issues/AML-109079
*Description of changes:* Fix assert statements in test_tag/test_tags method in association tests
*Testing done:*  tox -e py39 -- tests/integ/sagemaker/lineage --sagemaker-client-config {\"endpoint_url\":\"https://api.sagemaker.beta.us-west-2.ml-platform.aws.a2z.com\"}
collected 30 items                                                                                                                                                                                                                        
tests/integ/sagemaker/lineage/test_action.py ....... …
=> test_tag/test_tags method assert fix in association tests

doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.md, doc/api/training/smp_versions/v1.2.0/smd_model_parallel_tensorflow.rst
* removing mention of TF 2.4 from SM distributed model parallel docs
`tox -e black-check,flake8,pylint,docstyle,sphinx,doc8 --parallel all`
=> documentation: removing mention of TF 2.4 from SM mp docs

buildspec-deploy.yml, buildspec-release.yml
Since we now run the release build in each region, moving the package preparation and publishing to the deploy step so it occurs only once.
=> infra: move package preparation and publishing to the deploy step

tox.ini
a recent update to a transitive dep rolled in that caused breakages: https://pypi.org/project/astroid/#history
* pin astroid to 2.4.2 for the time being
```
❯ tox -e pylint
...
pylint installdeps: pylint, astroid==2.4.2
pylint installed: astroid==2.4.2,isort==5.7.0,lazy-object-proxy==1.4.3,mccabe==0.6.1,pylint==2.6.0,six==1.15.0,toml==0.10.2,wrapt==1.12.1
pylint run-test-pre: PYTHONHASHSEED='231695462'
pylint run-test: commands[0] | python -m pylint --rcfile=.pylintrc -j 0 src/sagemaker
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
______________________________________________ summary …
```
=> fix: pin astroid to 2.4.2

src/sagemaker/analytics.py, tests/integ/test_clarify_model_monitor.py
These two tests consistently run for over 30 minutes. A baselining job is a normal Clarify processing job which has been tested by integ/test_clarify.py and the create_monitor_schedule part has already been covered with other tests in the same test module. Removing the two tests to shorten pr tests runtime.
=> change: remove slow test_run_xxx_monitor_baseline tests

src/sagemaker/image_uris.py, tests/unit/sagemaker/image_uris/test_retrieve.py
Added fix to enable py3 to cuda11 images.
unit tests
=> fix: add the mapping from py3 to cuda11 images for pytorch containers

buildspec-slowtests.yml, tests/data/multimodel/container/Dockerfile, tests/integ/test_lda.py, tests/integ/test_model_quality_monitor.py, tests/integ/test_multidatamodel.py, tests/integ/test_tf.py, tests/integ/test_tuner.py
Couple of the slow tests were not running because the slow tests run in us-west-2 and the multimodel tests only runs in us-east-2. They only run in us-east-2 because the base ubuntu16 image was only pushed to us-east-2 in the dev account. Switching to ECR public and upgrade to ubuntu18 so we can run the tests in all regions. 
This change also mark a few more tests as slow_test. …
=> fix: use ECR public for multidatamodel tests

tests/integ/test_workflow.py
We are using a separate workflow_session in some of the workflow tests which is not required. We can simply use sagemaker_session.
updated test_workflow.py to use sagemaker_session in all the tests
Ran integ tests locally
=> change: use sagemaker_session in workflow tests

doc/workflows/pipelines/sagemaker.workflow.pipelines.rst, src/sagemaker/workflow/steps.py
remove unsupported `FailStep`
```
✔ OK flake8 in 35.836 seconds
✔ OK black-format in 46.193 seconds
✔ OK pylint in 53.496 seconds
✔ OK docstyle in 36.988 seconds
✔ OK doc8 in 34.241 seconds
✔ OK twine in 42.776 seconds
✔ OK sphinx in 3 minutes, 31.701 seconds
✔ OK py36 in 9 minutes, 32.944 seconds
✔ OK py37 in 9 minutes, 32.309 seconds
✔ OK py38 in 7 minutes, 54.123 seconds
```
By submitting this pull request, …
=> fix: remove FailStep from pipelines

buildspec-release.yml, tests/integ/test_experiments_analytics.py
- reduce concurrency of release builds to reduce likelihood of throttling
- increase test set to `not (local_mode or slow_test)`
- eliminate redundant `experiment_analytics` test
=> infra: unblock regional release builds

buildspec-release.yml
Add quotes around the pytest mark arg.
=> infra: fix release buildspec typo syntax error

buildspec-localmodetests.yml, buildspec-release.yml, buildspec-slowtests.yml, buildspec-unittests.yml, buildspec.yml, tox.ini
Temporary security patch for [CVE-2021-3177](https://python-security.readthedocs.io/vuln/ctypes-buffer-overflow-pycarg_repr.html#cve-2021-3177)
=> infra: remove py38 tox env

buildspec.yml
Temporary security patch for CVE-2021-3177
=> infra: remove python3.8 from buildspec

tests/integ/test_airflow_config.py, tests/integ/test_chainer.py, tests/integ/test_debugger.py, tests/integ/test_mxnet.py
Remove the `canary_quick` pytest mark from some tests that are flaky, redundant, or otherwise not needed.
=> infra: remove canary_quick pytest mark from flaky/unnecessary tests

tests/integ/test_airflow_config.py, tests/integ/test_tuner_multi_algo.py
Remove `canary_quick` pytest mark from more flaky integ tests.
=> infra: unmark more flaky integ tests

tests/integ/test_artifact_analytics.py, tests/integ/test_auto_ml.py, tests/integ/test_byo_estimator.py, tests/integ/test_experiments_analytics.py, tests/integ/test_horovod.py, tests/integ/test_horovod_mx.py, tests/integ/test_inference_pipeline.py, tests/integ/test_linear_learner.py, tests/integ/test_marketplace.py, tests/integ/test_model_monitor.py, tests/integ/test_mxnet.py, tests/integ/test_neo_mxnet.py, tests/integ/test_ntm.py, tests/integ/test_processing.py, tests/integ/test_pytorch.py, tests/integ/test_rl.py, tests/integ/test_sklearn.py, tests/integ/test_sparkml_serving.py, tests/integ/test_tf.py, tests/integ/test_tfs.py, tests/integ/test_transformer.py, tests/integ/test_tuner.py
Rename the `canary_quick` pytest mark to `release` for the regional release builds.
=> infra: rename canary_quick pytest mark to release

doc/frameworks/mxnet/using_mxnet.rst
documentation: update doc for Elastic Inference MXNet 1.7.0
=> documentation: update doc for Elastic Inference MXNet 1.7.0

tests/unit/sagemaker/lineage/test_visualizer.py
*Issue #, if available:* https://sim.amazon.com/issues/AML-110751
*Description of changes:* 1. Add tests for training jobs and transform jobs in visualizer
2. Refactor tests in visualizer to remove redundancy
tox -e py39 ~/github/sagemaker-python-sdk/tests/unit/sagemaker/lineage
tox -e py39 ~/github/sagemaker-python-sdk/tests/integ/sagemaker/lineage
Both tests passed successfully
=> Add tests for Training job & Transform job in visualizer

tests/integ/test_smdataparallel_tf.py
There is a bad version of smdebug released in the new tf 2.3.1 image. That's causing this test to fail and block all the prs.
https://github.com/awslabs/sagemaker-debugger/pull/451
https://github.com/aws/deep-learning-containers/pull/874
=> fix: ignore failing smdataparallel test

src/sagemaker/feature_store/feature_group.py, tests/integ/test_feature_store.py
https://github.com/aws/sagemaker-python-sdk/issues/2110
=> fix: feature group should ignore nan values

src/sagemaker/lineage/_utils.py, src/sagemaker/lineage/action.py, src/sagemaker/lineage/artifact.py, src/sagemaker/lineage/association.py, src/sagemaker/lineage/context.py, src/sagemaker/lineage/visualizer.py
*Issue #, if available:* https://sim.amazon.com/issues/AML-96242
*Description of changes:* Added Type Annotations for .py files under lineage directory
` tox -e py39 -- tests/unit/sagemaker/lineage    `
collected 45 items                                                                                                                                                                                                        
tests/unit/sagemaker/lineage/test_action.py ...........                                                                                                                                                             [ 24%]
tests/unit/sagemaker/lineage/test_artifact.py ............ …
=> change: add type annotations for Lineage

src/sagemaker/workflow/_utils.py, src/sagemaker/workflow/step_collections.py, tests/integ/test_workflow.py, tests/unit/sagemaker/workflow/test_step_collections.py
Addresses: https://github.com/aws/sagemaker-python-sdk/issues/2104
Add description parameter for RegisterModelStep.
This allows setting the ModelPackageDescription, as per: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModelPackage.html#sagemaker-CreateModelPackage-request-ModelPackageDescription
=> fix: add description parameter for RegisterModelStep

src/sagemaker/feature_store/feature_group.py, tests/integ/test_feature_store.py, tests/unit/sagemaker/feature_store/test_feature_store.py
Preparation for: https://github.com/aws/sagemaker-python-sdk/issues/2111
=> fix: return all failed row indices in feature_group.ingest

src/sagemaker/predictor.py, tests/integ/test_mxnet.py, tests/unit/test_predictor.py
Do lazy initialization of model names and endpoint configuration name in predictor
When a predictor object is created, the initialization issues DescribeEndpoint and DescribeEndpointConfiguration API calls to get the model names and endpoint configuration name. These fields are only necessary for updating the predictor. They are unnecessary if we only want to make predict calls on the predictor object. The changes move the initialization to the relevant update functions to call the describe APIs if the fields have not been populated yet. This helps make the predictor object become more scalable by reducing the required API calls when only making predict requests.
The changes are covered by existing unit tests in …
=> change: Do lazy initialization in predictor

src/sagemaker/feature_store/feature_group.py, tests/integ/test_feature_store.py, tests/unit/sagemaker/feature_store/test_feature_store.py
=> change: use ResolvedOutputS3Uir for Hive DDL LOCATION

src/sagemaker/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/huggingface/__init__.py, src/sagemaker/huggingface/estimator.py, src/sagemaker/image_uri_config/huggingface.json, src/sagemaker/image_uris.py, tests/conftest.py, tests/data/huggingface/run_glue.py, tests/data/huggingface/train/dummy.csv, tests/integ/test_huggingface.py, tests/unit/sagemaker/huggingface/__init__.py, tests/unit/sagemaker/huggingface/test_estimator.py, tests/unit/sagemaker/image_uris/test_dlc_frameworks.py, tests/unit/sagemaker/image_uris/test_retrieve.py
=> feature: add HuggingFace framework estimator

tests/integ/test_huggingface.py, tests/integ/test_tfs.py
=> fix: skip HuggingFace tests in regions without p2 instances

tests/integ/test_horovod.py, tests/integ/test_huggingface.py, tests/integ/test_tf.py
=> fix: disable profiler in some release tests

tests/integ/test_horovod_mx.py
Continuation of https://github.com/aws/sagemaker-python-sdk/pull/2261
Disable profiler on a release test to avoid ISEs.
=> infra: disable_profiler on mx-horovod test

src/sagemaker/huggingface/estimator.py, tests/conftest.py, tests/integ/test_huggingface.py, tests/unit/sagemaker/huggingface/test_estimator.py
=> fix: add version length mismatch validation for HuggingFace

doc/frameworks/huggingface/index.rst
A link/documentation on how to "Use Hugging Face with SageMaker Python SDK". We (@icywang86rui & I) decided not to create a separate documentation page in the SDK rather than referring to the documentation page in `transformers` at https://huggingface.co/transformers/sagemaker.html. This Documentation page will be always updated and maintained by the HF team. 
Screenshot of Sagemaker python SDK documentation page
=> doc: add Documentation for how to use

doc/amazon_sagemaker_featurestore.rst
The parameter used in feature store runtime in the doc was incorrect
https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_featurestore.html
in featurestore_runtime = boto_session.client(service_name=‘PARAM’,
region_name=region
)
replaced 'featurestore-runtime' with 'sagemaker-featurestore-runtime'
=> Updated boto3 client param for feature store

doc/api/training/sdp_versions/latest.rst, doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.md
- Adding release notes for smdistributed.dataparallel v1.1.2
`tox -e black-check,flake8,docstyle,sphinx,doc8 --parallel all`
=> documentation: release notes for smdistributed.dataparallel v1.1.2

src/sagemaker/estimator.py, tests/unit/sagemaker/workflow/test_steps.py
… a pipeline
Related to:
** #2114
** #2115
Hyperparameters in a Tensorflow estimator cannot be parameterized for a pipeline. Update the `_json_encode_hyperparameters` in the `Framework` class to handle pipeline parameters correctly.
Unit tests, manual tests.
=> fix: Allow hyperparameters in Tensorflow estimator to be parameterized

tests/unit/sagemaker/model/test_framework_model.py, tests/unit/sagemaker/tensorflow/test_estimator.py, tests/unit/sagemaker/tensorflow/test_estimator_init.py, tests/unit/test_amazon_estimator.py, tests/unit/test_chainer.py, tests/unit/test_estimator.py, tests/unit/test_fm.py, tests/unit/test_image.py, tests/unit/test_ipinsights.py, tests/unit/test_job.py, tests/unit/test_kmeans.py, tests/unit/test_knn.py, tests/unit/test_lda.py, tests/unit/test_linear_learner.py, tests/unit/test_ntm.py, tests/unit/test_object2vec.py, tests/unit/test_pca.py, tests/unit/test_pipeline_model.py, tests/unit/test_randomcutforest.py, tests/unit/test_sklearn.py, tests/unit/test_tuner.py, tests/unit/test_xgboost.py
`black` was updated. Applied changes to the SDK repo.
=> infra: black format unit tests

tests/integ/test_smdataparallel_pt.py, tests/integ/test_smdataparallel_tf.py
ticekt no: V357338340
All of our PRs are failing due to the smdataparallel integ tests. These tests runs on a large ML instances. Our account doesn't have the limit to run both of the  test_smdataparallel_pt and test_smdataparallel_tf at the moment. So, skipping the tests now until we get more resource increase or any other solution. 
`tox -e black-format` …
=> infra: disable smdataparallel tests

src/sagemaker/pytorch/estimator.py
* The link that was previously used here does not contain information about supported framework version of PyTorch. 
* Adding a link to the DLC images, which contains all supported PT version. https://github.com/aws/deep-learning-containers/blob/master/available_images.md
=> Documentation: replacing unhelpful link

doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.md
=> doc: SMDDP 1.2.0 release notes

src/sagemaker/workflow/parameters.py, tests/unit/sagemaker/workflow/test_parameters.py
*Issue #, if available:* #2144
Correctly Check if the pipeline parameter is null, the previous check ignored value for `ParameterInteger` if default value is 0
Added unit test for the parameter
=> fix: default value removed if zero for integer param

src/sagemaker/session.py, tests/unit/test_session.py
=> fix: call DescribeDomain as fallback in get_execution_role

src/sagemaker/workflow/steps.py
N/A
Type information on this argument should match `inputs` from estimator's `fit()` method.
N/A
=> documentation: Correct type annotation for TrainingStep inputs

src/sagemaker/model.py, src/sagemaker/session.py, src/sagemaker/workflow/_utils.py, src/sagemaker/workflow/step_collections.py, tests/unit/sagemaker/workflow/test_step_collections.py
N/A
Add tags argument to RegisterModel step to allow for tagging model package groups.
Manual, unit.
=> change: Register model step tags

doc/amazon_sagemaker_featurestore.rst
New `batch_get_record` api call.
-  [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)
=> documentation: update to include new batch_get_record api call

src/sagemaker/feature_store/feature_group.py
N/A
Adding a default retry strategy configuration to the feature group ingestion's boto3 client.
Manual E2E testing:
- Verified that overrides are honored (max_attempts and total_max_attempts) when configured in the SageMaker Session.
- Verified that the new defaults take effect when there are no overrides to retry attempts. 
- Verified that other configurations (e.g. region_name) are not retained even after defaults are set. …
=> change: add default retries to feature group ingestion.

src/sagemaker/huggingface/__init__.py, src/sagemaker/huggingface/estimator.py, src/sagemaker/huggingface/model.py, src/sagemaker/image_uri_config/huggingface.json, src/sagemaker/image_uris.py, src/sagemaker/model.py, tests/conftest.py, tests/integ/test_huggingface.py, tests/unit/sagemaker/huggingface/test_estimator.py
created model.py for HF. updated image uris and integ test.
Unit tests and integ tests
=> feature: HuggingFace Inference

doc/frameworks/huggingface/sagemaker.huggingface.rst, src/sagemaker/huggingface/model.py
Added Hugging Face docs for display on ReadTheDocs site
built locally
- [X ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
=> doc: Add Hugging Face docs

tox.ini
=> infra: enable py38 tox env

doc/api/utility/lambda_helper.rst, doc/workflows/pipelines/sagemaker.workflow.pipelines.rst, src/sagemaker/lambda_helper.py, src/sagemaker/session.py, src/sagemaker/workflow/lambda_step.py, src/sagemaker/workflow/pipeline.py, src/sagemaker/workflow/steps.py, tests/integ/test_workflow.py, tests/unit/sagemaker/workflow/test_lambda_step.py, tests/unit/test_lambda_helper.py
AML-116688
Added a new Lambda_helper class and boto3 wrappers to create, update, delete and invoke lambdas.
Added support for LambdaStep
Added relevant unit tests and integ tests
=> feature: add LambdaStep support for SageMaker Pipelines

src/sagemaker/session.py
=> fix: enable isolation while creating model from job

src/sagemaker/sklearn/processing.py, tests/integ/test_local_mode.py, tests/integ/test_processing.py, tests/integ/test_sklearn.py, tests/unit/test_processing.py
=> fix: revert #2251 changes for sklearn processor

tests/integ/test_processing.py
=> fix: sklearn integ test for custom bucket

doc/api/utility/inputs.rst, src/sagemaker/dataset_definition/inputs.py, src/sagemaker/inputs.py
PR #2456 fixed `dataset_definition.inputs` path to corretly link the classes in the documentation:
- `sagemaker.dataset_definition.inputs.S3Input`
- `sagemaker.dataset_definition.inputs.DatasetDefinition`
- `sagemaker.dataset_definition.inputs.AthenaDatasetDefinition`
- `sagemaker.dataset_definition.inputs.RedshiftDatasetDefinition`
However, the aforementioned classes are still missing on the documentation.
Added `sagemaker.dataset_definition.inputs` to sphinx's automodule.
I also took the opportunity to fix the link for `sagemaker.inputs` as well.
I built sphinx doc locally, using instructions from the [README](https://github.com/tuliocasagrande/sagemaker-python-sdk/tree/master#building-sphinx-docs), and verified that the …
=> documentation: add dataset_definition to processing page

tests/unit/sagemaker/image_uris/test_algos.py, tests/unit/sagemaker/image_uris/test_data_wrangler.py, tests/unit/sagemaker/image_uris/test_debugger.py, tests/unit/sagemaker/image_uris/test_neo.py, tests/unit/sagemaker/image_uris/test_sklearn.py, tests/unit/sagemaker/image_uris/test_sparkml.py, tests/unit/sagemaker/image_uris/test_xgboost.py
https://tiny.amazon.com/1eo2abrqk
Need to add KIX regional account ids for unit tests that are missing the same, and use local config for unit tests
Ran all unit tests
================== test session starts ===================================
platform darwin -- Python 3.8.3, pytest-6.0.2, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
rootdir: /Users/pandishr/MLFrameworks/sagemaker-python-sdk, configfile: tox.ini
plugins: cov-2.12.1, xdist-2.3.0, rerunfailures-10.1, timeout-1.4.2, forked-1.3.0
==========5003 passed, 447 skipped, 1 xfailed, 1 xpassed, 3046 warnings in ==================
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, …
=> fix: unit tests for KIX and remove regional calls to boto

src/sagemaker/feature_store/feature_group.py
Documentation offline_store_kms_key_id is not inclusive and lead charging customers more on encryption.
Add more descriptive documentation message of offline_store_kms_key_id in create feature group to elaborate how to bring down the cost of using bucket key.
tox
=> documentation: Info about offline s3 bucket key when creating feature group

.github/PULL_REQUEST_TEMPLATE.md
Update PR template to add checks for backward incompatibility
=> updated pr template to check backward compatibility

src/sagemaker/session.py, tests/unit/test_session.py
Add additional safety check for Execution Role when fetching from UserSettings since it is not a required parameter. Additionally, add more unit tests for all the scenarios.
Ran unit tests
=> fix: add checks for ExecutionRole in UserSettings, adds more unit tests

src/sagemaker/clarify.py, tests/unit/test_clarify.py
Add joinsource to DataConfig. 
Joinsource parameter in DataConfig will represent the name of a column in the dataset that acts as an identifier (for instance, while performing a join), and not used for any other computations. 
All tests have passed. I have updated unit tests to include joinsource as well. 
=> feature: add joinsource to DataConfig

.coveragerc
Tests are failing currebly due to a change in dependency Coverage Py:
https://github.com/nedbat/coveragepy/commit/c9d821deba6f7ee5eef30fef5355f7c93808b4f9
affected pr: https://github.com/aws/sagemaker-python-sdk/pull/2756
Tested in dummy PR: https://github.com/aws/sagemaker-python-sdk/pull/2778
=> fix: Fix coverage concurrency

tests/integ/sagemaker/lineage/conftest.py
Lineage tests are failing here:
```
def test_endpoint_contexts(
static_model_artifact,
sagemaker_session,
):
contexts_from_query = static_model_artifact.endpoint_contexts()
associations_from_api = traverse_graph_forward(
static_model_artifact.artifact_arn, sagemaker_session=sagemaker_session
)
>       assert len(contexts_from_query) > 0
E       assert 0 > 0
E        +  where 0 = len([])
tests/integ/sagemaker/lineage/test_model_artifact.py:43: AssertionError
```
Recreate the test data to see if this is transient.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going …
=> fix: Recreate static lineage test data

src/sagemaker/feature_store/feature_group.py, tests/unit/sagemaker/feature_store/test_feature_store.py
Add `profile_name` for Feature Store ingestion so user can specify which credential to use for `PutRecord`.
Added one unit test and passed in Python 3.6/3.7/3.8.
I wrote a piece of sample ingestion with and without `profile_name` specified and both show the expected behavior.
=> feature: Add profile_name support for Feature Store ingestion

src/sagemaker/session.py
When an existing endpoint config exists with an identical name, throw an error instead of reusing it. The reason is that when the model.deploy() method is called, the model on which the deploy() method is called may not be the same model which is configured in the existing endpoint config. It is safer to throw an error, the same way that an error is thrown when an endpoint with the same name exists.
See the ticket for more information:
https://t.corp.amazon.com/P46903451
*Testing done:* unit tests all pass
- …
=> fix endpoint bug

src/sagemaker/local/image.py, src/sagemaker/local/utils.py, tests/unit/test_local_utils.py
https://t.corp.amazon.com/P54529910
Local mode: support relative file structure
Current support exists for absolute path Ex: file:///target/dir (host directory: /target/dir)
This change will add support for relative path for Ex: file://relative_dir/target/dir (host directory: ./relative_dir/target/dir)
Tested locally: https://paste.amazon.com/show/mufi/1637692063
Also added and tested unit tests. …
=> fix: local mode - support relative file structure

tests/integ/sagemaker/lineage/conftest.py, tests/integ/test_auto_ml.py
The static endpoint needed for lineage query tests was deleted. Handle this during test setup and redeploy it if necessary.
=> fix: Re-deploy static integ test endpoint if it is not found

src/sagemaker/session.py, tests/integ/sagemaker/lineage/conftest.py, tests/integ/test_kmeans.py
Current failure scenario sequence:
1. Deploy KMeans Model, deploy, predict.
2. Delete Endpoint.
3. Predictor delete_model.
- Checks for endpoint config name by checking endpoint description.
- Endpoint does not exist as already deleted.
```
>       predictor.delete_model()
tests/integ/test_kmeans.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py38/lib/python3.8/site-packages/sagemaker/predictor.py:339: in delete_model
current_model_names = self._get_model_names()
.tox/py38/lib/python3.8/site-packages/sagemaker/predictor.py:529: in _get_model_names
current_endpoint_config_name = self._get_endpoint_config_name()
.tox/py38/lib/python3.8/site-packages/sagemaker/predictor.py:519: in …
```
=> fix: fix kmeans test deletion sequence, increment lineage statics

tests/integ/sagemaker/lineage/conftest.py
- Found out the code deleting the static lineage endpoint (functions/clean_all_endpoints_prod_us-west-2) and added a workaround to filter the lineage endpoint.
- Just Incrementing the static lineage pipeline in this PR.
=> fix: Increment static lineage pipeline

tests/integ/sagemaker/lineage/test_dataset_artifact.py, tests/integ/sagemaker/lineage/test_endpoint_context.py, tests/integ/sagemaker/lineage/test_model_artifact.py
N/A
Simplify the assertions in lineage query tests. Asserting that lineage data is exactly the same as graph data is problematic; recursively walking the lineage data forward or backwards is different than the graph traversal logic being done on the backend.
Manual, ran integ tests locally
=> fix: Fix lineage query integ tests

.gitignore, src/sagemaker/estimator.py, src/sagemaker/fw_utils.py, src/sagemaker/model.py, src/sagemaker/session.py, src/sagemaker/session_settings.py, src/sagemaker/utils.py, tests/unit/test_estimator.py, tests/unit/test_fw_utils.py, tests/unit/test_utils.py, tox.ini
AppSec finding affecting SageMaker JumpStart TT: V497918765
This PR changes the default behavior of the SDK when uploading artifacts to the S3 bucket of the `Session`. Previously, if no `kms_key` argument was specified, the SDK uploaded artifact to `S3` without server-side encryption. Now, the artifact on `S3` is uploaded with server-side encryption enabled, and `S3` uses the AWS managed KMS key for S3 in the customer account.
According to KMS team and AppSec, there is no downside to enabling server-side encryption in `S3` for customers: any `S3:getObject` call to such objects will be automatically decrypted by `S3` if the requester has access to the object.  If a customer wishes to disable the server-side encryption for their artifacts …
=> feat: default repack encryption

doc/workflows/pipelines/sagemaker.workflow.pipelines.rst, src/sagemaker/workflow/parallelism_config.py, src/sagemaker/workflow/pipeline.py, tests/integ/test_workflow.py, tests/unit/sagemaker/workflow/test_pipeline.py
=> feature: support large pipeline

src/sagemaker/lineage/query.py, tests/unit/sagemaker/lineage/test_query.py
Support new type "Action" to lineage response object
unit test
=> change: Add action type to lineage object

src/sagemaker/lineage/query.py, tests/unit/sagemaker/lineage/test_query.py
AML-146902
Due to the cross-account feature, there might be duplicate vertices and edges in query lineage response. This pr is to collapse cross-account artifacts.
Unit test
=> fix: Collapse cross-account artifacts in query lineage response
