src/sagemaker/workflow/lambda_step.py
tests/unit/sagemaker/workflow/test_lambda_step.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/2676
remove unnecessary session call while generating pipeline definition for lambda step
unit test and integ test

fix: fixes unnecessary session call while generating pipeline definition for lambda step

---

src/sagemaker/lineage/context.py
tests/integ/sagemaker/lineage/conftest.py
tests/integ/sagemaker/lineage/test_endpoint_context.py
tests/unit/sagemaker/lineage/test_endpoint_context.py

Add models_v2 under lineage context. models_v2 return list of models by using lineage query
- unit test:
`tox -e py36 -- tests/unit/sagemaker/lineage/test_endpoint_context.py -vv`
tests/unit/sagemaker/lineage/test_endpoint_context.py::test_models PASSED                                                                                                                                                              [ 50%]
tests/unit/sagemaker/lineage/test_endpoint_context.py::test_models_v2 PASSED                                                                                                                                                           [100%]
============================================================================= …

feature: Add models_v2 under lineage context

---

setup.py
tox.ini

https://issues.amazon.com/issues/V487986263
Enable python 3.9
Ran unit tests for Python3.9 locally.
```
mufi@3c22fbe5d54b sagemaker-python-sdk % ./.githooks/pre-push
GLOB sdist-make: /Users/mufi/workspace/sagemaker-python-sdk/setup.py
✔ OK black-check in 6.874 seconds
✔ OK twine in 14.327 seconds
✔ OK pylint in 22.443 seconds
✔ OK docstyle in 24.571 seconds
✔ OK flake8 in 40.13 seconds
__________________________________________________________________________________ summary __________________________________________________________________________________
docstyle: commands succeeded
black-check: commands succeeded
twine: commands succeeded …
```

feature: enable python 3.9

---

CHANGELOG.md

change: Update CHANGELOG.md

---

src/sagemaker/workflow/execution_variables.py

The documentation for [`workflow.execution_variables.ExecutionVariables`](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.execution_variables.ExecutionVariables) does not show the available variables:
This PR adds the existing execution variables to the docstring, so they get rendered in the Sphinx documentation:
Build Sphinx docs locally. …

doc: Document the available ExecutionVariables

---

src/sagemaker/lineage/query.py
tests/unit/sagemaker/lineage/test_query.py

AML-149503
Currently there might be some duplicate nodes in query lineage paginated responses. This pr is to remove duplicate vertex/edge.
Unit test

fix: Remove duplicate vertex/edge in query lineage

---

src/sagemaker/workflow/steps.py
tests/unit/sagemaker/workflow/test_steps.py

N/A
Add support for `PipelineModel` to the `CreateModelStep`
Unit, manual

feature: Support model pipelines in CreateModelStep

---

src/sagemaker/parameter.py
src/sagemaker/tuner.py
tests/integ/test_workflow.py
tests/unit/test_tuner.py

Range and Static Hyperparameters
support JsonGet/Join parameterization in tuning step Hyperparameter Range and Static Hyperparameters

feature: support JsonGet/Join parameterization in tuning step Hyperparameters

---

doc/Makefile
doc/api/training/sdp_versions/latest/smd_data_parallel_pytorch.rst
doc/api/training/sdp_versions/latest/smd_data_parallel_tensorflow.rst
doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.rst

- Add SageMaker distributed data parallal v1.2.2 release note.
- Add `no_sync()` to the `DistributedDataParallel` class.
- Minor typo and style fixes.

doc: Enhance smddp 1.2.2 doc

---

src/sagemaker/workflow/airflow.py
tests/unit/test_airflow.py

Add Support for checkpoint to be passed from estimator.
Updated unit test to test change. 
python3 -m tox -e py38 test/unit/

feature: support checkpoint to be passed from estimator

---

src/sagemaker/workflow/steps.py
tests/unit/sagemaker/workflow/test_steps.py

This change will allow ARN of the KMS key to be passed as kms_key that is used to encrypt the user code file kms_key to be passed for processing step
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ x ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x ] I used the commit message format …

fix: allow kms_key to be passed for processing step

---

setup.py
src/sagemaker/estimator.py
src/sagemaker/model.py
src/sagemaker/serverless/__init__.py
src/sagemaker/serverless/serverless_inference_config.py
src/sagemaker/session.py
src/sagemaker/tensorflow/model.py
tests/integ/test_serverless_inference.py
tests/unit/sagemaker/model/test_deploy.py
tests/unit/sagemaker/serverless/test_serverless_inference_config.py
tests/unit/test_estimator.py
tests/unit/test_session.py

Add support for Liberty feature aka [serverless inference](https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html):
1. Add `sagemaker.serverless.serverless_inference_config` as the configuration class for serverless inference
2. Add support in `sagemaker.estimator`, `sagemaker.model`, `sagemaker.tensorflow.model` to let users deploy serverless endpoint by passing the configuration object.
3.Add support in `sagemaker.session` to generate production variants with serverless config and also create endpoints using serverless configurations.
Detailed Design is in [this doc](https://quip-amazon.com/Q0DUAxkl7MWa/Design-Async-Serverless-Inference-Python-SDK-Support)
1. Test the walk through behavior for …

feature: Adds support for Serverless inference

---

src/sagemaker/lineage/action.py
src/sagemaker/lineage/query.py
tests/integ/sagemaker/lineage/conftest.py
tests/integ/sagemaker/lineage/test_action.py
tests/unit/sagemaker/lineage/test_action.py

feature: Add support for SageMaker lineage queries in action.
- Get downstream Artifacts in aciton
- Get upstream Artifacts in action
- Get dataset in ModelPackageApprovalAction
- Get ModelPackage in ModelPackageApprovalAction
- Get Endpoint in ModelPackageApprovalAction
- unit test
- integration test

feature: Add support for SageMaker lineage queries in action

---

src/sagemaker/workflow/emr_step.py
src/sagemaker/workflow/properties.py
src/sagemaker/workflow/steps.py
tests/data/workflow/emr-script.sh
tests/integ/test_workflow.py
tests/unit/sagemaker/workflow/test_emr_step.py
tests/unit/sagemaker/workflow/test_properties.py

Issue #, if available:
Add EMRStep support in Sagemaker pipeline
Description of changes:
Created a new EMRStep class in Sagemaker workflow to support creating EMR step in Sagemaker pipeline
Testing done:
Tested with unit and integ tests
Merge Checklist
Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request.
General
I have read the CONTRIBUTING doc
I used the commit message format described in CONTRIBUTING
I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
I have updated any necessary documentation, including READMEs and API docs (if …

feature: Add EMRStep support in Sagemaker pipeline

---

src/sagemaker/lineage/context.py
tests/integ/sagemaker/lineage/conftest.py
tests/integ/sagemaker/lineage/test_model_package_group_context.py
tests/unit/sagemaker/lineage/test_model_package_group_context.py

Add support for SageMaker lineage queries context
- Return Pipeline Execution in ModelPackageGroup
Integration test
tox -e py36 -- tests/integ/sagemaker/lineage/test_model_package_group_context.py -vv
`tests/integ/sagemaker/lineage/test_model_package_group_context.py::test_pipeline_execution_arn PASSED                                                                                                        [100%]`
tox -e py36 -- tests/integ/sagemaker/lineage/test_endpoint_context.py -vv
`
collected 6 items
tests/integ/sagemaker/lineage/test_endpoint_context.py::test_pipeline_execution_arn PASSED                                                                                                                   [100%]
`
_Put an …

feature: Add support for SageMaker lineage queries context

---

src/sagemaker/algorithm.py
src/sagemaker/chainer/estimator.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/estimator.py
src/sagemaker/model.py
src/sagemaker/pytorch/estimator.py
src/sagemaker/rl/estimator.py
src/sagemaker/tensorflow/estimator.py
tests/unit/test_estimator.py

This PR adds script mode support to the `Estimator` and `EstimatorBase` classes. 
This was basically done by adding the parameters `source_dir, git_config, hyperparameters, container_log_level, code_location, entry_point, dependencies` to the `Estimator` and `EstimatorBase` classes. 
The changes to the `Estimator` class do not break any existing unit tests. In addition, new unit tests were added to simulate the script mode use case for the `Estimator` class, and confirm that the calls to `sagemaker.create_training_job()` and `s3` are the same for the `Estimator` class and `Framework` class when both use script mode. A test was also added to ensure that git support works with the `Estimator` class. Integration tests will be …

feat: Script mode support for Estimator class

---

src/sagemaker/environment_variables.py
src/sagemaker/image_uris.py
src/sagemaker/jumpstart/accessors.py
src/sagemaker/jumpstart/artifacts.py
src/sagemaker/jumpstart/cache.py
src/sagemaker/jumpstart/constants.py
src/sagemaker/jumpstart/exceptions.py
src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/model_uris.py
src/sagemaker/script_uris.py
tests/unit/sagemaker/image_uris/jumpstart/test_common.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/sagemaker/model_uris/jumpstart/test_common.py
tests/unit/sagemaker/script_uris/jumpstart/test_common.py

This PR adds adds support for the deprecated and vulnerability fields of the JumpStart model specs. If specs for a vulnerable or deprecated model are requested, a new exception type will be surfaced. There is a user option to override these safety checks, so they may use a vulnerable/deprecated model if they wish.  

feature: jumpstart vulnerability and deprecated check

---

src/sagemaker/clarify.py
tests/unit/test_clarify.py

In Clarify DataConfig, there is a parameter called `s3_data_distribution_type` which can currently take two values: `FullyReplicated` or `ShardedByS3Key`. However, going forward, the only valid option for this variable will be `FullyReplicated`. This CR also adds a deprecation warning to the class `DataConfig` so that customers get time to make changes to their code, as we will eventually remove this parameter (which will be a backward incompatible change). 
By submitting this pull request, …

Add deprecation warning for s3_data_distribution_type in Clarify Data Config

---

tests/conftest.py
tests/integ/test_horovod.py

Due to unavailability of ml.p2.xlarge instances we have updated to ml.p3.2xlarge instance type.

update instance types for integ test

---

doc/conf.py
src/sagemaker/analytics.py
src/sagemaker/utils.py
tests/data/multimodel/container/Dockerfile
tests/integ/sagemaker/lineage/helpers.py
tests/integ/test_workflow.py
tests/integ/test_workflow_retry.py
tests/unit/sagemaker/feature_store/test_feature_store.py
tox.ini

Update the source to remove the `u` from strings in order to incorporate latest `black` changes.
Details of the changes can be found in [this PR](https://github.com/psf/black/pull/2297/files)

fix: update to incorporate black v22, pin tox versions

---

setup.py

Release builds are failing on xdist dependency. Pinning xdist to unblock releases.
```
py36 run-test: commands[1] | pytest --cov=sagemaker --cov-append tests/integ -m release -n 8 --boxed --reruns 4 --boto-config '{"region_name": "us-east-2"}'
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/codebuild/output/src863200597/src/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 236, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/codebuild/output/src863200597/src/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 911, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File …
```

fix: pin pytest-xdist to avoid release failures

---

src/sagemaker/jumpstart/validators.py

fix: jumpstart typo

---

tests/conftest.py
tests/integ/__init__.py
tests/integ/test_horovod.py
tests/integ/test_horovod_mx.py
tests/integ/test_huggingface.py

With the recent change  in https://github.com/aws/sagemaker-python-sdk/pull/2881 to use p3.2 gpu instance types for integ tests in us-west-2. Adding appropriate checking for other regions per availability of p3.2 was missed. This pr should fix it. 

fix: gpu use p3/p2 per avail for region

---

tests/conftest.py
tests/integ/__init__.py

Add CMH to the non-P3 list
Low p3 availability in CMH has caused failures in pipeline release.

fix: Add CMH to the non-P3 list

---

tests/integ/sagemaker/lineage/conftest.py
tests/integ/test_workflow.py

Update static endpoint from SdkIntegTestStaticPipeline17 to SdkIntegTestStaticPipeline19

fix: Update Static Endpoint

---

tests/integ/sagemaker/lineage/test_action.py

Add exception in test_action

---

doc/workflows/pipelines/sagemaker.workflow.pipelines.rst
src/sagemaker/workflow/fail_step.py
src/sagemaker/workflow/steps.py
tests/integ/test_workflow_with_fail_steps.py
tests/unit/sagemaker/workflow/test_fail_step.py

*Description of changes:* Add FailStep support for SageMaker model building pipeline.
*Testing done:* unit tests and integ tests

feature: Add FailStep Support for Sagemaker Pipeline

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_neo.py
tests/unit/test_mxnet.py

* use recommended inference image URI from Neo [`DescribeCompilationJob`](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeCompilationJob.html) API response 
* related unit tests
* Creating a new one since the last [PR](https://github.com/aws/sagemaker-python-sdk/pull/2806) gets messier overtime. 
unit tests passed

change: use recommended inference image uri from Neo API

---

doc/workflows/index.rst
doc/workflows/lineage/index.rst
doc/workflows/lineage/sagemaker.lineage.rst

Add lineage docs in https://sagemaker.readthedocs.io/en/stable/index.html
NA

fix: Add lineage doc

---

src/sagemaker/lineage/lineage_trial_component.py
tests/integ/sagemaker/lineage/conftest.py
tests/unit/sagemaker/lineage/test_lineage_trial_component.py

- Update lineage_trial_compoment pipeline execution arn method, get the pipeline execution arn by passing source arn instead of trial component arn.
- Update partial integ test to rely on trial component instead of endpoint_context
tox -e py36 -- tests/integ/sagemaker/lineage
```tests/integ/sagemaker/lineage/test_action.py ...........                                                  [ 19%]
tests/integ/sagemaker/lineage/test_artifact.py ............                                               [ 40%]
tests/integ/sagemaker/lineage/test_association.py ....                                                    [ 47%]
tests/integ/sagemaker/lineage/test_context.py ........                                                    [ 61%] …
```

fix: update lineage_trial_compoment get pipeline execution arn

---

doc/doc_utils/jumpstart_doc_utils.py

This PR changes the data source used to populate the JumpStart available models table in docs so there are no redundant entries.
The doc build script was ran and verified

fix: jumpstart model table

---

tests/scripts/run-notebook-test.sh

change: update code to get commit_id in codepipeline

---

doc/api/training/sdp_versions/latest/smd_data_parallel_tensorflow.rst

Add notes to the smdistributed.dataparallel APIs for TensorFlow

documentation: smddp doc update

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_framework_model.py
tests/unit/sagemaker/model/test_model.py

Fixes a bug wherein file:// prefix was wrongly appended even for S3 URI Paths
Ran unit tests, integs to follow here

fix: container env generation for S3 URI and add test for the same

---

src/sagemaker/huggingface/estimator.py
src/sagemaker/training_compiler/config.py

- Improve the Training Compiler config docstring
- In addition to that, rephrase the HuggingFace estimator docstring

documentation: update sagemaker training compiler docstring

---

doc/overview.rst

Fix/jumpstart docs network isolation. JumpStart xgboost and sklearn models require network isolation to be turned on for inference. All other models can also work in network isolation mode. In order to ensure customers are able to launch all models, we'd like to have the official documentation use network isolation mode. This is a temporary solution while JumpStart team debugs the issue at the root cause. …

fix: jumpstart docs network isolation

---

src/sagemaker/image_uri_config/autogluon.json
tests/unit/sagemaker/image_uris/test_autogluon.py

Added image_uri metadata for AutoGluon 0.3.2 and 0.4.0
tox

feature: AutoGluon 0.3.2 and 0.4.0 image_uris

---

.readthedocs.yaml
tests/conftest.py
tests/integ/test_huggingface.py
tests/integ/test_tf.py

1. With Capacity crunch in PDX in daytime for p3.2x instances, falling back on p2 instances and retry.
Note: that I would fix the code redundancy here later after finding a better way but currently the PR checks are blocked.
3. Update readthedocs build version to v2
1. Tested integ runs locally. 
2. `tox -e sphinx` on py39 env
```The HTML pages are in _build/html.
_______________________________________________________________ summary _______________________________________________________________
sphinx: commands succeeded
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

fix: gpu integs CapacityError - fallback to available compute

---

src/sagemaker/estimator.py

fix: Align max_wait definitions in EstimaorBase and Estimator

---

src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/model_monitor/model_monitoring.py
tests/integ/test_model_monitor.py
tests/unit/sagemaker/monitor/test_clarify_model_monitor.py
tests/unit/sagemaker/monitor/test_model_monitoring.py

Enable `InterContainerTrafficEncryption`  for create monitoring schedule.
unit and integ

feat: enable EnableInterContainerTrafficEncryption for model monitoring

---

src/sagemaker/estimator.py
src/sagemaker/parameter.py
src/sagemaker/tuner.py
src/sagemaker/workflow/entities.py
src/sagemaker/workflow/execution_variables.py
src/sagemaker/workflow/functions.py
src/sagemaker/workflow/parameters.py
src/sagemaker/workflow/properties.py
tests/integ/sagemaker/workflow/test_pipeline_var_behaviors.py
tests/integ/sagemaker/workflow/test_tuning_steps.py
tests/unit/sagemaker/workflow/test_entities.py
tests/unit/sagemaker/workflow/test_execution_variables.py
tests/unit/sagemaker/workflow/test_functions.py
tests/unit/sagemaker/workflow/test_parameters.py
tests/unit/sagemaker/workflow/test_properties.py
tests/unit/sagemaker/workflow/test_steps.py
tests/unit/test_tuner.py

*Description of changes:* This PR implement the overridden solution to make the SM Pipeline variables to have similar behaviors as Python primitives to resolve some possible customer issues.
*Testing done:* unit tests and integ tests (will be uncommented once the backend changes deploy)

change: Implement override solution for pipeline variables

---

doc/overview.rst

Fixes wrong documentation code snippet. cc @ahsan-z-khan 

fix: remove `new` from serverless

---

src/sagemaker/utils.py
tests/unit/test_utils.py

Add APIs to allow retrieval of data configuration for Example Notebooks.
Added unit tests
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license

feature: Retrieve data configuration

---

src/sagemaker/exceptions.py
src/sagemaker/session.py
tests/integ/test_huggingface.py
tests/integ/test_tf.py
tests/integ/utils.py
tests/unit/test_exception_on_bad_status.py

1. Raise CapacityError in case the failure reason for job failure is Capacity issue from EC2.
2. Provide a pluggable instance fallback mechanism which can be used with integ test.
Added unit test.
Made sure tests pass locally for backwards compatibility.

feature: pluggable instance fallback mechanism, add CapacityError

---

tests/integ/sagemaker/lineage/conftest.py

more insight into build failures https://us-west-2.console.aws.amazon.com/codesuite/codebuild/142577830533/projects/sagemaker-python-sdk-pr/build/sagemaker-python-sdk-pr%3A2afc29c4-ef6f-4422-b180-8123bd066b9e/?region=us-west-2#

more logging info for static pipeline test data setup

---

src/sagemaker/workflow/_utils.py
tests/unit/sagemaker/workflow/test_utils.py

…gz error
[3038](https://github.com/aws/sagemaker-python-sdk/issues/3038)
Repack model injection is not working for S3 source directories. Refactor this to follow logic similar to Model's repack method.
Manual, unit

fix: Refactor repack_model script injection, fixes tar.gz error

---

doc/overview.rst
src/sagemaker/chainer/model.py
src/sagemaker/huggingface/model.py
src/sagemaker/image_uris.py
src/sagemaker/model.py
src/sagemaker/mxnet/model.py
src/sagemaker/pytorch/model.py
src/sagemaker/sklearn/model.py
src/sagemaker/tensorflow/model.py
src/sagemaker/xgboost/model.py
tests/integ/test_factorization_machines.py
tests/integ/test_ipinsights.py
tests/integ/test_kmeans.py
tests/integ/test_knn.py
tests/integ/test_lda.py
tests/integ/test_linear_learner.py
tests/integ/test_mxnet.py
tests/integ/test_ntm.py
tests/integ/test_object2vec.py
tests/integ/test_pca.py
tests/integ/test_pytorch.py
tests/integ/test_randomcutforest.py
tests/integ/test_sklearn.py
tests/integ/test_tf.py
tests/integ/test_xgboost.py
tests/unit/sagemaker/model/test_deploy.py
tests/unit/sagemaker/model/test_model.py
tests/unit/sagemaker/tensorflow/test_tfs.py
tests/unit/test_estimator.py

```Image_uri.retrieve``` requires instance type now but that's not needed in serverless inference. To support this function, we default serverless inference to CPU instance type to get Amazon SageMaker first-party algorithm containers.
Add more integration tests

feature: add serverless inference image_uri support

---

src/sagemaker/workflow/utilities.py
tests/unit/sagemaker/workflow/test_utilities.py

N/A
ProcessingStep hashes the contents of local files passed to `code` to fix cache miss issues. Update the hash function to support file URIs.
Unit, manual

fix: Support file URIs in ProcessingStep's code parameter

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_model.py

V542026104
This PR fixes the inference host environment variable for `SAGEMAKER_SUBMIT_DIRECTORY`, so that it gets the proper value when the script/model artifacts get repackaged. 

fix: xgboost, sklearn network isolation for jumpstart

---

doc/frameworks/tensorflow/deploying_tensorflow_serving.rst

n/a
Change prefix "pos" to "post" before "processing".
n/a

documentation: fix minor typo

---

src/sagemaker/utils.py

Customer reported issue when load-testing multiple notebooks:
"While executing AutoGluon Notebook, 5/20 users encountered failures while creating a model and endpoint. We modified our examples to create a unique resource name using sagemaker util below. Looks like, collision seems high with this tool.
model_name = sagemaker.utils.unique_name_from_base("inf-pipeline-model")
As the seed for random by default is timestamp it is creating same unique 4-digit hex when accessed around same time"
#using uuid to randomize random.seed(), otherwise system timestamp is used. 
Modified sagemaker sdk locally, tested changes. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …

#using uuid to randomize, otherwise system timestamp is used

---

src/sagemaker/image_uri_config/huggingface-training-compiler.json
tests/conftest.py
tests/integ/__init__.py
tests/integ/test_training_compiler.py
tests/unit/sagemaker/training_compiler/test_huggingface_pytorch_compiler.py
tests/unit/sagemaker/training_compiler/test_huggingface_tensorflow_compiler.py

- Update tensorflow version for Training Compiler to 2.6.3 and Pytorch to 1.10.2
- Added unit test for Tensorflow. 
- Added all supported regions for integration tests

feat: add Tensorflow and Pytorch version for SM Training Compiler and expand to regular regions

---

tests/integ/sagemaker/lineage/conftest.py

more debug logging for intermittent failed integration tests

fix: Add more logging when unexpected number of artifacts found

---

tests/integ/sagemaker/lineage/conftest.py

during automated this test typically passes, however it has failed rarely. retry to avoid flakiness.

fix: retry context delete

---

doc/doc_utils/jumpstart_doc_utils.py
doc/overview.rst

Added a section to display all JumpStart example notebooks that use the SageMaker Python SDK.
`tox`

feature: Add Jumpstart example notebooks

---

src/sagemaker/estimator.py
src/sagemaker/workflow/steps.py
src/sagemaker/workflow/utilities.py
tests/unit/sagemaker/workflow/test_utilities.py
tests/unit/sagemaker/workflow/test_utils.py
tests/unit/test_estimator.py

*Description of changes:* Present cache misses for TrainingStep reruns by changing the training job name, as well as upload path of user's training scripts. New name is calculated by hashing the inputted scripts/source_dir/dependencies. This change is similar to https://github.com/aws/sagemaker-python-sdk/pull/2790
unit testing

fix: TrainingStep cache misses due to timestamp based job name

---

tests/integ/test_training_compiler.py

https://github.com/aws/sagemaker-python-sdk/pull/3045 introduced a breaking change to our release regional tests as new region support was added. This PR Fixes this.
Tested in personal account in some regions like - GRU, BOM.

fix: integs for training compiler in non-PDX regions

---

doc/api/training/distributed.rst
doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst
doc/api/training/smp_versions/latest.rst

- SageMaker distributed model parallel library v1.8.0 release note
- Doc build tested locally.

doc: sm model parallel 1.8.0 release notes

---

src/sagemaker/local/image.py
tests/unit/test_image.py

#2180
No longer print token during login. Feel free to make any changes needed directly.
Sorry about the formatting changes, black really wanted those unrelated lines formatted and it seems to be right with `-l 100`.
Tested locally, this likely should be validated in notebook environments to ensure docker behaves the same there. It should, since docker warns about passing of credentials in an insecure manner and recommends doing this. I frequently docker login this way when testing images in ci.  …

fix: local mode printing of credentials during docker login closes #2180

---

src/sagemaker/estimator.py
src/sagemaker/model.py

Add encryption setting to tar_and_upload_dir method in following files
- sagemaker/estimator.py
-  sagemaker/model.py

fix: Add encryption setting to tar_and_upload_dir method

---

tests/integ/test_auto_ml.py

Fixing the PR integ automl integ tests. It seems like the [describe_auto_ml_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.describe_auto_ml_job) InputDataConfig response has been updated.

fix: Automl integ describe job check

---

src/sagemaker/model.py
src/sagemaker/session.py
tests/unit/sagemaker/model/test_model.py

feat: add validation specification

---

src/sagemaker/model.py
tests/integ/test_local_mode.py

https://github.com/aws/sagemaker-python-sdk/issues/3031
https://github.com/aws/sagemaker-python-sdk/issues/3084
`sagemaker.model.Model` uploads data to S3 when repacking, regardless and despite of local mode settings being specific to use local_code.
Locally tested, added test for checking botosession.resource('s3') and botosession.client('s3') calls are not getting made. …

fix: repack model locally when local_code local mode

---

src/sagemaker/workflow/_utils.py
src/sagemaker/workflow/callback_step.py
src/sagemaker/workflow/clarify_check_step.py
src/sagemaker/workflow/condition_step.py
src/sagemaker/workflow/emr_step.py
src/sagemaker/workflow/fail_step.py
src/sagemaker/workflow/lambda_step.py
src/sagemaker/workflow/model_step.py
src/sagemaker/workflow/pipeline.py
src/sagemaker/workflow/quality_check_step.py
src/sagemaker/workflow/step_collections.py
src/sagemaker/workflow/steps.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/unit/sagemaker/workflow/helpers.py
tests/unit/sagemaker/workflow/test_callback_step.py
tests/unit/sagemaker/workflow/test_condition_step.py
tests/unit/sagemaker/workflow/test_emr_step.py
tests/unit/sagemaker/workflow/test_lambda_step.py
tests/unit/sagemaker/workflow/test_model_step.py
tests/unit/sagemaker/workflow/test_processing_step.py
tests/unit/sagemaker/workflow/test_step_collections.py
tests/unit/sagemaker/workflow/test_steps.py
tests/unit/sagemaker/workflow/test_training_step.py

- Support Properties for StepCollection
- Support dependency declaration of StepCollection (i.e. depended by other steps)
*Testing done:* unit tests and integ tests

change: Support Properties for StepCollection

---

src/sagemaker/lambda_helper.py
src/sagemaker/workflow/pipeline.py
tests/unit/sagemaker/workflow/test_pipeline.py

*Description of changes:* [PR 3052](https://github.com/aws/sagemaker-python-sdk/pull/3052) introduced a bug where pipelines that were upserted would try to update user's lambda step function code twice. This resulted in the following error for the second  update_function_code call:
```
[ERROR]	2022-05-12T03:49:04.962Z	c0ba672c-1dbd-4894-ab57-ec1ecfc6c448	Encountered exception {'Message': 'The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:<region>:<account-id>:function:<function-name>', 'Code': 'ResourceConflictException'}
```
This PR aims to fix this issue but changing the pipeline upsert logic to either create or update pipeline (not both).
It also includes retries in case lambda does throw a …

fix:ResourceConflictException from AWS Lambda on pipeline upsert

---

src/sagemaker/image_uris.py
src/sagemaker/workflow/entities.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/integ/sagemaker/workflow/test_retry.py
tests/integ/sagemaker/workflow/test_training_steps.py
tests/integ/sagemaker/workflow/test_tuning_steps.py
tests/integ/sagemaker/workflow/test_workflow.py
tests/unit/sagemaker/image_uris/test_retrieve.py
tests/unit/sagemaker/workflow/test_execution_variables.py
tests/unit/sagemaker/workflow/test_functions.py
tests/unit/sagemaker/workflow/test_parameters.py
tests/unit/sagemaker/workflow/test_properties.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3024 
- Raise Error to prevent users from passing in `PipelineVariable` object into `image_uris.retrieve`. The reason is, the `image_uris.retrieve` retrieve images in compile time (PySDK) while the `PipelineVariable` is parsed in runtime (Pipeline backend).
- Update the error message thrown in `__str__` defined in `PipelineVariable` to make it more informative
- unit tests
By submitting this pull request, I confirm …

fix: Prevent passing PipelineVariable object into image_uris.retrieve

---

src/sagemaker/image_uris.py
src/sagemaker/workflow/entities.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/integ/sagemaker/workflow/test_retry.py
tests/integ/sagemaker/workflow/test_training_steps.py
tests/integ/sagemaker/workflow/test_tuning_steps.py
tests/integ/sagemaker/workflow/test_workflow.py
tests/unit/sagemaker/image_uris/test_retrieve.py
tests/unit/sagemaker/workflow/test_execution_variables.py
tests/unit/sagemaker/workflow/test_functions.py
tests/unit/sagemaker/workflow/test_parameters.py
tests/unit/sagemaker/workflow/test_properties.py

…retrieve (#3054)"
This reverts commit edd246342751df50867eecd45ca0138318c10ca5.

Revert "fix: Prevent passing PipelineVariable object into image_uris.retrieve (#3054)"

---

src/sagemaker/huggingface/model.py
src/sagemaker/sklearn/model.py

*Description of changes:* Add missing params to register methods for framework Models to fix unexpected keyword errors when registering a model.
*Testing done:* Tested registration of SKLearn and HuggingFace models. Ran unit and integration tests.

fix: fix missing register method params for framework models

---

src/sagemaker/image_uris.py
src/sagemaker/workflow/entities.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/integ/sagemaker/workflow/test_retry.py
tests/integ/sagemaker/workflow/test_training_steps.py
tests/integ/sagemaker/workflow/test_tuning_steps.py
tests/integ/sagemaker/workflow/test_workflow.py
tests/unit/sagemaker/image_uris/test_retrieve.py
tests/unit/sagemaker/workflow/test_execution_variables.py
tests/unit/sagemaker/workflow/test_functions.py
tests/unit/sagemaker/workflow/test_parameters.py
tests/unit/sagemaker/workflow/test_properties.py

This reverts commit 4d9c92cea045e2c6f8fa0df1ba89125358b9434f.
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3024
*Description of changes:* This PR adds back the previous reverted change: https://github.com/aws/sagemaker-python-sdk/commit/edd246342751df50867eecd45ca0138318c10ca5, since the dependent Project service has locked the sagemaker SDK version on their templates and the deployment has completed. …

fix: Add back Prevent passing PipelineVariable object into image_uris.retrieve

---

setup.py

fix: pin protobuf to < 4.0 to fix breaking change

---

src/sagemaker/clarify.py

*Description of changes:* Changed the metric default for methods run_pre_training_bias, run_post_training_bias, run_bias per service team's request 
From:
– Selector of a subset of potential metrics: [..]. Defaults to computing all.
To: 
– Selector of a subset of potential metrics: [..]. Defaults to str "all" to run all metrics if left unspecified.
Modification is in the comments section only. Will wait for the RTD doc CI to pass.
By submitting this pull request, I confirm that my contribution is made under the terms …

documentation: Changed method description per AWS request

---

src/sagemaker/estimator.py
src/sagemaker/fw_utils.py
src/sagemaker/workflow/__init__.py
src/sagemaker/workflow/clarify_check_step.py
src/sagemaker/workflow/entities.py
src/sagemaker/workflow/fail_step.py
src/sagemaker/workflow/parameters.py
src/sagemaker/workflow/quality_check_step.py
src/sagemaker/workflow/steps.py
tests/unit/sagemaker/workflow/helpers.py
tests/unit/sagemaker/workflow/test_execution_variables.py
tests/unit/sagemaker/workflow/test_functions.py
tests/unit/sagemaker/workflow/test_parameters.py
tests/unit/sagemaker/workflow/test_properties.py
tests/unit/sagemaker/workflow/test_steps.py
tests/unit/sagemaker/workflow/test_utils.py
tests/unit/test_tuner.py

*Issues:* https://github.com/aws/sagemaker-python-sdk/issues/3091
- Turn off Pipeline Parameter inheritance from python primitives as this has brought many hidden problems
- Clean up `PipelineNonPrimitiveInputTypes`  type collection as it's duplicate with `PipelineVariable`
- Change the behavior of `startswith` and `endswith` of `PipelineVariable`. Instead of always return false, we should throw exceptions explicitly here as the return false can hide some problems.
By submitting …

change: turn off Pipeline Parameter inheritance from python primitives

---

src/sagemaker/tensorflow/estimator.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/unit/sagemaker/workflow/test_training_step.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3142
Fix Tensorflow default `model_dir` generation when `output_path` is pipeline variable. Originally, if `model_dir` is None, `output_path` would be used to generate a default `model_dir`. However, this won't work if `output_path` is a PipelineVariable. This PR updates to use the default bucket to replace `output_path` in this case.
*Testing done:* unit tests and integ tests …

fix: Fix Tensorflow default model_dir generation when output_path is pipeline variable

---

doc/amazon_sagemaker_model_building_pipeline.rst

Fix: fix pipeline doc code example where process.run only accepts argument

---

setup.py

- Updated the upper bound to `<=4.4.0` in `setup.py`
- Created a new environment with`python -m venv`
- Activated the environment.
- Did `pip install .` with the changes checkout out.
- Verified that `importlib-metadata==4.4.0` was installed
- Mandatory CodeBuild tests on the PR

change: bump importlib-metadata version upperbound to support TF2.9

---

src/sagemaker/image_uri_config/autogluon.json
tests/unit/sagemaker/image_uris/test_autogluon.py

Added image_uri metadata for AutoGluon 0.4.2
tox

feature: AutoGluon 0.4.2 image_uris support

---

src/sagemaker/session.py
tests/unit/test_default_bucket.py

https://github.com/aws/sagemaker-python-sdk/issues/2910
Current check for bucket existence in `session.py` requires `s3:ListAllMyBuckets`. This permission shouldn't be necessary and is often not allowed in environments following the least privileges principle. Also Without `s3:ListAllMyBuckets` permissions the case of bucket existence, still requires `s3:CreateBucket` perms otherwise the check doesn't work properly.
Expected behavior
Users should be able to create a Sagemaker jobs without having to assign s3:ListAllMyBuckets or s3:CreateBucket to the IAM role. 
With this change users can now use a `s3:ListBucket` on a specific bucket, which can support the case of same or cross account specific bucket access.
For backwards …

fix: bucket exists check for session.default_bucket

---

doc/frameworks/tensorflow/sagemaker.tensorflow.rst
src/sagemaker/huggingface/__init__.py
src/sagemaker/huggingface/estimator.py
src/sagemaker/huggingface/training_compiler/config.py
src/sagemaker/image_uris.py
src/sagemaker/tensorflow/__init__.py
src/sagemaker/tensorflow/estimator.py
src/sagemaker/tensorflow/training_compiler/config.py
src/sagemaker/training_compiler/config.py
tests/integ/test_training_compiler.py
tests/unit/sagemaker/training_compiler/test_tensorflow_compiler.py

As title
This is a fast follow up to https://github.com/aws/sagemaker-python-sdk/pull/3154
Local testing and PR testing

feature: Adding Training Compiler support for TensorFlow estimator starting TF 2.9

---

tests/conftest.py
tests/integ/__init__.py
tests/integ/test_horovod.py
tests/integ/test_horovod_mx.py
tests/integ/test_huggingface.py
tests/integ/test_tf.py

fix: integs fallback from p3 to p2 instance

---

tests/integ/test_training_compiler.py

fix: changing trcomp integ tests to be able to run in all regions

---

src/sagemaker/image_uris.py
src/sagemaker/processing.py
src/sagemaker/workflow/utilities.py
tests/unit/sagemaker/image_uris/test_retrieve.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3141
- Add `override_pipeline_parameter_var` decorator to `image_uris.retrieve` to give grace period for users to remove passing pipeline variables to this method
- Note this only provides grace period to passing `ParameterString` with default value to the `image_uris.retrieve` which are all the issue reports we've received. And for other types of pipeline variables, they did not work previously so should not be impacted by the Git issue 3141.
- Update the doc string of the `definition` field of `ProcessingOutput` as it's not correct in Pipeline context.
*Testing done:* Unit tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure …

change: Add override_pipeline_parameter_var decorator to give grace period to update invalid pipeline var args

---

requirements/extras/test_requirements.txt
tests/integ/test_huggingface.py

Stanfords website is down, need to skip integ test temporarily.
Pytest update is needed for Py 310.
Local testing

fix: update pytest, skip hf integ temp

---

tests/data/pytorch_neo/code/inference.py

change: Update model name from 'compiled.pt' to 'model.pth' for neo

---

tests/integ/test_auto_ml.py

change: Skipping test_candidate_estimator_default_rerun_and_deploy

---

doc/frameworks/tensorflow/using_tf.rst

documentation: edit to clarify how to use inference.py

---

src/sagemaker/estimator.py
src/sagemaker/network.py
src/sagemaker/parameter.py
src/sagemaker/processing.py
src/sagemaker/transformer.py
src/sagemaker/tuner.py
tests/unit/sagemaker/workflow/test_training_step.py

*Description of changes:* This PR adds PipelineVariable annotation to base classes defined in estimator.py, processing.py, tuner.py, transformer.py. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.
*Testing done:* Unit tests

change: Add PipelineVariable annotation in estimator, processing, tuner, transformer base classes

---

src/sagemaker/clarify.py

*Issue #*
https://sim.amazon.com/issues/RAI-2029
Minor changes to the **docstrings** of [clarify.py](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/clarify.py) to adhere to the [SageMaker Python SDK Documentation Guidelines](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#documentation-guidelines) and keep information up-to-date.
Specifically:
* make language more precise and grammatically comply with Doc Guidelines (present tense, fix typos)
* add missing API references to other Clarify & SageMaker classes 
* specify default behavior (& numerical parameters) for ImageConfig parameters
* briefly define complex terms (SHAP, PDP, etc) & add links to their pages in the Clarify developer guide
* add "Raises" annotations to methods that throw …

documentation: add detail & links to clarify docstrings

---

src/sagemaker/model.py

…sion
*Description of changes:* For inferentia as compilation target device, we need to add Framework Version in the create_compilation_job requests to get the best result.

fix: fix: neo inferentia as compilation target not using framework ver

---

src/sagemaker/workflow/condition_step.py
src/sagemaker/workflow/conditions.py
tests/unit/sagemaker/workflow/test_condition_step.py
tests/unit/sagemaker/workflow/test_conditions.py

Remove redundant `primitive_or_expr()` which is used in `to_request()` in some Pipeline conditions. This behavior is redundant since PropertyReferences or other PipelineVariables are interpolated when creating pipeline definition, early interpolation results in plain request dict (PipelineVariables are converted into dictionary) returned by ConditionStep.to_request(), which lose PipelineVariable information. Preserving PipelineVariable information is required by Pipeline local mode. 
Updated related unit test cases and ran locally
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …

change: remove primitive_or_expr() from conditions

---

src/sagemaker/workflow/step_collections.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/unit/sagemaker/workflow/test_step_collections.py

*Description of changes:* Rename RegisterModel inner steps to prevent duplicate step names while building a PipelineGraph
added unit tests

fix: rename RegisterModel inner steps to prevent duplicate step names

---

doc/api/training/smd_model_parallel_general.rst
doc/api/training/smp_versions/archives.rst
doc/api/training/smp_versions/latest.rst
doc/api/training/smp_versions/latest/smd_model_parallel_pytorch.rst
doc/api/training/smp_versions/latest/smd_model_parallel_pytorch_tensor_parallel.rst
doc/api/training/smp_versions/v1.9.0/smd_model_parallel_common_api.rst
doc/api/training/smp_versions/v1.9.0/smd_model_parallel_pytorch.rst
doc/api/training/smp_versions/v1.9.0/smd_model_parallel_pytorch_tensor_parallel.rst
doc/api/training/smp_versions/v1.9.0/smd_model_parallel_tensorflow.rst
doc/api/training/smp_versions/v1_9_0.rst

Launch doc for the SageMaker model parallel library v1.10

documentation: SageMaker model parallel library v1.10.0 documentation

---

src/sagemaker/inputs.py

- a quick fix for heterogeneous-related docstrings
passed `tox -e black-check,flake8,docstyle,sphinx,doc8,twine --parallel all`

documentation: heterogeneous cluster api doc fix

---

src/sagemaker/clarify.py
tests/integ/test_clarify.py
tests/unit/test_clarify.py

https://sim.amazon.com/issues/RAI-1197
feature: support running bias detection with Clarify when facets are not included in the input dataset (and passed through as other parameters). 
* documentation: add clarify `DataConfig` params for facet not included in input dataset
* documentation: add clarify `DataConfig` param for analysis with predicted labels
* documentation: add clarify `DataConfig` param for analysis with excluded columns
* documentation: correct `DataConfig` label parameter description
* documentation: add details about running SHAP and PDP to run_explainability
- unit tests passed
- successfully ran tox commands for `sphinx`, `twine`, `docstyle`, `flake8`, `pylint`, `black-check`
- created integration tests for new parameters & re-ran …

feature: support clarify bias detection when facets not included

---

src/sagemaker/image_uris.py
src/sagemaker/model.py
src/sagemaker/rl/estimator.py
src/sagemaker/tensorflow/model.py
src/sagemaker/workflow/model_step.py
src/sagemaker/workflow/pipeline_context.py
src/sagemaker/workflow/utilities.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/unit/sagemaker/image_uris/test_retrieve.py
tests/unit/sagemaker/workflow/test_model_step.py

- Issue 1:
The repack step is doing model repack in pipeline execution time and currently the output path of the repacked model is the default path generated by the repack step (a training job under the hood). 
This output path is not aligned with the compile time model repack path (generated in Python SDK) and consequently it is not able to be customized via the `code_location` argument in model class.
This PR makes the repack step output path to be aligned with the compile time model repack path:
- If `code_location` is given, the runtime repack output path should be: `s3://<bucket_name>/<code_location>/<model_name>/......`
- If `code_location` is None, the runtime repack output path is: `s3://<bucket_name>/<model_name>/......`
- Issue 2: …

change: Make repack step output path align with model repack path

---

src/sagemaker/amazon/factorization_machines.py
src/sagemaker/amazon/ipinsights.py
src/sagemaker/amazon/kmeans.py
src/sagemaker/amazon/knn.py
src/sagemaker/amazon/lda.py
src/sagemaker/amazon/linear_learner.py
src/sagemaker/amazon/ntm.py
src/sagemaker/amazon/object2vec.py
src/sagemaker/amazon/pca.py
src/sagemaker/amazon/randomcutforest.py
src/sagemaker/sparkml/model.py
src/sagemaker/utils.py
tests/unit/test_utils.py

*Description of changes:* This PR adds PipelineVariable annotation in amazon models. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.

change: Add PipelineVariable annotation in amazon models

---

tests/integ/test_profiler.py

Add profiler integration test to show that profiler is enabled even when debugger_hook_config is set to false in python SDK. https://docs.aws.amazon.com/sagemaker/latest/dg/debugger-turn-off.html

feature: Add test for profiler enablement with debugger_hook false

---

src/sagemaker/chainer/model.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/model.py
src/sagemaker/multidatamodel.py
src/sagemaker/mxnet/model.py
src/sagemaker/parameter.py
src/sagemaker/pipeline.py
src/sagemaker/pytorch/model.py
src/sagemaker/sklearn/model.py
src/sagemaker/tensorflow/model.py
src/sagemaker/tuner.py
src/sagemaker/utils.py
src/sagemaker/xgboost/model.py
tests/unit/test_utils.py

*Description of changes:* This PR does the following:
- Add PipelineVariable annotation in framework models. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.
- Fix issues figured out by the test mechanism …

change: Add PipelineVariable annotation in framework models

---

src/sagemaker/workflow/pipeline.py
tests/unit/sagemaker/workflow/test_pipeline.py
tests/unit/sagemaker/workflow/test_pipeline_graph.py
tests/unit/sagemaker/workflow/test_step_collections.py

Steps defined in ConditionStep are missed when building the step map in Pipeline object. Consequently, if there're StepCollections added in a ConditionStep and they depend on each other, a KeyError would be thrown due to the StepCollections are missed to add to the step map
*Description of changes:* Allow StepCollection added in ConditionStep to be depended on
*Testing done:* Unit tests

fix: Allow StepCollection added in ConditionStep to be depended on

---

src/sagemaker/fw_utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/test_fw_utils.py

*Description of changes: Added a check to prevent launching a modelparallel job on CPU only instances.
*Testing done:
- All unit tests passed after the change (We ran unit tests in a conda environment with `python=3.8`. Please find the following results). **Since we only add a check by directly using an existing API, we would like to discuss with the reviewers to see if a new unit test is necessary.**
```
$ tox tests/unit
...
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
black-format: commands succeeded
docstyle: commands …
```

change: add a check to prevent launching a modelparallel job on CPU only instances

---

doc/api/training/sdp_versions/latest.rst
doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.rst
doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst

- Add the SageMaker data parallel library v1.5.0 release note
- The libraries' currency update for PT 1.12
`tox -e black-check,flake8,docstyle,sphinx,doc8,twine --parallel all`

documentation: smdistributed libraries currency updates

---

src/sagemaker/estimator.py

fix: fix that failing in certain debugger rules leads to end training jobs with no description.
*Issue #, if available:*  There are debugger rules that are valid only for XGBoost algorithms, but there is no warning or error message for users when the rules are incorrectly used.
*Description of changes:* Add warning for using XBGoost debugger rules outside of XGBoost algorithms. 
*Testing done:* Passed all unit tests.

feature: add warnings for xgboost specific rules in debugger rules

---

src/sagemaker/fw_utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/test_fw_utils.py

Reverts aws/sagemaker-python-sdk#3262

fix: Revert "change: add a check to prevent launching a modelparallel job on CPU only instances"

---

src/sagemaker/local/entities.py
tests/unit/test_local_entities.py

fix: Update localmode code to decode urllib response as UTF8

---

doc/amazon_sagemaker_model_building_pipeline.rst
doc/workflows/pipelines/sagemaker.workflow.pipelines.rst
src/sagemaker/estimator.py
src/sagemaker/processing.py
src/sagemaker/transformer.py
src/sagemaker/workflow/execution_variables.py
src/sagemaker/workflow/steps.py
tests/unit/sagemaker/workflow/test_processing_step.py
tests/unit/sagemaker/workflow/test_training_step.py
tests/unit/sagemaker/workflow/test_transform_step.py

…aunched jobs
*Description of changes:* Allow users to customize trial component display names for pipeline launched jobs

feature: Allow customizing trial component display names for pipeline launched jobs

---

src/sagemaker/amazon/amazon_estimator.py
src/sagemaker/debugger/debugger.py
src/sagemaker/debugger/profiler_config.py
src/sagemaker/drift_check_baselines.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/training_compiler/config.py
src/sagemaker/inputs.py
src/sagemaker/metadata_properties.py
src/sagemaker/model.py
src/sagemaker/model_metrics.py
src/sagemaker/serverless/serverless_inference_config.py
src/sagemaker/session.py
src/sagemaker/tensorflow/estimator.py

*Description of changes:* This PR does the following:
- Add PipelineVariable annotation in `Model` and `TensorFlow`. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.
- Fix issues figured out by the test mechanism.

change: Add PipelineVariable annotation in model base class and tensorflow estimator

---

src/sagemaker/clarify.py
tests/unit/test_clarify.py

- Added `_AnalysisConfigGenerator` class to simplify maintainability of the config creation. 
- Also, with this generator, customers may reproduce the state of the config locally during debugging (i.e. without a need to opening it in the S3 bucket)
- Simplified `job_name` creation part
- Added a private method `_last_analysis_config`) to store last analysis_config used for a run (to be useful in case of debugging)
- Extended the std out with the analysis config used for a run. Currently it already prints other values, like Job Name, Inputs, and Outputs:
```
Job Name:  Clarify-Bias-2022-07-22-09-00-31-294
Inputs:  [{...}]
Outputs:  [...}]
```
Unit Tests
_Put an `x` in the boxes that apply. You can also fill these out after …

feature: added _AnalysisConfigGenerator for clarify

---

src/sagemaker/clarify.py

Correct documentation error - `label` and `predicted_label` can be used together. 
*Testing done:* No tests. Just a documentation change

documentation: Correct documentation error

---

tests/integ/sagemaker/lineage/conftest.py

fix: using unique name for lineage test to unblock PR checks

---

src/sagemaker/feature_store/feature_group.py
src/sagemaker/session.py
tests/unit/sagemaker/feature_store/test_feature_store.py

feature: adding workgroup functionality to athena query

---

src/sagemaker/clarify.py
tests/integ/test_clarify.py
tests/unit/test_clarify.py

Added endpoint_name to clarify.ModelConfig, so the users could re-use existing model endpoints.
Added Unit Tests

feat: Added endpoint_name to clarify.ModelConfig

---

src/sagemaker/image_uri_config/spark.json

Adding CGK region for Spark Image.
- [x ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
By …

Add CGK in config for Spark Image

---

CONTRIBUTING.md
README.rst
requirements/extras/test_requirements.txt
setup.py
tests/integ/test_airflow_config.py

* support python 3.10
* update airflow dependency.

feat: support python 3.10, update airflow dependency

---

tests/integ/test_training_compiler.py

fix: trcomp fixtures to override default fixtures for integ tests

---

src/sagemaker/clarify.py
src/sagemaker/fw_utils.py
src/sagemaker/huggingface/processing.py
src/sagemaker/mxnet/processing.py
src/sagemaker/pytorch/processing.py
src/sagemaker/sklearn/processing.py
src/sagemaker/tensorflow/processing.py
src/sagemaker/xgboost/processing.py

- Add PipelineVariable annotation in all Processor subclasses. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.
- Fix issues figured out by the test mechanism.

change: Add PipelineVariable annotation for all processor subclasses

---

doc/frameworks/sklearn/using_sklearn.rst

Properly formatting some links + nit style fixes
`tox -e black-check,flake8,docstyle,sphinx,doc8,twine --parallel all`

documentation: fix links according to the app security scan

---

src/sagemaker/local/pipeline.py
tests/integ/test_local_mode.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3323
*Description of changes:* Fixed local pipeline argument parsing logic to account for lists of PipelineVariables
*Testing done:* Edited integ test to cover this case

fix: local pipeline step argument parsing bug

---

src/sagemaker/session.py

We recently started supporting feature for heterogeneousClusters and missed this part where we return instanceCount from ResourceConfig -> InstanceType For heterogeneousCluster jobs the total instanceCount is sum total of the instanceCount of all the instance groups. Fixing the same.

fix: Fixing the logic to return instanceCount for heterogeneousClusters

---

setup.py
src/sagemaker/clarify.py
tests/unit/test_clarify.py

When containers run, such schema validation is applied anyways. 
So added `ANALYSIS_CONFIG_SCHEMA_V1_0` to shorten feedback.
I also, added a flag for users to skip early validation. So they are not blocked in case we add a new feature in containers,  but cannot manage deploying the update in SDK on time.
- Added unit tests for 
- Used Schema containers use on the backend side. …

feat: added ANALYSIS_CONFIG_SCHEMA_V1_0 in clarify

---

src/sagemaker/amazon/amazon_estimator.py
src/sagemaker/amazon/factorization_machines.py
src/sagemaker/amazon/ipinsights.py
src/sagemaker/amazon/kmeans.py
src/sagemaker/amazon/knn.py
src/sagemaker/amazon/lda.py
src/sagemaker/amazon/linear_learner.py
src/sagemaker/amazon/ntm.py
src/sagemaker/amazon/object2vec.py
src/sagemaker/amazon/pca.py
src/sagemaker/amazon/randomcutforest.py

- Add PipelineVariable annotation in Amazon Estimator subclasses. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.
- Fix issues figured out by the test mechanism.

change: Add PipelineVariable annotation to Amazon estimators

---

requirements/extras/test_requirements.txt
setup.py

Expand version of `attrs` to allow `attrs==22.*` installation

change: Upgrade attrs>=20.3.0,<23

---

src/sagemaker/fw_utils.py
tests/unit/test_fw_utils.py

The json schemas for `sagemaker-xgboost` versions `1.2-1`, `1.2-2`, `1.3-1`, and `1.5-1` do not have the fields `processors` and `py_versions`. This causes the function `sagemaker.image_uris.retrieve` to return an ECR URI that is incorrectly parsed in the XGB estimator because the format does not match what is expected: https://github.com/aws/sagemaker-python-sdk/blob/v2.105.0/src/sagemaker/xgboost/estimator.py#L268-L277
The following lines of code demonstrate the difference between `1.0-1` - which has these fields - and `1.5-1`, which does not:
```python3
import sagemaker
print(sagemaker.image_uris.retrieve("xgboost", "us-west-2", "1.0-1"))
print(sagemaker.image_uris.retrieve("xgboost", "us-west-2", "1.5-1"))
>>> …
```

fix: Add regex for short-form sagemaker-xgboost tags

---

src/sagemaker/session.py

The current instance count retrieval logic is incorrect as the TrainingJob API would return `0` instance count even if instanceGroups is defined

fix: instance count retrieval logic

---

requirements/extras/test_requirements.txt
tests/integ/test_airflow_config.py

The code is security fix to bump apache-airflow from `2.3.4` to `2.4.0` in `/requirements/extras`
I have also fixed the `integ-tests`, `pr` test failures due to version upgrade.
The testing is done locally and all existing tests are passing.
No new tests introduced.

fix: security issue by bumping apache-airflow from 2.3.4 to 2.4.0

---

src/sagemaker/processing.py
tests/unit/sagemaker/workflow/test_pipeline_session.py

support kms key in processor pack local code

fix: support kms key in processor pack local code

---

src/sagemaker/workflow/monitor_batch_transform_step.py
tests/data/xgboost_abalone/inference.py
tests/integ/sagemaker/workflow/test_monitor_batch_transform_step.py

feature: added monitor batch transform step (pipeline)

---

src/sagemaker/algorithm.py
src/sagemaker/chainer/estimator.py
src/sagemaker/pytorch/estimator.py
src/sagemaker/rl/estimator.py
src/sagemaker/sklearn/estimator.py
src/sagemaker/training_compiler/config.py
src/sagemaker/workflow/pipeline.py
src/sagemaker/workflow/utilities.py
src/sagemaker/xgboost/estimator.py
tests/unit/sagemaker/workflow/test_training_step.py
tests/unit/test_sklearn.py

- Add PipelineVariable annotation in framework Estimator subclasses. The PipelineVariable annotation will be leveraged by a test mechanism: https://github.com/aws/sagemaker-python-sdk/pull/3163 to scan and check the incompatible issues between Pipeline steps and downstream classes caused by pipeline variables.
- Fix issues figured out by the test mechanism.

change: Add PipelineVariable annotation to framework estimators

---

doc/api/training/smp_versions/latest/smd_model_parallel_pytorch.rst
doc/requirements.txt

- Fix kwargs and descriptions per the SM model parallel service team's request
- Add `schema` to the doc/requirements.txt for local test `tox -e sphinx`
`tox -e black-check,flake8,docstyle,sphinx,doc8,twine --parallel all`

documentation: fix kwargs and descriptions of the smdmp checkpoint function

---

doc/requirements.txt
tests/integ/sagemaker/lineage/test_endpoint_context.py

*Description of changes:* Lineage integ tests having recurring failures. Temporarily disabling failing tests to unblock pipeline while we resolve the issue.
*Testing done:* Run unmodified integ test file and confirm that I see same issue locally, run modified integ test file and confirm the failing tests are skipped.

Fix: Temporarily disable failing lineage tests

---

tests/integ/test_airflow_config.py

Workaround to try any add retries for ConfigParser Failures.
Ran integ tests locally

fix: Add retry for airflow ParsingError

---

src/sagemaker/job.py
tests/unit/test_job.py

https://github.com/aws/sagemaker-python-sdk/issues/3414
Currently when dump the pipeline definition if estimator role is assigned with a pipeline parameter, the SDK will raise error as pipeline parameter expected as a valid input. This change is to support pass pipeline parameter to the role and don't expand it when load the job config.
tox
- [] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [] I have updated any …

feature: do not expand estimator role when it is pipeline parameter

---

src/sagemaker/fw_utils.py
src/sagemaker/image_uri_config/pytorch.json
src/sagemaker/image_uri_config/tensorflow.json
src/sagemaker/image_uris.py
tests/conftest.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_graviton.py

Added the necessary changes to incorporate the [Graviton instances](https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-graviton-sagemaker-1.12.1-inf-cpu-py38) into the `PyTorch` and `Tensorflow` frameworks.
Locally tested the feature to extract image string with the following code, where the output should match with expected DLC image URI's for PyTorch
(`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-graviton:1.12.1-cpu-py38-ubuntu20.04-sagemaker`) 
and Tensorflow
(`763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-inference-graviton:2.9.1-cpu-py38-ubuntu20.04-sagemaker`).
```bash
>>> sagemaker.image_uris.retrieve("pytorch","us-west-2", instance_type="ml.c6g.4xlarge") …
```

feature: Graviton support for PyTorch and Tensorflow frameworks

---

src/sagemaker/model.py
src/sagemaker/tensorflow/model.py
tests/unit/sagemaker/workflow/test_model_step.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3413
*Description of changes:* Change S3 output_path to remove adjacent slashes
*Testing done:* unit testing

fix: adjacent slash in s3 key

---

src/sagemaker/estimator.py
tests/integ/test_debugger.py
tests/unit/sagemaker/tensorflow/test_estimator.py
tests/unit/sagemaker/workflow/test_steps.py

fix: remove debugger environment var set up

---

tests/integ/test_tuner.py

fix: regex in tuning integs

---

src/sagemaker/tuner.py
tests/unit/test_tuner.py

*Description of changes:* Now the AWS SagemakerHPO support new strategy: GridSearch. In this strategy, we asking the user don't specify the max_jobs value, because we'll recalculate it later. Because of that, in this CR the default value is None, but if the strategy is not a GridSearch -- we'll fallback to a previous default: 1. So, that's backward compatible
*Testing done:* expended unit tests …

feature: support the GridSearch strategy for hyperparameter optimization

---

src/sagemaker/fw_utils.py
tests/unit/sagemaker/image_uris/test_graviton.py

Update instance families list supported by Graviton instances in SageMaker.
Tested changes using unit tests.

fix: Update Graviton supported instance families

---

src/sagemaker/estimator.py
src/sagemaker/fw_utils.py
tests/unit/test_fw_utils.py

Set `disable_profiler = True` for Trainium instance types since the profiler is not supported in trn1 instance types currently.
Locally tested the code changes through unit tests. 

feature: Disable profiler for Trainium instance type

---

doc/amazon_sagemaker_model_building_pipeline.rst

Issue #, if available: none
Description of changes: Update to pipelines caching configuration
Testing done: all tox tests (black-check,flake8,pylint,docstyle,sphinx,doc8)

feature: Pipelines cache keys update

---

doc/frameworks/pytorch/using_pytorch.rst
src/sagemaker/image_uri_config/pytorch-neuron.json
src/sagemaker/image_uris.py
tests/conftest.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_trainium.py

Added the necessary changes to incorporate the `v1.0-pt-1.11.0-tr-neuron-sdk2.3.0-py38` image into the `PyTorch` framework.
Locally tested the feature to extract image string with the following code, where the output matched with the [released DLC image](https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-1.11.0-tr-neuron-sdk2.3.0-py38)
```bash
import sagemaker, boto3
sagemaker.image_uris.retrieve(framework="pytorch",
region=boto3.Session().region_name,
instance_type="ml.trn1.xlarge")
'763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training-neuron:1.11.0-neuron-py38-sdk2.3.0-ubuntu20.04'
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …

feature: Trainium Neuron support for PyTorch

---

src/sagemaker/automl/automl.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/model.py
src/sagemaker/model.py
src/sagemaker/pipeline.py
src/sagemaker/session.py
src/sagemaker/tensorflow/model.py
tests/unit/sagemaker/automl/test_auto_ml.py
tests/unit/sagemaker/model/test_deploy.py
tests/unit/test_estimator.py
tests/unit/test_pipeline_model.py

This change also enables customization of ML instance storage volume size for Hosting Endpoints.
This change gives customers access to the capability of customizing 1) model data download timeout 2) inference container startup health check timeout and 3) ML instance storage volume size via SageMaker python SDK.
- Unit tests

feature: support customized timeout for model data download and inference container startup health check for Hosting Endpoints

---

src/sagemaker/spark/processing.py

The type annotations are backwards, so I fixed them.
None

fix: Fix type annotations

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_neo.py

There was a typo "ml_inf" which should be "ml_inf1"
Fixed the typo
Unit tests

fix: fix ml_inf to ml_inf1 in Neo multi-version support

---

doc/overview.rst

There was a syntax error in the documentation for creating a new AsyncInferenceConfig object.

fix: Fix AsyncInferenceConfig documentation typo

---

src/sagemaker/huggingface/training_compiler/config.py
src/sagemaker/tensorflow/training_compiler/config.py
src/sagemaker/training_compiler/config.py

feature: SageMaker Training Compiler does not support p4de instances

---

src/sagemaker/fw_utils.py
tests/unit/test_fw_utils.py

*Description of changes:* When passing distribution dict to estimator API PyTorch, we can let smp_config be either a dict (current behavior) or a string representing a config file.
```
distribution = {
"smdistributed": {
"modelparallel": {
"enabled": True,
"parameters": smp_config,
},
},
...
}
```
The config file needs to be a json file. e.g., `params.json`
```
{"partitions": 1, "tensor_parallel_degree": 2, "microbatches": 1, "optimize": "speed", "pipeline": "interleaved", "ddp": 1, "auto_partition": false, "default_partition": 0}
```
*Testing done:* local unit tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what …

feature: make estimator accept json file as modelparallel config

---

tests/unit/sagemaker/image_uris/test_algos.py

DeepAR's repository for `ap-northeast-3` was missing (see screenshot).

Add DeepAR ap-northeast-3 repository.

---

src/sagemaker/spark/processing.py

#3167
SparkProcessor and SparkJarProcessor, unlike all other processors, have instance_type and instance_count in constructor in reverse order. When the type hints were added in #3167, they were probably copy-pasted from other processors, hence str and int type hints got assigned in reverse order by mistake.
This is the fix to get correct type hints only, without changing the order of parameters and without breaking the backward compatibility. 
Yes
By submitting this …

fix: Fixing type hints for Spark processor that has instance type/count params in reverse order

---

src/sagemaker/image_uris.py
tests/unit/sagemaker/image_uris/test_graviton.py

Return ARM XGB/SKLearn tags if `image_scope` is `inference_graviton`.
Old behavior: 
```
In [2]: sagemaker.image_uris.retrieve("sklearn", "us-west-2", version="1.0-1", image_scope="inference_graviton")
Out[2]: '246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:1.0-1'
```
New behavior:
```
In [2]: sagemaker.image_uris.retrieve("sklearn", "us-west-2", version="1.0-1", image_scope="inference_graviton")
Out[2]: '246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:1.0-1-arm64-cpu-py3'
```
Also, a validation error is thrown if `image_scope` is set to `inference_graviton` with a non-arm instance.
Valid:
```
In [3]: sagemaker.image_uris.retrieve("sklearn", "us-west-2", version="1.0-1", …
```

fix: Return ARM XGB/SKLearn tags if `image_scope` is `inference_graviton`

---

src/sagemaker/spark/processing.py

Currently the signature type `instance_type` and `instance_count` of the `PySparkProcessor.__init__` is wrong.
https://github.com/aws/sagemaker-python-sdk/blob/284ddbebcf6240f0a4d3c734244f8e8ad066a9b3/src/sagemaker/spark/processing.py#L683-L684

fix: type hint of PySparkProcessor __init__

---

src/sagemaker/spark/processing.py

*Description of changes:* In the `sagemaker.spark.processing` module, the `PySparkProcessor` object constructor params `instance_type` and `instance_count` params have wrong typing:
- `instance_type` is a `str` but is being typed as `int`;
- `instance_count` is an `int` but is being typed as `str`.

fix: fix PySparkProcessor __init__ params type

---

tests/data/multimodel/container/Dockerfile

Allow Py 3.7 for MMS Test Docker env

fix: Allow Py 3.7 for MMS Test Docker env

---

src/sagemaker/git_utils.py

The goal of this PR is to make the code more Pythonic by incorporating Python with statements.

refactoring : using with statement

---

src/sagemaker/transformer.py
tests/integ/test_transformer.py

feature: Added transform with monitoring pipeline step in transformer

---

src/sagemaker/processing.py
tests/integ/test_xgboost.py

*Description of changes:* Bug was found which would upload bootstrapping code to override the source directory if it was named anything other than 'sourcedir.tar.gz'. Fix allows source directory to have any name.
EDIT 11/30 - It seems there are several places in the background which require the source directory to be named `sourcedir.tar.gz`. Rather than trying to refactor everything, I added documentation clarifying the requirement and validation which raises an error when misnamed. Also added testing of validation.
*Testing done:* Ran customer workflow using new update, confirmed that the uploaded source directory was not replaced, and bootstrapping code was separately uploaded as 'runproc.sh'. Also ran tox tests.
_Put an `x` in the boxes that apply. You can …

fix: Fix bug forcing uploaded tar to be named sourcedir

---

src/sagemaker/image_uri_config/pytorch-training-compiler.json

Fix: Differentiate SageMaker Training Compiler's PT DLCs from base PT DLC

---

setup.py
src/sagemaker/jumpstart/cache.py

Packaging library changed the exception  if a version is invalid. A custom try-except statement has been added to fix the exceptions returned.

fix: Fix failing jumpstart cache unit tests

---

src/sagemaker/workflow/_utils.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/unit/sagemaker/workflow/conftest.py
tests/unit/sagemaker/workflow/test_model_step.py
tests/unit/sagemaker/workflow/test_utils.py

*Issue #, if available:* If a user provide `model_package_name` to a ModelStep, the pipeline definition can be successfully generated but it will break the CreatePipeline call with the following error:
```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: Unable to parse pipeline definition. Unknown Argument member 'ModelPackageName'.
```
The reason is the pipeline backend excludes this field from the API model.
- Pop out ModelPackageName from pipeline definition
- Add a warning to inform customers about the pop out behavior
*Testing done:* unit test and integ test
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …

fix: Pop out ModelPackageName from pipeline definition

---

src/sagemaker/clarify.py

https://tiny.amazon.com/10tcxpyzj
Currently the analysis configuration schema of SageMaker Clarify API allows the content_type configuration "image/jpeg" and "image/jpg", but the service side validation only accepts the former which is the registered MIME type for JPEG (see [rfc3745](https://www.rfc-editor.org/rfc/rfc3745) and [JPEG specification](https://www.w3.org/Graphics/JPEG/)). The commit removes the latter from the schema to avoid confusion, and enable early API validation.
**Manual Test**
Passed.
if the customer set content_type configuration to image/jpg, then the job will by CustomerError, the error message looks like below,
* Without the change, the job was launched and it rejected the type,
``` …
```

fix: Remove content type image/jpg from analysis configuration schema

---

src/sagemaker/fw_utils.py

allowlists p4de in SMDDP supported instance types.
made this change locally and installed from source, and successfully ran a smddp job on p4de instances on SM

feature: Add p4de to smddp supported instance types

---

doc/api/training/sdp_versions/latest.rst
doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.rst
doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst
doc/api/training/smp_versions/latest.rst

smdistributed libraries release notes
tox sphinx passed
RTD PR builder passed:
- https://sagemaker--3543.org.readthedocs.build/en/3543/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.html#sagemaker-distributed-data-parallel-1-6-0-release-notes
- https://sagemaker--3543.org.readthedocs.build/en/3543/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.html#sagemaker-distributed-model-parallel-1-13-0-release-notes
By submitting this pull …

documentation: smdistributed libraries release notes

---

src/sagemaker/clarify.py
src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/model_monitor/model_monitoring.py
src/sagemaker/workflow/clarify_check_step.py

https://tiny.amazon.com/l78gdtmh
SageMaker Clarify API (including the Clarify Model Monitor API) docstrings use term JSONPath, but actually the SageMaker Clarify processing container expects [JMESPath](https://jmespath.org/) expression. 
The commit corrects the term to avoid customer confusion. No code change, only updates to docstrings.

fix: Correct SageMaker Clarify API docstrings by changing JSONPath to JMESPath

---

src/sagemaker/debugger/profiler_config.py

fix: Do not specify S3 path for disabled profiler

---

doc/overview.rst

Fix broken reference.

---

tests/integ/test_airflow_config.py

This change adds a retry to import utils from airflow in case it trys to load util from local module instead of airflow dependency

Retry ValueError for airflow tests

---

tests/integ/sagemaker/workflow/helpers.py
tests/integ/sagemaker/workflow/test_automl_steps.py
tests/integ/sagemaker/workflow/test_clarify_check_steps.py
tests/integ/sagemaker/workflow/test_experiment.py
tests/integ/sagemaker/workflow/test_fail_steps.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/integ/sagemaker/workflow/test_monitor_batch_transform_step.py
tests/integ/sagemaker/workflow/test_pipeline_var_behaviors.py
tests/integ/sagemaker/workflow/test_processing_steps.py
tests/integ/sagemaker/workflow/test_quality_check_steps.py
tests/integ/sagemaker/workflow/test_retry.py
tests/integ/sagemaker/workflow/test_training_steps.py
tests/integ/sagemaker/workflow/test_tuning_steps.py
tests/integ/sagemaker/workflow/test_workflow.py
tests/integ/sagemaker/workflow/test_workflow_with_clarify.py

*Issue #, if available:* We've seen pipeline resource leak in staging repo accounts because in some of the pipeline integ tests, we deleted pipelines without waiting for the execution to complete, which led to the deletion failed silently.
- Wait for executions to complete before deleting the pipelines
- Improve Pipeline integ tests by extract the execution.wait code blocks to a helper method
*Testing done:* Integ tests
By submitting this pull request, I confirm that my contribution is made under the terms …

fix: Improve Pipeline integ tests and fix resource leak

---

tests/unit/sagemaker/workflow/conftest.py
tests/unit/sagemaker/workflow/test_automl_step.py
tests/unit/sagemaker/workflow/test_condition_step.py
tests/unit/sagemaker/workflow/test_emr_step.py
tests/unit/sagemaker/workflow/test_lambda_step.py
tests/unit/sagemaker/workflow/test_model_step.py
tests/unit/sagemaker/workflow/test_processing_step.py
tests/unit/sagemaker/workflow/test_step_collections.py
tests/unit/sagemaker/workflow/test_training_step.py
tests/unit/sagemaker/workflow/test_transform_step.py
tests/unit/sagemaker/workflow/test_tuning_step.py

*Description of changes:* Clean up Pipeline unit tests by moving common constant vars and mock objects to `workflow/conftest.py`

change: Clean up Pipeline unit tests

---

src/sagemaker/experiments/run.py
tests/integ/sagemaker/experiments/test_run.py
tests/unit/sagemaker/experiments/test_run_context.py

*Description of changes:* Currently only the Run constructor support auto passing in experiment config to job env. This pr enables load_run auto pass in exp config
*Testing done:* Unit tests and integ tests

change: Enable load_run auto pass in experiment config

---

tests/integ/sagemaker/lineage/test_artifact.py

*Issue #, if available:* flaky integration test, related to internal ticket
*Description of changes:* increase creation time verification window from 1 minute to 2 minutes
*Testing done:* ran locally

increase creation time slack minutes

---

src/sagemaker/processing.py
tests/unit/test_processing.py

No issue associated
Currently, the SDK throws an error if the `role` parameter of the `Processor` class is passed as `PipelineParameter` [because it expects only strings](https://github.com/aws/sagemaker-python-sdk/blob/7faf9ce252a7694cac63be3a8ec8986776276708/src/sagemaker/processing.py#L62). With this modification the class `Processor` is now able to accept the role parameter as `PipelineParameter`, enabling then the possibility of feeding the role parameter when the pipeline is triggered.

feature: Support role as PipelineParameter in Processor class

---

src/sagemaker/session.py
src/sagemaker/tuner.py
tests/unit/test_session.py
tests/unit/tuner_test_utils.py

We know support the environment variables in the HPO. They already exist in the BaseEstimator class, so we'll just use them into our code.
Unit tests are extended.

feature: Support for environment variables in the HPO

---

tox.ini

*Description of changes:* When somebody has a black formatting error, they should be able to run `tox -e black-check` and see what the error is, rather than just see that an error exists.
*Testing done:* tox -e black-check displays diff of formatting fix, rather than just `1 file would be reformatted`.

feature: Display file diff on black-check

---

src/sagemaker/processing.py

Use logger instead of print function.
This allow developers using the library to silenc undesired output
Remove `print` function and use `logger.debug` instead.

Do not use print function. Use logger instead

---

src/sagemaker/feature_store/feature_group.py

Updating ingest function description (https://sagemaker.readthedocs.io/en/stable/api/prep_data/feature_store.html#sagemaker.feature_store.feature_group.FeatureGroup.ingest) according to discussion in a thread (https://amzn-aws.slack.com/archives/C02FT61K4BV/p1661876115110819).
https://t.corp.amazon.com/P71244023
Clarify failed_rows logic and other descriptions according to the discussion here: https://amzn-aws.slack.com/archives/C02FT61K4BV/p1661876115110819
By …

Update feature_group.py ingest() description

---

src/sagemaker/feature_store/feature_group.py
tests/unit/sagemaker/feature_store/test_feature_group.py

*Issue #, if available: 3332
*Description of changes: fixing ingestion to use FeatureGroup's Session in non-concurrency ingestion
*Testing done: Unit & Integration

fix: use FeatureGroup's Session in nonconcurrency ingestion

---

src/sagemaker/debugger/framework_profile.py
src/sagemaker/debugger/metrics_config.py

Add deprecation note for DetailedProfileConfig.
https://sagemaker--3583.org.readthedocs.build/en/3583/api/training/debugger.html#sagemaker.debugger.DetailedProfilingConfig

doc: Add a deprecation note for DetailedProfileConfig

---

src/sagemaker/processing.py
tests/integ/sagemaker/workflow/test_processing_steps.py
tests/unit/sagemaker/workflow/test_processing_step.py
tests/unit/test_processing.py

Thanks so much for francescoalongi@ to work on https://github.com/aws/sagemaker-python-sdk/pull/3605 to fill in a feature gap for us.
This PR3618 attempts to make the related tests more concrete, including:
- Update the two unit tests added by francescoalongi@ to make it more concrete, i.e. 
- use the PipelineSession rather than the Sagemaker Session, as the new step interface (i.e. `step_args = processor.run(...)` ) only take effect when PipelineSession is presented.
- Move these unit tests under workflow's processing step test files, as the test is extended to create a ProcessingStep and a Pipeline based on the processor.
- Group these two similar tests with parametrize pytest. 
- Verify in the eventual output - pipeline definition level.
- Update existing …

fix: Make test_processor_with_role_as_pipeline_parameter more concrete

---

tests/conftest.py
tests/data/experiment/inference.py
tests/data/experiment/process_job_script_for_run_clz.py
tests/data/experiment/train_job_script_for_run_clz.py
tests/integ/sagemaker/experiments/test_run.py

*Description of changes:* Enable Experiment integ test on beta SageMaker and SageMaker Metrics clients so that we can include Experiment integ tests in beta stage in the service pipeline.
*Testing done:* Integ tests

change: Enable Experiment integ test on beta clients

---

src/sagemaker/feature_store/feature_group.py

A feature store worker that's been told to ingest rows 1 to 100 of a data frame would emit a log line given below if some rows failed to ingest, 
```
Failed to ingest row 1 to 100. 
```
This often confuse some customers into thinking more rows have failed than what actually have, because the same line is logged if all but one row had succeeded .
There is already a log line in line 234 indicating row number and exception of failed rows that customers can use to debug.  This PR is for removing aforementioned extra log line. 
Verified the change by installing SDK locally and ingesting a data frame containing some faulty rows. 
This is a only a minor logging change, so below checklist is not applicable.  The code path is already covered by existing unit and integration tests.
By submitting …

fix: Remove confusing log line emitted during feature group ingestion

---

src/sagemaker/experiments/_environment.py
src/sagemaker/experiments/_metrics.py
src/sagemaker/experiments/_utils.py
src/sagemaker/experiments/run.py
tests/data/experiment/inference.py
tests/integ/sagemaker/experiments/test_metrics.py
tests/integ/sagemaker/experiments/test_run.py
tests/unit/sagemaker/experiments/test_environment.py
tests/unit/sagemaker/experiments/test_metrics.py
tests/unit/sagemaker/experiments/test_run.py

- As transform job team has helped to add a env var to supply the job source arn, it's a good time to enable load_run without name args in Transform env
- Clean up some TODO items in the unit/integ tests
- Clean up two unused clases
*Testing done:* unit tests and integ tests

change: Enable load_run without name args in Transform env

---

src/sagemaker/experiments/run.py
tests/unit/sagemaker/experiments/test_run.py

Whenever you execute an experiment run, the RUN_TC_TAG is appended to your run tags via the _append_run_tc_label_to_tags function. If you pass the same variable for tags over more than one experiment run, the RUN_TC_TAG gets appended more than once to your tag variable. This will cause a duplicate tag exception unless you manually remove the RUN_TC_TAG after each run. This change is to make sure that the RUN_TC_TAG doesn't get duplicated if it already exists on your tags.
RUN_TC_TAG
```
{
"key": "sagemaker:trial-component-source",
"value": "run"
}
```
Exception
```
ClientError: An error occurred (ValidationException) when calling the CreateTrialComponent operation: Duplicate tag key
```
Scenario to re-create the exception
```
tags = [
{ …
```

fix(experiments/run.py): Stop duplication of RUN_TC_TAG on Consecutive Experiment Runs

---

doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst
doc/api/training/smp_versions/latest.rst

Update release note for SM model parallelism library
RTD PR build suceeded: https://sagemaker--3621.org.readthedocs.build/en/3621/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.html#sagemaker-distributed-model-parallel-1-14-0-release-notes

documentation: SageMaker distributed - model parallism library release note

---

src/sagemaker/estimator.py

Reopening this PR to refresh the outdated PR https://github.com/aws/sagemaker-python-sdk/pull/3350

documentation: add security note for the estimator hyperparameter arg 

---

src/sagemaker/estimator.py
src/sagemaker/huggingface/model.py
src/sagemaker/inference_recommender/inference_recommender_mixin.py
src/sagemaker/model.py
src/sagemaker/tensorflow/model.py
tests/integ/test_inference_recommender.py
tests/unit/sagemaker/inference_recommender/constants.py
tests/unit/sagemaker/inference_recommender/constructs.py
tests/unit/sagemaker/model/test_deploy.py
tests/unit/test_estimator.py

- [ x I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ x I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

feature: Inference recommendation id deployment support

---

src/sagemaker/session.py
src/sagemaker/tuner.py
tests/integ/test_tuner.py
tests/unit/sagemaker/workflow/test_steps.py
tests/unit/test_tuner.py

We want to support the flexible instance types, the feature which allows customers to override their instance types if one of the is now available.
Unit tests and integ tests are added

feature: Support for flexible instance types in the HPO

---

src/sagemaker/session.py
src/sagemaker/tuner.py
tests/unit/test_tuner.py
tests/unit/tuner_test_utils.py

*Description of changes:* We want to support the intelligent stopping, the feature which allows customers to specify the condition on which we could stop their tuning jobs.
*Testing done:* Unit tests are added

feature: support of the intelligent stopping in the tuner

---

src/sagemaker/feature_store/dataset_builder.py
tests/integ/test_feature_store.py
tests/unit/sagemaker/feature_store/test_dataset_builder.py

Adds three new parameters to the `with_feature_group` Feature Store `dataset_builder` class.
These three new parameters are:
```
feature_name_in_target (str): A string representing the feature in the target feature group
that will be compared to the target feature in the base feature group. If None is
provided, the record identifier will be used in the join statement. (default: None).
join_comparator (JoinComparatorEnum): A JoinComparatorEnum representing the comparator used
when joining the target feature in the base feature group and the feature in the target
feature group (default: None).
join_type (JoinTypeEnum): A JoinTypeEnum representing the type of join between the base and
target feature groups. (default: None).
``` …

feature: feature store with_feature_group functionality changes

---

tests/integ/sagemaker/experiments/test_run.py

Skip test_run_from_transform_job integ test to unblock python-sdk code pipeline

---

tests/integ/test_tuner.py

*Description of changes:* we want to disable this test because the service which we test doesn't work in some regions yet, so this test should not block the release.
*Testing done:* run all unit and integration tests

change: disable the tuner test

---

src/sagemaker/image_uri_config/spark.json

Issue: We are not able to use newer version of Spark image because validation failure on the SageMaker Python SDK side. 
I deep dive into the [code](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/image_uri_config/spark.json). This file should support our current Spark set up which doesn't right now. It should support python 3.9 and Spark 3.2 according to processing spark image.
- [X ] I have read the …

feature: Add python 3.9 and spark 3.2 support for spark processor

---

src/sagemaker/experiments/experiment.py
src/sagemaker/experiments/trial.py
src/sagemaker/experiments/trial_component.py
src/sagemaker/session.py
src/sagemaker/utils.py
src/sagemaker/workflow/pipeline.py
tests/integ/test_inference_pipeline.py
tests/integ/test_mxnet.py
tests/integ/test_pytorch.py
tests/integ/test_sklearn.py
tests/unit/common.py
tests/unit/sagemaker/experiments/test_experiment.py
tests/unit/sagemaker/experiments/test_trial.py
tests/unit/sagemaker/experiments/test_trial_component.py
tests/unit/sagemaker/workflow/test_pipeline.py
tests/unit/test_endpoint_from_model_data.py
tests/unit/test_session.py
tests/unit/test_utils.py

…#3285)"
This reverts commit 5bc3ccf.*Issue #, if available:*
The changes help fix the resource based tag related routines to unblock customers to use resource tags.
Issue 1: Tag permission issue due to describe before create
Fix: Describe before create routines are now switched to create and check for resource existence, to unblock tag based access.
Issue 2: Tag propagation delay
Fix: On resource create and wait for resource creation - we will now wait for tag propagation. 
Tested all units and integs as part of the PR checks.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …

fix: tag permission issue - remove describe before create

---

doc/api/training/sdp_versions/latest.rst
doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.rst

smddp v1.7.0 release note
RTD PR builder preview
https://sagemaker--3653.org.readthedocs.build/en/3653/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.html#sagemaker-distributed-data-parallel-1-7-0-release-notes

Documentation: smddp v1.7.0 release note

---

src/sagemaker/model_monitor/model_monitoring.py
tests/unit/sagemaker/monitor/test_model_monitoring.py

Bugfix: Added support to update arguments in create_monitoring_schedule

---

src/sagemaker/model_monitor/dataset_format.py
src/sagemaker/model_monitor/model_monitoring.py
tests/integ/test_model_monitor.py
tests/unit/sagemaker/monitor/test_model_monitoring.py

Fixed: Cron expression resetting on update monitor

---

src/sagemaker/local/utils.py
tests/unit/sagemaker/local/test_local_utils.py

closes [#2527](https://github.com/aws/sagemaker-python-sdk/issues/2647)
This is a clone of https://github.com/aws/sagemaker-python-sdk/pull/2644 but has allow commits from maintainers on so should be easier to merge. 
Description of changes:
Add try except around file cleanup in sagemaker.local.utils.copy_directory_structure. This was causing local mode to fail when docker (running as root) writes files to a mounted dir and the user does not have permission to remove the files.
The same pattern is followed [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/image.py#L956).
Testing done:
Add test for failed removal, behaves as expected.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're …

fix: local mode deletion of temp files on job end

---

src/sagemaker/lambda_helper.py
src/sagemaker/workflow/lambda_step.py
tests/unit/sagemaker/workflow/test_lambda_step.py
tests/unit/test_lambda_helper.py

https://github.com/aws/sagemaker-python-sdk/issues/3568
https://t.corp.amazon.com/D68130934/communication
This PR fixes two things:
1. fixes lambda.update in lambda_helper use default S3 bucket if one is not provided
2. Update the lambda function code when function_arn parameter is provided to Lambda instance in LambdaStep
Added unit tests

fix: update lambda function when function arn is provided

---

src/sagemaker/feature_store/feature_group.py

https://github.com/aws/sagemaker-python-sdk/issues/3090
Sagemaker Session in `FeatureGroup` class is not initialized properly if the input is `None`. It is being set to `Session` _class_ instead of an instance of it (i.e `session = Session` instead of `sesssion = Session()`).  
Problems created by this incorrect assignment is explained in linked issue. 
Installed the SDK in virutalenv, created a `FeatureGroup` without passing a Session and invoked `describe()`. 
```
from sagemaker.feature_store.feature_group import FeatureGroup
f = FeatureGroup(
name = 'test-fg'
)
print(f.describe())
```
**Output**
```
botocore.errorfactory.ResourceNotFound: An error occurred (ResourceNotFound) when calling the DescribeFeatureGroup operation: Resource Not Found: Amazon SageMaker can't find a FeatureGroup …
```

Create a default SageMaker Session inside FeatureGroup class

---

src/sagemaker/git_utils.py

*Issue #, if available:* [#2242](https://github.com/aws/sagemaker-python-sdk/issues/2442)
*Description of changes:* Currently users cannot use configured ssh/config to clone private repos, since we override with GIT_SSH; this allows cloning of private repo.
With this change, we try the original method, and if it doesn't work we remove GIT_SSH and try to run same command. If ssh config is present without GIT_SSH it will succeed, as demonstrated by the workarounds implemented in the issue (see [here](https://github.com/aws/sagemaker-python-sdk/issues/2442#issuecomment-893592131) and [here](https://github.com/aws/sagemaker-python-sdk/pull/3645/files))
*Testing done:* Tested git_clone_repo with private repo using ssh before change and got `CalledProcessError`; after change clone succeeds. …

fix: Support cloning private repo using ssh key

---

README.rst

`Integrations tests` => `Integration tests`
*Description of changes:* Update Readme
*Testing done:* None

documentation: update README

---

tests/unit/sagemaker/image_uris/test_graviton.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3680
*Description of changes:* Fixing typo: 'pytotch' -> 'pytorch
*Testing done:* Ran tests in test_graviton.py.

fix: Typo in graviton algos

---

requirements/extras/test_requirements.txt

Reverts aws/sagemaker-python-sdk#3682
Causes multiple tests to fail - unable to find 'airflow.providers.amazon.aws.operators.sagemaker_transform'

Revert back to stable apache-airflow-providers-amazon from 7.2.1 to 4.0.0.

---

doc/amazon_sagemaker_featurestore.rst
src/sagemaker/feature_store/dataset_builder.py

- Improves API reference for the DatasetBuilder class
- Adds brief user guide for using Offline Store SDK / Databuilder class in Feature Store docs

docs: update feature store dataset builder docs

---

src/sagemaker/inference_recommender/inference_recommender_mixin.py
src/sagemaker/session.py
tests/integ/test_inference_recommender.py
tests/unit/sagemaker/inference_recommender/test_inference_recommender_mixin.py
tests/unit/test_session.py

Decouple moel.right_size() from model registry
Add unit test.
pip install . and run end 2 end tests with model not registerd.

feature: Decouple model.right_size() from model registry

---

src/sagemaker/image_uri_config/djl-deepspeed.json
tests/unit/sagemaker/image_uris/test_djl.py

N/A
Adds the latest container release to image_uris for djl-deepspeed. 
*Testing done:* Updated unit tests

change: Add djl 0.21.0 dlc images

---

doc/frameworks/djl/index.rst
doc/frameworks/djl/sagemaker.djl_inference.rst
doc/frameworks/djl/using_djl.rst
doc/frameworks/index.rst
src/sagemaker/djl_inference/__init__.py
src/sagemaker/djl_inference/defaults.py
src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

**Please wait to merge this PR until https://github.com/aws/sagemaker-python-sdk/pull/3685 has been merged**
This change adds a new module, djl_inference, that provides Model implementations that leverage the djl_inference DLCs. We provide a Model implementations that let users leverage the different engines/backends we offer in our DJL DLCs.
This integration makes it easy for users to deploy large models that require multiple GPUs (via Tensor Parallelism or Pipeline Parallelism) on Sagemaker. 
- All model types for for both DeepSpeed integration, and HuggingFace Accelerate integration have been tested with an ml.g5.48xlarge endpoint instance. I can share more details and the notebook with the testing code if needed.
- …

feature: Djl Large Model Support

---

src/sagemaker/feature_store/dataset_builder.py
tests/integ/test_feature_store.py
tests/unit/sagemaker/feature_store/test_dataset_builder.py

Adds three new parameters to the `with_feature_group` Feature Store `dataset_builder` class.
These three new parameters are:
```
feature_name_in_target (str): A string representing the feature in the target feature group
that will be compared to the target feature in the base feature group. If None is
provided, the record identifier will be used in the join statement. (default: None).
join_comparator (JoinComparatorEnum): A JoinComparatorEnum representing the comparator used
when joining the target feature in the base feature group and the feature in the target
feature group (default: None).
join_type (JoinTypeEnum): A JoinTypeEnum representing the type of join between the base and
target feature groups. (default: None).
``` …

feature: with_feature_group [feature_store]

---

tests/integ/test_inference_recommender.py

Integration test is failing, fix to make it successful.
Ran `tox tests/integ/test_inference_recommender.py::test_default_right_size_and_deploy_unregistered_base_model` and the tests is successful.

fix: Fix integration test error in test_default_right_size_and_deploy_unregistered_base_model

---

doc/frameworks/pytorch/using_pytorch.rst
src/sagemaker/pytorch/estimator.py

documentation: Torchrun gpu support documentation change

---

src/sagemaker/workflow/model_step.py
src/sagemaker/workflow/step_collections.py

All repack steps forward the `output_kms_key` of the model that they are repacking.

fix: RepackStep must use the same KMS key as the Model

---

src/sagemaker/inference_recommender/inference_recommender_mixin.py
tests/unit/sagemaker/inference_recommender/test_inference_recommender_mixin.py

Avoid double encoding to JSON
unit tests

fix: Avoid double encoding to JSON in InferenceRecommenderMixin

---

src/sagemaker/session.py

fix:  Wait on describe for tag propagation

---

src/sagemaker/image_uris.py
tests/unit/sagemaker/image_uris/test_graviton.py
tests/unit/sagemaker/image_uris/test_trainium.py

fix: Fix image_uris.retrieve() function to return ValueError when framework is not allowed for an instance_type

---

.coveragerc

There is a lot of clutter in codebuild logs with module-not-measured warnings such as below
```
/codebuild/output/src977214894/src/github.com/aws/sagemaker-python-sdk/.tox/py37/lib/python3.7/site-packages/coverage/inorout.py:533: CoverageWarning: Module sagemaker was previously imported, but not measured (module-not-measured)
self.warn(msg, slug="module-not-measured")
```
As per this [doc](https://coverage.readthedocs.io/en/coverage-5.2.1/cmd.html?highlight=warnings#warnings:~:text=Module%20XXX%20was%20never%20imported%20(module%2Dnot%2Dimported)) we are asking coverage.py to measure module XXX, but it was never imported by our program.
Disabling this to avoid this.
_Put an `x` in the boxes that apply. You can also fill …

fix: Disable module-not-measured warnings to avoid clutter in build logs

---

requirements/extras/test_requirements.txt
tox.ini

build(deps): bump apache-airflow from 2.4.1 to 2.5.1

---

requirements/extras/test_requirements.txt
tests/integ/test_airflow_config.py

fix: Upgrade apache-airflow-providers-amazon version

---

src/sagemaker/session.py
tests/unit/test_session.py

*Issue #, if available:* N/A, internal sim ticket
*Description of changes:* Register model step for cross account must make create_model_package call rather than create_model_package_group call, due to which when customer is passing arn in model_package_group_name, they are facing a ValidationException. This change was not accomodated when migration to ModelStep.
*Testing done:* Yes
tox -e pylint, flake8, black-format, twine, docstyle, sphinx, doc8 
tox -e py39 tests/unit/test_session.py::test_create_model_package_from_containers_cross_account_mpg_name export 
All passed locally
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going …

fix: Fix cross account register model

---

src/sagemaker/spark/processing.py
tests/unit/sagemaker/spark/test_processing.py

*Issue #, if available:* #3200
This PR gives the user the possibility to specify, when initializing objects of `PySparkProcessor` and `SparkJarProcessor` classes, where the EMR application configuration and Spark dependencies will be uploaded. It is inspired by the `code_location` parameter of the `FrameworkProcessor` class.
`export IGNORE_COVERAGE=- ; tox -e py310 -- -s -vv tests/unit/sagemaker/spark/test_processing.py ; unset IGNORE_COVERAGE`
By submitting this pull request, I confirm that …

feat: locations for EMR configuration and Spark dependencies

---

src/sagemaker/feature_store/feature_group.py

FeatureStore only supports kms key in ARN format. Update Python SDK to disambiguate for customers. https://t.corp.amazon.com/P82550390

Fix FeatureGroup kms key id documentation

---

src/sagemaker/image_uri_config/djl-fastertransformer.json
tests/unit/sagemaker/image_uris/test_djl.py

N/A
This change makes the new DJL FasterTransformer DLCs available through the PySDK image_uris module.
Added new unit tests for the change.

[change] Add DJL FasterTransformer image uris

---

src/sagemaker/tuner.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3743
*Description of changes:* adds missing dictionary keys in the `to_input_req` method of the `TuningJobCompletionCriteriaConfig` class
*Testing done:* interactively in jupyter notebook and by launching an HPO job successfully

Fixes the completion_criteria_config dict in the to_input_req method

---

src/sagemaker/config/config.py
src/sagemaker/local/local_session.py
src/sagemaker/session.py
tests/integ/test_sagemaker_config.py

fix: load_sagemaker_config should lazy initialize a default S3 resource

---

doc/overview.rst
src/sagemaker/async_inference/async_inference_config.py
src/sagemaker/async_inference/async_inference_response.py
src/sagemaker/exceptions.py
src/sagemaker/model.py
src/sagemaker/predictor_async.py
tests/integ/test_async_inference.py
tests/unit/sagemaker/async_inference/test_async_inference_config.py
tests/unit/sagemaker/async_inference/test_async_inference_response.py
tests/unit/sagemaker/inference_recommender/test_inference_recommender_mixin.py
tests/unit/sagemaker/model/test_deploy.py
tests/unit/test_estimator.py
tests/unit/test_predictor_async.py

*Description of changes:* Add support to async inline error notifications
*Testing done:* Manually tested the changes in a notebook and verified the unit, integ tests.
- [ x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in …

feature: add support for async inline error notifications

---

src/sagemaker/fw_utils.py

Add a comment that smdataparallel lib excludes tf 2.12 support
Add a comment as a reminder that smdataparallel lib drops support for tf 2.12 and 2.12 should not be included in the supported list.

change: Add a comment that smdataparallel lib excludes tf 2.12 support

---

src/sagemaker/clarify.py
tests/unit/sagemaker/monitor/test_clarify_model_monitor.py
tests/unit/test_clarify.py

*Issue #, if available:* https://issues.amazon.com/issues/RAI-4263
*Description of changes:* Add support for JSON model inputs for Clarify Processor via updates to the `content_template` field and adding a `record_template` to `ModelConfig`
*Testing done:* Unit testing locally, ran `make html` to verify documentation format is correct
*Backwards compatibility*: The `content_template` field was changed to be required when `content_type` is `application/json` or `application/jsonlines`.  Previously, we allowed omitting this field for `application/jsonlines` and we end up falling back to the [SageMaker dense format](https://docs.aws.amazon.com/sagemaker/latest/dg/cdf-inference.html#common-in-formats), but that was not documented in the Python SDK, nor in our [AWS …

feature: Add support for JSON model inputs for Clarify Processor

---

doc/experiments/sagemaker.experiments.rst

*Issue #, if available:* no related issue
*Description of changes:* the current auto generated documentation does not include `run_name` in the parameter list, change the reference to the method to hopefully fix that.
https://sagemaker.readthedocs.io/en/stable/experiments/sagemaker.experiments.html#sagemaker.experiments.load_run
*Testing done:* none

doc: Update reference to load run method in documentation

---

src/sagemaker/collection.py
src/sagemaker/session.py
tests/integ/test_collection.py
tests/unit/test_collection.py

Support for create and delete Model Registry Collection

Feat: Create/Delete Model Collection

---

src/sagemaker/djl_inference/defaults.py

*Issue #, if available:* [3748](https://github.com/aws/sagemaker-python-sdk/issues/3748)
*Description of changes:* Add `ml.p4d.*` and `ml.p4de.*` as supported instance types for DeepSpeedModel
*Testing done:* Ran unit tests. Tested model deploy using Sagemaker Python SDK.

change: Added ml.p4d and ml.p4de as supported instances for DeepSpeed

---

doc/api/inference/model_collection.rst
src/sagemaker/collection.py

*Description of changes: Added SDK documentation for Model Registry Model Collections
*Testing done: (tox checks) black-check,flake8,pylint,docstyle,sphinx,doc8

documentation: Add Model Registry Model Collection

---

tests/integ/test_inference_recommender.py
tests/integ/test_marketplace.py

fix: skip failing tests temporarily

---

src/sagemaker/feature_store/feature_group.py
src/sagemaker/feature_store/inputs.py
src/sagemaker/session.py
tests/integ/test_feature_store.py
tests/unit/sagemaker/feature_store/test_feature_group.py

*Description of changes: Add support for specifying different record deletion modes
*Testing done: Unit and integration testing

feature: support different types of deletion mode

---

src/sagemaker/huggingface/estimator.py
tests/integ/test_huggingface_torch_distributed.py

This PR adds the `torch_distrubted` support to the `HuggingFace` estimator. The code is mostly copied from the already existing implementation for it in the `PyTorch` estimator. 
local tests and added a new test `test_huggingface_torch_distributed.py`

[huggingface] Add `torch.distributed` support for Trainium and `torchrun`

---

doc/overview.rst
doc/remote_function/sagemaker.remote_function.rst
src/sagemaker/remote_function/client.py

* Add remote function related classes and method specifications
* Update Configuration File specification to include remote function function as supported SageMaker capability.
* Tested locally to see the changes on HTML.
* `tox -e twine,sphinx` pass locally.

documentation: Add Remote Function updates

---

src/sagemaker/interactive_apps/tensorboard.py
tests/unit/test_tensorboard.py

Add TensorBoard class as an interactive app. It is used to create/access TensorBoard applications hosted on SageMaker.
Mirror PR of https://github.com/aws/sagemaker-python-sdk-staging/pull/844
Added unit tests

feature: Add TensorBoard app

---

src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

https://github.com/aws/sagemaker-python-sdk/issues/3769
If user provides sagemaker session, we should honor that and pass it to downstream calls.
Updated unit test to validate this use case.

[fix]: Pass sagemaker session to downstream s3 calls

---

doc/remote_function/sagemaker.remote_function.rst
src/sagemaker/remote_function/client.py

* Address some small misses from remote function doc release.
* ran `tox -e twine,sphinx --parallel` locally - no failures.

documentation: fix minor misses from the remote function doc release

---

src/sagemaker/image_uri_config/huggingface.json

*Issue #3669:*
Update Image URI for:
* Transformers 4.26 - TensorFlow Inference DLC: https://github.com/aws/deep-learning-containers/pull/2697
* (Waiting for the DLC release)Transformers 4.26 - TensorFlow Training DLC: https://github.com/aws/deep-learning-containers/pull/2693

[Feature - Hugging Face] Update Transformers 4.26 - TensorFlow 2.11.0 Image uri

---

src/sagemaker/clarify.py
tests/unit/test_clarify.py

*Issue #, if available:* https://issues.amazon.com/issues/RAI-4934
*Description of changes:* `baseline` in SHAPConfig should allow arbitrary JSON for JSON support.
*Testing done:*  Unit tests, and some manual testing with an example notebook

fix: Update Clarify SHAPConfig baseline to allow JSON structures

---

src/sagemaker/image_uri_config/djl-deepspeed.json
tests/unit/sagemaker/image_uris/test_djl.py

Update LMI container to its latest version
- [x ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ x] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) …

[FT] update LMI container image

---

doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst
doc/api/training/smp_versions/latest.rst
doc/api/training/smp_versions/latest/smd_model_parallel_pytorch_tensor_parallel.rst

the SM model parallel library v1.15.0 release note
The DistributedTransformerLayer class: 
https://sagemaker--3806.org.readthedocs.build/en/3806/api/training/smp_versions/latest/smd_model_parallel_pytorch_tensor_parallel.html#smdistributed.modelparallel.torch.nn.DistributedTransformerLayer
Release note:
https://sagemaker--3806.org.readthedocs.build/en/3806/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.html …

documentation: the SM model parallel library v1.15.0 release note

---

doc/frameworks/pytorch/using_pytorch.rst

There was a typo in requirements.txt file
Typo when referring 'requirements.txt' file in docs.
- [] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc

Fix typo in using_pytorch.rst

---

src/sagemaker/remote_function/client.py
tests/unit/sagemaker/remote_function/test_client.py

*Description of changes:* Right now, the `RemoteExecutor` context manager blocks on all pending futures completing. This is not the intended behavior. This change makes it non-blocking by changing the value of `wait` parameter provided to `ThreadPoolExecutor.shutdown()`  https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.shutdown

fix: make RemoteExecutor context manager non-blocking on pending futures

---

tests/integ/test_edge.py

Test failed with error `E           botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateEdgePackagingJob operation: We are retiring Amazon Sagemaker Edge on April 26th, 2024. Use this (step-by-step guide)<https://docs.aws.amazon.com/sagemaker/latest/dg/edge-eol.html> to learn about how to continue deploying your models to edge devices`. Disabling test until feature team can fix/deprecate feature
By submitting this pull …

fix: Skip edge test

---

doc/frameworks/djl/using_djl.rst

N/A
Fixes a broken link in the sagemaker docs for djl framework.
Tested the link 😄 

[fix][doc] Fix broken link in DJL SageMaker docs

---

src/sagemaker/remote_function/runtime_environment/runtime_environment_manager.py

fix: remote_function python version mismatch issue

---

doc/frameworks/djl/sagemaker.djl_inference.rst
doc/frameworks/djl/using_djl.rst
src/sagemaker/djl_inference/__init__.py
src/sagemaker/djl_inference/defaults.py
src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

Adds support for DJLFasterTransformer container in djl_inference module.
endpoint tested on ml.g5.48xlarge

[feat] Add FasterTransformer DJL support

---

src/sagemaker/tensorflow/model.py

N/A
Update_endpoint is a deprecated positional arg. Moved to deploy() kwargs to get rid of annoying warning when using TensorFlowModel:
```
DeprecationWarning: update_endpoint is a no-op in sagemaker>=2.
```
Yes

fix: Remove deprecated update_endpoint from deploy() args in TensorFlowModel

---

src/sagemaker/deserializers.py
tests/unit/sagemaker/test_deserializers.py

**Issue #, if available:** #3696
**Description of changes:**
Enable the built-in `NumpyDeserializer` to read `application/x-npz` archives (which may be produced model-side by e.g. [numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html) or [numpy.savez_compressed](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html)) containing multiple named arrays. Added a unit test to exercise the new functionality.
As mentioned in the attached issue, this feature is already implemented in the same `numpy.load` method the serializer currently calls, but the typical `application/x-npz` Content Type is rejected by the header check.
**Testing done:**
- Run linting/formatting/etc locally
- Added unit test to demonstrate the deserialization
_Put an `x` in the …

Support npz archives in NumpyDeserializer

---

tests/integ/sagemaker/experiments/test_run.py

*Issue #, if available:* none
*Description of changes:* Improve reliability of this test, can be unreliable in `beta` environment.
*Testing done:*  `tox -e py39 -- tests/integ/sagemaker/experiments/test_run.py -k test_run_name_vs_trial_component_name_edge_cases`

fix: retry is_run assertion

---

src/sagemaker/processing.py

https://github.com/aws/sagemaker-python-sdk/issues/3699
fixing: https://github.com/aws/sagemaker-python-sdk/pull/3366
When using an S3 bucket with a policy that restricts PUT objects unless a kms key is specified, the creation of a processing job fails due to the fact that the SDK doesn't pass the value to all sections of the code. This change will fix that. …

fix: Pass KMS value to create processing job

---

tests/integ/sagemaker/remote_function/conftest.py
tests/integ/sagemaker/remote_function/test_auto_capture.py
tests/integ/sagemaker/remote_function/test_decorator.py

Add a test for remote function auto_capture functionality. This test is a bit non trivial where we first create a docker container and run the test in that docker container. The test execution needs a conda environment to be available on the client side which is not present in the container used by code build. Hence we need to run the test in its own container. …

feature: add integ tests for remote_function auto_capture functionality

---

tests/data/huggingface_byoc/requirements.txt
tests/integ/test_clarify_model_monitor.py
tests/integ/test_inference_pipeline.py
tests/integ/test_model_quality_monitor.py

1. Pinned the deps of pytorch training integ test to unblock repo contribution.
2. Added retries to some known flaky slow tests.
Tested in personal account.

fix: integs - pytorch transformer deps and add test retry

---

tests/integ/__init__.py

Add BOM to no No P2 Availability region list

fix: Add BOM to no No P2 Availability region list

---

setup.py
src/sagemaker/serverless/serverless_inference_config.py
tests/integ/test_serverless_inference.py
tests/unit/sagemaker/serverless/test_serverless_inference_config.py

feature: Add support for SageMaker Serverless inference Provisioned Concurrency feature)
*Description of changes:* Amazon SageMaker Serverless Inference support Provisioned Concurrency recently. Adding this support to SageMaker Python SDK as well.
- Adding Unit test for this new field in ServerlessInferenceConfig
- Adding integ test for Provisioned Concurrency Serverless inference …

feature: Add support for SageMaker Serverless inference Provisioned Concurrency feature

---

src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

N/A
There is a bug in the 0.20.0 versions of DJL containers for huggingface that is fixed in subsequent versions (0.21.0, 0.22.1). This change in the SDK only implements the workaround for containers and scenarios known to have the issue, and removes the workaround in other cases.
- [ x] I certify that the changes I am introducing will be backward …

[fix] Update dtype logic for huggingface backend for new containers

---

src/sagemaker/remote_function/client.py
src/sagemaker/remote_function/core/serialization.py
src/sagemaker/remote_function/core/stored_function.py
src/sagemaker/remote_function/errors.py
src/sagemaker/remote_function/invoke_function.py
src/sagemaker/remote_function/job.py
tests/integ/sagemaker/remote_function/test_decorator.py
tests/unit/sagemaker/remote_function/core/test_serialization.py
tests/unit/sagemaker/remote_function/core/test_stored_function.py
tests/unit/sagemaker/remote_function/test_client.py
tests/unit/sagemaker/remote_function/test_errors.py
tests/unit/sagemaker/remote_function/test_invoke_function.py
tests/unit/sagemaker/remote_function/test_job.py

fix: perform integrity checks for remote function execution

---

tests/scripts/run-notebook-test.sh

The MeadTestUtils notebook test was updated to allow the argument --consider-skips-failures. Adding this so that notebook tests passing guarantees that the tests actually succeeded.

feature: Update run-notebook-test to consider skips failures

---

requirements/extras/test_requirements.txt
setup.py
tox.ini

* Updating airflow to 2.6.0
* Moving relevant local and scipy requirements in test requirements. Skipping docker compose due to conflicts with airflow and also pypi seems to be an unsupported distribution partner for latest docker compose releases. We install docker compose in our infra image directly.
```
The conflict is caused by:
sagemaker[test] 2.154.1.dev0 depends on jsonschema
apache-airflow 2.6.0 depends on jsonschema>=4.0.0
docker-compose 1.29.2 depends on jsonschema<4 and >=2.5.1
```
* Tested package resolution locally.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …

fix: update apache airflow and update test requirements

---

doc/frameworks/sklearn/using_sklearn.rst

- updating the `framework_version` with a version using a maintained version of python (i.e., > 3.6)
- typo correction

update container version

---

doc/frameworks/djl/using_djl.rst
src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

feature: Partition support for DJLModel using SM Training job

---

src/sagemaker/estimator.py
src/sagemaker/fw_utils.py

Corrected the documentation and type annotations for some methods and variables which handle `UploadedCode` instances. In some places they were referred to as `str` and in some places as the nonexistent `UserCode` type. Now they are all `UploadedCode` (or `Optional[UploadedCode]`).
* ran it through mypy, got one fewer error than before
* ran `tox tests/unit`

fix: Make type annotation of UploadedCode consistent

---

requirements/extras/local_requirements.txt
requirements/extras/test_requirements.txt

#3857
Relax local-mode PyPI requirements on `urllib3` to a range `urllib3>=1.26.8,<1.26.15`

Relax local-mode PyPI requirements on urllib3

---

src/sagemaker/pytorch/model.py

Documentation on default value for `model_server_workers` on GPU for PyTorch is confusing.
Hence we are fixing this doc with correct explanation.

doc: Update doc for model_server_workers param in PyTorchModel

---

src/sagemaker/huggingface/processing.py

There are conflicts between the specified version in docstring and the actual implementation. This PR fixes the docstring of the HuggingFaceProcessor to match actual implementation.

documentation: Fix tensorflow and pytorch supported version in HuggingFaceProcessor

---

src/sagemaker/spark/processing.py

N/A
This patch enables setting [default values](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-sagemaker-python-sdk-default-values-parameters/) (`role` parameter) for Spark processors.
Yes

feature: Enable default role for Spark processors

---

.pylintrc

Adds some of the standard CPython extension packages to pylint's allow list.
This greatly reduces the number of spurious error messages pylint generates, making it a bit easier to see any actual warnings/errors in the output.
Also changed the configuration key to `extension-pkg-allow-list`. This is supported since [pylint-2.7.3 (March 2021)](https://github.com/pylint-dev/pylint/releases/tag/pylint-2.7.3).
This only affects the test suite, which still runs.

Update the list of extension packages pylint is allowed to load

---

src/sagemaker/config/config.py
src/sagemaker/config/config_utils.py
src/sagemaker/session.py
src/sagemaker/utils.py

change: SDK Defaults - switch from config printing to logging

---

src/sagemaker/image_uri_config/tensorflow.json

Adding TFS 2.12.1 Graviton image to SDK
Image testing on Deep Learning Containers.

[tensorflow][graviton] Add TFS 2.12.1 graviton image

---

src/sagemaker/experiments/run.py

*Issue #, if available:* 3881
*Description of changes:* update the log message to remove the suggestion to use load_run

change: remove unnecessary log messages for loading existing experiment runs

---

tests/integ/test_sagemaker_config.py

*Description of changes:* Add new field to expected_model to resolve failing integ test

fix: Fix failing integ test

---

src/sagemaker/session.py
src/sagemaker/tuner.py
tests/data/mxnet_mnist/mnist.py
tests/integ/test_tuner.py
tests/integ/test_tuner_multi_algo.py
tests/unit/test_tuner.py

- HyperparameterTuner constructor: add extra fields for autotune functionality, _map_tuning_config and _map_training_config are adapted for autotune
- Session: add autotune field to create_tuning_job
- unit test
- end2end integration test

feature: Add autotune for HyperparameterTuner

---

src/sagemaker/huggingface/__init__.py
src/sagemaker/huggingface/llm_utils.py
src/sagemaker/image_uri_config/huggingface-llm.json
src/sagemaker/image_uris.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

Huggingface is going to release Text Generation Inference DLC. This PR is to add the dlc images.
Unit test
`tests/unit/sagemaker/image_uris/test_huggingface_llm.py`

feature: Add huggingface-llm 0.6.0 dlc images

---

tests/integ/test_tuner.py

*Issue #, if available:* Removing release tag as it's blocking our release pipeline, due to feature not being available in ap-south-1

fix: Remove release tag from non-global feature

---

src/sagemaker/huggingface/model.py
src/sagemaker/image_uri_config/huggingface-neuronx.json
src/sagemaker/image_uris.py
tests/conftest.py
tests/unit/sagemaker/huggingface/huggingface_utils.py
tests/unit/sagemaker/huggingface/test_estimator.py

*Issue #3845:*
Add Image URI for:
* [Transformers 4.28 - PyTorch 1.13.0 - Neuronx Training DLC](https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.28.1-pt-1.13.0-tr-neuronx-sdk2.9.1-py38)
* [Transformers 4.28 - PyTorch 1.13.0 - Neuronx Inference DLC](https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.28.1-pt-1.13.0-inf-neuronx-sdk2.9.1-py38) …

feature: Add Neuronx Image uri - Transformers 4.28 - PyTorch 1.13

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_neo.py

Fixing a bug that was stopping version information from being passed to Neo service even when Neo supports versions for that edge target.
Added unit tests to validate that devices that should now pass version info do, and that devices that shouldn't still don't

fix: Update neo multiversion support to include edge devices

---

tests/scripts/run-notebook-test.sh

This notebook is currently failing at: https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-pipelines/tabular/abalone_build_train_deploy/sagemaker-pipelines-preprocess-train-evaluate-batch-transform.ipynb?short_path=bd99ba4#L1306
Traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/utils.py:1384, in volume_size_supported(instance_type)
1381 try:
1382 
1383     # local mode does not support volume size
-> 1384     if instance_type.startswith("local"):
1385         return False
AttributeError: 'ParameterString' object has no attribute …
```

fix: skip pipelines abalone notebook test

---

src/sagemaker/session.py
tests/integ/test_inference_recommender.py
tests/unit/test_session.py

Pass tagging into the `create_inference_recommendations_job()` call in `session.py`
updated `test_session.py`
ran integ tests and confirmed that tagging is working:
```
aws sagemaker list-tags --resource-arn arn:aws:sagemaker:us-west-2:079808353510:inference-recommendations-job/test-ir-right-size-job-name-1685982310-175f
{
"Tags": [
{
"Key": "ClientType",
"Value": "PythonSDK-RightSize"
}
]
}
``` …

feat: Add tagging support for create ir job

---

requirements/extras/local_requirements.txt

*Issue #, if available:* #3902
*Description of changes:* Loosen requirements for PyYAML, so that it doesn't conflict with reqs in setup.py

fix: Loosen local reqs for PyYAML

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_neo.py

Add ml_inf2 and ml_trn1 framework version support in compilation job config

change: enable neo framework version support on ml_inf2 and ml_trn1

---

tests/integ/test_marketplace.py
tests/integ/test_model_card.py

fix: tag more integs as flaky for auto-retry
fix: re-enable marketplace integs
N/A

fix: tag more integs as flaky for auto-retry

---

src/sagemaker/inference_recommender/inference_recommender_mixin.py
src/sagemaker/model.py
tests/integ/test_inference_recommender.py
tests/unit/sagemaker/inference_recommender/constants.py
tests/unit/sagemaker/inference_recommender/test_inference_recommender_mixin.py
tests/unit/sagemaker/model/test_deploy.py
tests/unit/sagemaker/model/test_model_package.py

The Inference Experience Team has launched a new feature called Deployment Recommendation that can be retrieved from the DescribeModel API. Provide PythonSDK support for deployment via Deployment Recommendation ID
See: https://github.com/aws/sagemaker-python-sdk/pull/3695
- within inference_recommender_mixin -> provided support for Deployment Recommendation ID
- add requisite unit tests
- add requisite integ tests …

feat: Add support for Deployment Recommendation ID in model.deploy(). No tagging support

---

doc/overview.rst

*Issue #, if available:* None available
*Description of changes:* Add missing quotation mark
*Testing done:* no.

documentation: add missing quotation mark

---

tests/unit/sagemaker/inference_recommender/test_inference_recommender_mixin.py
tests/unit/sagemaker/model/test_deploy.py

add `tags=None` into failing asserts
ran test ir and test deploy. All passing

fix: add tagging assert to inference recommender integ tests

---

src/sagemaker/tuner.py
tests/unit/test_tuner.py

\-
1. Replaced an identity-based `strategy` argument comparison with the `GRID_SEARCH` variable in the `__init__` of the `HyperparameterTuner` class with the `==` comparison.
2. Renamed incorrect `GridSearch` hyperparameter tuning strategy to `Grid` ([Amazon Sagemaker API Reference](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_HyperParameterTuningJobConfig.html#sagemaker-Type-HyperParameterTuningJobConfig-Strategy)).
Existing unit tests already cover the issues.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

fix: Fix HPO Grid Search comparison and name

---

src/sagemaker/jumpstart/utils.py
src/sagemaker/model.py
src/sagemaker/pipeline.py
src/sagemaker/utils.py
tests/unit/sagemaker/jumpstart/estimator/test_intelligent_defaults.py
tests/unit/sagemaker/jumpstart/model/test_intelligent_defaults.py
tests/unit/test_utils.py

fix: SDK Defaults Config - Handle config injection for None Sessions

---

src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

This change fixes a bug where the s3url option for djl model was still being set. This option is deprecated in favor of model_id, and has been causing issues with the partition method which assumes that only model_id is set.
DJL SageMaker Endpoint Test run for gpt-j-6b exposed this issue, and this change has fixed it https://github.com/deepjavalibrary/djl-serving/actions/runs/5283377099/jobs/9559547157.
By submitting this pull request, I confirm that my contribution …

fix: Remove deprecated option.s3url in favor of option.model_id

---

doc/api/inference/model_monitor.rst
src/sagemaker/model_monitor/__init__.py
src/sagemaker/model_monitor/data_quality_monitoring_config.py
src/sagemaker/model_monitor/model_monitoring.py
tests/integ/test_model_monitor.py
tests/unit/sagemaker/monitor/test_data_quality_monitoring_config.py
tests/unit/sagemaker/monitor/test_model_monitoring.py

* Added an optional parameter `monitoring_config_override` in `suggest_baseline` API for `overriding` global monitoring_config suggested in constraints by Model Monitor container. Currently, categorical_drift_method can only be overriden using the same.
* Tested `suggest_baseline API` manually and added corresponding integration tests for the same.

feat: Add optional monitoring_config_override parameter in suggest_baseline API

---

src/sagemaker/estimator.py
src/sagemaker/job.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/test_estimator.py
tests/unit/test_job.py

*Issue #, if available: SDK change to support output compressed upload. The new feature is to allow models to be uploaded without compression to improve upload performance.
*Description of changes: Add flag disable_output_compression in Estimator to support uncompressed model upload, "True" value on the flag will be translated to OutputCompressionType "NONE", as part of OutputDataConfig when creating training job.
*Testing done: all unit tests passed. Integration test on test_jumpstart_model.py passed. Manual tested creating training job with disable_output_compression set to true in estimator.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of …

feature: support uncompressed model upload

---

src/sagemaker/clarify.py
tests/unit/test_clarify.py

*Issue #, if available:* https://issues.amazon.com/issues/RAI-2685
*Description of changes:* Add `SegmentationConfig` class and `segmentation_config` parameter to `DataConfig` to support customer defined row wise dataset segments.
*Testing done:* Added unit tests and ran unit and integration tests locally.

feature: Add segment config for Clarify

---

src/sagemaker/config/__init__.py
src/sagemaker/config/config_schema.py
src/sagemaker/estimator.py
tests/data/config/config.yaml
tests/unit/__init__.py
tests/unit/sagemaker/config/conftest.py
tests/unit/sagemaker/config/test_config_schema.py
tests/unit/test_estimator.py

Add support for DebugHookConfig defaults in TrainingJob API as part of SDK defaults feature.

feat: SDK Defaults - DebugHookConfig defaults in TrainingJob API

---

src/sagemaker/feature_store/feature_processor/_constants.py
src/sagemaker/feature_store/feature_processor/feature_scheduler.py
tests/integ/sagemaker/feature_store/feature_processor/test_feature_processor.py
tests/unit/sagemaker/feature_store/feature_processor/test_feature_scheduler.py

Allow users to add tags through to_pipeline API.
Verified through notebook.

feature: Add support for tags in to_pipeline API for feature processor

---

src/sagemaker/session.py
tests/unit/test_session.py

resource key is of type string as per:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_edge_packaging_job.html
docs mention it is of type string but it is being converted to tuple causing a ParamValidationError when calling
session.package_model_for_edge
However in this commit it is being used as a tuple: https://github.com/aws/sagemaker-python-sdk/blame/master/src/sagemaker/session.py#L2546
Updating to use string, modified Unit test to cover the use case
resource key is of type string as per:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_edge_packaging_job.html
but it is being passed as tuple and throws Parameter Validation Error. Not sure if this ever worked …

fix: Update CreateEdgePackagingJob resourceKey with type string

---

src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/model.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/model/test_model.py

https://github.com/aws/sagemaker-python-sdk/issues/3969
If `async_inference_config` field is used with `JumpStartModel` or `JumpStartEstimator`, we use the predictor associated with async inference, not try to create a predictor with JumpStart-defaulted values. 
Wrote unit tests. 

fix: jumpstart async inference config predictor support

---

setup.py

* Remove unused dependency `protobuf3-to-dict`
protobuf3-to-dict is not used by the SageMaker Python SDK.
No occurrence in the source code:
```shell
> ag protobuf_to_dict
doc/frameworks/tensorflow/upgrade_from_legacy.rst
230:    from protobuf_to_dict import protobuf_to_dict
240:    protobuf_to_dict(json_format.Parse(result, tensor_pb2.TensorProto()))
```
This dependency has not been updated since 2017 and causes issues in certain combinations of poetry and pyenv. I suggest to remove it.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …

fix: Remove unused dependency `protobuf3-to-dict`

---

src/sagemaker/image_uri_config/djl-deepspeed.json
tests/unit/sagemaker/image_uris/test_djl.py
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

Update the container image of DLC.

change: Upgrade DJL deepspeed versions

---

src/sagemaker/djl_inference/model.py
tests/unit/test_djl_inference.py

fix: Add volume to partition djl_inference

---

src/sagemaker/session.py

*Issue #, if available:* None.
*Description of changes:* In #1204, the `wait_for_endpoint` `poll` default was changed from 5 to 30, but the docstring wasn't updated. Update the docstring to  match.
*Testing done:* None.

documentation: fix wait_for_endpoint docstring

---

src/sagemaker/session.py
src/sagemaker/tuner.py

https://github.com/aws/sagemaker-python-sdk/issues/3983
Changed documentation to match documentation from AWS provided elsewhere.

doc: Correct runtime param

---

requirements/extras/test_requirements.txt

**Description**
Updating the apache airflow version to fix the vulnerability.

fix: Update apache airflow version

---

tox.ini

**Description**
Updating the apache airflow contraints to
match with the apache airflow updated version
done as part of this PR : https://github.com/aws/sagemaker-python-sdk/pull/3998
- [x ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x ] I used the …

Fix: Update the apache airflow constraints

---

tests/integ/sagemaker/jumpstart/model/test_jumpstart_model.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/model/test_model.py

Adds integration test coverage for JumpStart Llama V2 models. Also adds unit tests for ensuring that model package arns are used to create the sagemaker model. 

chore: add jumpstart llama 2 tests

---

doc/api/training/smp_versions/latest/smd_model_parallel_pytorch.rst

*Description of changes:*  
Add an smp module for supporting flash attn
https://sagemaker--4009.org.readthedocs.build/en/4009/api/training/smp_versions/latest/smd_model_parallel_pytorch.html#smdistributed-modelparallel-torch-nn-flashattentionlayer

documentation: add smp class for supporting flash attn

---

tests/scripts/run-notebook-test.sh

**Description**
Some of the notebook tests that are run as part of release have been removed as part of PR : #4257 Removing them from test config
https://github.com/aws/amazon-sagemaker-examples/pull/4257

fix: Remove deleted notebook tests from test confg

---

src/sagemaker/jumpstart/cache.py
src/sagemaker/jumpstart/constants.py
src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/estimator.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/utils.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/test_utils.py

Whenever `verify_model_region_and_return_specs` was called, new logs would appear. In practice, since this method was invoked repeatedly, it causes excessive logging. The logging has been refactored to be performed only when the metadata is initially read from s3.

fix: excessive jumpstart logging

---

src/sagemaker/estimator.py
src/sagemaker/model.py
src/sagemaker/session.py
tests/unit/sagemaker/model/test_model.py
tests/unit/sagemaker/model/test_model_package.py
tests/unit/sagemaker/model/test_neo.py
tests/unit/test_endpoint_from_job.py
tests/unit/test_estimator.py
tests/unit/test_session.py

n/a
This change supports deployment of uncompressed ML model from S3 to SageMaker Hosting endpoints. It makes the feature available to customers via existing `Estimator`, `Session` and `Model` constructs and their sub-classes. Along with [uncompressed model upload support in SageMaker Training](https://github.com/aws/sagemaker-python-sdk/commit/6d42cc8faea8913b3ee365580b1daad8d9b7dea9), this feature enables customers to train uncompressed ML model on SageMaker Training and deploy the trained model to SageMaker Hosting with existing SageMaker python SDK use pattern.
Per https://docs.aws.amazon.com/sagemaker/latest/dg/large-model-inference-uncompressed.html
- Unit tests
- Used the feature to deploy an uncompressed ML model …

feat: Deploy uncompressed ML model from S3 to SageMaker Hosting endpoints

---

doc/amazon_sagemaker_featurestore.rst
src/sagemaker/feature_store/feature_group.py
src/sagemaker/feature_store/feature_store.py
src/sagemaker/feature_store/inputs.py
src/sagemaker/session.py
tests/integ/test_feature_store.py
tests/unit/sagemaker/feature_store/test_feature_group.py
tests/unit/sagemaker/feature_store/test_feature_store.py
tests/unit/test_session.py

- doc: add smp class for supporting flash attn (#4009)
- fix: Remove deleted notebook tests from test confg (#4013)
- build(deps): bump pygments from 2.11.2 to 2.15.0 in /requirements/tox (#4010)
- chore: jumpstart deprecation messages (#3992)
- fix: excessive jumpstart logging (#4023)
- feature: AutoGluon 0.8.2 image_uris update (#4012)
- feature: support online store ttl for records …

feature: support online store ttl for records

---

src/sagemaker/feature_store/feature_processor/feature_scheduler.py
src/sagemaker/feature_store/feature_processor/lineage/_feature_processor_lineage.py
tests/unit/sagemaker/feature_store/feature_processor/lineage/test_constants.py
tests/unit/sagemaker/feature_store/feature_processor/lineage/test_feature_processor_lineage.py
tests/unit/sagemaker/feature_store/feature_processor/test_feature_scheduler.py

- Propagate tags from pipeline to underlying lineage resources
- UT and manual testing from notebook

feat: Enable full tag propagation to lineage resources in feature processing

---

src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/workflow/clarify_check_step.py

When ClarifyProcessor is create, we upload the analysis config as a json file to S3. When customer specifies a KMS key, we pass it along to the S3 object to write it by encrypting it with the key. However, when it is created through ModelMonitor, the key is not passed with to S3, and this is presumably writing it unencrypted. This CR fixes this. 

fix: Pass kms_key to _upload_analysis_config when provided

---

tests/integ/test_huggingface_torch_distributed.py

Previously we saw consistent failure of integ test failure due to CapacityError while running huggingface g5 tests. This is due to we don't have enough capacity for ml.g5.12xlarge in PDX. After checking capacity, switching to ml.g5.8xlarge. 
Confirmed integ tests passed after the change. 

fix: change instance type for huggingface test to ml.g5.8xlarge

---

tests/scripts/run-notebook-test.sh

Skipping test until fix in example notebook to install docker-compose is complete
./amazon-sagemaker-examples/sagemaker-python-sdk/tensorflow_moving_from_framework_mode_to_script_mode/tensorflow_moving_from_framework_mode_to_script_mode.ipynb \

fix: skip tensorflow local mode notebook test

---

tests/scripts/run-notebook-test.sh

The fix has been merged for the failing test highlighted in the original PR - https://github.com/aws/sagemaker-python-sdk/pull/3903.
This PR reverses pr_3903

revert-PR_3903

---

src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/model_monitor/model_monitoring.py
tests/integ/test_model_monitor.py
tests/unit/sagemaker/monitor/test_clarify_model_monitor.py

*Description of changes:* Adding support to display the processing job logs for the latest monitoring schedule execution

feat: Support to get latest monitoring execution processing logs

---

src/sagemaker/image_uri_config/tensorflow.json

Adding TensorFlow Serving (Inference) 2.13 Graviton images to image_uri_config for use.

feat: Add TFS 2.13 Graviton SM images

---

src/sagemaker/jumpstart/artifacts/model_packages.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/model/test_model.py

https://github.com/aws/amazon-sagemaker-examples/issues/4337
fix: gated models unsupported region
Unit tests written

fix: gated models unsupported region

---

src/sagemaker/workflow/pipeline.py
tests/integ/sagemaker/workflow/test_workflow.py
tests/unit/sagemaker/workflow/test_pipeline.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4017
- pipeline.upsert failed to pass parallelism_config to update, so the updated parallelism_config won't be able to take effect.
- Add more unit/integ tests to prove the functionality of parallelism_config
*Testing done:* unit and integ tests

fix: pipeline upsert failed to pass parallelism_config to update

---

tests/scripts/run-notebook-test.sh

Temporarily skip kmeans notebook. A fix to new conda environment is beng planned by example notbooks team, following which we will re-enable this test.
N/A, will rely on PR checks.

fix: temporarily skip kmeans notebook

---

src/sagemaker/interactive_apps/base_interactive_app.py
src/sagemaker/interactive_apps/tensorboard.py
tests/unit/test_tensorboard.py

In order to confirm that we are in Studio environment, we cannot just rely on the existence of NOTEBOOK_METADATA_FILE as this file exists for SM Notebook Instances as well. We also need to check if domain id and user profile name are present in the file.
Following are some notable minor changes:
-   Using variable _in_studio_env instead of function _is_in_studio()
-   Removing unused functions _is_in_studio() and _validate_domain_and_user()
-   No default value for domain id and user profile name in validate functions
-   Deduplicate calls to validate functions
-  Tested functionality in notebook instances, along with ec2 and studio.
-  Also added a unit test to cover notebook instance use case.
_Put an `x` in the boxes …

feat: enable notebook instances to get presigned url

---

src/sagemaker/image_uri_config/data-wrangler.json
tests/unit/sagemaker/image_uris/test_data_wrangler.py
tests/unit/sagemaker/wrangler/test_processing.py

Adding Data Wrangler version 3.x images. including new TLV image.
tox -- tests/unit/sagemaker/image_uris/test_data_wrangler.py
tox -- tests/unit/sagemaker/wrangler/test_processing.py

change: Add Data Wrangler TLV and version 3.x images

---

src/sagemaker/jumpstart/constants.py

https://github.com/aws/sagemaker-python-sdk/issues/4106
fix: handle bad jumpstart default session

fix: handle bad jumpstart default session

---

doc/overview.rst
src/sagemaker/local/image.py
tests/scripts/run-notebook-test.sh
tests/unit/sagemaker/local/test_local_image.py

https://github.com/aws/sagemaker-python-sdk/issues/3659
https://github.com/aws/sagemaker-python-sdk/issues/4038
Local Mode - Add Support for Docker Compose V2
Added units and tested in a SageMaker NPI with G4DN instance - https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-python-sdk/pytorch_cnn_cifar10/pytorch_local_mode_cifar10.ipynb

feat: Local Mode - Add Support for Docker Compose V2

---

src/sagemaker/chainer/model.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/model.py
src/sagemaker/model.py
src/sagemaker/mxnet/model.py
src/sagemaker/pipeline.py
src/sagemaker/pytorch/model.py
src/sagemaker/session.py
src/sagemaker/sklearn/model.py
src/sagemaker/tensorflow/model.py
src/sagemaker/workflow/_utils.py
src/sagemaker/workflow/step_collections.py
src/sagemaker/xgboost/model.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/unit/sagemaker/workflow/test_pipeline_session.py
tests/unit/sagemaker/workflow/test_step_collections.py
tests/unit/test_session.py

*Description of changes:* Added SkipModelValidation for the model Registry step

feat: SkipModelValidation in modelRegistry

---

tests/unit/sagemaker/image_uris/conftest.py
tests/unit/sagemaker/image_uris/test_base_python.py
tests/unit/sagemaker/image_uris/test_data_wrangler.py

change: Enhance unit-tests to automatically consume image URIs config registries from config JSONs

---

src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/model_monitor/cron_expression_generator.py
src/sagemaker/model_monitor/model_monitoring.py
src/sagemaker/session.py
tests/integ/test_clarify_model_monitor.py
tests/integ/test_model_monitor.py
tests/unit/sagemaker/monitor/test_cron_expression_generator.py
tests/unit/sagemaker/monitor/test_model_monitoring.py

Added support for one time schedule in model monitor

feat: Support for one time monitoring schedule

---

tests/integ/auto_ml_utils.py
tests/integ/sagemaker/feature_store/feature_processor/test_feature_processor.py
tests/integ/test_auto_ml.py
tests/integ/test_inference_recommender.py
tox.ini

Fix auto ml tests:
* Add `CUSTOM_S3_OBJECT_KEY_PREFIX` to expected input and output path for `test_auto_ml_describe_auto_ml_job()` and `test_auto_ml_attach()`
* Required because [session object used in tests](https://github.com/aws/sagemaker-python-sdk/blob/cadd0a17f39640ecb3b2763cad903d4a77486967/tests/conftest.py#L142-L169) has `default_bucket_prefix` defined
* refactor to use `test_session_job_name` fixture instead of hardcoded name (`python-sdk-integ-test-base-job`). This way a new  test-session-job is created once each test session and can be reused in relevant tests
* fix parity issue between new testing accounts and old testing accounts which created `python-sdk-integ-test-base-job` job once for lifetime of account. Old accounts …

fix: auto ml integ tests and add flaky test markers

---

src/sagemaker/chainer/model.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/model.py
src/sagemaker/model.py
src/sagemaker/mxnet/model.py
src/sagemaker/pipeline.py
src/sagemaker/pytorch/model.py
src/sagemaker/session.py
src/sagemaker/sklearn/model.py
src/sagemaker/tensorflow/model.py
src/sagemaker/workflow/_utils.py
src/sagemaker/xgboost/model.py
tests/integ/test_model_package.py
tests/unit/sagemaker/model/test_model.py
tests/unit/sagemaker/model/test_model_package.py

*Description of changes:* Added support to update approval in a model package

feat: Model Package support for updating approval

---

tests/unit/sagemaker/workflow/test_transform_step.py

- Fix failing `tests/unit/sagemaker/workflow/test_transform_step.py::test_transform_step_with_transformer` unit test
- Change to  'assert step_def["Arguments"]["TransformJobName"].startswith("TestTransformJobPrefix")` since TransformerJobName includes timestamp suffix 
- [name_from_base() ](https://github.com/aws/sagemaker-python-sdk/blob/e100e0ad3d1506a88b7ca2baf654c66c3b70a3fb/src/sagemaker/utils.py#L75)
-  [transform.py](https://github.com/aws/sagemaker-python-sdk/blob/f1a809c3192808c36a302b0fd9da672a1bae8d93/src/sagemaker/transformer.py#L261)
* tox -e py310 -- -s -vv tests/unit/sagemaker/workflow/test_transform_step.py::test_transform_step_with_transformer
_Put an `x` in the boxes that apply. You can also fill these …

fix: transform step  unit test

---

src/sagemaker/session.py
tests/unit/test_default_bucket.py

For cases when SageMaker PySDK decides the bucket name on behalf of user, make sure that the bucket exists in Users AWS Session configured account.
Added unit tests.
Tested the logic by creating a test account A and created the bucket "sagemaker-us-west-2-A" in account B. With appropriate access setup, running sagemaker_session.default_bucket() in account A, the PYSDK shows the expected Error. …

change: Add bucket owner check

---

doc/frameworks/huggingface/sagemaker.huggingface.rst
doc/frameworks/mxnet/sagemaker.mxnet.rst
doc/frameworks/pytorch/sagemaker.pytorch.rst
doc/frameworks/tensorflow/sagemaker.tensorflow.rst

*Issue #, if available:* Fix #3513

documentation: Add missing API docs for processors

---

doc/api/prep_data/feature_store.rst
src/sagemaker/feature_store/feature_definition.py
src/sagemaker/feature_store/feature_group.py
src/sagemaker/feature_store/inputs.py
tests/integ/test_feature_store.py
tests/unit/sagemaker/feature_store/test_feature_definition.py
tests/unit/sagemaker/feature_store/test_feature_group.py
tests/unit/sagemaker/feature_store/test_inputs.py

Adds support for online store storage type input in create feature group, using which customer can optionally select to use Standard or InMemory storage types for their feature group.
Add support for collection types (Set, List, and Vector) for defining a feature in a feature group.
*Testing done:* Unit test and Integration Test.

feature: Add support for in-memory feature groups and collection type features in Feature Store. 

---

src/sagemaker/feature_store/feature_processor/__init__.py
src/sagemaker/feature_store/feature_processor/_config_uploader.py
src/sagemaker/feature_store/feature_processor/_data_source.py
src/sagemaker/feature_store/feature_processor/_factory.py
src/sagemaker/feature_store/feature_processor/_feature_processor_config.py
src/sagemaker/feature_store/feature_processor/_params_loader.py
src/sagemaker/feature_store/feature_processor/_spark_factory.py
src/sagemaker/feature_store/feature_processor/_udf_arg_provider.py
src/sagemaker/feature_store/feature_processor/_validation.py
src/sagemaker/feature_store/feature_processor/feature_processor.py
src/sagemaker/feature_store/feature_processor/lineage/_feature_processor_lineage.py
src/sagemaker/feature_store/feature_processor/lineage/_s3_lineage_entity_handler.py
tests/integ/sagemaker/feature_store/feature_processor/test_feature_processor.py
tests/unit/sagemaker/feature_store/feature_processor/lineage/test_constants.py
tests/unit/sagemaker/feature_store/feature_processor/lineage/test_feature_processor_lineage.py
tests/unit/sagemaker/feature_store/feature_processor/lineage/test_s3_lineage_entity_handler.py
tests/unit/sagemaker/feature_store/feature_processor/test_config_uploader.py
tests/unit/sagemaker/feature_store/feature_processor/test_data_helpers.py
tests/unit/sagemaker/feature_store/feature_processor/test_data_source.py
tests/unit/sagemaker/feature_store/feature_processor/test_factory.py
tests/unit/sagemaker/feature_store/feature_processor/test_feature_processor_config.py
tests/unit/sagemaker/feature_store/feature_processor/test_feature_scheduler.py
tests/unit/sagemaker/feature_store/feature_processor/test_spark_session_factory.py
tests/unit/sagemaker/feature_store/feature_processor/test_udf_arg_provider.py
tests/unit/sagemaker/feature_store/feature_processor/test_validation.py

* Enable feature_processor to connect with user defined data sources
* Add local integration test for BaseDataSource
* Fix the integration tests
* Add custom data source name validations
* Remove test unused imports
* Fix the data source name invalid pattern
* Resolve minor PR comments
* Add extra abstraction layer for feature processor
* Fix the docstring of BaseDataSource
* Fix the failed integration test …

feat: feature-processor extra data sources support

---

doc/api/prep_data/feature_store.rst
src/sagemaker/feature_store/feature_group.py

*Issue #, if available:* Fix #2677

documentation: Include FeatureGroup's load_feature_definitions API documentation

---

src/sagemaker/remote_function/core/serialization.py
src/sagemaker/remote_function/job.py
src/sagemaker/remote_function/runtime_environment/bootstrap_runtime_environment.py
tests/unit/sagemaker/remote_function/core/test_serialization.py
tests/unit/sagemaker/remote_function/runtime_environment/test_bootstrap_runtime_environment.py

Closes #4090
#4090
Fixes the `@remote` functionality on windows.
This request is coming from a github organization so you might not be able to edit it directly. Let me know if it needs rebased or any changes. Feel free to take the patch and apply it if that makes things easier.
Tested on multiple windows machines.
@diegodebrito @vadecp

fix: use correct line endings and s3 uris on windows

---

src/sagemaker/local/data.py

*Issue #, if available:* Fix https://github.com/aws/sagemaker-python-sdk/issues/2632
This makes the local mode inline with the classic mode.

feature: Batch transform, add support for split_type == "None" in local mode

---

doc/overview.rst
src/sagemaker/config/__init__.py
src/sagemaker/config/config.py
src/sagemaker/config/config_schema.py
src/sagemaker/local/image.py
src/sagemaker/local/local_session.py
src/sagemaker/session.py
tests/unit/sagemaker/config/conftest.py
tests/unit/sagemaker/config/test_config.py
tests/unit/sagemaker/config/test_config_schema.py
tests/unit/sagemaker/local/test_local_image.py
tests/unit/sagemaker/local/test_local_session.py
tox.ini

- closes #4025 
- closes #3331 
- closes #2482
- closes #2729
- Add schema to validate the local mode config file
- Add a new keyword: `container_config` to the local mode config file, this allows users to define configs for the container created by local mode.
- Add validation to the `LocalSession.config` attribute.
- Update documentation for the local mode
- Unit tests added …

feat: allow configuring docker container in local mode

---

src/sagemaker/feature_store/feature_processor/_config_uploader.py
src/sagemaker/remote_function/client.py
src/sagemaker/remote_function/job.py
tests/unit/sagemaker/feature_store/feature_processor/test_config_uploader.py
tests/unit/sagemaker/feature_store/feature_processor/test_feature_scheduler.py
tests/unit/sagemaker/remote_function/test_client.py
tests/unit/sagemaker/remote_function/test_job.py

*Issue #, if available:*  closes #4094
Users can provide a filter function to the `remote` decorator or the `RemoteExecutor` class, this function is used to select job dependencies to be uploaded. If the filter is not provided, the default behavior is uploading only python files.
- New argument `custom_file_filter` in the `remote` decorator and `RemoteExecutor` constructor.
- New argument `custom_file_filter` in the `_JobSettings` constructor and `remote_function.job._prepare_and_upload_dependencies` function.
- Unit tests added.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …

feature: allow non-python files in job dependencies

---

src/sagemaker/jumpstart/payload_utils.py

if `sagemaker` was imported in an unsupported JumpStart region, an exception would be thrown since `get_jumpstart_content_bucket()` was a default argument. This has been moved to the method body.
```
dev-dsk-evakravi-1e-d82d1ee5 % aws configure
AWS Access Key ID [****************JHE7]: 
AWS Secret Access Key [****************Pn46]: 
Default region name [ap-northeast-3]: 
Default output format [None]: 
(env) 
(23-10-12 17:58:31) <0> [~/workspace/github/sdk-fix-import-bug/sagemaker-python-sdk]  
dev-dsk-evakravi-1e-d82d1ee5 % python3 -c "import sagemaker"                              
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: …
```

fix: import error in unsupported js regions

---

src/sagemaker/config/config_schema.py

closes #4183 
- Add `container_root` to the local mode config schema.

fix: update local mode schema

---

src/sagemaker/remote_function/__init__.py
src/sagemaker/remote_function/checkpoint_location.py
src/sagemaker/remote_function/job.py
tests/integ/sagemaker/remote_function/test_decorator.py
tests/unit/sagemaker/remote_function/test_job.py

feat: Support job checkpoint in remote function
unit and integ test cases

feat: Support job checkpoint in remote function

---

src/sagemaker/pipeline.py

- Closes https://github.com/aws/sagemaker-python-sdk/issues/4041
- Update docstring of `PipelineModel.register`

documentation: Update PipelineModel.register documentation

---

src/sagemaker/inference_recommender/inference_recommender_mixin.py
tests/integ/test_inference_recommender.py

[V1058341966]
Inference Recommender integration tests are flaky when searching for InstanceType in recommendations due to serverless support launched 8/2023. Enforce realtime-only endpoints for integration tests.
`tox -e py310 -- tests/integ/test_inference_recommender.py`

fix: fix flaky Inference Recommender integration tests

---

requirements/extras/test_requirements.txt
tox.ini

change: bump apache-airflow to `v2.7.2`

---

tests/conftest.py
tox.ini

* Add `pytest_collection_modifyitems` hook to mark all tests in `tests/unit/sagemaker/image_uris` with pytest.mark.image_uris_unit_test
* `pytest_collection_modifyitems` is called after all test items collected
*  https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.hookspec.pytest_collection_modifyitems
* add `image_uris_unit_test` pytest mark
* `tox -e py310 -- -s -vv -m "image_uris_unit_test"  tests/unit`
By submitting this pull request, I confirm that …

change: add image_uris_unit_test pytest mark

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_framework_model.py
tests/unit/sagemaker/model/test_model.py

- closes https://github.com/aws/sagemaker-python-sdk/issues/3772
- A new method `is_repack` is added to the `Model` and `FrameworkModel` classes to check if the model needs to be repacked. It helps loosen the relation between `Model` and its subclass `FrameworkModel`.
- The `is_repack` logic is simplified since the class type checking is not needed.
- unit tests added …

change: add method to Model class to check if repack is needed

---

src/sagemaker/djl_inference/model.py
src/sagemaker/huggingface/llm_utils.py
src/sagemaker/image_uri_config/djl-deepspeed.json
src/sagemaker/image_uri_config/djl-fastertransformer.json
tests/unit/sagemaker/image_uris/test_djl.py
tests/unit/sagemaker/image_uris/test_huggingface_llm.py
tests/unit/test_djl_inference.py

*Description of changes:* Updates default versions and image

change: Updates for DJL 0.24.0 Release

---

src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/model.py
tests/integ/sagemaker/jumpstart/model/test_jumpstart_model.py
tests/unit/sagemaker/jumpstart/model/test_model.py

feat: Added register step in Jumpstart model

---

src/sagemaker/estimator.py
src/sagemaker/pytorch/estimator.py
tests/unit/test_estimator.py

Update estimator to allow `smdistributed` to be enabled with `torch_distributed` for a new `smdistributed` release that supports using `smdistributed` with `torch_distributed`.
Disable launching of jobs with smddp on p5 instances or using the p5 image (`2.0.1-gpu-py310-cu121-ubuntu20.04-sagemaker-pr-3303`) without `torch_distributed` enabled.
Ran and passed `tests/unit/test_estimator.py`, `tests/unit/test_pytorch.py` and `tests/unit/test_fw_utils.py` locally.

change: allow smdistributed to be enabled with torch_distributed.

---

tests/unit/sagemaker/image_uris/conftest.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_algos.py
tests/unit/sagemaker/image_uris/test_autogluon.py
tests/unit/sagemaker/image_uris/test_djl.py
tests/unit/sagemaker/image_uris/test_dlc_frameworks.py
tests/unit/sagemaker/image_uris/test_graviton.py
tests/unit/sagemaker/image_uris/test_huggingface_llm.py
tests/unit/sagemaker/image_uris/test_model_monitor.py
tests/unit/sagemaker/image_uris/test_neo.py
tests/unit/sagemaker/image_uris/test_rl.py
tests/unit/sagemaker/image_uris/test_sklearn.py
tests/unit/sagemaker/image_uris/test_sparkml.py
tests/unit/sagemaker/image_uris/test_stabilityai.py
tests/unit/sagemaker/image_uris/test_trainium.py
tests/unit/sagemaker/image_uris/test_xgboost.py

* Enhance image_uri_config unit tests to get image URIs config registries dynamically instead of using hardcoded values
* tox -vv -e py39 -- tests/unit -m image_uris_unit_test

change: enhance image_uris unit tests

---

src/sagemaker/serve/model_server/tgi/prepare.py

JumpStart updated their `model_data` format when launching uncompressed artifacts. This introduced a bug in ModelBuilder as we expected the original S3 URI string not the new dictionary.
Get the S3 URI from the dictionary.

fix: fast follow on js uncompressed support - ModelBuilder

---

tests/data/experiment/inference.py
tests/data/experiment/process_job_script_for_run_clz.py
tests/data/experiment/train_job_script_for_run_clz.py
tests/integ/sagemaker/experiments/test_run.py

*Issue #, if available:* Some Exp Run failing tests were skipped in this commit https://github.com/aws/sagemaker-python-sdk/commit/ae3748a67d74e674c5987e2685bb9799bacf49b2 due to the error thrown `in the training job:
```
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/miniconda3/lib/python3.8/site-packages/botocore/utils.py)
```
The issue was caused by a breaking change in boto3/botocore 1.33.2, and a github issue was opened under botocore: https://github.com/boto/botocore/issues/3082
Given the suggested solution provided in this github issue, we should make sure all 3 libraries boto3, botocore and s3transfer are in latest version to resolve the issue. However, given the test training job log, the three versions were aligned but the issue persisted.
It turns …

fix: Fix Experiment Run integ test w.r.t unexpected boto3 version

---

src/sagemaker/serve/save_retrive/version_1_0_0/save/utils.py

fix: save utils fix

---

src/sagemaker/fw_utils.py
tests/unit/test_fw_utils.py

Clean up API for SMP v2.
`partitions` key will still be checked on library side for SMP v1.
Remove related test checking that error is thrown if partitions is not passed.
Ran `tox -e py310 -- -s -vv tests/unit/test_fw_utils.py` which is passing.

deprecation: remove explicit `partitions` key requirement on pysdk side.

---

src/sagemaker/local/entities.py
src/sagemaker/remote_function/core/stored_function.py
src/sagemaker/workflow/pipeline.py
tests/integ/sagemaker/workflow/test_step_decorator.py
tests/integ/test_local_mode.py
tests/unit/sagemaker/local/test_local_pipeline.py

*Description of changes:* Enable retrieving function step results for local mode
Already reviewed in https://github.com/aws/sagemaker-python-sdk-staging/pull/1407
*Testing done:* unit and integ tests

feat: Enable retrieving function step results for local mode

---

src/sagemaker/serve/utils/types.py
src/sagemaker/serve/validations/check_image_and_hardware_type.py
tests/unit/sagemaker/serve/validations/test_check_image_and_hardware_type.py

- Add image and instance type validation for inf and graviton
- Unit test
- Formatting

fix: update image and hardware validation with inf and graviton

---

src/sagemaker/serve/marshalling/triton_translator.py
src/sagemaker/serve/model_server/triton/triton_builder.py
tests/unit/sagemaker/serve/model_server/triton/test_triton_builder.py

- Allow `model.register()` for model built using triton model server
- Populate `CONTENT_TYPE` and `ACCEPT` field for Triton specific translators to be used in `model.register()`
- Unit test
- Formatting
- Ran Triton notebook and model.register()

feature: support model.register() with triton model

---

src/sagemaker/serve/builder/model_builder.py
src/sagemaker/serve/detector/dependency_manager.py
src/sagemaker/serve/model_server/torchserve/prepare.py
src/sagemaker/serve/model_server/torchserve/server.py
src/sagemaker/serve/model_server/torchserve/xgboost_inference.py
tests/unit/sagemaker/serve/builder/test_model_builder.py
tests/unit/sagemaker/serve/detector/test_dependency_manager.py
tests/unit/sagemaker/serve/model_server/torchserve/test_prepare.py

https://github.com/aws/sagemaker-python-sdk/issues/4288
- Install old version in `inference.py` when using 1P xgboost container
- Restrict `sagemaker>=2.199` to ensure it installed version with `ModelBuilder`
- Ran XGBoost notebook
- Ran pytorch notebook
- Unit testing all passed
- Formatting all passed

fix: mitigation of xgboost container incompatibility with new version

---

src/sagemaker/image_uri_config/sagemaker-geospatial.json
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_sagemaker_geospatial.py

* Adding the SageMaker Geospatial Images in us-west-2
* Added Unit Tests and they are succeeded 
* Ran all the unit tests using tox -e py310 -- -s -vv tests/unit

feat: Add SageMaker Geospatial verison 1.x images

---

src/sagemaker/dataset_definition/inputs.py
src/sagemaker/model_monitor/model_monitoring.py
src/sagemaker/processing.py

Raised in https://github.com/aws/sagemaker-python-sdk/issues/3962

Change: Mention "FastFile" support for s3_input_mode in docstrings

---

src/sagemaker/remote_function/job.py
src/sagemaker/session.py
tests/integ/sagemaker/remote_function/test_decorator.py
tests/integ/test_local_mode.py
tests/unit/sagemaker/remote_function/test_job.py
tests/unit/test_session.py

*Issue #, if available:* As remote function serves as the foundation for step decorator, previously when we enabled local mode for step decorator, we have filled in most of the gaps for remote function local mode as well.
However, there is still an issue that the remote function result is not retrievable in local mode. The root cause is, when trying to retrieve the local job results, the current SDK is trying to describe the remote job rather than the local job as it uses the wrong client.
*Description of changes:* This PR fixes the issue mentioned above.
*Testing done:* Integ test
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

change: Support local mode for remote function

---

src/sagemaker/model.py
tests/unit/sagemaker/model/test_model.py

https://github.com/aws/sagemaker-python-sdk/issues/4248

Change: Accept model_data as dictionary in the model deploy

---

src/sagemaker/config/config.py
src/sagemaker/config/config_utils.py
tests/unit/sagemaker/config/test_config.py

closes #4123 
- Add `repeat_log` argument to `load_sagemaker_config`, if `False`, the info log message with the same content will not be emitted. Default to `False`.
- unit tests

feat: add non-repeating config logger

---

src/sagemaker/estimator.py
tests/unit/test_estimator.py

*Issue #, if available:* Fix https://github.com/aws/sagemaker-python-sdk/issues/2107
Raise a runtime error whenever the custom VPC is not completely set.

Change: Raise error if custom VPC is halfway defined

---

src/sagemaker/remote_function/core/pipeline_variables.py
src/sagemaker/remote_function/core/serialization.py
src/sagemaker/remote_function/core/stored_function.py
src/sagemaker/remote_function/job.py
src/sagemaker/workflow/function_step.py
tests/integ/sagemaker/workflow/test_step_decorator.py
tests/unit/sagemaker/remote_function/core/test_pipeline_variables.py
tests/unit/sagemaker/remote_function/core/test_stored_function.py
tests/unit/sagemaker/remote_function/test_job.py
tests/unit/sagemaker/workflow/test_function_step.py

*Issue #, if available:* For notebook users, if their custom step decorated function contains variables/classes with the same name of outer variables/classes, collision would take place and disrupt the pipeline compilation.
Moving the func and args serialization of function step from pipeline compilation to step level to resolve the issue.
*Description of changes:* Move func and args serialization of function step to step level
*Testing done:* unit and integ tests …

fix: Move func and args serialization of function step to step level

---

src/sagemaker/remote_function/runtime_environment/bootstrap_runtime_environment.py
src/sagemaker/remote_function/runtime_environment/runtime_environment_manager.py
tests/integ/sagemaker/conftest.py
tests/integ/sagemaker/remote_function/test_decorator.py
tests/integ/sagemaker/workflow/test_step_decorator.py
tests/unit/sagemaker/remote_function/runtime_environment/test_bootstrap_runtime_environment.py
tests/unit/sagemaker/remote_function/runtime_environment/test_runtime_environment_manager.py

*Issue #, if available:* This is a known issue on SageMaker Distribution image
If the step/remote decorated function is running in a job container with non-root user, it may not have the write permission to write job outputs to the following container folders: `/opt/ml/model /opt/ml/output /tmp`. 
This will lead to the job's silent failure as it's unable to write the exceptions to the output folder and as a result, the job is unaware that the invoked function has failed.
1. unit and integ tests
2. manually tested with the dev tar on SageMaker Distribution image
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

fix: Add write permission to job output dirs for remote and step decorator running on non-root job user

---

src/sagemaker/model.py
src/sagemaker/session.py
tests/integ/test_model_package.py
tests/unit/sagemaker/model/test_model_package.py

*Description of changes:*  Support for updating a model package

Feat: Added update for model package

---

src/sagemaker/base_predictor.py
src/sagemaker/cli/compatibility/v2/files.py
src/sagemaker/fw_utils.py
src/sagemaker/inference_recommender/inference_recommender_mixin.py
src/sagemaker/local/entities.py
src/sagemaker/local/image.py
src/sagemaker/model.py
src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/model_monitor/model_monitoring.py
src/sagemaker/model_monitor/monitoring_files.py
src/sagemaker/session.py
tests/integ/timeout.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3938 and https://github.com/aws/sagemaker-python-sdk/issues/1657
Complementary with https://github.com/aws/sagemaker-python-sdk/pull/3591
Remove `print` functions calls and use `logger.debug`, `logger.info` and `logger.error` instead.
Also rename `_LOGGER` or `LOGGER` variables into `logger` for the sake of code homogeneity (it is called `logger` everywhere else in the codebase) …

change Using logging instead of prints

---

src/sagemaker/local/image.py
src/sagemaker/local/utils.py
tests/unit/sagemaker/local/test_local_utils.py

- Closes  https://github.com/aws/sagemaker-python-sdk/issues/1354
- Unit test

change: update model path in local mode

---

src/sagemaker/session.py
tests/unit/test_session.py

Closes https://github.com/aws/sagemaker-python-sdk/issues/300
- New boolean argument `use_default` in `sagemaker.get_execution_role`: 
- Use a default role if ``session.get_caller_identity_arn`` can not return a correct role. 
- This default role will be created if needed. Defaults to ``False``.

change: create role if needed in `get_execution_role`

---

src/sagemaker/experiments/_helper.py
src/sagemaker/experiments/run.py
tests/unit/sagemaker/experiments/test_helper.py
tests/unit/sagemaker/experiments/test_run.py

Fix https://github.com/aws/sagemaker-python-sdk/issues/3710

Change: Allow extra_args to be passed to uploader

---

setup.cfg

Follow up on https://github.com/aws/sagemaker-python-sdk/issues/3181

Change: Drop py2 tag from the wheel as we don't support Python 2

---

tests/integ/test_inference_recommender.py

Disable failed test in IR

---

src/sagemaker/experiments/run.py
tests/unit/sagemaker/experiments/test_run.py

#3989
- Adding a field to load_run to also support loading in tags. This avoids access denied errors when a user using TBAC instead of RBAC for authentication.
- Unit test
- Manual test to ensure that the feature works. Followed the testing in #3989, but with a custom container.

fix: Supporting tbac in load_run

---

src/sagemaker/local/image.py
src/sagemaker/local/utils.py
tests/unit/sagemaker/local/test_local_image.py
tests/unit/sagemaker/local/test_local_utils.py

* feature: support local mode in SageMaker Studio
* chore: fix typo
* chore: fix formatting
* chore: revert changes for docker compose logs
* chore: black-format
* change: Use predtermined dns-allow-listed-hostname for Studio Local Support
* add support for CodeEditor and JupyterLabs
---------

feature: support local mode in SageMaker Studio (#1300)

---

tests/integ/sagemaker/workflow/test_notebook_job_step.py
tests/integ/test_inference_component_based_endpoint.py

fix: skip failing integs

---

src/sagemaker/local/pipeline.py
src/sagemaker/workflow/conditions.py
tests/integ/sagemaker/workflow/test_fail_steps.py
tests/unit/sagemaker/workflow/test_condition_step.py
tests/unit/sagemaker/workflow/test_conditions.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/2746
*Description of changes:* change ConditionNot incorrect property Expression to Condition
*Testing done:* unit and integ tests

fix: change ConditionNot incorrect property Expression to Condition

---

src/sagemaker/workflow/_utils.py
src/sagemaker/workflow/model_step.py
tests/unit/sagemaker/workflow/test_model_step.py

We've received several feature requests for exposing repack model settings:
- https://github.com/aws/sagemaker-python-sdk/issues/4218
- https://github.com/aws/sagemaker-python-sdk/issues/4098
*Description of changes:* Support custom repack model settings
*Testing done:* Unit tests and validate the create job request.

feat: Support custom repack model settings

---

src/sagemaker/workflow/utilities.py
tests/unit/sagemaker/workflow/test_model_step.py

- Add warning message for when customers are using custom-prefixing in their pipelines and do NOT specify a job-name to prefix.
- E.G. Cx fails to provide model-name here
```
tuning_step_prefix = prefix + "/Training_Artifacts"
model = Model(
image_uri=image_uri,
model_data=step_tuning.get_top_model_s3_uri(
top_k=0, s3_bucket=bucket, prefix=tuning_step_prefix
),
sagemaker_session=pipeline_session,
role=role,
name="A_Name" <<<<<<<<<<<<<<<<<<<<<<<<<<<<
)
```
results in this error
```
TypeError: expected string or byte like object
```
-unit 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

fix: add warning message for job-prefixed pipeline steps when no job name is provided

---

src/sagemaker/jumpstart/constants.py

map TLV buckets through python sdk.
- [ X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc

 JumpStart: TLV region launch

---

doc/api/prep_data/feature_store.rst
src/sagemaker/feature_store/feature_group.py
src/sagemaker/feature_store/inputs.py
src/sagemaker/session.py
tests/integ/test_feature_store.py
tests/unit/sagemaker/feature_store/test_feature_group.py
tests/unit/test_session.py

**Issue #, if available:**
None. Feature addition PR. 
**Description of changes:**
SageMaker Feature store recently launched `Provisioned` throughput mode for Feature Groups. This PR is modifying feature store interface to accept an optional throughput configuration that will be included in `create_feature_group` and `update_feature_group` API invocations. 
[AWS documentation about throughput modes](https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store-throughput-mode.html). 
Requires `boto3>=1.34.13`. 
**Testing done:**
* Wrote new unit tests and ran them successfully.
* Wrote new integ tests and ran them successfully.

feat: add throughput management support for feature group

---

src/sagemaker/local/entities.py
tests/integ/test_local_mode.py
tests/unit/sagemaker/local/test_local_entities.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4016
*Description of changes:* Add validation for empty ParameterString value in start local pipeline to make the behavior consistent with the remote mode
*Testing done:* unit test

fix: Add validation for empty ParameterString value in start local pipeline

---

src/sagemaker/remote_function/core/pipeline_variables.py
src/sagemaker/remote_function/job.py
src/sagemaker/remote_function/runtime_environment/runtime_environment_manager.py
src/sagemaker/workflow/function_step.py
src/sagemaker/workflow/pipeline.py
tests/integ/sagemaker/workflow/helpers.py
tests/integ/sagemaker/workflow/test_selective_execution.py
tests/integ/sagemaker/workflow/test_step_decorator.py
tests/unit/sagemaker/remote_function/core/test_pipeline_variables.py
tests/unit/sagemaker/remote_function/core/test_stored_function.py
tests/unit/sagemaker/remote_function/runtime_environment/test_runtime_environment_manager.py
tests/unit/sagemaker/remote_function/test_job.py
tests/unit/sagemaker/workflow/test_pipeline.py

Currently configuring selective pipeline execution w.r.t the step decorated functions would fail as such functions' output are uploaded to the s3 path: `<root>/<pipeline_name>/<ExecutionVariables.PIPELINE_EXECUTION_ID>/<step_name>/results`
The `ExecutionVariables.PIPELINE_EXECUTION_ID` is always pointing to the current execution, but in selective pipeline execution, we may need to retrieve step output from the previous execution, which leads to the issue of unable to retrieve the dependent step output.
*Description of changes:* Support selective pipeline execution for function step.
As in backend, the selective pipeline execution logics would replace the step properties with the source execution steps' output, in SDK we can replace the entire s3 path …

feat: Support selective pipeline execution for function step

---

src/sagemaker/local/pipeline.py
tests/unit/sagemaker/local/test_local_pipeline.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4307
Using PipelineDefinitionConfig in local mode would come across the error below:
```
Pipeline step 'preprocess-data' FAILED. Failure message is: TypeError: create_processing_job() got multiple values for argument 
```
*Description of changes:*  Honor the job name defined in base_job_name if PipelineDefinitionConfig is opted in. Otherwise, it falls back to the existing behavior, which is set the job name as per the step name
*Testing done:* Unit tests
By …

fix: Support using PipelineDefinitionConfig in local mode

---

setup.py

They are not used in the codebase.
Closes #4361 #4295
*Issue #, if available:* #4361 #4295
I cannot tell why these are in the install requirements. Searching the codebase for fastapi-related imports yields nothing. 
Happy to move them to an extra if there is a feature I'm missing but as far as I can tell they are never imported.
Noticed a bunch of web app related dependencies in our SBOM's and traced it back to this. git grepping for imports doesn't show they are used.
By submitting this …

fix: remove fastapi and uvicorn dependencies

---

src/sagemaker/workflow/quality_check_step.py
tests/unit/sagemaker/workflow/test_quality_check_step.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4227
*Description of changes:* Support PipelineVariable for ModelQualityCheckConfig attributes

fix: Support PipelineVariable for ModelQualityCheckConfig attributes

---

src/sagemaker/model_monitor/clarify_model_monitoring.py
src/sagemaker/model_monitor/model_monitoring.py
tests/integ/test_model_monitor.py

fix for - https://github.com/aws/sagemaker-python-sdk/issues/1624
Resetting the monitoring schedule name so that the monitoring schedule can be created again in case of failure during creation.

Bugfix: fixed create monitoring schedule failing after validation error

---

setup.py

Closes #4362
*Issue #, if available:* #4362
Relax the urllib deps to allow using newer versions. Boto supports them as well.

fix: relax upper bound for urllib dependency

---

src/sagemaker/serve/builder/model_builder.py
tests/integ/sagemaker/serve/test_serve_js_happy.py
tests/integ/sagemaker/serve/test_serve_pt_happy.py
tests/unit/sagemaker/serve/builder/test_model_builder.py

We've introduced a new transformers builder logic that relies on the pipeline tag in HF metadata. Move the Hub token fetching step to be only when we don't explicitly set the flags for jumpstart or djl.
Move HUB token fetch step to be in else block.
Remove changes to UT, and Integ test as they don't exercise that code path.
Reran UT, and Integ tests

Fetch HF metadata only when explicit type is not selected

---

CONTRIBUTING.md

*Description of changes:* Added instructions on how to set up the documentation building environment
*Testing done:* documentation change only.

documentation: add setup commands for documentation generation

---

src/sagemaker/workflow/clarify_check_step.py

…support
*Issue #, if available:* (internal ticket)
*Description of changes:* Fix the ClarifyCheckStep documentation to mention that PDP is also supported. 
*Testing done:* Only documentation change

documentation: fix the ClarifyCheckStep documentation to mention PDP

---

src/sagemaker/workflow/entities.py

N/A
There is a missing space in the error message. It will look like:
> TypeError: Pipeline variables do not support __str__ operation. Please use `.to_string()` to convert it to string type in execution timeor use `.expr` to translate it to Json for display purpose in Python SDK.
Notice the lack of space between "time" and "or". 

fix: fix PipelineVariable error message typo

---

src/sagemaker/serve/builder/djl_builder.py
src/sagemaker/serve/builder/jumpstart_builder.py
src/sagemaker/serve/builder/model_builder.py
src/sagemaker/serve/builder/tgi_builder.py
src/sagemaker/serve/builder/transformers_builder.py
src/sagemaker/serve/utils/telemetry_logger.py
src/sagemaker/serve/utils/types.py
tests/unit/sagemaker/serve/builder/test_transformers_builder.py
tests/unit/sagemaker/serve/utils/test_telemetry_logger.py

- Add telemetry metrics on usage of default images for ModelBuilder
- Enable vpc_config in jumpstart models and transformer models

Add telemetry metrics on usage of default images for ModelBuilder

---

src/sagemaker/remote_function/core/serialization.py
src/sagemaker/remote_function/job.py
src/sagemaker/remote_function/runtime_environment/bootstrap_runtime_environment.py
src/sagemaker/remote_function/runtime_environment/runtime_environment_manager.py
tests/unit/sagemaker/remote_function/core/test_serialization.py
tests/unit/sagemaker/remote_function/runtime_environment/test_bootstrap_runtime_environment.py
tests/unit/sagemaker/remote_function/runtime_environment/test_runtime_environment_manager.py
tests/unit/sagemaker/remote_function/test_job.py

*Issue #, if available:* As the sagemaker pysdk is installed in both local client side and job side, we've received issues reported relating to the inconsistent sagemaker versions. For example, if the local client side has more up-to-date  sagemaker version which introduces new serialization behavior that old sdk in the job side is unable to deserialize, a runtime error would be thrown.
*Description of changes:* Pass the local client side sagemaker pysdk version to the job and compare the version with that in the job side. If it does not match, log a warning to inform the user on potential unexpected behaviors
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …

change: Add validation for sagemaker version on remote job

---

tests/integ/sagemaker/jumpstart/estimator/test_jumpstart_estimator.py
tests/unit/sagemaker/jumpstart/test_notebook_utils.py

`meta-textgeneration-llama-2-7b` version` 2.*` contains a vulnerability.  For the purposes of passing the integ test (in case customers choose to use the vulnerable old model version), we tolerate the vulnerability. 
`test_list_jumpstart_models_script_filter` is flaky and will be temporarily skipped until JumpStart can figure out the root cause and write a fix.  …

fix: tolerate vulnerable old model for integ test and temporarily skip test_list_jumpstart_models_script_filter

---

src/sagemaker/user_agent.py
tests/unit/test_session.py
tests/unit/test_user_agent.py

* Basic test to verify User Agent propagation by adding test_user_agent.py
* Test to ensure that notebook instance is injected
* Test to ensure that studio app type is injected

feat: Prepend SageMaker Studio App Type to boto3 User Agent string

---

src/sagemaker/image_uri_config/sagemaker-tritonserver.json
src/sagemaker/image_uris.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_sagemaker_tritonserver.py

1. Starting Triton version 23.12, sagemaker tritonserver is available in a different set of accounts, similar to other model servers such as djl-serving, torchserve etc. i.e. original DLC accounts, as opposed to SageMaker Neo accounts. Triton on SageMaker will be available on both Neo accounts and new DLC accounts until v23.05. After v23.05, Triton will only be available in the new DLC URIs (i.e. accounts listed in this PR).
2. Adding the account id and region map for DLC accounts.
```
pytest -s tests/unit/sagemaker/image_uris/test_sagemaker_tritonserver.py 
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …

feat: Add new Triton DLC URIs

---

src/sagemaker/accept_types.py
src/sagemaker/content_types.py
src/sagemaker/deserializers.py
src/sagemaker/jumpstart/artifacts/kwargs.py
src/sagemaker/jumpstart/artifacts/model_packages.py
src/sagemaker/jumpstart/artifacts/predictors.py
src/sagemaker/jumpstart/artifacts/resource_requirements.py
src/sagemaker/jumpstart/artifacts/script_uris.py
src/sagemaker/jumpstart/curated_hub/utils.py
src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/predictor.py
src/sagemaker/resource_requirements.py
src/sagemaker/serializers.py
tests/unit/sagemaker/jumpstart/curated_hub/test_utils.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/test_predictor.py

…
Adds `hub_arn` support for `JumpStartModel` class. Notably for accept_types, content_types, serializers, deserializers, and predictor
- We exclude ResourceRequirements and ModelPackage registration. We want to include these
All tests passing for updated files

add hub_arn support for accept_types, content_types, serializers, deserializers, and predictor

---

src/sagemaker/remote_function/client.py

https://github.com/aws/sagemaker-python-sdk/issues/4425
Remote decorator does not support enable_network_isolation

fix: remove enable_network_isolation from the python doc

---

doc/api/prep_data/feature_store.rst

Add doc for new feature processor APIs and classes

doc: Add doc for new feature processor APIs and classes

---

src/sagemaker/config/config.py
tests/unit/sagemaker/config/test_config.py

Closes #4456
#4456
Properly close the file.
Unit tests with `python -X dev -X tracemalloc=20 -m pytest ./tests/unit/sagemaker/config -W error`

fix: properly close sagemaker config file after loading config

---

src/sagemaker/local/image.py
tests/unit/sagemaker/local/test_local_image.py

when running sagemaker in `local_gpu` mode it does not find the GPUs. The following config:
```yaml
deploy:
resources:
reservations:
devices:
- capabilities: [gpu]
```
This will result in no GPUs being found (Docker Compose version v2.24.1).
Specifying `count: all` in the `docker-compose.yml` solves this issue, and shouldn't change the behaviour (according to docker compose doc this should be the default behaviour https://docs.docker.com/compose/gpu-support/).
```yaml
deploy:
resources:
reservations:
devices:
- count: all
capabilities: [gpu]
```
Running without this change, no GPUs are found, with this change they are.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …

fix: make sure gpus are found in local_gpu run

---

tests/integ/__init__.py
tests/integ/test_auto_ml_v2.py

fix: Skip No Canvas regions for test_deploy_best_candidate

---

setup.py

Upgrade tblib to allow for latest version 3.0.0 to be used. It has been out since Oct. 2023 and is stable. My project cant build because we upgraded tblib.
```
235.0 The conflict is caused by:
235.0     The user requested tblib==3.0.0
235.0     sagemaker 2.209.0 depends on tblib<3 and >=1.7.0
``` 

Change: Update tblib constraint

---

src/sagemaker/model.py
tests/unit/sagemaker/training_compiler/test_huggingface_pytorch_compiler.py

feature: Accept user-defined env variables for the entry-point

---

src/sagemaker/remote_function/runtime_environment/bootstrap_runtime_environment.py
src/sagemaker/remote_function/runtime_environment/runtime_environment_manager.py
tests/unit/sagemaker/remote_function/runtime_environment/test_bootstrap_runtime_environment.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4484
Previously we added validation check on sagemaker sdk version between job vs client. And things happening in this order: import sagemaker -> get sagemaker.__version__ -> compare the sagemaker version in job vs client and do warning if needed -> bootstrap to install all dependencies
The import happens before bootstrap which causes issue if sagemaker is not pre-installed in the container.
Thus this PR move the validation to go after the bootstrap.
*Testing done:* manually tested via studio via the `remote` and `step` decorator and both work.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

fix: Move sagemaker pysdk version check after bootstrap in remote job

---

.github/workflows/codebuild-ci.yml

* Enabling github actions for PRs
* Use github actions to trigger Unit Tests and Linters
* Testing in personal fork: https://github.com/benieric/sagemaker-python-sdk/pull/6
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
By submitting this …

change: enable github actions for PRs

---

src/sagemaker/chainer/model.py
src/sagemaker/estimator.py
src/sagemaker/huggingface/model.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/model.py
src/sagemaker/mxnet/model.py
src/sagemaker/pipeline.py
src/sagemaker/pytorch/model.py
src/sagemaker/session.py
src/sagemaker/sklearn/model.py
src/sagemaker/tensorflow/model.py
src/sagemaker/utils.py
src/sagemaker/workflow/_utils.py
src/sagemaker/workflow/step_collections.py
src/sagemaker/xgboost/model.py
tests/integ/test_model_package.py
tests/unit/sagemaker/model/test_model.py
tests/unit/sagemaker/model/test_model_package.py
tests/unit/test_session.py
tests/unit/test_utils.py

- Supporting Model Data Source and Source Uri parameter for model package and register steps. Involves:
- Adding source_uri to register step of Model class and other children classes. 
- Removal of existing checks for disallowing `dict` form for model data when registering/ creating model package, instead disallow only if it is un-versioned model package. Also disallow source uri usage if un-versioned.
-  when source_uri and containers are specified during registration:
- if source_uri is not a model package or model arn:
- first make model package with inference spec derived from containers and then update the model package with source_uri. This is done since the base sdk disallows providing source uri and inference spec simultaneously …

feature: Add ModelDataSource and SourceUri support for model package.

---

CONTRIBUTING.md
tox.ini

Remove default coverage flags from tox.ini to prevent it from running 
during integ and other tests
This will prevent slug trace pr checks from hanging and remove one type of the flakiness 
Remove --cov and --cov append from default testenv
& allow it via {pos args} if needed.
Added a runcoverage testenv to perform the same if required.
`tox -e runcoverage -- tests/unit/test_knn.py `
`tox -e py311 -- tests/unit/test_knn.py --cov=sagemaker --cov-append --cov-report xml`
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull …

change: split coverage out from testenv in tox.ini

---

.github/workflows/codebuild-ci-health.yml
README.rst

* add CI Health Checks
* Run our CI checks every 3 hours to monitor health
* add badge to `README.rst`
* On backend will alarm on failures
* In personal fork: https://github.com/benieric/sagemaker-python-sdk/actions/workflows/codebuild-ci-health.yml

change: add ci-health checks

---

tests/integ/test_auto_ml_v2.py

Disabling some long-running tests to unblock CI/CD canaries and tests.
Manual testing of unit-tests.

Skip of tests which are long running and causing the ResourceLimitInUse exception

---

src/sagemaker/tuner.py

Just a small improvement of the HPO Tuner documentation (add list of the strategies and link to the proper documentation).
Manual testing + documentation review after the build.

Improvement of the tuner documentation

---

src/sagemaker/jumpstart/notebook_utils.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/test_notebook_utils.py

This change fixes the list jumpstart model experience when there are multiple versions of the same proprietary model and some of the versions are not a valid `Version` object.
This change is done in the doc utils in the main PR but missed in the notebook_utils in the previous PR.

fix: list jumpstart models with invalid version strings

---

tests/integ/test_feature_store.py

*Description of changes: Temporarily skip failing feature store test search integ test

fix: skip failing feature store search integ test

---

requirements/extras/test_requirements.txt
setup.py

_Issue #, if available:_
_Description of changes:_
Change: An alternative to adding extras to test requirements explicitly, all the time. 
- Test dependencise should not have to be duplicated from extras files to the test reqs file - which is error prone and can lead to asynch versions (depends on the developer remembering to update the requirement explicitly in multiple locations) 
- Test dependencies are a superset of all extras. 
_Testing done:_
pip install .  …

fix: Simplify how we process test dependencies, which are supposed to include all extras.

---

src/sagemaker/serve/builder/model_builder.py
src/sagemaker/serve/builder/schema_builder.py
src/sagemaker/serve/utils/hardware_detector.py
tests/integ/sagemaker/serve/test_serve_pt_happy.py
tests/unit/sagemaker/serve/builder/test_model_builder.py
tests/unit/sagemaker/serve/utils/test_hardware_detector.py

1. Move accelerate out of ModelBuilder to prevent import issues
2.  Fix attribute error in SchemaBuilder.repr() when custom translators are used

Fix: Move accelerate dependency closer to size calculations

---

src/sagemaker/session.py
tests/integ/sagemaker/workflow/conftest.py
tests/integ/sagemaker/workflow/test_experiment.py
tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/integ/sagemaker/workflow/test_pipeline_var_behaviors.py
tests/integ/sagemaker/workflow/test_retry.py
tests/integ/sagemaker/workflow/test_selective_execution.py
tests/integ/sagemaker/workflow/test_step_decorator.py
tests/integ/sagemaker/workflow/test_workflow.py
tests/integ/sagemaker/workflow/test_workflow_with_clarify.py

Workflow integ tests (e.g. `test_model_registration_with_model_repack `) have race condition with model_builder tests. The latter[ changes the `sagemaker_session.settings._local_download_dir` when doing the `model_builder.build`](https://github.com/aws/sagemaker-python-sdk/blame/c8d1428b1176e020c5225161d0426d3dc8853289/src/sagemaker/serve/builder/model_builder.py#L610) and when the test is done, the tmp file in` _local_download_dir`  is cleaned up but the field is not reset, which blocks the workflow integ tests to upload model inference entry point file to S3. See the error thrown in 
https://github.com/aws/sagemaker-python-sdk/blame/c8d1428b1176e020c5225161d0426d3dc8853289/src/sagemaker/fw_utils.py#L453-L464
```
if (
settings is not None
and …
```

fix: Create workflow module scoped sagemaker_session to resolve test race condition

---

tests/integ/test_experiments_analytics.py

Doesn't appear to be an sdk issue. Search is returning 0 results. Thus the test is failing.

fix: skip test_experiment_analytics to unblock release

---

tests/integ/test_pytorch.py

* Remove test for deprecated feature that is blocking release.
Fails like: 
```
E           botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateEndpoint operation: AcceleratorType is no longer a supported feature. Please see https://aws.amazon.com/machine-learning/elastic-inference/faqs/ for more information.
``` …

fix: remove pytorch test for deprecated function

---

src/sagemaker/jumpstart/notebook_utils.py
tests/unit/sagemaker/jumpstart/test_notebook_utils.py

This change fixes the list models flaky unittests by making sure the mocks are set up correctly.

fix: JumpStart list models flaky tests

---

.github/workflows/codebuild-ci-health.yml
.github/workflows/codebuild-ci.yml
README.rst
setup.py

Adding UTs for py311 and official support
run with pytest 

change: update readme, trigger p311 tests

---

tests/integ/test_mxnet.py
tests/integ/test_tfs.py
tests/unit/test_model_card.py

Failing tests due to ` AcceleratorType is no longer a supported feature. Please see https://aws.amazon.com/machine-learning/elastic-inference/faqs/` 

fix: remove failing deprecated tests from suite

---

src/sagemaker/jumpstart/estimator.py
tests/integ/sagemaker/jumpstart/estimator/test_jumpstart_estimator.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py

Attaching a `JumpStartEstimator` for a gated model results in the exception:
```ValueError: Need to define 'accept_eula'='true' within Environment. Model 'huggingface-llm-gemma-2b-instruct' requires accepting end-user license agreement (EULA). See https://jumpstart-cache-prod-us-west-2.s3.us-west-2.amazonaws.com/fmhMetadata/terms/gemmaTerms.txt for terms of use.```
This issue is now fixed so that an exception is not thrown.
Unit, integ tests added
Manual test
By …

fix: attach jumpstart estimator for gated model

---

src/sagemaker/serve/save_retrive/version_1_0_0/save/utils.py

- Switch to subprocess in ModelBuilder when capturing dependencies

[Fix] Switch to subprocess in ModelBuilder when capturing dependencies

---

src/sagemaker/session.py
tests/unit/test_session.py

SAV-1014
Unit tests/integ tests

fix: Remove space specific business logic from Python SDK function to fetch execution role

---

.github/workflows/codebuild-ci.yml

Change: add collab-check and wait-for-approval to PR Check workflow

---

src/sagemaker/jumpstart/constants.py

Have confirmed the  bucket jumpstart-cache-prod-ap-northeast-3 and jumpstart-private-cache-prod-ap-northeast-3 exist with models stored.

change: add kix to launched regions

---

src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/test_utils.py

Fixes a typo in JumpStart manifest enum, and refine the logic to retrieve manifest files.

fix: typo in jumpstart manifest and refine tests

---

.github/workflows/codebuild-ci.yml

* migrate integ-tests to GitHub Actions trigger
* add new `integ-tests` job to `codebuild-ci.yml`
* testing in personal fork: https://github.com/benieric/sagemaker-python-sdk/actions/runs/8653491635/job/23728767218?pr=25
* see `integ-tests` job

change: add integ-tests to codebuild-ci.yml

---

tests/integ/sagemaker/serve/test_serve_mlflow_pytorch_flavor_happy.py
tests/integ/sagemaker/serve/test_serve_mlflow_xgboost_flavor_happy.py

- Disable modelbuilder mlflow local integ tests
- Local container integ test is flaky since they all bind to the same hosts and cannot be run in parallel idempotently.

[fix] disable modelbuilder mlflow local integ tests

---

tests/integ/sagemaker/serve/test_serve_js_happy.py

ModelBuilder JS Gated model test failed because container failed to start, see below error.
```
torch.cuda.OutOfMemoryError: CUDA out of memory. 
Tried to allocate 172.00 MiB. GPU 0 has a total capacty of 
15.78 GiB of which 37.75 MiB is free. Process 11089 has 15.74 GiB memory in use. Of the allocated memory 14.06 GiB is allocated by PyTorch, and 470.23 MiB is reserved by PyTorch but unallocated.
If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Revert to using stable JS non-gated model to unblock. 
tox -e py39 -- tests/integ/sagemaker/serve/test_serve_js_happy.py
``` …
```

Flaky test

---

src/sagemaker/estimator.py
tests/unit/sagemaker/huggingface/test_estimator.py
tests/unit/sagemaker/tensorflow/test_estimator.py
tests/unit/sagemaker/training_compiler/test_huggingface_pytorch_compiler.py
tests/unit/sagemaker/training_compiler/test_huggingface_tensorflow_compiler.py
tests/unit/sagemaker/training_compiler/test_pytorch_compiler.py
tests/unit/sagemaker/training_compiler/test_tensorflow_compiler.py
tests/unit/test_chainer.py
tests/unit/test_estimator.py
tests/unit/test_mxnet.py
tests/unit/test_pytorch.py
tests/unit/test_rl.py
tests/unit/test_sklearn.py
tests/unit/test_xgboost.py

A sagemaker config file would override this parameter if it was True in the config but False in the Estimator parameters.
Closes #4542
*Issue #, if available:* #4542
*Description of changes:* Forward the parameter to boto.
*Testing done:*  Manually verified via the logs. I'm not sure where to add a unit test for this. If you can point me to the right spot, happy to add.

fix: forward network_isolation parameter to Estimators when False

---

.github/workflows/codebuild-ci.yml

Collaborator check workflow does not work when member is part of team. e.g., `xyz` is part of `@aws/abc-team` but shows as not a collaborator.
Adding correct token with right permissions to check for collaborator who is part of a GitHub team.

fix: Update Collaborator Check workflow to check for users which are part of collaborator team

---

src/sagemaker/feature_store/dataset_builder.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4569
*Description of changes:* Use `rstrip` to remove trailing slash when uploading the temp file to s3 during dataset creation.
*Testing done:* Installed the modified version and ran the code that was previously failing

fix: remove trailing slash when uploading to S3 with dataset_builder.to_csv_file

---

src/sagemaker/serve/builder/model_builder.py

Add supported hugging face task types for schema builder omission/automatic inference in the ModelBuilder interface. 

Documentation: Add supported task types to schema builder omission

---

requirements/extras/test_requirements.txt
tox.ini

change: bump apache-airflow version to 2.8.4

---

src/sagemaker/base_serializers.py
src/sagemaker/serve/builder/schema_builder.py
src/sagemaker/serve/builder/transformers_builder.py
tests/integ/sagemaker/serve/test_schema_builder.py

Add back automatic speech recognition task serialization (This feature is in BETA). Ensure latest version of transformers is picked in transformers builder. This allows the latest whisper models to be detected.
E.g.
`Detected 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-inference:2.1.0-transformers4.37.0-cpu-py310-ubuntu22.04. Proceeding with the the deployment.` …

fix: Add back serialization for automatic speech recognition

---

src/sagemaker/image_uri_config/djl-neuronx.json

This is updating our latest version in image_uri_config, so while our users retrieve the image using the latest version in sagemaker-python-sdk, it would work.

change: bump djl-inference 0.27.0 neuronx sdk to 2.18.1

---

src/sagemaker/jumpstart/constants.py

change: add DXB and CGK to Jumpstart regions

---

src/sagemaker/estimator.py
src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/estimator.py
src/sagemaker/jumpstart/types.py
src/sagemaker/session.py
tests/unit/test_estimator.py
tests/unit/test_session.py

*Description of changes:* Added field for Estimator for new ABAC feature for Sagemaker Training
*Testing done:* Manually tested + added unit tests.

feature: support session tag chaining for training job

---

src/sagemaker/jumpstart/enums.py
src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/estimator.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/session_utils.py
src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/predictor.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/test_predictor.py
tests/unit/sagemaker/jumpstart/test_session_utils.py
tests/unit/sagemaker/jumpstart/test_utils.py

*Description of changes:* This PR updates the JumpStart Model and Estimator to tag resource with config names, and also supports extracting config names from existing resources and gets passed into follow-up actions.

feat: tag JumpStart resource with config names

---

src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/serve/builder/jumpstart_builder.py
src/sagemaker/utils.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/sagemaker/jumpstart/utils.py
tests/unit/sagemaker/serve/builder/test_js_builder.py

CX with PySDK: Modelbuilder
* Init 
```
model="meta-textgeneration-llama-2-7b-f",
schema_builder=SchemaBuilder(sample_input, sample_output),
)
```
* list api
```
model_builder.list_deployment_configs()
```
* output
```
[{'DeploymentConfigName': 'deepspeed',
'DeploymentArgs': {'ImageUri': '763104351884.dkr.ecr.us-west-2.amazonaws.com/djl-inference:0.27.0-deepspeed0.12.6-cu121',
'ModelData': {'S3DataSource': {'S3Uri': 's3://jumpstart-private-cache-prod-us-west-2/meta-textgeneration/meta-textgeneration-llama-2-7b-f/artifacts/inference-prepack/v1.1.0/',
'S3DataType': 'S3Prefix',
'CompressionType': 'None'}},
'Environment': {'SAGEMAKER_PROGRAM': 'inference.py',
'ENDPOINT_SERVER_TIMEOUT': '3600',
'MODEL_CACHE_ROOT': …
```

ModelBuilder: Add functionalities to get and set deployment config.

---

src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/predictor.py
tests/integ/sagemaker/jumpstart/estimator/test_jumpstart_estimator.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/utils.py

This change fixes the default config name population in jumpStart model class.
Expected usage:
```
model_id = "meta-textgeneration-llama-2-7b-f"
model = JumpStartModel(
model_id=model_id,
model_version="*",
role=sagemaker_session.get_caller_identity_arn(),
sagemaker_session=sagemaker_session,
)
assert model.config_name == "deepspeed"
```

fix: populate default config name to model

---

src/sagemaker/jumpstart/model.py

Fixing bug related to `get_instance_rate_per_hour` api.
As per https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-price-list-query-api.html
This policy is needed for `get_instance_rate_per_hour` to work.
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"pricing:DescribeServices",
"pricing:GetAttributeValues",
"pricing:GetProducts"
],
"Resource": [
"*"
]
}
]
}
```
- [x ] I have read the …

Fix fetch instance rate bug

---

src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/model.py
tests/unit/sagemaker/jumpstart/model/test_model.py

This change made the `set_deployment_config` interface to require two mandatory input: config_name and instance_type, since these two combination will be deterministic for a config. This change also removes the possibility to unset a config, since now both config name and instance_type is required field.

chore: require config name and instance type in set_deployment_config

---

src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/serve/builder/jumpstart_builder.py
src/sagemaker/utils.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/test_types.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/sagemaker/jumpstart/utils.py
tests/unit/sagemaker/serve/builder/test_js_builder.py
tests/unit/test_utils.py

* Init Deployment config outside Model init
* ModelBuilder set deployment to accept both deployment config name and instance type
* Display deployment config benchmark metrics to display multiple raw.
Unit tests and Notebooks E2E
```
jumpstart_model = JumpStartModel(model_id="meta-textgeneration-llama-2-7b-f")
jumpstart_model.list_deployment_configs()
```
Output
```
[{'DeploymentConfigName': 'lmi',
'DeploymentArgs': {'ImageUri': '763104351884.dkr.ecr.us-west-2.amazonaws.com/djl-inference:0.27.0-deepspeed0.12.6-cu121',
'ModelData': {'S3DataSource': {'S3Uri': 's3://jumpstart-private-cache-prod-us-west-2/meta-textgeneration/meta-textgeneration-llama-2-7b-f/artifacts/inference-prepack/v2.0.0/',
'S3DataType': 'S3Prefix', …
```

Deployment Configs - Follow-ups

---

src/sagemaker/base_deserializers.py
tests/unit/sagemaker/deserializers/test_deserializers.py

Setting the NumpyDeserializer allow_pickle default value to False. 
All Base predictor class will now require an instantiation of the NumpyDeserializer with the allow_pickle=True explicitly
if not error message "Please set the param allow_pickle=True to deserialize pickle objects" will be thrown. 
Local testing with UTs

feature: set default allow_pickle param to False

---

src/sagemaker/utils.py
tests/unit/test_utils.py

*Description of changes:* We need a different separator when flatten the dict and merge. This is because `ml.p4d.24xlarge` got treated as nested dict with the original separator `.`.

fix: use different separator to flatten dict

---

src/sagemaker/jumpstart/enums.py
src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/estimator.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/session_utils.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/predictor.py
src/sagemaker/utils.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/model/test_model.py
tests/unit/sagemaker/jumpstart/test_predictor.py
tests/unit/sagemaker/jumpstart/test_session_utils.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/test_utils.py

This PR is a follow-up of the tagging mechanism for configs. We will tag separately for inference_config and training_config, so that the resources are identified clearly with their configs.
Together in this change, addressed a comment to improve on the deep_override_merge dict method, so that we don't rely on any string separator which could conflict with metadata fields. …

Use separate tags for inference and training configs

---

src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/types.py
tests/integ/sagemaker/jumpstart/constants.py
tests/integ/sagemaker/jumpstart/estimator/test_jumpstart_estimator.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/test_types.py

The current mainline code is seeing an error parsing the new config metadata. We will bump the min_sdk_version for these models, but raising this PR to fix this error.

Fix:invalid component error with new metadata

---

src/sagemaker/jumpstart/notebook_utils.py
src/sagemaker/jumpstart/payload_utils.py
tests/unit/sagemaker/jumpstart/test_notebook_utils.py

1. Some of the JumpStart notebook_utils tests are skipped due to flakiness, and one of the test is failing consistently. This change fixes these tests.
2. Together, update the `_construct_payload` internal function to accept model_type, this is used by Margaret team internally.

chore: update skipped flaky tests

---

src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/factory/estimator.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/types.py
tests/integ/sagemaker/jumpstart/constants.py
tests/integ/sagemaker/jumpstart/estimator/test_jumpstart_estimator.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py
tests/unit/sagemaker/jumpstart/test_notebook_utils.py
tests/unit/sagemaker/jumpstart/test_types.py

This change introduces supported inference config and supported incremental training config, and choose them correspondingly from the training config being used.

Add supported inference and incremental training configs

---

src/sagemaker/session.py
src/sagemaker/user_agent.py
tests/unit/test_session.py
tests/unit/test_user_agent.py

This PR fixes an issue with User-Agent header of SageMaker Python SDK which got introduced with the breaking change in Boto [v1.27.0](https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#L2276) released on July 3, 2023 where a [new UserAgent format 2.0](https://github.com/boto/botocore/pull/2977) was introduced and downstream use or direct modification of the original User-Agent header from boto was [removed](https://github.com/boto/botocore/pull/2977/files#diff-5060d2324ee91a83dabd55d229d545c2900d28da7b07b7eb70e4dd01ae52a108R1011). Consequently, SageMaker Python SDK started to fail to log its specific UserAgent string in the logs.
In order to fix this issue with the UserAgent logging, we would be making use of `user_agent_extra` …

fix: Fix UserAgent logging in Python SDK

---

src/sagemaker/serve/builder/model_builder.py

Other integration tests are failing du to race condition. This is caused by use of single `sagemaker_session` object for all integration tests and ModelBuilder mutate the object.
Note: There is no need to mutate the session as it's not needed. `model_path` is passed directly to `s3_downloader`.
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/serve/model_server/djl_serving/prepare.py#L228
See: https://github.com/aws/sagemaker-python-sdk/actions/runs/9010187570/job/24755797329
Notebook
```
model="bigscience/bloom-7b1",
schema_builder=SchemaBuilder(sample_input, sample_output),
model_path="/home/ec2-user/SageMaker/LoadTestResources/bloom-7b1",
mode=Mode.LOCAL_CONTAINER
) …
```

fix: model builder race condition on sagemaker session

---

src/sagemaker/image_uri_config/huggingface-llm-neuronx.json
src/sagemaker/image_uri_config/huggingface-llm.json
src/sagemaker/image_uri_config/huggingface-neuronx.json
src/sagemaker/jumpstart/utils.py
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

1. https://github.com/awslabs/llm-hosting-container/pull/73
2. https://github.com/awslabs/llm-hosting-container/pull/74
3. https://github.com/aws/deep-learning-containers/pull/3823
4. https://github.com/aws/deep-learning-containers/pull/3824
Release the above 4 updates to Huggingface TGI images.

chore: add new images for HF TGI release

---

tests/integ/sagemaker/conftest.py

change: add debug logs to workflow container dist creation. The change will help debug the flakiness in workflow/remote decorator integ tests.
N/A

change: add debug logs to workflow container dist creation

---

src/sagemaker/serve/builder/transformers_builder.py
tests/unit/sagemaker/serve/builder/test_transformers_builder.py

Don't override customer provided image_uri since it blocks customers from testing latest images. 
1. Change check to set uri only if not set.
2. Fix instance type being logged. 
1. Added UT

Fix: Image URI should take precedence for HF models

---

src/sagemaker/image_uris.py

Add tei according to https://github.com/aws/sagemaker-python-sdk/pull/4375
This PR is a supplement for https://github.com/aws/sagemaker-python-sdk/pull/4681
- [x ] I have added tests that prove my fix is effective or that my feature works (if appropriate) …

chore: cover tei with image_uris.retrieve API

---

src/sagemaker/serve/builder/jumpstart_builder.py
src/sagemaker/serve/mode/local_container_mode.py
tests/integ/sagemaker/serve/test_serve_js_happy.py

Fix: JS Model with non-TGI/non-DJL deployment failure
Notebook
```
model="huggingface-sentencesimilarity-bge-m3",
schema_builder=SchemaBuilder(sample_input, sample_output),
)
model = model_builder.build()
predictor = model.deploy()
```
```
INFO:sagemaker:2024-05-16T06:05:27,302 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 9161
INFO:sagemaker:2024-05-16T06:05:27,302 [WARN ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerLifeCycle - attachIOStreams() threadName=W-model-1
INFO:sagemaker:2024-05-16T06:05:29,865 [INFO ] pool-2-thread-3 ACCESS_LOG - /169.254.178.2:46500 "GET /ping HTTP/1.1" 200 0
INFO:sagemaker:2024-05-16T06:05:34,865 [INFO ] pool-2-thread-3 …
```

Fix: JS Model with non-TGI/non-DJL deployment failure

---

src/sagemaker/serve/builder/transformers_builder.py
tests/integ/sagemaker/serve/test_serve_transformers.py
tests/unit/sagemaker/serve/builder/test_transformers_builder.py

In Transformers builder if image_uri is provided, directly initialize the pySDK model.
Else fetch HF framework version etc to create the Model and then fetch latest image. 
If we cannot set the image_uri, throw an error to customer with message to override image if possible. 
1. Add UT

Fix: Add Image URI overrides for transformers models

---

src/sagemaker/fw_utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/test_fw_utils.py
tests/unit/test_pytorch.py

The `pytorchddp` and `smdistributed` launchers are very similar and causing confusion for customers over which one to use. To simplify while still supporting both config options, this PR internally converts configs which use `pytorchddp` to use `smdistributed` instead.
I've tested that the unit tests pass, and tested a few jobs with the change. I tried running the integration tests locally but it seems like the setup is non-trivial so I'm hoping to just run them using the review pipeline.

Convert pytorchddp distribution to smdistributed distribution

---

src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/utils.py
tests/unit/sagemaker/jumpstart/constants.py
tests/unit/sagemaker/jumpstart/test_types.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/sagemaker/jumpstart/utils.py

```
jumpstart_model = JumpStartModel(model_id="meta-textgeneration-llama-3-8b")
jumpstart_model.list_deployment_configs()
[{'DeploymentConfigName': 'lmi-accelerated',
'DeploymentArgs': {'ImageUri': '763104351884.dkr.ecr.us-west-2.amazonaws.com/djl-inference:0.27.0-deepspeed0.12.6-cu121',
'ModelData': {'S3DataSource': {'S3Uri': 's3://jumpstart-private-cache-prod-us-west-2/meta-textgeneration/meta-textgeneration-llama-3-8b/artifacts/inference-prepack/v1.0.0/',
'S3DataType': 'S3Prefix',
'CompressionType': 'None'}},
'Environment': {'SAGEMAKER_PROGRAM': 'inference.py',
'ENDPOINT_SERVER_TIMEOUT': '3600',
'MODEL_CACHE_ROOT': '/opt/ml/model',
'SAGEMAKER_ENV': '1',
'HF_MODEL_ID': '/opt/ml/model',
'SERVING_LOAD_MODELS': 'test::MPI=/opt/ml/model', …
```

fix benchmark feature read-only apis

---

.github/workflows/codebuild-ci.yml

Change the project name in workflow file dynamic so staging repo would use staging codebuild project
Will monitor the pr check logs

Change: make project name in workflow files dynamic

---

src/sagemaker/serve/builder/jumpstart_builder.py

Update: ModelBuilder to support display with filter.
```
model="meta-textgeneration-llama-3-8b",
schema_builder=SchemaBuilder(sample_input, sample_output),
)
model_builder.display_benchmark_metrics()
| Instance Type            | Config Name     |   Concurrent Users |   Latency for each user (TTFT in ms) |   Throughput per user (token/seconds) |   Instance Rate (USD/Hrs) |
|:-------------------------|:----------------|-------------------:|-------------------------------------:|--------------------------------------:|--------------------------:|
| ml.g5.12xlarge (Default) | tgi             |                  1 |                                13.40 |                                    72 | …
```

ModelBuilder to support display with filter.

---

requirements/extras/test_requirements.txt

change: bump requests from 2.31.0 to 2.32.2 in /requirements/extras

---

src/sagemaker/jumpstart/factory/estimator.py
tests/unit/sagemaker/jumpstart/estimator/test_estimator.py

https://github.com/aws/amazon-sagemaker-examples/issues/4666
Fixes issue with not using user-supplied instance type for `Estimator.deploy`
Unit test added

fix: estimator.deploy not respecting instance type

---

src/sagemaker/serve/builder/djl_builder.py
src/sagemaker/serve/builder/tei_builder.py
src/sagemaker/serve/builder/tgi_builder.py
src/sagemaker/serve/model_server/djl_serving/server.py
src/sagemaker/serve/model_server/tei/server.py
src/sagemaker/serve/model_server/tgi/server.py
tests/unit/sagemaker/serve/model_server/tei/test_server.py

Added support for customers to use HF_HOME. Address Future warning by Adding HF_HOME to env variables. Older variables will be deprecated once all customers move to v5 version of Transformers. 
```
/opt/conda/lib/python3.10/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
warnings.warn(
```
Integr tests run locally
By submitting this pull request, …

feature: add support for HF_HOME

---

src/sagemaker/remote_function/client.py
src/sagemaker/telemetry/constants.py
src/sagemaker/telemetry/telemetry_logging.py
tests/unit/sagemaker/remote_function/test_client.py
tests/unit/sagemaker/telemetry/test_telemetry_logging.py

Enable telemetry logging for Remote function 
* We need to retrieve the `sagemaker_session` from the [kwargs](https://github.com/knikure/sagemaker-python-sdk/blob/382fde11a534b9848176994c16b15c1872acc92a/src/sagemaker/remote_function/client.py#L80) of remote function since it is not a class function.
Tested on the Example notebook [here](https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-remote-function/quick_start/quick_start.ipynb).
By submitting …

change: Enable telemetry logging for Remote function

---

tests/integ/sagemaker/jumpstart/estimator/test_jumpstart_estimator.py

chore: use ml.g5.2xlarge for integ test (test_gated_model_training_v2)

chore: use ml.g5.2xlarge for integ test

---

tox.ini

Update tox.ini to use 2.9.2 apache airflow constraints file

fix: Update tox.ini

---

src/sagemaker/jumpstart/hub/hub.py

for Python3.8 list_models() function was failing with an error
```
in list_models
**{
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```
this PR is to fix the compatibility issue with Python3.8
Rootcause: 
In Python 3.8 and earlier versions, the bitwise OR operator (|) is not overloaded to work with dictionaries.
fixing it with an alternative compatible code for PySDK
End to end test with example notebook using Python3.8
By submitting this pull …

fix: list_models() for python3.8

---

src/sagemaker/estimator.py

Improve docstrings for estimator tags giving clarity to users that the estimator tags won't be propagated to Models/Endpoints via `deploy` method. The deploy method takes in a seperate tags parameter for the same.
N/A

fix: Improve docstrings for estimator tags

---

src/sagemaker/serve/builder/model_builder.py
tests/unit/sagemaker/serve/builder/test_model_builder.py

Fix check to allow for server override and inf spec 
Update validation
Added UT

fix: allow for inf spec and server override to be passed

---

src/sagemaker/model_card/helpers.py

*Description of changes: Fix for #4772

Fix: Adding application/octet-stream to content type #4772

---

tests/unit/sagemaker/image_uris/expected_uris.py

add support for new regions

---

src/sagemaker/image_uri_config/huggingface-llm.json
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

Add Huggingface TGI 2.2.0 image configs.

chore: add huggingface TGI 2.2.0 config

---

src/sagemaker/image_uri_config/huggingface-llm.json
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

This change fixes the TGI 2.2.0 image uri that was introduced in the previous commit.

fix: image uri in TGI 2.2.0 image

---

tests/integ/test_sklearn.py
tests/integ/test_xgboost.py

* Pinning framework versions in serverless inference tests to last version that supports serverless inference.
* New [xgboost](https://github.com/aws/sagemaker-xgboost-container) and [sklearn](https://github.com/aws/sagemaker-scikit-learn-container) image not compatible for serverless inference

chore: pin framework version in serverless inference tests

---

tests/integ/test_byo_estimator.py

*Description of changes: Fixed cpu isntance type for the estimator register test

Fixed cpu isntance type for the estimator register test

---

src/sagemaker/serve/builder/tei_builder.py
src/sagemaker/serve/builder/tgi_builder.py
src/sagemaker/serve/builder/transformers_builder.py
src/sagemaker/serve/model_server/tei/server.py
src/sagemaker/serve/model_server/tgi/server.py
tests/unit/sagemaker/serve/builder/test_djl_builder.py
tests/unit/sagemaker/serve/builder/test_tgi_builder.py
tests/unit/sagemaker/serve/builder/test_transformers_builder.py
tests/unit/sagemaker/serve/model_server/tei/test_server.py
tests/unit/sagemaker/serve/model_server/tgi/test_tgi_serving.py

1. For TGI, TEI, Transformers builder, if not optimized & if overwritting, upload the model artifacts to customer's S3 location
2. Prune deprecated TRANSFORMERS_CACHE env var from the builder code
3. Switch deprecated TRANSFORMERS_OFFLINE env var to HF_HUB_OFFLINE env var
1. Add UT coverage for TGI, TEI, Transformers builder to verify that on overwrite to SAGEMAKER_ENDPOINT mode that S3 upload is set to True
2. Add UT coverage for TGI, TEI, Transformers builder to verify that when going DIRECTLY to SAGEMAKER_ENDPOINT mode that S3 upload is not enabled
3. Add UT coverage for TGI, TEI, Transformers builder to verify that when the model has been optimized that S3 upload is not enabled
4. Add new UT suite for TGI …

fix: Enable S3 Upload on local container -> sagemaker endpoint overwrite for TGI, TEI, MMS

---

tests/data/marketplace/iris/scoring_logic.py

The first change was to print only the error type rather than the entire stack trace as it may reveal the application as well as any internal components it relies on. 
The second change escape the user input before returning it to avoid a cross-site scripting vulnerability.
Tested changes in my own fork and CodeQL recognizes them as fixes.
- [ x] I …

fix: avoided printing stack trace and escaped input

---

.github/workflows/security-monitoring.yml

Created a workflow that calls the GitHub RESTAPI to list out the alerts in the repository, checks if any exist, and sends either a value of 1 or 0 depending on if any are found or not.
Tested in my fork and it successfully sends the metrics according to if there are security vuln or not.
- [x ] I certify that the changes I am introducing will be backward …

feat: implemented security-monitoring to send metrics to CW #1510

---

.github/workflows/codeql.yml
.github/workflows/security-monitoring.yml

changed times for codeQL to run at 8:30 am PST and security-monitoring to run on 9:00 am PST
- [ x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in …

aligned UTC times with PST

---

src/sagemaker/utils.py
tests/unit/test_utils.py

When a `trn1` instance family is used, the PySDK would automatically use volume size argument when creating the endpoint config. However, this instance family does not support attaching an ebs volume, hence volume size argument throws a service exception. This PR updates the `volume_size_supported` function to correctly identify `trn1` instance types as not supporting volume size. 
Unit tests added.  …

fix: trn1 instance family does not support volume size

---

tests/data/tensorflow_mnist/mnist_v2.py

There is a recent update from keras 3.5.0, which adds a check to its save model method that requires a file extension with `.keras` or `.h5`. This PR is fixing the integration test by adding `.keras` in the file path.

fix: add keras extension in the file path of integ test

---

src/sagemaker/jumpstart/artifacts/metric_definitions.py
src/sagemaker/jumpstart/factory/model.py
src/sagemaker/jumpstart/hub/parser_utils.py
src/sagemaker/jumpstart/types.py
src/sagemaker/jumpstart/utils.py
tests/unit/sagemaker/jumpstart/hub/test_utils.py

- Model Deployment and training failed for curatedHub customers last week for models with alt configs. 
- Reverting back on this commit fixed the issue locally so investigated this commit for fixing the issue https://github.com/aws/sagemaker-python-sdk/commit/ba7e6a9b3fa6d3b8f9c104d024acec518605e96d
- Notebook testing
- Unit tests

fix: alt configs model deployment and training issues

---

tests/data/tensorflow_mnist/mnist_v2.py
tests/integ/test_tf.py
tests/integ/test_tuner.py

Some integration tests are failing because of an upstream bug from Tensorflow 2.16: https://github.com/tensorflow/io/issues/2039. Skipping these tests to fix CI.

fix: disable failing integration tests

---

src/sagemaker/jumpstart/cache.py
src/sagemaker/jumpstart/hub/utils.py

- Fixing Cross Account private hub model fine-tuning 
- Current Unit tests/ integ tests
- Notebook tests: PrivateHub Model Deployment and Training, PrivateHub Cross account model deployment and training

fix: cross account private hub model fine-tuning

---

.pylintrc
src/sagemaker/algorithm.py
src/sagemaker/base_predictor.py
src/sagemaker/estimator.py
src/sagemaker/local/entities.py
src/sagemaker/session.py

1. Updated pydocs for methods to include section on what all exceptions can be thrown and when.
2. Linked troubleshooting document in create/ update training, create processing and create/ update endpoint.
3. Improved some exception messages thrown from the SDK.
*Testing done:* Installed tar file on studio and executed example notebooks.

change: Add troubleshooting links to exceptions

---

src/sagemaker/image_uri_config/huggingface-llm-neuronx.json
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

Add the new HF Neuronx 0.0.24 image to image uri configuration.

chore: add HF LLM neuronx 0.0.24 image

---

src/sagemaker/serve/builder/djl_builder.py
src/sagemaker/serve/builder/jumpstart_builder.py
src/sagemaker/serve/builder/model_builder.py
src/sagemaker/serve/builder/tei_builder.py
src/sagemaker/serve/builder/tf_serving_builder.py
src/sagemaker/serve/builder/tgi_builder.py
src/sagemaker/serve/builder/transformers_builder.py
tests/unit/sagemaker/serve/builder/test_djl_builder.py
tests/unit/sagemaker/serve/builder/test_model_builder.py
tests/unit/sagemaker/serve/builder/test_tei_builder.py
tests/unit/sagemaker/serve/builder/test_tensorflow_serving_builder.py
tests/unit/sagemaker/serve/builder/test_tgi_builder.py

- When passing name, the name should be propagated from ModelBuilder to the Model created. It currently does not
```
mode=Mode.SAGEMAKER_ENDPOINT,
schema_builder=sklearn_schema_builder,
role_arn="arn:aws:iam::337323248444:role/service-role/AmazonSageMaker-ExecutionRole-20230412T172825",
model_metadata={"MLFLOW_MODEL_PATH": source_path},
name="testing-name-propagation"
)
```
- Update all builder variants to propagate name to the Model
- Updated Unit Testing
- Verified Integration Testing With Fix
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what …

fix: pass name from modelbuilder constructor to created model

---

src/sagemaker/image_uri_config/clarify.json

*Description of changes:* add Clarify image URIs for us-isof regions (us-isof-south-1, us-isof-east-1)

feature: add Clarify image URIs for us-isof

---

.pylintrc
src/sagemaker/local/image.py
src/sagemaker/local/utils.py
src/sagemaker/workflow/_repack_model.py
src/sagemaker/workflow/_utils.py
tests/data/_repack_model.py
tests/integ/sagemaker/workflow/test_retry.py
tests/unit/sagemaker/local/test_local_image.py
tests/unit/sagemaker/local/test_local_utils.py
tests/unit/sagemaker/workflow/test_step_collections.py
tests/unit/test_chainer.py

Closes https://github.com/aws/sagemaker-python-sdk/issues/4534 https://github.com/aws/sagemaker-python-sdk/issues/3028
Issue #, if available: https://github.com/aws/sagemaker-python-sdk/issues/4534
* From this PR: https://github.com/aws/sagemaker-python-sdk/pull/4544

fix: remove deprecated distutils

---

src/sagemaker/jumpstart/cache.py
src/sagemaker/jumpstart/exceptions.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/utils.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/jumpstart/test_cache.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/test_utils.py

- Improve eula logging so that url gets regionalized correctly for ADC regions. 
- Add suggestion to try another AWS region when the specified model is not found in the manifest, since there's a chance it could've been removed only for that region but available in other regions. 
- Unit tests added

change: improve logging and exception messages

---

src/sagemaker/huggingface/model.py

Pass kwargs in `HuggingFaceModel.deploy()` to its base class call `super(HuggingFaceModel, self).deploy()`. This will pass several missing arguments like `inference_component_name`.

Fix: Pass kwargs in HuggingFaceModel.deploy() to the base class call

---

pyproject.toml
src/sagemaker/estimator.py
src/sagemaker/mlflow/forward_sagemaker_metrics.py
tests/unit/sagemaker/mlflow/test_forward_sagemaker_metrics.py
tests/unit/test_estimator.py

The goal of this feature is to integrate SageMaker Jumpstart (which runs in network isolation mode) with SageMaker MLflow. Specifically, we need to provide the option to forward metrics from a Jumpstart training job to a SageMaker [MLflow tracking server](https://mlflow.org/docs/latest/tracking/server.html#:~:text=MLflow%20tracking%20server%20is%20a,endpoints%20for%20tracking%20runs%2Fexperiments.) (so the metrics can be viewed and tracked within experiments).
```log_sagemaker_job_to_mlflow``` is a callable method only requiring the training_job_name as input.
Look into adding documentation such that user can call this method in-case of any failures during `fit()`
Run through modified [jumpstart …

Feat: Support logging of MLFlow metrics when network_isolation mode is enabled

---

pyproject.toml

This reverts commit 8709d9eaea436817404487a06923922f64a09074.

Revert "update cloudpickle version to >=2.2.1 in pyproject.toml (#4899)"

---

src/sagemaker/serve/utils/conda_in_process.yml
src/sagemaker/serve/utils/in_process_requirements.txt

charset-normalizer is misplet in the
requirements.txt files
run tox locally for UTs
- [ x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/m …

fix: fixing typo in dependency setup

---

src/sagemaker/pipeline.py
tests/integ/test_inference_pipeline.py
tests/unit/test_pipeline_model.py

Added register step in PipelineModel to return ModelPackage object.
Have added integration tests

Fix: Returning ModelPackage object on register of PipelineModel

---

.github/PULL_REQUEST_TEMPLATE.md

Added warning to spell check dependencies added
and ensure they exist in PyPi
- [x ] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/ …

fix: modified pull request template

---

tests/unit/sagemaker/image_uris/test_graviton.py

* fix image uris test to consider container version
* `tox -e py310 -- -vv -s tests/unit/sagemaker/image_uris/test_graviton.py::test_graviton_framework_uris `

Fix: image_uris graviton image uri

---

CONTRIBUTING.md
src/sagemaker/image_uri_config/huggingface-llm.json
tests/unit/sagemaker/image_uris/test_huggingface_llm.py

This reverts commit 0ea59948daeed1f3b12d4269db637852a17ee6e4.

Revert "change: add TGI 2.4.0 image uri (#4922)"

---

src/sagemaker/jumpstart/model.py
src/sagemaker/jumpstart/utils.py
src/sagemaker/model.py
src/sagemaker/serve/builder/model_builder.py
tests/integ/sagemaker/serve/test_serve_js_deep_unit_tests.py
tests/unit/sagemaker/jumpstart/test_utils.py
tests/unit/sagemaker/model/test_model.py
tests/unit/sagemaker/serve/builder/test_js_builder.py

*Description of changes:*  
- Allow deploying JumpStart models w/gated draft models through ModelBuilder
- Fixing regression on Fast Model Loading on GoldFinch
- Fix compilation and quantization of Llama 3.1 models
*Testing done:* E2E notebook testing, UTs and integ tests.

Fix: ModelBuilder deployment & optimization of JumpStart llama-3.1 models

---

src/sagemaker/serve/builder/model_builder.py
tests/unit/sagemaker/serve/builder/test_model_builder.py

Updating Inference Optimization Validations

---

src/sagemaker/serve/model_server/multi_model_server/inference.py
src/sagemaker/serve/model_server/torchserve/inference.py
src/sagemaker/serve/model_server/torchserve/xgboost_inference.py

https://github.com/aws/sagemaker-python-sdk/issues/4959
Some model servers (MMS in specific) decode the request from bytes ahead of time if the content type of the request is in a known format.
In these scenarios, we should honor that logic. If the request by the time it gets to our decoder is no longer in a bytes / bytestream format then propagate it as is.
We should not get into the business of re-encoding it back into a bytes or bytestream format
In the first iteration: https://github.com/aws/sagemaker-python-sdk/pull/4960 a regression was introduced. Fixed that here
```
tests/integ/sagemaker/serve/test_serve_mlflow_pytorch_flavor_happy.py::test_happy_pytorch_sagemaker_endpoint_with_torch_serve PASSED
```
_Put an `x` in …

Fix: Account for requests that have already been decoded by model server

---

pyproject.toml

* [Twine](https://github.com/pypa/twine/commit/0605ef02a6a5ffa8bddab6816f7ff3e0db9a442f) does not yet support core-metadata-version 2.4 which is new default for [hatchling](https://github.com/pypa/hatch/issues/1856).  Pinning to unblock 
```
root@b3e99f464864:/sagemaker-python-sdk# python3 -m twine check --strict dist/*
Checking dist/sagemaker-2.237.4.dev0-py3-none-any.whl: PASSED
Checking dist/sagemaker-2.237.4.dev0.tar.gz: PASSED
root@b3e99f464864:/sagemaker-python-sdk# git diff
diff --git a/pyproject.toml b/pyproject.toml
index 21eb1850..7711249c 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -73,6 +73,7 @@ pattern = "(?P<version>.+)"
[tool.hatch.metadata.hooks.custom]
[tool.hatch.build.targets.wheel] …
```

fix: pin metadata-version to 2.3

---

doc/overview.rst

* Transform job supports tag for default config but is missing in docs - https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/config/config_schema.py#L1032

change: add missing schema definition in docs

---

tests/integ/sagemaker/workflow/test_model_create_and_registration.py
tests/integ/sagemaker/workflow/test_model_steps.py
tests/integ/sagemaker/workflow/test_training_steps.py
tests/integ/test_transformer.py

* Skipping tests with TF >= 2.16 due to lack of s3 support - https://github.com/tensorflow/io/issues/2039

fix: skip TF tests for unsupported versions

---

src/sagemaker/modules/train/sm_recipes/utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/sagemaker/modules/train/sm_recipes/test_utils.py
tests/unit/test_pytorch.py

* Adding support for deepseek recipes in Pytorch Estimator and ModelTrainer

feat: Add support for deepseek recipes

---

src/sagemaker/image_uris.py

Add docstring of `base_framework_version` for `image_uris.retrieve()` to address https://github.com/aws/sagemaker-python-sdk/issues/4483

Add docstring for image_uris.retrieve()

---

tests/integ/sagemaker/serve/test_base_model_builder_deploy.py

Fix breaking integ test failures

Add cleanup logic to model builder integ tests for endpoints

---

src/sagemaker/estimator.py
src/sagemaker/fw_utils.py
src/sagemaker/huggingface/estimator.py
src/sagemaker/jumpstart/estimator.py
src/sagemaker/jumpstart/model.py
src/sagemaker/model.py
src/sagemaker/mxnet/estimator.py
src/sagemaker/pytorch/estimator.py
src/sagemaker/rl/estimator.py
src/sagemaker/sklearn/estimator.py
src/sagemaker/xgboost/estimator.py

According to https://github.com/aws/sagemaker-python-sdk/issues/3269, fix all docstrings about the s3 filename of tar.gz files.

Fix sourcedir.tar.gz filenames in docstrings

---

src/sagemaker/processing.py

Add type hint for ProcessingOutput according to https://github.com/aws/sagemaker-python-sdk/issues/3650

Add type hint for ProcessingOutput

---

src/sagemaker/feature_store/feature_group.py

Update docstring according to https://github.com/aws/sagemaker-python-sdk/issues/4762

Fix FeatureGroup docstring

---

doc/workflows/step_functions/index.rst

Update a new tutorial link for using SageMaker with Step Functions according to https://github.com/aws/sagemaker-python-sdk/issues/4864

Fix the workshop link for Step Functions

---

src/sagemaker/jumpstart/cache.py
src/sagemaker/jumpstart/hub/utils.py
tests/integ/sagemaker/jumpstart/private_hub/model/test_jumpstart_private_hub_model.py
tests/unit/sagemaker/jumpstart/hub/test_utils.py
tests/unit/sagemaker/jumpstart/test_cache.py

When instantiating a `JumpStartModel` or `JumpStartEstimator` with a `hub_name` param for private hubs, the `sagemaker_session` gets overridden to None in certain lower level function calls. This code change ensures that whenever the session is overridden to None, it takes on the default session value. Furthermore, unit tests and integ tests were added to cover this case.
Added unit tests and integ tests. Also ran sample notebook code (since that is where the issue was discovered)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …

fix: keep sagemaker_session from being overridden to None

---

doc/v2.rst
src/sagemaker/amazon/common.py
src/sagemaker/amazon/factorization_machines.py
src/sagemaker/amazon/kmeans.py
src/sagemaker/amazon/knn.py
src/sagemaker/amazon/lda.py
src/sagemaker/amazon/linear_learner.py
src/sagemaker/amazon/ntm.py
src/sagemaker/amazon/pca.py
src/sagemaker/amazon/randomcutforest.py
src/sagemaker/base_deserializers.py
src/sagemaker/base_serializers.py
src/sagemaker/cli/compatibility/v2/modifiers/serde.py
src/sagemaker/deserializers.py
src/sagemaker/serializers.py
tests/unit/sagemaker/cli/compatibility/v2/modifiers/test_serde.py
tests/unit/test_common.py

https://github.com/aws/sagemaker-python-sdk/issues/1994
Move RecordSerializer and RecordDeserializer from sagemaker.amazon.common to sagemaker.serializers and sagemaker.deserialzers

Move RecordSerializer and RecordDeserializer to sagemaker.serializers and sagemaker.deserialzers

---

doc/frameworks/tensorflow/deploying_tensorflow_serving.rst
doc/frameworks/tensorflow/using_tf.rst

https://github.com/aws/sagemaker-python-sdk/issues/2630
Add framework_version to all TensorFlowModel examples

Add framework_version to all TensorFlowModel examples

---

src/sagemaker/tuner.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/2835
*Description of changes:* Fix hyperparameter restrictions for `strategy` var
*Testing done:* Codestyle

Fix hyperparameter strategy docs

---

doc/frameworks/pytorch/using_pytorch.rst

https://github.com/aws/sagemaker-python-sdk/issues/2571
Add warning about not supporting torch.nn.SyncBatchNorm

Add warning about not supporting torch.nn.SyncBatchNorm

---

src/sagemaker/experiments/_metrics.py

https://github.com/aws/sagemaker-python-sdk/issues/4482
Fix the KeyError by changing the response key according to https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_metrics_BatchPutMetrics.html#API_metrics_BatchPutMetrics_ResponseSyntax

Fix key error in _send_metrics()

---

src/sagemaker/session.py
tests/unit/test_session.py

Adding check using the listModelPackageGroup API call to check if the model package group is already present for the account

bugix: Added check for the presence of model package group before creating one

---

src/sagemaker/utils.py

https://github.com/aws/sagemaker-python-sdk/issues/4663
Use sagemaker session's s3_resource in download_folder instead of creating a new s3 resource

Use sagemaker session's s3_resource in download_folder

---

src/sagemaker/pipeline.py
src/sagemaker/test.py
src/sagemaker/workflow/steps.py

https://github.com/aws/sagemaker-python-sdk/issues/2993
Initiated a session for the model before `CreateModelStep` tries to call `_create_model_request()`

Fix error when there is no session to call _create_model_request()

---

src/sagemaker/workflow/pipeline.py

https://github.com/aws/sagemaker-python-sdk/issues/5069
The function indeed returns a string, but is JSON formatted which might cause confusion. Clarify the same in function doc

pipeline definition function doc update

---

src/sagemaker/_studio.py
tests/unit/sagemaker/test_studio.py

*Issue #4967*
This PR fixes an infinite loop in _find_config that occurs on Windows systems. The issue was caused by using Path.match("/") to detect root directories, which never matches on Windows due to different path separators.
Changes made:
1. Replace platform-specific Path.match("/") with Path.anchor comparison
2. Implement proper root directory detection for both Windows and Unix systems
3. Add comprehensive cross-platform tests
- Verified fix on both Windows and Linux systems
- Added test_find_config_cross_platform to validate:
- Basic path traversal
- Nested directory structures
- Root directory handling
- Non-existent config scenarios
- Added test_find_config_path_separators to verify handling of:
- Forward slashes
- Backslashes
- Mixed …

fix: resolve infinite loop in _find_config on Windows systems

---

tests/conftest.py

New Python Version support for Pytorch added in automated Commit yesterday . 
https://github.com/aws/sagemaker-python-sdk/commit/30fe0ee0a04ebab3df09d6bf62290852b4e42c9f
Unit Test Build

Fixing Pytorch training python version in tests

---

tests/integ/sagemaker/experiments/helpers.py
tests/integ/sagemaker/experiments/test_run.py

N/A
During CI Health job execution, the `test_run.py` integ tests keep failing due to
```
RuntimeError: It is not allowed to use nested 'with' statements on the Run
```
Ex: https://github.com/aws/sagemaker-python-sdk/actions/runs/13530847522/job/37812455750
This is due to the [RunContext](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/experiments/_run_context.py#L23) (which is a global context to track currently "in scope" Run) not being cleared after being set in a previous test. The reason for not being cleared is still being investigated.
To prevent further test failures due to RunContext not being cleared, and to investigate where the RunContext is failing to be cleared from, a helper fixture …

fix: Prevent RunContext overlap between test_run tests

---

tests/integ/sagemaker/serve/test_serve_model_builder_gpu.py
tests/integ/sagemaker/serve/test_serve_transformers.py

Skip tests failed due to deprecated instance type

---

tests/integ/sagemaker/jumpstart/model/test_jumpstart_model.py

n/a
The model version for certain integ tests was pinned to major version `3.x`, but major version `4.x` for llama-2-7b had a metadata update to default to using ml.g5.12xlarge for inference rather than ml.g5.2xlarge. Now, we are not pinning to any version, and the test should always use the latest version.
Ran the integ tests impacted locally to verify that they pass. …

chore: fix integ tests to use latest version of model

---

tests/integ/test_spark_processing.py

* https://github.com/aws/sagemaker-python-sdk/actions/runs/14095833798/job/39482861839
* Fails because of flaky condition where shared test resource is deleted 
```
E               ValueError: code /codebuild/output/src4051418682/src/github.com/aws/sagemaker-python-sdk/tests/integ/../data/spark/code/java/hello-java-spark/hello-spark-java.jar wasn't found. Please make sure that the file exists.
```
* Modify tests and fixture so setup and teardown only happen once for whole module test run
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

fix: fix flaky spark processor integ

---

tests/unit/sagemaker/monitor/test_clarify_model_monitor.py

* https://github.com/aws/sagemaker-python-sdk/actions/runs/14079305493/job/39428419047
* Fix flaky clarify model monitor test
* From fail test run can see that it the test fails when incorrectly invoking test class, which is not expected in the test
```
cls = <class 'tests.unit.sagemaker.monitor.test_clarify_model_monitor.test_clarify_model_monitor.<locals>.DummyClarifyModelMonitoir'>
``` 
By submitting this pull request, I confirm that my contribution is made under …

fix: fix flaky clarify model monitor test

---

src/sagemaker/serve/utils/telemetry_logger.py
tests/unit/sagemaker/serve/utils/test_telemetry_logger.py

Action items from: https://t.corp.amazon.com/P208359337
We will append the MLFlow tracking arn to our ModelBuilder PythonSDK telemetry mechanism along with EndpointName to BI for revenue tracking from the ModelBuilder specifically.
Add MLflow tracking arn to the extra info in telemetry
Ran unit tests.

Add mlflow tracking arn telemetry

---

src/sagemaker/image_uri_config/instance_gpu_info.json
tests/integ/sagemaker/serve/utils/test_hardware_detector.py
tests/unit/sagemaker/serve/utils/test_hardware_detector.py

Tests failed due to ec2 update instance gpu info.
```
__________________________ test_get_gpu_info_success ___________________________
[gw42] linux -- Python 3.10.13 /codebuild/output/src4177795889/src/github.com/aws/sagemaker-python-sdk/.tox/py310/bin/python
sagemaker_session = <sagemaker.session.Session object at 0x7f0e61a990f0>
def test_get_gpu_info_success(sagemaker_session):
gpu_info = hardware_detector._get_gpu_info(VALID_INSTANCE_TYPE, sagemaker_session)
>       assert gpu_info == EXPECTED_INSTANCE_GPU_INFO
E       assert (8, 183104) == (8, 196608)
E         At index 1 diff: 183104 != 196608
E         Full diff:
E         - (8, 196608)
E         + (8, 183104)
tests/integ/sagemaker/serve/utils/test_hardware_detector.py:28: AssertionError …
```

Update instance gpu info

---

src/sagemaker/workflow/steps.py
tests/unit/sagemaker/workflow/test_steps.py
tests/unit/sagemaker/workflow/test_utils.py

*Issue #, if available:* #5099 
* Remove historical job_name caching which causes job name to exceed 63 characters with the addition of the 64 char sha256 hash
* Both TrainingJobName and ProcessingJobName have character limits of 63:
* https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateProcessingJob.html#sagemaker-CreateProcessingJob-request-ProcessingJobName
* https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html#sagemaker-CreateTrainingJob-request-TrainingJobName
* local artifact hash is now used instead of timestamp in the s3 path to support caching usecases
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …

fix: remove historical job_name caching which causes long job name

---

src/sagemaker/workflow/notebook_job_step.py
tests/unit/sagemaker/workflow/test_notebook_job_step.py

*Issue #, if available:* #4586

Fix issue #4856 by copying environment variables

---

requirements/extras/test_requirements.txt

Failing model_builder unit test in py3.8 blocking PySDK
https://t.corp.amazon.com/V1741503526/communication
Pin orderly-set<5.4.0 while using deepdiff>=8.0.0
```
successful run: deepdiff==8.4.2 with ordered-set==4.1.0, orderly-set==5.3.2, 
failed run: deepdiff==8.4.2 with  ordered-set==4.1.0, orderly-set==5.4.0
```

Fix deepdiff dependencies

---

tests/unit/sagemaker/image_uris/test_huggingface_llm.py

The image uri configs for tgi images are now updated via an automated process. To achieve this automation, we have to relax the unit test for this container to not require hardcoding the mappings between versions and full repository tag name. 
Unit tests pass. 

fix: tgi image uri unit tests

---

src/sagemaker/image_uri_config/huggingface.json

add latest huggingface images:
huggingface-pytorch-training:2.3.0-transformers4.48.0-gpu-py311-cu121-ubuntu20.04 https://github.com/aws/deep-learning-containers/releases/tag/v2.1-hf-4.48.0-pt-2.3.0-tr-gpu-py311
huggingface-pytorch-training:2.5.1-transformers4.49.0-gpu-py311-cu124-ubuntu22.04 https://github.com/aws/deep-learning-containers/releases/tag/v2.0-hf-4.49.0-pt-2.5.1-tr-gpu-py311
huggingface-pytorch-inference:2.6.0-transformers4.49.0-gpu-py312-cu124-ubuntu22.04
huggingface-pytorch-inference:2.6.0-transformers4.49.0-cpu-py312-ubuntu22.04 https://github.com/aws/deep-learning-containers/releases/tag/v2.1-hf-4.49.0-pt-2.6.0-inf-py312
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …

chore: add huggingface images

---

src/sagemaker/image_uri_config/sagemaker-distribution.json
src/sagemaker/serve/builder/model_builder.py
src/sagemaker/serve/mode/sagemaker_endpoint_mode.py
src/sagemaker/serve/model_server/smd/custom_execution_inference.py
src/sagemaker/serve/model_server/smd/prepare.py
src/sagemaker/serve/model_server/smd/server.py
src/sagemaker/serve/spec/inference_base.py
src/sagemaker/serve/utils/telemetry_logger.py
src/sagemaker/serve/utils/types.py
tests/integ/sagemaker/serve/constants.py
tests/integ/sagemaker/serve/test_serve_model_builder_inference_component_happy.py
tests/unit/sagemaker/image_uris/expected_uris.py
tests/unit/sagemaker/image_uris/test_sagemaker_distribution.py
tests/unit/sagemaker/serve/builder/test_model_builder.py

support custom workflow deployment in ModelBuilder using SMD inference image.

feature:support custom workflow deployment in ModelBuilder using SMD image.

---

tests/integ/sagemaker/conftest.py

The latest mamba update was causing `mamba env update -n integ_test_env --file /sagemaker_remote_function_workspace/conda_env.yml` command to get stuck. I pinned the download url to the previous version and the training job succeeded as expected.
Tested locally using 
```
export IGNORE_COVERAGE=- ; tox -e py310 -- -s -vv tests/integ/sagemaker/workflow/test_step_decorator.py::test_decorator_with_conda_env ; unset IGNORE_COVERAGE
``` …

fix: pin mamba version to 24.11.3-2 to avoid inconsistent test runs

---

src/sagemaker/workflow/notebook_job_step.py
tests/unit/sagemaker/workflow/test_notebook_job_step.py

*Issue #, if available:* #4855
Fixed initialization script name in error message 
tested bad init script input manually

fix: fix bad initialization script error message

---

requirements/extras/test_requirements.txt

* Pin dependency causing break in CI during dependency resolution - https://github.com/aws/sagemaker-python-sdk/actions/runs/14916056502/job/41901811171

fix: pin test dependency

---

src/sagemaker/modules/train/sm_recipes/utils.py
tests/unit/sagemaker/modules/train/sm_recipes/test_utils.py

* Correctly map llama models to corresponding training script for HyperPod Recipes. 
* Ie, both `llama_v3` and `llama_v4` should map to `llama_pretrain.py`
* Updated unit tests

fix: Map llama models to correct script

---

src/sagemaker/modules/train/container_drivers/common/utils.py
tests/unit/sagemaker/modules/train/container_drivers/test_utils.py

* Honor JSON serialization of HPs. The `safe_deserialize()` method breaks contract for JSON serialization by forcibly changing non JSON boolean strings to lower case. This change corrects this by honoring the serialization.
* Fix unit tests

fix: honor json serialization of HPs

---

pyproject.toml

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/5162
* Allow omegaconf >=2.2,<3 to address issue with earlier versions using deprecated library

chore: Allow omegaconf >=2.2,<3

---

src/sagemaker/model_monitor/clarify_model_monitoring.py
tests/unit/sagemaker/monitor/test_clarify_model_monitor.py

*Issue #, if available:
* error reported: https://github.com/aws/sagemaker-python-sdk/issues/4431
*Description of changes:
* add missing parameters `data_analysis_end_time` and `data_analysis_start_time` for Model Explainability Monitor
*Testing done:
* tox -e py310 -- -s -vv tests/unit/sagemaker/monitor/test_clarify_model_monitor.py

fix: clarify model monitor one time schedule bug

---

src/sagemaker/jumpstart/cache.py
src/sagemaker/jumpstart/factory/estimator.py
src/sagemaker/jumpstart/types.py
tests/unit/sagemaker/jumpstart/factory/test_estimator.py
tests/unit/sagemaker/jumpstart/test_cache.py
tests/unit/sagemaker/jumpstart/test_types.py

- This PR fixes an issue with `JumpStartEstimator` not including the model channel when invoking `CreateTrainingJob`
- Unit tests added
- Integration tests pass
- Tested workflow locally 
- TO-DO: Add integration test for gated uncompressed training once artifacts and metadata are in production

fix: include model channel for gated uncompressed models

---

src/sagemaker/modules/train/model_trainer.py
tests/unit/sagemaker/modules/train/test_model_trainer.py
tox.ini

* Small change in behavior for managing inputs in ModelTrainer. 
* merge method inputs with class inputs instead of override
Previous Behavior:
```
model_trainer = ModelTrainer(input_data_config=[model_input]) # user provides model channel 
model_trainer.train(input_data_config[train_input]) # User provides train input, and would override the model input when calling train
```
New Behavior:
```
model_trainer = ModelTrainer(input_data_config=[model_input]) # user provides model channel 
model_trainer.train(input_data_config[train_input]) # method and class inputs merged when calling API
```
* Unit test
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, …

change: merge method inputs with class inputs

---

requirements/extras/test_requirements.txt
tests/unit/sagemaker/mlflow/test_forward_sagemaker_metrics.py

MLFLow update for dependabot

---

src/sagemaker/estimator.py

Update estimator documentation regarding hyperparameters for source_dir

---

tests/conftest.py

Update TF DLC python version to py312

---

src/sagemaker/image_uri_config/sagemaker-distribution.json
tests/unit/sagemaker/image_uris/test_sagemaker_distribution.py

- Bump custom workflow deployment to use SMD 3.2 image
- Custom workflow deployment fails because only introduced in sagemaker 2.44.0 (https://github.com/aws/sagemaker-python-sdk/releases/tag/v2.244.0)
- custom workflow deployment is using SMD 3.0 which only has sagemaker 2.42.0 ([SMD 3.0 changelog](https://github.com/aws/sagemaker-distribution/blob/1d914a7c263ba081e5c43970125be960d4b31ab3/build_artifacts/v3/v3.0/v3.0.0/CHANGELOG-gpu.md))
- Deployed workflow IC successfully 
```
INFO:sagemaker:Creating endpoint-config with name llama-mistral-endpoint-34caa6b8577611f083385a17-1751482587-429a
INFO:sagemaker:Creating endpoint with name llama-mistral-endpoint-34caa6b8577611f083385a17-1751482587-429a
----!
INFO:sagemaker:Creating model with name: …
```

Bump SMD version to enable custom workflow deployment.

---

.gitignore
src/sagemaker/estimator.py
src/sagemaker/fw_utils.py
src/sagemaker/modules/constants.py
src/sagemaker/modules/train/model_trainer.py
src/sagemaker/modules/train/sm_recipes/utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/sagemaker/modules/train/sm_recipes/test_utils.py
tests/unit/sagemaker/modules/train/test_model_trainer.py
tests/unit/test_pytorch_nova.py

* feature: Added Amazon Nova training support for ModelTrainer and Estimator
Added Nova training support to both Estimator and Modeltrainer
Privately tested

Nova training support

---

src/sagemaker/serve/builder/model_builder.py
tests/integ/sagemaker/serve/test_base_model_builder_deploy.py
tests/integ/sagemaker/serve/test_serve_model_builder_inference_component_happy.py
tests/unit/sagemaker/serve/builder/test_model_builder.py

*Description of changes:* ModelBuilder is generating a unique name from the customer-provided endpoint name as base. Leads to confusion and inconsistencies in the user experience, especially when customers already set a UUID string for uniqueness in their base name.
*Testing done:* UTs and integ tests succeed locally

Directly use customer-provided endpoint name for ModelBuilder deployment.

---

tests/integ/test_multidatamodel.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/blob/e65b0d75e41d38cc33a1706b5ad25c09c60a587d/tests/integ/test_multidatamodel.py#L350
Fixes intermittently flaky tests by allowing time for the model to deploy after endpoint is created

fix: add sleep for model deployment to fix flaky test

---

tests/integ/sagemaker/conftest.py

fix: dockerfile stuck on interactive shell

---

src/sagemaker/modules/train/sm_recipes/utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/sagemaker/modules/train/sm_recipes/test_utils.py
tests/unit/test_pytorch.py

GPT OSS Hotfix

---

src/sagemaker/workflow/emr_step.py
tests/integ/sagemaker/workflow/test_emr_steps.py
tests/unit/sagemaker/workflow/test_emr_step.py

*Description of changes:* Backend EMR step is using retryable step, but the sagemaker python sdk didn't have retryable step, so customers couldn't configure retry policies in their EMR step. This change fixes that so customer are able to optionally pass in retry policies.
*Testing done:* Ran unit and integration tests for the changes:
tox -e py310 -- -s -vv tests/unit/sagemaker/workflow/test_emr_step.py
tox -e py310 -- -s -vv tests/integ/sagemaker/workflow/test_emr_steps.py
Old unit and integ tests also pass, so backward compatibility is in place.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to …

fix: add retryable option to emr step in SageMaker Pipelines

---

src/sagemaker/modules/train/sm_recipes/utils.py
src/sagemaker/pytorch/estimator.py
tests/unit/sagemaker/modules/train/sm_recipes/test_utils.py
tests/unit/test_pytorch_nova.py

Support nova custom evaluation SMTJ job to have a eval specific hyperparameter, I have previously created a PR: https://github.com/aws/sagemaker-python-sdk/pull/5272 which is to set the hyperparameter from model trainer. This PR set the hyperparameter from estimator.
This change is to support nova custom evaluation SMTJ job to have a eval specific hyperparameter.
Tested on Sagemaker training job locally, verify the hyperparameter field is set correctly
By submitting …

Add nova custom lambda in hyperparameter from estimator

---

src/sagemaker/pytorch/estimator.py
tests/unit/test_pytorch_nova.py

`tox -e flake8,pylint,docstyle,black-check,twine,black-format --parallel all`
`tox -e py310 -- -s -vv tests/unit/ `

feature: add model_type hyperparameter support for Nova recipes
