aws/sagemaker-python-sdk

- README.rst
- doc/conf.py
- doc/factorization_machines.rst
- doc/index.rst
- doc/lda.rst
Update version for docs to match current and updates in README.
> Add FM and LDA to the documentation.

- src/sagemaker/amazon/linear_learner.py
- tests/integ/test_linear_learner.py
- tests/unit/test_linear_learner.py
Invoke deploy on Estimator and Model in integration tests.
> Fixes in LinearLearner and unit tests addition.

- CHANGELOG.rst
naming idea taken from: https://www.python.org/dev/peps/pep-0440/#developmental-releases. Feel free to suggest something better.
> Add entry for new version in changelog

- .gitignore
- doc/conf.py
Attempt to fix: https://readthedocs.org/projects/sagemaker/builds/7040261/
Based on: http://docs.readthedocs.io/en/latest/faq.html#mock-c-extensions
> Mock numpy/scipy for Sphinx on readthedocs

- CHANGELOG.rst
- README.rst
- doc/conf.py
- doc/randomcutforest.rst
- setup.py
- src/sagemaker/__init__.py
- src/sagemaker/amazon/amazon_estimator.py
- src/sagemaker/amazon/randomcutforest.py
- tests/integ/test_randomcutforest.py
- tests/unit/test_randomcutforest.py
*Description of changes:* Adding Random Cut Forest support to client libraries Python SDK
> Adding Random Cut Forest support to client libraries Python SDK

- CHANGELOG.rst
> Bump version to 1.2.4

- CHANGELOG.rst
- src/sagemaker/__init__.py
- src/sagemaker/mxnet/__init__.py
- src/sagemaker/tensorflow/__init__.py
Change module names to string in __all__. This is required for wild import.
I also test wild import locally. Didn't add unit tests because wild import cannot be performed in scope of function/method.
> Change module names to string type in __all__

- CHANGELOG.rst
- setup.py
> bump version to 1.2.5

- CHANGELOG.rst
> Fix changelog: Move Local Serving of Models to 1.4.3

- src/sagemaker/pytorch/README.rst
Remove reference to gluon from pytorch readme.
> Fix pytorch readme.

- CHANGELOG.rst
- README.rst
- setup.py
> Bump version to 1.5.1

- CHANGELOG.rst
- README.rst
- setup.py
- src/sagemaker/amazon/amazon_estimator.py
Support SageMaker algorithms in ICN region.
> Support SageMaker algorithms in ICN region.

- CHANGELOG.rst
- README.rst
- setup.py
> Bump version to 1.5.3

- CHANGELOG.rst
- src/sagemaker/amazon/amazon_estimator.py
Added: Docker Registry for all 1p algorithms in amazon_estimator.py. Added: FRA and SYD regions to registry. Added: get_image_uri method in amazon-estimators.py. Added: object-detection algorithm to registry
> Added get_image_uri. Support for FRA and SYD regions.

- CHANGELOG.rst
- README.rst
- setup.py
> Bump version to 1.5.4

- CHANGELOG.rst
- src/sagemaker/amazon/linear_learner.py
- tests/integ/test_linear_learner.py
- tests/unit/test_linear_learner.py
* added new hyperparameters for multiclass classification in linear learner.
* add unit and integration tests.
> multiclass support for linear learner

- CHANGELOG.rst
- README.rst
- setup.py
> Bump version to 1.6.1

- README.rst
> fix typos in README example

- CHANGELOG.rst
- README.rst
- setup.py
> bump to 1.7.1

- tests/data/pytorch_mnist/mnist.py
- tests/integ/test_tuner.py
A little overdue, but here's an integ test for PyTorch with hyperparameter tuning
> Add PyTorch hyperparameter tuning integ test

- setup.py
> Bump version in setup.py

- CHANGELOG.rst
- README.rst
- src/sagemaker/__init__.py
- src/sagemaker/amazon/README.rst
- src/sagemaker/amazon/amazon_estimator.py
- src/sagemaker/amazon/knn.py
- src/sagemaker/amazon/linear_learner.py
- src/sagemaker/tuner.py
- tests/integ/test_knn.py
- tests/unit/test_knn.py
> Add support for Amazon k-nearest neighbors(KNN) algorithm

- CHANGELOG.rst
- README.rst
- setup.py
> Bump version to 1.8.0

- src/sagemaker/local/image.py
fcntl is only available on linux systems. Importing sagemaker on Windows fails cause of this. This change removes usage of fcntl.
_stream_out exists because jupyter swallows stderr and stdout from a child process. We have to capture it from the main process and pipe to stdout here. This change redirects the child process's stderr to stdout so we only need to read from stdout which is already non-blocking.
By submitting this pull request, I confirm that my contribution is made under …
> Remove usage fcntl

- CHANGELOG.rst
- setup.py
> Increase version to 1.9.3

- tests/conftest.py
- tests/integ/test_chainer_train.py
- tests/integ/test_mxnet_train.py
- tests/integ/test_pytorch_train.py
- tests/integ/test_tf.py
1. Allow passing argument for test framework version in pytest
2. Mark regional tests for image deployment test
> Allow argument for test framework version and mark regional tests

- CHANGELOG.rst
- README.rst
- doc/conf.py
- setup.py
fix RST warnings in the readme file
- [x ] I have updated any necessary [documentation](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) (if appropriate)
> fix rst warnings

- setup.py
Fix version from incorrect 1.9.4 to 1.10.0 in setup.py
> Fix version to 1.10.0 in setup.py

- setup.py
> Fix version in setup.py

- CHANGELOG.rst
Move 'Add support for volume KMS key to Transformer' record to the correct version in changelog.
> Fix changelog.

- CHANGELOG.rst
- doc/conf.py
- setup.py
https://github.com/aws/sagemaker-python-sdk/issues/421
> Bump version to 1.11.2

- CHANGELOG.rst
- doc/conf.py
- setup.py
> Bump version to 1.11.3

- CHANGELOG.rst
- src/sagemaker/amazon/amazon_estimator.py
- src/sagemaker/amazon/linear_learner.py
New region
Added the image uris for all SageMaker built-in Algorithms for the new regions (SIN/LHR/BOM/SFO/YUL)
- [x ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x ] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a description of my changes (if appropriate)
- …
> Added the image uris for all SageMaker built-in Algorithms for SIN/LHR/BOM/SFO/YUL

- CHANGELOG.rst
- setup.py
- src/sagemaker/estimator.py
- src/sagemaker/job.py
- src/sagemaker/session.py
- src/sagemaker/tensorflow/estimator.py
- tests/integ/test_chainer_train.py
- tests/integ/test_mxnet_train.py
- tests/integ/test_pytorch_train.py
- tests/integ/test_tf.py
- tests/unit/test_estimator.py
- tests/unit/test_job.py
Make InputDataConfig optional for training.
> Make InputDataConfig optional for training.

- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
> bump version to 1.14.0

- src/sagemaker/utils.py
*Issue #, if available:* none
*Description of changes:*  Just improving the docstring on a utility class.
> Very minor: Better documentation comment on DeferredError.

- CHANGELOG.rst
- src/sagemaker/__init__.py
> Bump version to 1.14.2

- tests/integ/test_tfs.py
remove regional_testing tag (fixes deployment test errors)
> remove regional_testing tag

- tests/unit/test_analytics.py
fix test failing due to fixture error
> fix test for pytest 4

- CHANGELOG.rst
- src/sagemaker/tensorflow/deploying_tensorflow_serving.rst
Just fixing minor typos in the tensorflow depolyment serving documentation file.
> Fixing the tensorflow serving documentation minor typo

- .gitignore
- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
The lock file is used locally for tests - doesn't need to be committed to the repo.
> Bump version to 1.15.0 and remove local_mode_lock

- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
> Bump version to 1.15.1

- README.rst
- src/sagemaker/rl/README.rst
> RLEstimator documentaion

- src/sagemaker/sklearn/README.rst
Correct the numbered list of the table of content
> Correct numbering

- README.rst
> Add notebook references to Inference Pipelines README doc

- tests/conftest.py
- tests/integ/test_mxnet_train.py
- tests/integ/test_tf.py
Enable integ tests for elastic inference.
> enable ei integ tests

- setup.py
- avoid versions affected by CVE-2018-18074 
- narrow requests version bounds (to `requests>=2.20.0, <2.21`)
> narrow requests version bounds

- tests/integ/__init__.py
- skip p3 hosting tests in lhr
> skip p3 hosting tests in lhr

- .rtd-environment.yml
Fix requests version to 2.20 for readthedocs.
> Fix requests version to 2.20 for readthedocs.

- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
> Upgrade version to 1.16.3

- README.rst
>  Fix readthedocs link.

- src/sagemaker/transformer.py
- src/sagemaker/workflow/airflow.py
*Description of changes:* Adds TFRecord split type to doc strings where applicable
> Add TFRecord split type to docs

- CHANGELOG.rst
- src/sagemaker/model.py
- tests/unit/test_model.py
there is no straight forward way to create a batch transform job from a
SageMaker Model class. This supports the use case of bringing an
existing model artifact to SageMaker and performing batch inference from
within the SDK.
> Add Model.transformer()

- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
> Upgrade version to 1.17.0

- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
- src/sagemaker/session.py
- src/sagemaker/tuner.py
- tests/integ/test_tuner.py
- tests/unit/test_tuner.py
> Support VPC config for hyperparameter tuning and bump version to 1.17.2

- CHANGELOG.rst
- src/sagemaker/__init__.py
Don't think there was a reason this wasn't done before, so it'd be nice to have for consistency with other similar classes.
> Add 'tuner' to imports in 'sagemaker/__init__.py'

- CHANGELOG.rst
- doc/conf.py
- src/sagemaker/__init__.py
> Bump version to 1.18.1

- src/sagemaker/tensorflow/README.rst
> Add available versions in Horovod documentation

- tests/integ/test_mxnet_train.py
- tests/unit/test_tuner.py
noticed these while trying to unblock #617 
> Fix flake8 errors

- tests/integ/test_mxnet_train.py
> Add MXNet version to integ tests using MXNetModel

- src/sagemaker/tensorflow/README.rst
one more that I missed when doing #628 
> Fix RTD link in TF README

- .readthedocs.yml
- .rtd-environment.yml
- doc/requirements.txt
- doc/using_mxnet.rst
- readthedocs.yml
- src/sagemaker/tuner.py
Treat warnings as errors when building documentation. Migrate readthedocs configuration to version 2 and switch to use requirements.txt instead of conda environment in order to do so. 
> Treat warnings as errors when building documentation.

- CHANGELOG.rst
Added SKLearnModel default account fix to CHANGELOG.
> Fixed CHANGELOG with SKLearnModel default account fix.

- CHANGELOG.rst
- setup.py
> Bump version to v1.18.3

- CHANGELOG.rst
- src/sagemaker/tensorflow/deploying_python.rst
https://github.com/aws/sagemaker-python-sdk/commit/4732545bd9d1880390b3951c9b941f2bb62d6e5a#commitcomment-32326736
A user has pointed out the incorrect documentation.
Remove wrong parameter.
> fix EI TFS docs

- CHANGELOG.rst
- tox.ini
https://github.com/aws/sagemaker-python-sdk/pull/643
Added twine check step in tox
> add twine check in tox

- tests/integ/test_horovod.py
Test fails if region isn't configured on the host is running on.
> add local_sagemaker_session to horovod test

- CHANGELOG.rst
- doc/index.rst
- doc/using_tf.rst
Move using content from /tensorflow/README.txt
- [X ] I have updated the [changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.rst) with a description of my changes (if appropriate)
> Migrate tf using content into sphynx project

- buildspec.yml
Disable notebooks tests - they have never worked in new build system.
> Disable notebooks tests

- CHANGELOG.rst
- setup.py
> Bump version to 1.18.4

- doc/index.rst
- doc/using_chainer.rst
- doc/using_mxnet.rst
> doc: move chainer readme into sphinx project and fix broken link in using_mxnet

- doc/overview.rst
Updated sentence in local mode section of overview.rst in doc project to mention supported frameworks.
> doc: edit description of local mode in overview.rst

- tests/data/horovod/test_hvd_basic.py
- test_horovod.py is having flaky behavior. The tests was not printing the rank properly, making it hard to debug the issue. I'm wrapping the script in a main function and printing the file contents, allowing easier debuggability. 
> fix: wrap test horovod code inside main function

- tests/integ/test_tf_script_mode.py
> fix: use unique training job names in TensorFlow script mode integ tests

- tests/data/ray_cartpole/train_ray.py
matches the change made in https://github.com/aws/sagemaker-rl-container/blame/master/test/resources/ray_cartpole/train_ray.py#L8
don't merge if https://github.com/aws/sagemaker-python-sdk/pull/780 is merged 
> fix: adjust Ray test script for Ray 0.6.5

- setup.py
> fix: pin pytest version to 4.4.1 to avoid pluggy version conflict

- doc/using_sklearn.rst
Incorrect parameter name in docs. Updated to match what is implemented in the method and what is used in other estimators.
> documentation: Update using_sklearn.rst

- README.rst
> doc: fix punctuation in MXNet version list

- src/sagemaker/model.py
- tests/unit/test_model.py
> change: update Sagemaker Neo regions and instance families

- tests/integ/test_tfs.py
- moving not canary TFS tests to local mode to speed the tests
> change: moving not canary TFS tests to local mode

- buildspec.yml
- pytest-reruns is not compatible with xdist --boxed parameter. Removing the legacy parameter.
- increasing number of test reruns to 3
> change: Update buildspec.yml

- buildspec-notebooktests.yml
- tests/scripts/run-notebook-test.sh
SageMaker Role was being passed as null to this line https://github.com/aws/sagemaker-python-sdk/pull/900/files#diff-c23e9b26c8ede22a576d6c8b0de119ceR21 resulting in test failures.
> change: fix notebook tests

- .pylintrc
This commit tightens the pylint config with
inspiration from several of Google's pylint
configs.
This commit also expands the C and R exceptions
and disables the specific rules that cause issues
in this package.
> change: tighten pylint config and expand C and R exceptions

- .pylintrc
- src/sagemaker/amazon/record_pb2.py
- src/sagemaker/tensorflow/__init__.py
> change: enable wrong-import-position pylint check

- tox.ini
> change: ignore FI18 flake8 rule

- src/sagemaker/model.py
- tests/unit/test_model.py
tags not being added to tensorflow models when estimator.transform() is called.
change model class so that tags are passed correctly
> fix: model.transformer() passes tags to create_model()

- doc/overview.rst
- src/sagemaker/amazon/amazon_estimator.py
- src/sagemaker/inputs.py
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [x ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ x] I have updated any necessary [documentation](https://github.com/aws/sagemaker-python-sdk/blob/master/RE …
> Update: changed EFS directory path instructions in documentation and Docstrings

- CONTRIBUTING.md
> doc: add note to CONTRIBUTING to clarify automated formatting

- src/sagemaker/model.py
- tests/unit/test_model.py
Adding new regions to Sagemaker Neo API's
> change: update Sagemaker Neo regions

- src/sagemaker/session.py
- tests/unit/test_session.py
Add an initial attempt to get the role via DescribeNotebookInstance.
If that attempt fails fallback to the current heuristics-based behavior.
- [X ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [X ] I have added tests that prove my fix is effective or that …
> fix: get_caller_identity_arn gets role from DescribeNotebookInstance

- src/sagemaker/estimator.py
- tests/unit/test_estimator.py
> fix: pass enable_network_isolation in Estimator.create_model

- tests/integ/test_airflow_config.py
> change: skip lda tests in regions that does not support it.

- tests/integ/test_airflow_config.py
> change: skip airflow_config tests as they're blocking the release build

- src/sagemaker/model.py
> doc: model local mode

- setup.py
> Add pyyaml dependencies to the required list.

- src/sagemaker/utils.py
> doc: fix docstring wording.

- .github/PULL_REQUEST_TEMPLATE.md
1. We recently had some code changes that weren't agnostic to the region or AWS account running the integ tests, which caused issues with our release and test processes. Adding this extra checklist item to encourage people to remember to look out for that.
1. Often there's manual testing that's happening but not getting documented. I'm hoping that adding another prompt will encourage people to show how they've tested their changes, especially if it was more involved than simply running the test suite.
1. We should be using regional endpoints for S3 and STS, even though boto3 does not give us this behavior automatically like it does with other services. We've talked before about having a more automated check, but in the meantime a checklist item is probably the …
> change: update PR template with items about tests, regional endpoints, and API docs

- src/sagemaker/estimator.py
- tests/integ/test_debugger.py
*Description of changes:* `debugger_hook_config=False` now disables Debugger functionality.
*Testing done:* New Debugger IT.
> feature: allow disabling debugger_hook_config

- tests/integ/test_processing.py
> change: fix test_sklearn for regions without m4.xlarge instances.

- tests/integ/test_auto_ml.py
> change: fix test_auto_ml tests for regions without ml.c4.xlarge hosts

- setup.py
*Issue #, if available:* #1203
*Description of changes:*Relax urllib3 and requests restrictions based on
https://github.com/docker/compose/blob/1.25.0/setup.py#L36 
and
https://github.com/psf/requests/blob/v2.22.0/setup.py#L47
> change: relax urllib3 and requests restrictions.

- doc/debugger.rst
- doc/index.rst
Adding debugger API documentation
`tox -e sphinx`
> doc: add Debugger API docs

- README.rst
- doc/using_pytorch.rst
- Updated documentation to reflect all supported versions of PyTorch.
- Tested with [pytorch_mnist notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_mnist/pytorch_mnist.ipynb)
- changed "framework_version" and ran fit()
- verified 0.4.0, 1.0.0, 1.1.0, 1.2.0, and 1.3.1 are supported
> doc: Update supported versions of PyTorch

- src/sagemaker/estimator.py
https://github.com/aws/sagemaker-python-sdk/issues/1238
Minor edit to docstring with the correct error type
N/A
> doc: Update error type in delete_endpoint docstring

- setup.py
Updated `docker-compose` and `PyYAML` requirements for both security and compatibility with other packages such as aws-sam-cli.
> Update docker-compose and PyYAML dependencies

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
> doc: remove labels from issue templates

- src/sagemaker/mxnet/README.rst
- src/sagemaker/tensorflow/README.rst
Add Inferentia supported versions documentation in framework readme.
> doc: document inferentia supported version

- tests/unit/test_transformer.py
This was motivated by noticing that we weren't testing tags at all in the file.
* `tox -e pylint,flake8,black-format --parallel all`
* `tox -e py36 tests/unit`
> infra: improve unit tests for creating Transformers and transform jobs

- tests/unit/sagemaker/model/test_deploy.py
- tests/unit/sagemaker/model/test_framework_model.py
similar to #1420, #1424, #1425. another pretty much straight copy/paste.
`pytest tests/unit/sagemaker/model/`
> infra: move unit tests for updating an endpoint to test_deploy.py

- setup.py
> fix: upgrade boto3 to 1.13.6

- tests/integ/test_experiments_analytics.py
We've had quite a few integ test failures with:
```
E           botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the DeleteTrialComponent operation: TrialComponent 'arn:aws:sagemaker:us-east-1:123412341234:experiment-trial-component/tc-5383175d-9863-4de5-b978-38b40f1046c6' is linked to 1 or more trials and cannot be deleted.
```
Yet checking the TrialComponent later shows that it is no longer linked to a trial and can be deleted, so this change adds a little bit of waiting to try and minimize how often we see the above error.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
> infra: wait for DisassociateTrialComponent to take effect in experiment integ test cleanup

- doc/kubernetes/amazon_sagemaker_components_for_kubeflow_pipelines.rst
- doc/kubernetes/index.rst
- doc/kubernetes/using_amazon_sagemaker_components.rst
Added new documentation to describe the usage of Amazon Components for Kubeflow pipelines.
Docs built locally.
- [X ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change) …
> [doc] Added Amazon Components for Kubeflow Pipelines

- .github/PULL_REQUEST_TEMPLATE.md
tying up the other loose end of #1381
> infra: specify what kinds of clients in PR template

- .github/ISSUE_TEMPLATE/feature_request.md
- Some users have been mistakenly using the feature request issue template to submit bug reports.
- This change attempts to clarify the intended usage of the feature request issue template to encourage users to select the correct template and fill out the necessary information.
> infra: update feature request issue template

- setup.py
upgrade airflow to latest stable version
unit, integ
> infra: upgrade airflow to latest stable version

- .coveragerc
> infra: change coverage settings to reduce intermittent errors

- src/sagemaker/chainer/estimator.py
- src/sagemaker/estimator.py
- src/sagemaker/mxnet/estimator.py
- src/sagemaker/pytorch/estimator.py
- src/sagemaker/rl/estimator.py
- src/sagemaker/sklearn/estimator.py
- src/sagemaker/tensorflow/estimator.py
- src/sagemaker/utils.py
- src/sagemaker/xgboost/estimator.py
- tests/unit/test_estimator.py
- tests/unit/test_tuner.py
- tests/unit/test_utils.py
same motivation as #1645
unit tests
> change: infer base name from job name in estimator.attach()

- doc/workflows/index.rst
- doc/workflows/step_functions/index.rst
Adds info about Step Functions SDK to the workflows section.
Built locally.
> documentation: add Step Functions SDK info

- src/sagemaker/analytics.py
- tests/integ/test_experiments_analytics.py
- tests/unit/test_experiments_analytics.py
Reshape Artifacts into data frame in ExperimentsAnalytics
https://sim.amazon.com/issues/AML-71634
> change: reshape Artifacts into data frame in ExperimentsAnalytics

- src/sagemaker/amazon/amazon_estimator.py
- src/sagemaker/analytics.py
- src/sagemaker/estimator.py
- src/sagemaker/fw_registry.py
- src/sagemaker/local/entities.py
- src/sagemaker/local/image.py
- src/sagemaker/local/local_session.py
- src/sagemaker/tensorflow/estimator.py
- src/sagemaker/tensorflow/serving.py
- src/sagemaker/tuner.py
- src/sagemaker/utils.py
> fix: use 'sagemaker' logger instead of root logger

- src/sagemaker/deserializers.py
- tests/unit/sagemaker/test_deserializers.py
* Changed implementation of `JSONLinesDeserializer.deserialize`
* Fixed relevant tests in `test_deserializers`
> fix: Fix JSONLinesDeserializer

- CHANGELOG.md
- README.rst
https://github.com/aws/sagemaker-python-sdk/issues/1459#issuecomment-668825322
turns out our build system doesn't handle merge commits very well 😅 
> doc: update CHANGELOG to reflect v2.0.0 changes

- src/sagemaker/image_uri_config/inferentia-pytorch.json
- tests/conftest.py
- tests/unit/sagemaker/image_uris/test_neo.py
*Description of changes:* add inferentia pytorch inference container config
> feature: add inferentia pytorch inference container config

- doc/overview.rst
> doc: fix broken link to moved notebook

- src/sagemaker/deprecations.py
- src/sagemaker/predictor.py
- tests/scripts/run-notebook-test.sh
* additional notebooks
* attach logger for warning messages for contexts outside of development and `__main__`
notebook testing in sagemaker:
> change: include more notebook tests, logger to warn

- src/sagemaker/session.py
- src/sagemaker/transformer.py
> change: refactor out batch transform job input generation

- CHANGELOG.md
The purpose of this PR is to bump the minor version for re:Invent 2020 features that were introduced in: https://github.com/aws/sagemaker-python-sdk/commit/3bf146ef4134ce65e80c715aea3fb66e534b3401 and https://github.com/aws/sagemaker-python-sdk/pull/2006
The bump should have happened in this [commit](https://github.com/aws/sagemaker-python-sdk/commit/a0f7931c83bf6669a0c3f3be70b99053195a852c), however it looks like since the feature prefix wasn't prepended to the merge commit it was treated as a bug.
The change log is being updated to indicate that features were added.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here …
> feature: bump minor version for re:Invent 2020 features

- src/sagemaker/lineage/artifact.py
create artifact restricted to SM context note
> documentation: create artifact restricted to SM context note

- src/sagemaker/estimator.py
> documentation: fix description for max_wait

- src/sagemaker/deprecations.py
> fix: remove captureWarnings global logging setting

- src/sagemaker/estimator.py
- src/sagemaker/pytorch/estimator.py
- src/sagemaker/tensorflow/estimator.py
- tests/unit/test_estimator.py
> change: refactor distribution config construction

- tests/integ/test_experiments_analytics.py
allowed extra time for search to get updated. 
unit
> fix: increase allowed time for search to get updated

- doc/api/training/smp_versions/v1.2.0/smd_model_parallel_pytorch.rst
> Fix indentation

- tests/integ/test_experiments_analytics.py
* lower integ testing of experiments service to 1 tps
> infra: lower test tps for experiment analytics

- tests/integ/test_auto_ml.py
- tests/integ/test_clarify_model_monitor.py
- tests/integ/test_inference_pipeline.py
- tests/integ/test_model_quality_monitor.py
- tests/integ/test_multidatamodel.py
- tests/integ/test_mxnet.py
- tests/integ/test_tuner.py
Mark the top 10 tests so we can move them to a separate build project. These are the tests that run for 15 minutes plus.
> change: mark top 10 slow tests

- buildspec-slowtests.yml
- buildspec.yml
> change: add build spec for slow tests

- src/sagemaker/workflow/steps.py
Changed description of `sagemaker.workflow.steps.ProcessingStep` `name` parameter.
`tox -e black-check,flake8,pylint,docstyle,sphinx,doc8 --parallel all`
> documentation: fix pipelines processing step typo

- CHANGELOG.md
Removing ellipsis, as it is causing our release build to fail.
This will have to be done again for: https://github.com/aws/sagemaker-python-sdk/pull/2191
> doc: remove ellipsis from CHANGELOG.md

- setup.py
> change: move pandas to required dependency from specific use cases

- doc/api/prep_data/feature_store.rst
*Issue #, if available:* #2230
*Description of changes:* Add documentation of methods for Feature Store classes, including ingest() and put_record().
*Testing done:* Built and previewed locally.
> doc: add Feature Store methods docs

- doc/frameworks/pytorch/using_pytorch.rst
> documentation: update PyTorch version in doc

- doc/requirements.txt
> infra: pin version for ducutils

- src/sagemaker/image_uri_config/huggingface.json
Update huggingface transformer versions
Ran unit tests on py36 and py37
> feature: Add HF transformer version 4.5.0

- doc/api/training/sdp_versions/latest.rst
- doc/api/training/sdp_versions/v1.1.x/smd_data_parallel_pytorch.rst
- doc/api/training/sdp_versions/v1.1.x/smd_data_parallel_tensorflow.rst
- doc/api/training/sdp_versions/v1_1_x.rst
- doc/api/training/smd_data_parallel.rst
* Adding new version of SageMaker distributed data parallel 1.2.0.
> documentation: adding new version, SM dist. data parallel 1.2.0.

- doc/api/training/sdp_versions/latest.rst
- doc/api/training/sdp_versions/latest/smd_data_parallel_tensorflow.rst
- doc/api/training/sdp_versions/v1.1.x/smd_data_parallel_pytorch.rst
- doc/api/training/sdp_versions/v1.1.x/smd_data_parallel_tensorflow.rst
- doc/api/training/sdp_versions/v1_1_x.rst
- doc/api/training/smd_data_parallel.rst
- doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.md
- doc/api/training/smp_versions/latest.rst
- doc/api/training/smp_versions/latest/smd_model_parallel_pytorch.rst
- doc/api/training/smp_versions/latest/smd_model_parallel_tensorflow.rst
* Adding new versions for the new DLC launch
* EFA now available for SM distributed.
> Documentation: SM Distributed EFA Launch

- .github/ISSUE_TEMPLATE/config.yml
Updated the "Ask a question" contact link. It now links to the GitHub Discussions page for this repository instead of StackOverflow.
> documentation: Update "Ask a question" contact link

- tests/scripts/run-notebook-test.sh
> fix: remove failing notebooks from notebook pr test

- tests/conftest.py
- tests/data/huggingface/run_glue.py
- tests/integ/test_huggingface.py
> fix: parameterize PT and TF version for HuggingFace tests

- src/sagemaker/huggingface/estimator.py
> doc: update HF transformer version

- src/sagemaker/inputs.py
- src/sagemaker/session.py
> documentation: introduce input mode FastFile

- tests/integ/test_huggingface.py
> fix: skip hf inference test

- src/sagemaker/estimator.py
- [X ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
> documentation: update sagemaker.estimator.EstimatorBase

- CHANGELOG.md
> fix: Update Changelog to fix release

- .github/ISSUE_TEMPLATE/bug_report.md
> doc: update bug template

- .github/ISSUE_TEMPLATE/feature_request.md
> fix: update feature request label

- ci-scripts/queue_build.py
- src/sagemaker/local/image.py
- src/sagemaker/local/utils.py
- src/sagemaker/session.py
- tests/unit/test_local_utils.py
> change: update master

- doc/frameworks/pytorch/using_pytorch.rst
- src/sagemaker/dataset_definition/inputs.py
- src/sagemaker/workflow/_repack_model.py
- src/sagemaker/workflow/steps.py
- src/sagemaker/workflow/utilities.py
- tests/integ/test_processing.py
- tests/unit/sagemaker/workflow/test_repack_model_script.py
- tests/unit/sagemaker/workflow/test_steps.py
> change : update master

- doc/api/training/smd_data_parallel.rst
- doc/api/training/smd_model_parallel.rst
- doc/api/training/smd_model_parallel_general.rst
- doc/api/training/smd_model_parallel_release_notes/smd_model_parallel_change_log.rst
- doc/api/training/smp_versions/archives.rst
- doc/api/training/smp_versions/latest.rst
- doc/api/training/smp_versions/latest/smd_model_parallel_pytorch_tensor_parallel.rst
- doc/api/training/smp_versions/v1.4.0/smd_model_parallel_common_api.rst
- doc/api/training/smp_versions/v1.4.0/smd_model_parallel_pytorch.rst
- doc/api/training/smp_versions/v1.4.0/smd_model_parallel_tensorflow.rst
- doc/api/training/smp_versions/v1.5.0/smd_model_parallel_common_api.rst
- doc/api/training/smp_versions/v1.5.0/smd_model_parallel_pytorch.rst
- doc/api/training/smp_versions/v1.5.0/smd_model_parallel_tensorflow.rst
- doc/api/training/smp_versions/v1_4_0.rst
- doc/api/training/smp_versions/v1_5_0.rst
- src/sagemaker/model.py
- src/sagemaker/session.py
- tests/integ/sagemaker/lineage/conftest.py
- tests/integ/test_auto_ml.py
- tests/integ/test_kmeans.py
- tests/integ/test_mxnet.py
Merge latest `dev` changes to `master`.
> change: merge dev to master

- CHANGELOG.md
- doc/Makefile
- doc/api/training/sdp_versions/latest/smd_data_parallel_pytorch.rst
- doc/api/training/sdp_versions/latest/smd_data_parallel_tensorflow.rst
- doc/api/training/smd_data_parallel_release_notes/smd_data_parallel_change_log.rst
- setup.py
- src/sagemaker/image_uris.py
- src/sagemaker/lineage/context.py
- src/sagemaker/lineage/query.py
- src/sagemaker/parameter.py
- src/sagemaker/tuner.py
- src/sagemaker/workflow/airflow.py
- src/sagemaker/workflow/execution_variables.py
- src/sagemaker/workflow/lambda_step.py
- src/sagemaker/workflow/steps.py
- tests/integ/sagemaker/lineage/conftest.py
- tests/integ/sagemaker/lineage/test_endpoint_context.py
- tests/integ/test_workflow.py
- tests/unit/sagemaker/lineage/test_endpoint_context.py
- tests/unit/sagemaker/lineage/test_query.py
- tests/unit/sagemaker/workflow/test_lambda_step.py
- tests/unit/sagemaker/workflow/test_steps.py
- tests/unit/test_airflow.py
- tests/unit/test_tuner.py
- tox.ini
Changes to release for master branch
> Sync dev to master

- src/sagemaker/clarify.py
- tests/unit/test_clarify.py
https://tiny.amazon.com/324vu66t
Currently the Clarify BiasConfig only accepts facet name. Actually Clarify analysis configuration supports both name and index. This commit adds the same support to BiasConfig.
* unit test passed
* review the API doc built by sphinx
> fix: support specifying a facet by its column index

- doc/api/utility/environment_variables.rst
- doc/api/utility/hyperparameters.rst
- doc/api/utility/model_uris.rst
- doc/api/utility/script_uris.rst
- setup.py
- src/sagemaker/environment_variables.py
- src/sagemaker/estimator.py
- src/sagemaker/hyperparameters.py
- src/sagemaker/image_uris.py
- src/sagemaker/jumpstart/validators.py
- src/sagemaker/model.py
- src/sagemaker/model_uris.py
- src/sagemaker/script_uris.py
> merge dev to master

- README.rst
- doc/conf.py
- doc/doc_utils/jumpstart_doc_utils.py
- doc/overview.rst
- doc/requirements.txt
- doc/workflows/pipelines/sagemaker.workflow.pipelines.rst
- setup.py
- src/sagemaker/model.py
- src/sagemaker/workflow/fail_step.py
- src/sagemaker/workflow/steps.py
- tests/integ/sagemaker/lineage/conftest.py
- tests/integ/sagemaker/lineage/test_action.py
- tests/integ/test_workflow.py
- tests/integ/test_workflow_with_fail_steps.py
- tests/unit/sagemaker/model/test_neo.py
- tests/unit/sagemaker/workflow/test_fail_step.py
- tests/unit/test_mxnet.py
- tox.ini
> Rebase dev on master

- src/sagemaker/serializers.py
> fix: Style update in DataSerializer

- src/sagemaker/image_uri_config/inferentia-mxnet.json
- src/sagemaker/image_uri_config/inferentia-pytorch.json
- src/sagemaker/image_uri_config/inferentia-tensorflow.json
> Update Inferentia Image URI Config

- src/sagemaker/image_uri_config/huggingface.json
- tests/conftest.py
HF transformers 4.17.0 for TF2.6.3
> feature: Hugging Face Transformers 4.17 for TF 2.6

- doc/_static/js/analytics.js
Remove the old legacy code for web analytics
> Fix: remove old legacy code for web analytics

- tests/scripts/run-notebook-test.sh
> feature: Adds Spark Processing Notebook to Notebook Tests

- tests/integ/sagemaker/lineage/test_model_artifact.py
disable test to mitigate pipeline blockage, investigating this issue separately via AML-166905
> fix: disable test as mitigation

- setup.py
> fix: update setup.py to add minimum python requirement of 3.6

- requirements/extras/test_requirements.txt
Update dependencies to be able to support python 3.10
Tested with py310 in personal stack.
> feature: update dependencies to support python 3.10

- doc/overview.rst
*Description of changes: The list of ML frameworks supported by SageMaker workflows is incomplete.  Added more ML frameworks at are supported.
*Testing done: tox (pysdk code integration test)
> fix: added more ml frameworks supported by SageMaker Workflows

- tests/scripts/run-notebook-test.sh
> change: skip managed spot training mxnet nb

- doc/_static/kendrasearchtools.js
- doc/_templates/searchbox.html
None
Add filters to the RTD Search so that people can filter by the type of content they are looking for.
Deployed to https://amazon-sagemaker-examples.readthedocs.io/en/atqy-add-search-filter/ and tested that it worked.
- [] I have added tests that prove my fix is effective or that my feature works (if appropriate)
> feat: add search filters

- CODEOWNERS
- requirements/extras/local_requirements.txt
> feature: Add Code Owners file

- tests/integ/test_inference_pipeline.py
https://github.com/aws/sagemaker-python-sdk/issues/3520
> fix: Skip Bad Transform Test

- src/sagemaker/workflow/functions.py
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3778
Doc fix
> fix: update the doc for Join function

- tests/conftest.py
> add ap-south-1 to no p3 regions

- tests/integ/test_inference_recommender.py
> fix: Enable inference recommender slow tests

- src/sagemaker/model.py
> fix: add kms key support for Model registration

- src/sagemaker/image_uri_config/djl-neuronx.json
- tests/unit/sagemaker/image_uris/test_djl.py
> [change] add inferentia2 dlc images for djl framework

- src/sagemaker/remote_function/core/serialization.py
> fix: update to more actionable error message

- src/sagemaker/image_uri_config/huggingface-llm.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
*Description of changes:* Add huggingface-llm 0.8.2 dlc images
`tests/unit/sagemaker/image_uris/test_huggingface_llm.py`
> feature: Add huggingface-llm 0.8.2 dlc images

- doc/overview.rst
- requirements/extras/local_requirements.txt
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/3526
*Description of changes:* Remove docker-compose from requirements, since it has conflicting dependencies, and docker-compose v2 can't be installed via pip. Added instructions for installing docker-compose v2 to docs.
> change: Remove docker-compose from local requirements

- src/sagemaker/image_uri_config/djl-deepspeed.json
- src/sagemaker/image_uri_config/djl-fastertransformer.json
- src/sagemaker/image_uri_config/djl-neuronx.json
- tests/unit/sagemaker/image_uris/test_djl.py
This PR is raised for the upcoming new releases of DJL inference containers. 
> change: bump up djl inference image uri versions

- src/sagemaker/image_uri_config/huggingface-llm.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
*Description of changes:* Adding HF-TGI 0.9.3 release image.
*Testing done:* CI/CD testing and regional smoke tests for image.
> feature: Add huggingface-llm 0.9.3 dlc images

- doc/api/inference/deserializers.rst
- doc/api/inference/serializers.rst
*Issue #, if available:* Fix https://github.com/aws/sagemaker-python-sdk/issues/3976
> documentation: Bring back (de)serializers documentation

- src/sagemaker/image_uri_config/djl-neuronx.json
- tests/unit/sagemaker/image_uris/test_djl.py
*Description of changes:* Add DJL 0.24.0 Nueronx support
> change: Release DJL Neuronx 0.24.0

- src/sagemaker/feature_store/feature_processor/__init__.py
- src/sagemaker/feature_store/feature_processor/_constants.py
- src/sagemaker/feature_store/feature_processor/_event_bridge_rule_helper.py
- src/sagemaker/feature_store/feature_processor/_feature_processor_pipeline_events.py
- src/sagemaker/feature_store/feature_processor/feature_scheduler.py
- src/sagemaker/feature_store/feature_processor/lineage/_feature_processor_lineage.py
- src/sagemaker/feature_store/feature_processor/lineage/_feature_processor_lineage_name_helper.py
- src/sagemaker/feature_store/feature_processor/lineage/_pipeline_trigger.py
- src/sagemaker/feature_store/feature_processor/lineage/_s3_lineage_entity_handler.py
- tests/integ/sagemaker/feature_store/feature_processor/test_feature_processor.py
- tests/unit/sagemaker/feature_store/feature_processor/lineage/test_constants.py
- tests/unit/sagemaker/feature_store/feature_processor/lineage/test_feature_processor_lineage.py
- tests/unit/sagemaker/feature_store/feature_processor/lineage/test_pipeline_trigger.py
- tests/unit/sagemaker/feature_store/feature_processor/lineage/test_s3_lineage_entity_handler.py
- tests/unit/sagemaker/feature_store/feature_processor/test_event_bridge_rule_helper.py
- tests/unit/sagemaker/feature_store/feature_processor/test_feature_processor_pipeline_events.py
- tests/unit/sagemaker/feature_store/feature_processor/test_feature_scheduler.py
* feat: Ada EventBased Trigger initial commit
* add unit tests for event based triggers
* Resolve the malformatted docstring
* Resolve failed tests
* Remove role arn from put_rule method signature
* remove unused imports
* fix black format error
* Fix the tag upsert tests
* Add integ test and resolve a bug that rule cannot be deleted
---------
> [feat] feature processor event based triggers (#1132)

- src/sagemaker/fw_utils.py
- tests/unit/test_fw_utils.py
- closes https://github.com/aws/sagemaker-python-sdk/issues/4097
- update `fw_utils.validate_distribution` to deep-copy the input distribution before validating.
- unit test added
> fix: clone distribution in validate_distribution

- src/sagemaker/chainer/estimator.py
- src/sagemaker/huggingface/model.py
- src/sagemaker/mxnet/estimator.py
- src/sagemaker/sklearn/estimator.py
- src/sagemaker/tensorflow/estimator.py
- closes #4143 
- Update broken links
> documentation: update framework version links

- requirements/extras/test_requirements.txt
> fix: bump urllib3 version

- requirements/extras/test_requirements.txt
- tox.ini
> change: Bump test dependencies versions

- doc/frameworks/pytorch/using_pytorch.rst
Fix https://github.com/aws/sagemaker-python-sdk/issues/4193.
Fix https://github.com/aws/sagemaker-python-sdk/issues/4113.
Fix https://github.com/aws/sagemaker-python-sdk/issues/4195.
Fix https://github.com/aws/sagemaker-pytorch-training-toolkit/issues/255.
- Add a mention to add required packages to the environment's specification.
- Add a mention of training and inference toolkit
- Reword mention of AWS Deep Learning Containers …
> documentation: Mention for custom Docker Image

- src/sagemaker/image_uri_config/huggingface-llm.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
> feat: TGI 1.2.0 Image Uri

- src/sagemaker/serve/builder/model_builder.py
Fixes #4287
*Description of changes:* Fix user agent tag issue
> fix: Fix user agent tag issue

- setup.py
Fix https://github.com/aws/sagemaker-python-sdk/issues/4316
> Change: Update tblib constraint

- .github/ISSUE_TEMPLATE/bug_report.md
> documentation: update issue template.

- tests/integ/test_inference_recommender.py
> Raise Exception for debug

- src/sagemaker/estimator.py
https://github.com/aws/sagemaker-python-sdk/issues/4241
PT2.1 SM DLC currently does not support SMDDP or SMDMP.
> Adding PyTorch 2.1.0 SM Training DLC to UNSUPPORTED_DLC_IMAGE_FOR_SM_PARALLELISM list

- doc/requirements.txt
> change: update sphinx version

- doc/requirements.txt
> change: bump jinja2 to 3.1.3 in doc/requirments.txt

- src/sagemaker/image_uri_config/huggingface-llm.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
https://sim.amazon.com/issues/SMJS-213
> feature: TGI 1.4.0

- src/sagemaker/workflow/clarify_check_step.py
- src/sagemaker/workflow/quality_check_step.py
*Description of changes:* Explain the ClarifyCheckStep and QualityCheckStep parameters by pointing to relavent documentation.
*Testing done:* Tested building the documentation and they look OK. 
> documentation: Explain the ClarifyCheckStep and QualityCheckStep parameters

- doc/workflows/index.rst
*Description of changes: change the order of topics under Workflows to prioritize SM Pipelines
*Testing done: tox checks
> documentation: change order of pipelines topics

- src/sagemaker/serve/builder/model_builder.py
- Fix telemetry image uri option logic for ModelBuilder
> Fix telemetry image uri option logic for ModelBuilder

- tests/integ/test_training_compiler.py
> skip pytorch training compiler integ test

- src/sagemaker/image_uri_config/huggingface-llm.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
Release TGI 1.4.2 through SDK
- [ X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
> feature: TGI 1.4.2

- requirements/extras/test_requirements.txt
- tox.ini
> change: Bump Apache Airflow version to 2.8.2

- README.rst
> fix:urge customers to install latest version

- README.rst
> fix: fix badge in README

- src/sagemaker/image_uri_config/huggingface-llm-neuronx.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
release optimum 0.0.21
see https://github.com/awslabs/llm-hosting-container/blob/main/huggingface/pytorch/optimum/docker/0.0.21/Dockerfile
> feat: optimum 0.0.21

- src/sagemaker/image_uri_config/huggingface-llm.json
- tests/unit/sagemaker/image_uris/test_huggingface_llm.py
> chore: release TGI 2.0.0

- .github/workflows/codebuild-ci.yml
> Merge master .github/workflows/codebuild-ci.yml

- src/sagemaker/fw_utils.py
- src/sagemaker/image_uri_config/pytorch-smp.json
- [] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [] I have passed the region in to all S3 …
> Updates for SMP v2.3.1

- tests/integ/sagemaker/conftest.py
> Add more debuging

- tests/conftest.py
> fix: Fix ci unit-tests

- README.rst
Update README.rst to also show `conda-forge` version of SDK just like PyPI to make sure both of these versions are in sync.
> change: Update README.rst to show conda-forge version of SageMaker SDK

- .github/workflows/security-monitoring.yml
remove log statement in security monitoring workflow to keep alerts hidden
- [ x] I certify that the changes I am introducing will be backward compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#com …
> fix: removed log statement

- requirements/extras/test_requirements.txt
https://github.com/aws/sagemaker-python-sdk/actions/runs/10517512205/job/29141760997
> fix test fail

- requirements/extras/test_requirements.txt
https://t.corp.amazon.com/D167579840/overview
cloudpickle version incompatible issue
> update cloudpickle version to >=2.2.1

- pyproject.toml
> update cloudpickle version to >=2.2.1 in pyproject.toml

- requirements/extras/test_requirements.txt
* Local installs fails in fresh pyenv due to conflicts and `ResolutionTooDeep: 200000` issue
> fix: pin testing deps

- pyproject.toml
Updating SageMaker Core Dependency.
Built a wheel locally, pip install and "import sagemaker" works.
> change: Update sagemaker-core dep

- pyproject.toml
> Numpy update

- tests/data/serve_resources/mlflow/pytorch/requirements.txt
- tests/data/serve_resources/mlflow/tensorflow/requirements.txt
> Cloudpickle update

- pyproject.toml
> Cloudpickle upgrade

- src/sagemaker/serve/model_server/multi_model_server/inference.py
- src/sagemaker/serve/model_server/torchserve/inference.py
- src/sagemaker/serve/model_server/torchserve/xgboost_inference.py
> Fix Flake8 Violations

- src/sagemaker/session.py
- tests/integ/test_collection.py
> Fixed pagination failing while listing collections

- doc/frameworks/tensorflow/using_tf.rst
According to https://github.com/aws/sagemaker-python-sdk/issues/2964, update the Tensorflow doc link.
> Fix Tensorflow doc link

- tests/integ/test_horovod.py
- tests/integ/test_horovod_mx.py
> Skip tests with deprecated instance type

- tests/unit/sagemaker/remote_function/test_job.py
* https://github.com/aws/sagemaker-python-sdk/actions/runs/14090304879/job/39465061004
* These tests have some flakiness due to parallel execution of tests writing to same file
* Change uses temp file for tests rather than single global test
> fix: use temp file in unit tests

- doc/amazon_sagemaker_model_building_pipeline.rst
*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/4401
Fix ModelStep data dependency documentation
> documentation: update ModelStep data dependency info

- .github/workflows/codebuild-ci-health.yml
- .github/workflows/codebuild-ci.yml
> Py312 upgrade step 1: Update pr test to deprecate py38 and add py312

- tests/integ/sagemaker/serve/test_serve_js_deep_unit_tests.py
> Fix: Add model server timeout to fix integ test

- src/sagemaker/feature_store/feature_processor/_input_offset_parser.py
*Description of changes:* Fixed type annotations
> Fix type annotations

- tests/unit/sagemaker/model/test_deploy.py
> Fix test_deploy_with_update_endpoint()

- src/sagemaker/image_uri_config/huggingface-neuronx.json
Adding 
https://github.com/aws/deep-learning-containers/releases/tag/v1.1-hf-4.43.2-pt-2.1.2-tr-neuronx-sdk2.20.0-py310
and 
https://github.com/aws/deep-learning-containers/releases/tag/v2.2-hf-4.48.1-pt-2.1.2-tr-neuronx-sdk2.20.0-py310
and
https://github.com/aws/deep-learning-containers/releases/tag/v2.1-hf-4.43.2-pt-2.1.2-inf-neuronx-sdk2.20.0-py310
dlcs to the sagemaker sdk image_uri util
> huggingface-neuronx dlc image_uri

- src/sagemaker/image_uri_config/huggingface-llm-neuronx.json
Adding
https://github.com/aws/deep-learning-containers/releases/tag/v2.1-hf-4.43.2-pt-2.1.2-inf-neuronx-sdk2.20.0-py310
dlcs to the sagemakerSDK image_uri utils
> huggingface-llm-neuronx dlc

- requirements/extras/test_requirements.txt
> Fix Flask-Limiter version

- requirements/extras/test_requirements.txt
> Add more constraints to test requirements
